### ISSUE TITLE
Constrain permissible event triggers

### ISSUE THREAD

**Issue by iron3oxide** [reflex-dev/reflex#1008]
Linking to #980 and #754, it would be great if each component communicated explicitly for which event triggers it accepts callbacks. This would mean creating something like a `BaseEvents` class with each field typed as `Optional[Callable | pc.Var]` and inheriting from it in subclasses that e.g. add the `on_change` field. 

I just wrote something similar to this for my own project in which I have a `ghost()` function that returns a ghost button. Since I don't know in advance which callbacks the caller wants to register, I wrote an `EventHandler` TypedDict with every permissible event trigger as fields. It being a TypedDict part is important because that way I can simply unpack it in the `ghost()` function, something I cant do with e.g. `BaseModel.dict()` as the compiler can't handle it.

If the `Events` classes proposed here were TypedDicts as well, they could be reused by users in the same fashion.

**Comment by Lendemor** [comment]
As reference, could you provide an example of code/syntax that you would expect to work with said modifications?

**Comment by iron3oxide** [comment]
I just noticed that my original proposal would 

1. Require an API change as each component would now expect some kind of object, let's call it a handler, that maps event triggers to callbacks
2. Not require said handler to be a TypedDict as that was only necessary to unpack it before compilation, which one wouldn't have to do anymore because the component would now expect a single handler parameter instead of numerous event trigger callback parameters.

On the plus side, it would probably save some duplicate code when implementing #980, as the `create()` overrides wouldn't have to specify each and every event trigger as parameters anymore.

If that doesn't seem worth the API change and minor added hassle (e.g. for a button with nothing but an on_click callback you would now need to do something like `handler=Handler(on_click=State.do_something`), one could alternatively provide the aforementioned TypedDicts with every field initialized to `None`, which could then be used for component functions like the one mentioned in my original comment, but not much else.

**Comment by Lendemor** [comment]
I think this request is addressed in the new API for triggers event that  was introduced recently (v0.2.8).

Feel free to reopen if I'm wrong.
