### ISSUE TITLE
Make pc.toggle_color_mode callable 

### ISSUE THREAD

**Issue by iron3oxide** [reflex-dev/reflex#1009]
As of writing, it is not obvious how to hook into a theme change or how to trigger it manually. Since `pc.toggle_color_mode` is a `BaseVar` wrapping(?) an `EventChain`, it is not callable, which complicates a lot of use cases. In my case, I had to use both the `on_click` and `on_mouse_up` triggers in order to change the theme and the icon of the theme toggle button, which is hacky at best. Is there a way to enable an easier to use theme toggle or am I simply missing something?

**Comment by Lendemor** [comment]
Yes `toggle_color_mode` need improvements.

Maybe it deserve to have a separate issue, but alongside this, we also need to be able to get the current mode (light/dark) if we want to do some conditional rendering based on this.

**Comment by ElijahAhianyo** [comment]
closing this as there's docs for this here https://reflex.dev/docs/styling/theming#color-mode
