### ISSUE TITLE
Ways to disable line feed in datatable?

### ISSUE THREAD

**Issue by FHU-yezi** [reflex-dev/reflex#101]
I want to display some data, with a column called article title which can be up to 30 chars ( If it is too long, I will strip it ), but I want to enable horizontal scoll when screen width is too small to display all the chars.

I tried to add `white-space: nowrap` to the root node of datatable in DevTools, and it is work for my case, but when I turns to add kwargs in `pc.datatable`, it doesn't work.

Is the attr has been attched to a wrong DOM node? It is a Bug to fix or there are another way to do it?

**Comment by Alek99** [comment]
Got it do you have experience with gridjs https://gridjs.io this maybe be a good issue for you to tackle if you want to get more involved with the feature development on the framework.

We really appreciate your help with the open source so far!

**Comment by FHU-yezi** [comment]
Not any experience yet, but will try to dig into this.

**Comment by Alek99** [comment]
Ok awesome just as some guidance you will mostly be editing this file https://github.com/pynecone-io/pynecone/blob/main/pynecone/components/datadisplay/datatable.py. ill be free tomorrow to go over anything and would be happy to give you an introduction to the framework if you want
