### ISSUE TITLE
Adding a visual editor

### ISSUE THREAD

**Issue by yashgugale** [reflex-dev/reflex#1016]
It would be super useful to add a **visual editor** while building an app for the front end part. Being able to simply drag and drop elements from the library to create a base skeleton adds a lot of value. With this there would be the ability to customize the styling and interactions in code.
For someone who is not a frontend developer (or dreads it), laying out components using flex, grid, box, etc. is kind of tedious and annoying. So if there is a visual editor that allows you to create basic setup such as a layout, table, etc., that would be ideal.

**Comment by picklelo** [comment]
This is something we have scoped out - definitely want to make the UI development process a lot easier. I'll close this issue as the project is much bigger than a single issue.
