### ISSUE TITLE
Figma to Pynecone plugin

### ISSUE THREAD

**Issue by yashgugale** [reflex-dev/reflex#1023]
Are there any plans to convert Figma designs to Pynecone FE apps?

**Comment by Alek99** [comment]
We do have plans for this in the future but have been focusing on improving the core of the library because we have limited bandwidth at the moment

**Comment by yashgugale** [comment]
Makes sense. Is there a way to convert from ReactJS code to Pynecone source code directly? There are currently some plugins (such as [Quest](https://www.quest.ai/)) that convert Figma designs to React code. We could leverage that, and build on top of it to convert React code to Python Pynecone source files.

**Comment by Lendemor** [comment]
https://reflex.dev/docs/components/html-to-reflex/
