### ISSUE TITLE
Add Chakra Transitions

### ISSUE THREAD

**Issue by iron3oxide** [reflex-dev/reflex#1050]
Having the ability to add stylish transitions would be cool. Luckily, Chakra has [some components for this](https://chakra-ui.com/docs/components/transitions/usage) that look easy to wrap.

**Comment by Unknownsentinel193** [comment]
Hi, could please you assign this to me, i would like to do it

**Comment by TaiJuWu** [comment]
Is any method which can use hook like useDisclosure()?

**Comment by Lendemor** [comment]
We can add it to an `others` folder for now.

**Comment by Unknownsentinel193** [comment]
Sure will do that, Thank You for the quick response...

**Comment by include** [comment]
Question: isn't it possible to use Chakra UI altogether as an alternative to Tailwind UI directly? kthxbye

**Comment by masenf** [comment]
Looks completed via #1058, maybe just lacking docs and examples?
