### ISSUE TITLE
data_table behavior related to source of `data` and `column`

### ISSUE THREAD

**Issue by qenu** [reflex-dev/reflex#1114]
**Describe the bug**
When data and columns are each hard coded and referenced, it would fail to compile.

**To Reproduce**
 - Code/Link to Repo:
 ```python
class State(pc.state):
    data = [["some data"]]
def index():
    return pc.data_table(
        data = State.data,
        columns = ["item"],
    )
```

**Expected behavior**
data_table should be able to compile when data and columns are from different sources

**Screenshots**
Could provide if needed.

** Specifics (please complete the following information):**
 - Python Version: 3.11
 - Pynecone Version: v0.1.32
 - OS: MacOS
 - Browser (Optional): Safari

**Comment by jiangmiemie** [comment]
Table content Japanese table calculation is one whole, this is not possible bug

**Comment by Lendemor** [comment]
Tested with latest reflex, no error happens. Will close
