### ISSUE TITLE
Add copyright year

### ISSUE THREAD

**Issue by evandeng2009** [reflex-dev/reflex#1120]
**Describe the bug**
Generally, we'd like to add a statement like "@year_start - year_current . All rights reserved.". I'm thinking if pc.year or pc.copyright or something similar to construct such a statement.

**To Reproduce**
 - Code/Link to Repo:

**Expected behavior**

**Screenshots**

** Specifics (please complete the following information):**
 - Python Version:
 - Pynecone Version:
 - OS: 
 - Browser (Optional):
 
**Additional context**

**Comment by jiangmiemie** [comment]
sounds like special pc.text()

**Comment by palashcode** [comment]
@jiangmiemie Yes, Something like this can be done.
```python
text_style = {
    "position": "fixed",
    "left": "0",
    "bottom": "0",
    "width": "100%",
    "background-color": "#f8f9fa",
    "color": "black", 
    "text-align": "center",
    "padding": "10px 0",
    }
pc.text(f"© year_start - year_current . All rights reserved.", style=text_style)

**Comment by jiangmiemie** [comment]
agree ， that is my demo :
`                        pc.alert(
                            pc.alert_icon(),
                            pc.alert_title(pc.markdown("Copyright Notice © [:](https://creativecommons.org/licenses/by/4.0/legalcode) Licensed under the Creative Commons Attribution 4.0 International License Agreement, please indicate the source for reprinting!")),
                            status="info",
                        ),
                        ),
`
![image](https://github.com/pynecone-io/pynecone/assets/69161207/ce424f31-c832-4787-a0c7-a539b7c46b2a)


I think we should close this question 

> @jiangmiemie是的，这样的事情是可以做到的。
> 
> ```python
> text_style = {
>     "position": "fixed",
>     "left": "0",
>     "bottom": "0",
>     "width": "100%",
>     "background-color": "#f8f9fa",
>     "color": "black", 
>     "text-align": "center",
>     "padding": "10px 0",
>     }
> pc.text(f"© year_start - year_current . All rights reserved.", style=text_style)
> ```

**Comment by evandeng2009** [comment]
First, year_current is a var which changes when year changes, although we can set a var there in State.
Second, no one would set a copyright statement like your demo as an alert.
At last, all I want is a take-use component for copyright statement, without any manual modifications.

**Comment by jiangmiemie** [comment]
So I suggest to be able to describe clearly at the beginning . After all, it's not just me that thinks your idea is a **hyperlink with style** .

**Comment by jiangmiemie** [comment]
copyright just a link with style, you can use text() markdwon() why not as an alert...  

i can not understand your mind , may be you can provide some example urls.

If it's interesting enough, I think I'll try to write this component .

**Comment by evandeng2009** [comment]
Ok, pcweb is an example: 
![image](https://github.com/pynecone-io/pynecone/assets/11970778/129cd853-1f7d-40e2-9de8-dce19d23e65e)
![image](https://github.com/pynecone-io/pynecone/assets/11970778/a4bc9cc8-5e9f-4c21-befe-df01206de422)
What is required to do when 2024 comes? Change "2023" to "2024" manually. So key point of copyright component is chnage the year automatically.

Another one, Cloudflare and seems like it forgot to change the year:
![image](https://github.com/pynecone-io/pynecone/assets/11970778/48bb01ac-119c-401c-9702-8e5f6e8068d7)

And Heroku:
![image](https://github.com/pynecone-io/pynecone/assets/11970778/f9152b04-a03d-46a8-9fc8-bd2b469aaa01)

There is possibly a convention for copyright statement: @ + year(creation_year or current_year) + organization_name, this needs further investigation and discussion.

Anyway, this is a not big request, coz we can easily realize it without this component.

**Comment by evandeng2009** [comment]
Close this issue anway.
