### ISSUE TITLE
[REF-1293] Add way to scroll to component

### ISSUE THREAD

**Issue by picklelo** [reflex-dev/reflex#1122]
We can add something like `pc.scroll_to` that does this behavior: https://stackoverflow.com/questions/43441856/how-to-scroll-to-an-element

<sub>[REF-1293](https://linear.app/reflex-dev/issue/REF-1293/add-way-to-scroll-to-component)</sub>

**Comment by jiangmiemie** [comment]
I agree, this component can help me quickly jump to the corresponding position by clicking the directory next to the page

**Comment by heysujal** [comment]
Hi @picklelo, i want to work on this issue. Can you guide me, I am new to this project?
