### ISSUE TITLE
[question] use three.js

### ISSUE THREAD

**Issue by radu022003** [reflex-dev/reflex#1134]
How to use three.js with pynecone?
I have managed to use a javascript file by using the script_tags argument for add_page, but my javascript imports the three.js modules and those are not to be found.
I have placed the needed three.js files in the assets directory.

An example would be also highly appreciated.

**Comment by masenf** [comment]
I played around with this a bit today, and it seems much easier to use react-three. I wrote a small example app for some inspiration: https://github.com/reflex-dev/reflex-examples/pull/176
