### ISSUE TITLE
SQLAlchemy 2.0 compatibility

### ISSUE THREAD

**Issue by Viish** [reflex-dev/reflex#1140]
Hi,

**Describe the bug**
Pynecone requires SQLAlchemy `">=1.3.18,<1.4.43"`, but version 2.0 is out and if we don't want to use your DB API but SQLAlchemy directly we can't use the latest release...

**Expected behavior**
Could you update the dependency to allow 2.0 ?

Thanks in advance!

**Comment by bratao** [comment]
+1. This is a blocker for us, as we heavily use the SQLAlchemy 2.

Talking about that, pynecone should drop the tiangolo/sqlmodel. This is an unmaintained project, and it is possible to use SQLAlchemy 2 ORM now to get the same or better results.

**Comment by Alek99** [comment]
Yeah we are planning on dropping sql model and making out own the will support sql alchemy 2

**Comment by lejansenampeers** [comment]
+1. Would love to use reflex, but company is using SQLAlchemy 2 in all projects

**Comment by benedikt-bartscher** [comment]
sqlmodel 0.0.12 has added support for SQLAlchemy to 2.0, so this should be possible now
