### ISSUE TITLE
Unexpected outcome from the introduction doc

### ISSUE THREAD

**Issue by joaompinto** [reflex-dev/reflex#1180]
**Describe the bug**
I have follow the instructions from https://pynecone.io/docs/getting-started/introduction, executed the python script and it just silents exit.

**To Reproduce**
follow the instructions from https://pynecone.io/docs/getting-started/introduction

**Expected behavior**
I would expect a localhost url to be provided where I would eb able to browse the compiled application

**Screenshots**

** Specifics (please complete the following information):**
 - Python Version: 0.1.33
 - Pynecone Version: 0.1.33
 - OS: WSL2
 - Browser (Optional):
 
**Additional context**

**Comment by ElijahAhianyo** [comment]
When you run `pc init` and `pc run`, your app should start on port 3000 by default unless otherwise modified by the `--frontend-port` cli arg. You should also see in your console, the url your application runs on. Can you give more context(your code example as well as console logs) to the issue youre facing?

**Comment by ElijahAhianyo** [comment]
> Hi @ElijahAhianyo, it was a matter of presentation order, in the "Introduction" page there was no mention to the need of using "pc" to run the application.
> 
> The statement "Finally, we compile our app, and we are ready to run it." was too magic form my initial understanding. I assumed that as some other web frameworks, copy/paste of the example and running it as a regular Python app would work.
> 
> Probably there should be some line in the final step referring to the need to a) run the script b) run the application using pc .
> 
> Leaving the issue open in case it makes sense for a doc improvement, otherwise feel free to close it.
> 
> Thanks

Ah right, thanks for noting that. Will update the docs to reflect this
