### ISSUE TITLE
Issue while wrapping React components

### ISSUE THREAD

**Issue by pritam-dey3** [reflex-dev/reflex#1182]
**Describe the bug**
I am trying to use Mantine component in my application using the following code.
```python
class Collapse(pc.Component):
    library = "@mantine/core"
    tag = "Collapse"

    # variables
    in_: pc.Var[bool]  # type: ignore
    animate_opacity: pc.Var[bool]  # type: ignore
    transition_duration: pc.Var[int]  # type: ignore

    def get_triggers(self) -> Set[str]:
        """Get the event triggers for the component.

        Returns:
            The event triggers.
        """
        return super().get_triggers() | set({"on_transition_end"})
```
But I am facing this error
![image](https://github.com/pynecone-io/pynecone/assets/36327719/136ffd03-f417-43d9-84ec-3b679ca03f0d)

I suspect this is due to the fact that Mantine wants me to wrap my `App` with `MantineProvider` like this 
![image](https://github.com/pynecone-io/pynecone/assets/36327719/2e6b0941-3a04-4ba6-9cc7-cbe07c907696)

But the generated _app.js has only `ChakraProvider` wrapped around it
![image](https://github.com/pynecone-io/pynecone/assets/36327719/a459873a-2e02-4ad6-aa8f-6bfdd5ad9a3d)

Note that, `Collapse` was working for me for some earlier versions (I did not document the exact versions of either pynecone or Mantine).

**To Reproduce**
Try to wrap `Collapse` Mantine component.

**Expected behavior**
Users should be able to wrap any react component from any library

**Specifics (please complete the following information):**
 - Python Version: 3.11
 - Pynecone Version: 0.1.33
 - OS: Windows WSL
 - Browser (Optional): Chrome

**Comment by masenf** [comment]
This use case can actually be handled now, via the use of `_get_app_wrap_components` API.

```python
import reflex as rx
from reflex.components.component import Component


class MantineProvider(rx.Component):
    library = "@mantine/core"
    tag = "MantineProvider"

    with_global_styles: rx.Var[bool]  # type: ignore
    with_normalize_CSS: rx.Var[bool]  # type: ignore


mantine_provider = MantineProvider.create(with_global_styles=True, with_normalize_CSS=True)


class MantineComponent(rx.Component):
    library = "@mantine/core"

    @staticmethod
    def _get_app_wrap_components() -> dict[tuple[int, str], Component]:
        return {
            (10, "MantineProvider"): mantine_provider,
        }


class Collapse(MantineComponent):
    tag = "Collapse"

    # variables
    in_: rx.Var[bool]  # type: ignore
    animate_opacity: rx.Var[bool]  # type: ignore
    transition_duration: rx.Var[int]  # type: ignore

    def get_event_triggers(self):
        """Get the event triggers for the component.

        Returns:
            The event triggers.
        """
        return super().get_event_triggers() | {
            "on_transition_end": lambda: [],
        }


class Button(MantineComponent):
    tag = "Button"


class State(rx.State):
    is_opened: bool = False


def index():
    return rx.vstack(
        Button.create("Toggle", on_click=lambda: State.set_is_opened(~State.is_opened)),
        Collapse.create("foo", in_=State.is_opened),
    )


# Add state and page to the app.
app = rx.App()
app.add_page(index)
app.compile()
```
