### ISSUE TITLE
Audio Support

### ISSUE THREAD

**Issue by Alek99** [reflex-dev/reflex#1185]
We should integrate some sort of audio component to with web audio api.

https://developer.mozilla.org/en-US/docs/Web/API/Web_Audio_API

**Comment by milochen0418** [comment]
The support will depend on the Browser Compatibility 
https://developer.mozilla.org/en-US/docs/Web/API/Web_Audio_API#browser_compatibility.  
What audio api can be support by pynecone is depended on what version of browser pyencone plan to support.

**Comment by picklelo** [comment]
This is supported by the `rx.audio` component: https://reflex.dev/docs/library/media/audio/
