### ISSUE TITLE
Wrap local React components

### ISSUE THREAD

**Issue by picklelo** [reflex-dev/reflex#1195]
Currently the guide only shows how to wrap components from `npm`. We should also show how to wrap custom local React components (and add anything to the library to enable that if necessary).

**Comment by BenjaminLevyQB** [comment]
+1 for this. The same issue was open on the original pynecone and there wasn't any movement on it. Would love to see this!

**Comment by masenf** [comment]
completed via https://github.com/reflex-dev/reflex-web/pull/168

**Comment by pratyushseq** [comment]
@masenf How do we use npm packages in these local components? For example if I want to use `react-datepicker` in the above-mentioned `Welcome` component, how do I install and use it?

CC @picklelo
