### ISSUE TITLE
Better error message when directing to non-existing page

### ISSUE THREAD

**Issue by picklelo** [reflex-dev/reflex#1196]
Currently going to a bad route leaves a very confusing error message: "attempted to hard navigate to the same URL". It's not very obvious what this means, we should try to catch this and throw a better message somehow (perhaps using a `pc.window_alert`)

**Comment by masenf** [comment]
This has been fixed since August. Going to a non-existing page gives the default next 404 page, with the optional ability to replace it with a custom 404 page.
