### ISSUE TITLE
[REF-1311] Wrap pc.markdown in a box

### ISSUE THREAD

**Issue by picklelo** [reflex-dev/reflex#1197]
Currently you cannot apply styles to the markdown component. We should wrap it in a `pc.box` and apply the styles to the box.

<sub>[REF-1311](https://linear.app/reflex-dev/issue/REF-1311/wrap-pcmarkdown-in-a-box)</sub>

**Comment by tarunsamanta2k20** [comment]
I'd like to work on it.

**Comment by tarunsamanta2k20** [comment]
May i know the location of the markdown component i mean the file name?

**Comment by milochen0418** [comment]
@tarunsamanta2k20  pynecone/components/typography/markdown.py

**Comment by Billa05** [comment]
by pc.box do you mean the BOX class in box.py file?

**Comment by picklelo** [comment]
This works now as every component accepts css props.
