### ISSUE TITLE
Help: pcweb tutorial describing the project structure and concepts

### ISSUE THREAD

**Issue by mister-rao** [reflex-dev/reflex#1214]
Thank you for pynecone. I was looking for a webframework to build a landing page and webapp for my startup, and stumbled upon pynecone, looking at the vast capabilities I decided to use it for building the site.

It's a B2B webapp so I want it to be responsive. I found that pcweb is a great start as an example project that makes use of most of the features offered by pynecone.

I've even setup my basic project structure based on pcweb. The thing is I have to keep jumping around the codebase to know how things are sticthed together and made use of.

It would be awesome if there was a tutorial (written or video) explaining the pcweb codebase. It'll also serve as a great resource for other devs looking to build a full-scale webapp with pynecone.

**Comment by Alek99** [comment]
Good idea, we should make a tutorial that goes more in-depth on pcweb

**Comment by Lendemor** [comment]
The tutorial was added a while ago.
