### ISSUE TITLE
[REF-1489] Hash portion of URL (after the #) is not accessible in router_data

### ISSUE THREAD

**Issue by ritwickdsouza** [reflex-dev/reflex#1259]
**Describe the bug**
Unable to access fragments of the url for e.g. https://127.0.0.1:3000/#foo=bar

Currently only pathname is being passed to the router_data. basePath should also be passed to get the fragment 
https://nextjs.org/docs/pages/api-reference/functions/use-router

**To Reproduce**
N/A

**Expected behavior**
foo=bar should be accessible

**Screenshots**
N/A

** Specifics (please complete the following information):**
 - Python Version: 3.11.4
 - Reflex Version: 0.1.32
 - OS: MacOS
 - Browser (Optional):
 
**Additional context**
N/A

<sub>[REF-1489](https://linear.app/reflex-dev/issue/REF-1489/hash-portion-of-url-after-the-is-not-accessible-in-router-data)</sub>

**Comment by ZaneH** [comment]
I just ran into this yesterday with Supabase and Google OAuth2.

Example of the callback URL:

```
http://localhost:3000/#access_token=[snip]&expires_in=3600&refresh_token=[snip]&token_type=bearer```
```

**Comment by ritwickdsouza** [comment]
@ZaneH yes, same case as me. I ran into this issue while trying to integrate supabase auth.

**Comment by picklelo** [comment]
Thanks for reporting, we will look into this and fix in an upcoming release.

**Comment by ElijahAhianyo** [comment]
@ZaneH @ritwickdsouza Does `router.page.raw_path` (see eg below) not work?

```python

import reflex as rx

class State(rx.State):

    def display(self):
        print(self.router.page.raw_path)
```

**Comment by ZaneH** [comment]
> @ZaneH @ritwickdsouza Does `router.page.raw_path` (see eg below) not work?
> 
> ```python
> import reflex as rx
> 
> class State(rx.State):
> 
>     def display(self):
>         print(self.router.page.raw_path)
> ```

Console output:

```
event_actions={} handler=EventHandler(event_actions={}, fn=<function LoginState.display at 0x10c23b560>) client_handler_name='' args=()
```

Code:

```python
# index.py
...
Returns:
    The UI for the landing page.
"""
print(LoginState.display())
return rx.flex(
    rx.box(
...
```

```python
# login.py
# LoginState is defined here
...
is_loading: bool = False

def display(self):
    return self.router.page.raw_path

def on_submit(self, form_data) -> rx.event.EventSpec:
...
```

I'm not seeing any output I'd recognize using `.raw_path`

**Comment by ElijahAhianyo** [comment]
> > @ZaneH @ritwickdsouza Does `router.page.raw_path` (see eg below) not work?
> > ```python
> > import reflex as rx
> > 
> > class State(rx.State):
> > 
> >     def display(self):
> >         print(self.router.page.raw_path)
> > ```
> 
> Console output:
> 
> ```
> event_actions={} handler=EventHandler(event_actions={}, fn=<function LoginState.display at 0x10c23b560>) client_handler_name='' args=()
> ```
> 
> Code:
> 
> ```python
> # index.py
> ...
> Returns:
>     The UI for the landing page.
> """
> print(LoginState.display())
> return rx.flex(
>     rx.box(
> ...
> ```
> 
> ```python
> # login.py
> # LoginState is defined here
> ...
> is_loading: bool = False
> 
> def display(self):
>     return self.router.page.raw_path
> 
> def on_submit(self, form_data) -> rx.event.EventSpec:
> ...
> ```
> 
> I'm not seeing any output I'd recognize using `.raw_path`

No you cant call the eventhandler (`.display()`) out side of the state. 

```python
import reflex as rx

class State(rx.State):
    
    def display(self):
       print(self.router.page.raw_path)
  
    @rx.var
    def raw_path(self) -> str:
        return self.router.page.raw_path

def index():
     return rx.vstack(
         rx.text(State.raw_path),
     )
     
 app = rx.App()
 app.add_page(index, on_load=State.display)
 app.compile()
```

The example above will print the path in your console when the page loads as well display the path as a text on the page using a computed var

**Comment by ZaneH** [comment]
> > > @ZaneH @ritwickdsouza Does `router.page.raw_path` (see eg below) not work?
> > > ```python
> > > import reflex as rx
> > > 
> > > class State(rx.State):
> > > 
> > >     def display(self):
> > >         print(self.router.page.raw_path)
> > > ```
> > 
> > 
> > Console output:
> > ```
> > event_actions={} handler=EventHandler(event_actions={}, fn=<function LoginState.display at 0x10c23b560>) client_handler_name='' args=()
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Code:
> > ```python
> > # index.py
> > ...
> > Returns:
> >     The UI for the landing page.
> > """
> > print(LoginState.display())
> > return rx.flex(
> >     rx.box(
> > ...
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```python
> > # login.py
> > # LoginState is defined here
> > ...
> > is_loading: bool = False
> > 
> > def display(self):
> >     return self.router.page.raw_path
> > 
> > def on_submit(self, form_data) -> rx.event.EventSpec:
> > ...
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I'm not seeing any output I'd recognize using `.raw_path`
> 
> No you cant call the eventhandler (`.display()`) out side of the state.
> 
> ```python
> import reflex as rx
> 
> class State(rx.State):
>     
>     def display(self):
>        print(self.router.page.raw_path)
>   
>     @rx.var
>     def raw_path(self) -> str:
>         return self.router.page.raw_path
> 
> def index():
>      return rx.vstack(
>          rx.text(State.raw_path),
>      )
>      
>  app = rx.App()
>  app.add_page(index, on_load=State.display)
>  app.compile()
> ```
> 
> The example above will print the path in your console when the page loads as well display the path as a text on the page using a computed var

I see, my bad. That worked for me. Unfortunately it looks like I can only use it in certain places. I needed to use it outside of the component "render"
