### ISSUE TITLE
Support custom styles for rx.markdown

### ISSUE THREAD

**Issue by picklelo** [reflex-dev/reflex#1283]
Currently the Markdown component cannot be custom-styled.

We should support custom styles similar to https://react.email/docs/components/markdown

**Comment by Varshni11** [comment]
Hi @picklelo , I would like to contribute on this issue. This is my first time to contribute, could you guide me on how to get started with it...

**Comment by milochen0418** [comment]
> Hi @picklelo , I would like to contribute on this issue. This is my first time to contribute, could you guide me on how to get started with it...
Nice to contribute :) When your code is ready, you can refer to the following way to send your PR. 
https://github.com/pynecone-io/pynecone/blob/main/CONTRIBUTING.md

**Comment by bsarthak16** [comment]
Hi, I wanted to contribute to this issue, just wanted to know whether you want some specific color or if I can use any colors for custom styling
