### ISSUE TITLE
pynecone's web server automatically stops on VPS Ubuntu 20.04

### ISSUE THREAD

**Issue by mahiiraaj** [reflex-dev/reflex#1290]
**bug description**
When I do "pc run" the website starts but after a few hours when I open the URL of the website, it shows a connection error "This site can’t be reached" which means the server is stopped.

screenshot of I starting the service and list of running services.

![1688196449307](https://github.com/pynecone-io/pynecone/assets/3846031/1468e884-a545-4081-bf39-bd05253f36c2)
![1688196449259](https://github.com/pynecone-io/pynecone/assets/3846031/22f4ae21-1f82-41dc-b337-6cea532dca53)
![1688196449284](https://github.com/pynecone-io/pynecone/assets/3846031/470d6289-893c-454a-aff1-3c85cfc1decf)

**Expected behavior**
the web server should keep running it should not be stopped after some time.
**Screenshots**

 - Python Version:3.8.10
 - Reflex Version:    0.1.34
 - OS:  ubuntu 20.04 server
 
I'm using Python Poetry for the environment management
when I installed "aapanel" for the control panel the service did not stop automatically it was running always (at least for 1 day  what i checked) but now I have uninstalled it because it was showing Nginx server instead of my website.

**Comment by picklelo** [comment]
Closing this as we've made many updates since this. Can reopen if it's still an issue.
