### ISSUE TITLE
Return file to browser in the backend

### ISSUE THREAD

**Issue by evandeng2009** [reflex-dev/reflex#1310]
**Describe the bug**
I like the way that no record shown in browser console when call State.functions. Right now I'm trying to provide a button for downloading files. As discussed in https://github.com/pynecone-io/pynecone/issues/909, a link should be clicked by user. Any way to directly retun the file to browser for downloading and no link shown? By the way, what's the development status of pc.download_files()?

**To Reproduce**
 - Code/Link to Repo:

**Expected behavior**

**Screenshots**

** Specifics (please complete the following information):**
 - Python Version:
 - Reflex Version:
 - OS: 
 - Browser (Optional):
 
**Additional context**

**Comment by Lendemor** [comment]
Solved by #1797
