### ISSUE TITLE
Replit can't normal use

### ISSUE THREAD

**Issue by kai648846760** [reflex-dev/reflex#1323]
Using replit after the operation showed as follows

No code has been written.

The following commands are executed.
```bash
pip install reflex

mkdir my_app_name
cd my_app_name
reflex init
reflex run
```

Python : 3.10.8
OS : Linux 1d430db8ba03 5.19.0-1027-gcp #29~22.04.1-Ubuntu SMP Thu Jun 22 05:13:17 UTC 2023 x86_64 GNU/Linux

![image](https://github.com/pynecone-io/pynecone/assets/53172671/80adae2e-45e7-42bb-99ef-5cbf7fdeed92)

**Comment by masenf** [comment]
Can you provide more information, such as what code and commands you're running

**Comment by kai648846760** [comment]
> Can you provide more information, such as what code and commands you're running

I think I know what the problem is, because reflex will open two ports, and the url provided by replit will randomly use one port, so this phenomenon is caused.

**Comment by kai648846760** [comment]
The workaround is to add to the.replit file
[[ports]]
localPort = 8000
externalPort = 3000
