### ISSUE TITLE
Avoid automatic database table creation

### ISSUE THREAD

**Issue by siddhantgoel** [reflex-dev/reflex#1330]
**Describe the bug**
On startup, Reflex automatically creates a database table for all the models marked with `table=True`. In case the developer is using a different way to manage database tables (eg. Alembic migrations) the two conflict with each other.

In development, this means if I define a new model, Reflex will automatically reload the codebase and end up creating a database table right away, which leads to the Alembic migration file being empty.

The current workaround is to stop the main development server, generate the Alembic migration file and run the migrations, and then start the development server again.

It would be convenient if the automatic table creation could be put behind a configuration variable of some sort.

**Expected behavior**
A configuration variable (eg. `auto_create_tables` but naming is open) that controls whether database tables are automatically created on startup. The default value can be set to `True` to keep the existing behavior.

**Screenshots**
-

**Specifics (please complete the following information):**
 - Python Version: 3.11
 - Reflex Version: 0.2
 - OS: macOS
 - Browser (Optional):
 
**Additional context**
-

**Comment by masenf** [comment]
i can include a configuration knob as part of #1321

**Comment by siddhantgoel** [comment]
Awesome, I spent some time last week integrating Alembic into my project but it's good to see Alembic support being built in to Reflex. 🎉

The PR you linked to is already merged, so I assume the configuration knob is part of #1336?

Two questions came to mind when looking over those changes (and I hope it's OK I ask them here!).

1. With the addition of `Model.automigrate`, I wonder if `Model.create_all` is still needed? Or is it an intermediate thing that will be removed when Alembic support is released?
2. Autogenerated Alembic migrations generally include a note that the user should check the generated code before the migrations are run. From that perspective, it would be a bit more ergonomic if we wouldn't default to automatically generating and running the migrations in one go, but rather separate the two stages.

Thanks for implementing this feature!

**Comment by masenf** [comment]
@siddhantgoel alright #1336 is all polished up and ready for review. would love your feedback if you have time.

**Comment by siddhantgoel** [comment]
Awesome, I just left a few comments.

**Comment by masenf** [comment]
Fixed in reflex-0.2.1: database creation is _never_ automatic anymore. All db schema interaction and migrations are now exposed via `reflex db init`, `reflex db makemigrations` and `reflex db migrate`. We will be updating https://reflex.dev/docs/database/overview and https://reflex.dev/docs/api-reference/cli which describe the new flow.

#1321 
#1336 
#1362
