### ISSUE TITLE
reflex init error: UnicodeDecodeError: 'gbk' codec can't decode byte 0x93 in position 189: illegal multibyte sequence

### ISSUE THREAD

**Issue by evandeng2009** [reflex-dev/reflex#1332]
**Describe the bug**
reflex init and upgrade Pynecone project, errors as following:
`
  File "C:\Program Files\Python311\Lib\fileinput.py", line 251, in __next__
    line = self._readline()
           ^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\fileinput.py", line 372, in _readline
    return self._readline()
           ^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'gbk' codec can't decode byte 0x93 in position 189: illegal multibyte sequence
`

**To Reproduce**
 - Code/Link to Repo:

**Expected behavior**

**Screenshots**

**Specifics (please complete the following information):**
 - Python Version:
 - Reflex Version:
 - OS: 
 - Browser (Optional):
 
**Additional context**

**Comment by ElijahAhianyo** [comment]
can you provide the code to reproduce this error?

**Comment by evandeng2009** [comment]
Is it related to this issue? https://hub.fgit.ml/pynecone-io/reflex/issues/1244.

Not sure which part of code should I post here.

**Comment by evandeng2009** [comment]
Is it related to or similar with this issue https://github.com/pynecone-io/reflex/issues/1244?
Not sure which part of code should I post there.
