### ISSUE TITLE
Set an event handler for a button so that it will call browser-side JavaScript code.

### ISSUE THREAD

**Issue by milochen0418** [reflex-dev/reflex#1346]
**Describe the bug**

### Feature 

I know how to write simple html/javascript code and put them in the WebView of mobile 
so that iOS native apps and Android native apps can communicate to the webpage in the WebView. 

I am evaluating an outsourcing case to make iOS/Android mobile app. 
I will put the reflex web app in the WebView in the iOS/Android mobile app. 

- Scenario 1 
Still can show ID as QRCode from the native app when mobile's internet  is offline 
When mobile is in the offline status, there is a button in the web app, and the user can click it 
to trigger the function in the iOS/android native app to show the QRCode for some string.  
This string will be some special ID of a VIP member in the group.  
We hope they can still show their ID to check even if their mobile cannot connect to the internet.

- Scenario 2
mobile's internet is online in this scenario. 
When the user wants to scan QRCode, they can click the button in the web app. 
Click this button will call browser-side javascript code to trigger iOS/android native app
to show the camera to scan QRCode. 

When iOS/Android native app gets the scan result as a string from QRCode, 
it can send the string to the web app in the WebView by the API route. 

**To Reproduce**
 - Code/Link to Repo:

**Expected behavior**

**Screenshots**

**Specifics (please complete the following information):**
 - Python Version:
 - Reflex Version:
 - OS: 
 - Browser (Optional):
 
**Additional context**

**Comment by picklelo** [comment]
We can definitely support this - just have to think of the correct API design
1) How should the user define their custom JS functions
2) How to reference those functions from an event trigger

Will think more about this, feel free to post any ideas in this thread.

**Comment by milochen0418** [comment]
@picklelo 


### Final Result  (We expected from Idea )

Q1: How should the user define their custom JS functions
My answer is set all of your functions in `script_tags` when add_page. 

Q2: How to reference those functions from an event trigger
My answer is to use 
`yield rx.browser_js_call("{'__func__':'test_func', 'myname':'Milo', 'myaction':'Jump'  }")`
or `yield rx.browser_js_call(some_dict_obj )`





I did some experiments on the current code.
This is my plan. 

### experiments
I can set the script_tags attribute in add_page  
So that all of the functions we want to call can be set in the script 

In the script, I also put the following code to override the `window.alert("")` function 
```javascript
window.alert = function(msg){console.log(msg);};
```
When I use the following function in the event handler and trigger it
```python
yield rx.window_alert("ABCDE")
```
I can see the console show ABCDE. 

**The above experiment is working. 

### Step 2. 

```python
yield rx.window_alert("{'__func__':'test_func', 'myname':'Milo', 'myaction':'Jump'  }")
```


```javascript
window.alert = function(msg){
  //TODO...
  //if msg is  "{'__func__':'test_func', 'myname':'Milo', 'myaction':'Jump'  }", then 
  //this function will call the following test_func function to show the result "Milo:Jump" in console.log
};
function test_func(obj) {
  console.log(obj.myname + ":" + obj.myaction )
}

```

### Step 3. 
Research how to add a Special Event by referring to the implementation code of `rx.window_alert`  or `rx.console_log`. 
I can add this special event `browser_js_call`  
```python
yield rx.browser_js_call("{'__func__':'test_func', 'myname':'Milo', 'myaction':'Jump'  }")
```
And add the default javascript code of browser_js_call on all pages.

**Comment by milochen0418** [comment]
> We can definitely support this - just have to think of the correct API design
> 
> 1. How should the user define their custom JS functions
> 2. How to reference those functions from an event trigger
> 
> Will think more about this, feel free to post any ideas in this thread.

@picklelo 
This is the idea to implement to call browser-side javascript. 
https://www.youtube.com/watch?v=_gfbeOXPD6g <-- demo video 
https://github.com/milochen0418/reflex-call-browser-js <-- implementation on front-end by override window.alert temporary. 

For this way to call browser-side JS, I will make a new special event, its implementation may be similar to rx.console_log or rx.alert_window. 

I will send a PR to solve the issue tomorrow for the final step.
