### ISSUE TITLE
Failed to use alternative backend port other than 8000

### ISSUE THREAD

**Issue by cgjosephlee** [reflex-dev/reflex#1347]
**Describe the bug**
Change backend port to any number other than 8000, the app still listens to port 8000 and all interactions with `State` are not functioning.

**To Reproduce**
 - `reflex run --frontend-port 3800 --backend-port 9800`

**Expected behavior**
The app should be able to use port 9800.

**Screenshots**
Console log:
![截圖 2023-07-17 上午11 00 46](https://github.com/reflex-dev/reflex/assets/12654602/cfe5a1b4-6634-4911-be87-79f4a956220a)

**Specifics (please complete the following information):**
 - Python Version: 3.9
 - Reflex Version: 0.2.0
 - OS: macOS
 - Browser (Optional): Chrome
 
**Additional context**

**Comment by ElijahAhianyo** [comment]
What you want to do is set the `api_url` to `http://localhost:9800` in your `rxconfig.py`. The `api_url` is used for client-server communication and may not necessarily be the same as that of the server

**Comment by cgjosephlee** [comment]
Thank you, the issue is solved. Now I can change port under CLI (or get prompted to use another port because 8000 is occupied), but I still have to edit `rx_config.py` to make it work. This flow might be confusing.
