### ISSUE TITLE
Expose SQLALCHEMY_ECHO like sqlalchemy-flask

### ISSUE THREAD

**Issue by masenf** [reflex-dev/reflex#1351]
For debugging, it should be simple to set this common environment variable to allow creation of the engine with `echo=True`

**Comment by SlamChillz** [comment]
Hi @masenf I will like to work on the issue. Please assign it to me, thank you.

**Comment by SlamChillz** [comment]
Thank you @masenf. I will reach out if I encounter any issues.

**Comment by SlamChillz** [comment]
Hi @masenf, I have made a PR for this issue, please kindly review and let me know what changes to effect, thank you.
