### ISSUE TITLE
Add missing props for breadcrumb_link

### ISSUE THREAD

**Issue by picklelo** [reflex-dev/reflex#1366]
Currently it is missing props such as `href`. It should have all the props that `breadcrumb_item` has.

**Comment by markthepixel** [comment]
following

**Comment by Lendemor** [comment]
working on this as a side product of fixing #1365

**Comment by Billa05** [comment]
> Currently it is missing props such as `href`. It should have all the props that `breadcrumb_item` has.

do you mean these prop:
![Screenshot 2023-10-02 163448](https://github.com/reflex-dev/reflex/assets/90760974/b1b572ee-6767-4471-abe4-fa532c4f7aa9)
 or the classmethod?

**Comment by Billa05** [comment]
by missing prop do you mean these:
![Screenshot 2023-10-02 163448](https://github.com/reflex-dev/reflex/assets/90760974/04519237-9bd7-4a48-9be6-4681f4233e16)
 if yes should I also add the classmethod for herf?

**Comment by masenf** [comment]
Now that BreadcrumbLink inherits from Link, I think this issue has been solved. Can someone confirm that `breadcrumb_link` supports `href` now?
