### ISSUE TITLE
pc.init does not check process exit code when installing bun

### ISSUE THREAD

**Issue by siddhantgoel** [reflex-dev/reflex#1372]
**Describe the bug**
I just ran into a situation where I pushed my Reflex project to Fly and when Fly was building the Docker image, there were some issues with validating Github's SSL certificate, because of which `bun` installation failed.

Here's the relevant `reflex init` log from build time:

```
root@de9d849ca1d4:/code# poetry run reflex init 
───────────────────────────────────────────────────────────────────────────────────────────────────────────── Initializing code ──────────────────────────────────────────────────────────────────────────────────────────────────────────────
[17:57:45] Installing bun...                                                                                                                                                                                                     console.py:30
curl: (60) SSL: no alternative certificate subject name matches target host name 'objects.githubusercontent.com'
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.

error: Failed to download bun from "https://github.com/oven-sh/bun/releases/download/bun-v0.6.9/bun-linux-x64-baseline.zip"
[17:57:47] Initializing the web directory.                                                                                                                                                                                       console.py:30
[17:57:48] Finished Initializing: code                                                                                                                                                                                           console.py:30
]
```

This was somewhat tricky to debug because when building the Docker image, those error logs didn't show up, so I had no idea why the frontend was complaining about `bun` not being installed.

It would be nice if `pc.init` would check the status code of intermediate commands (particularly the `os.system(constants.INSTALL_BUN)` in this case) and exit if there was a problem.

**To Reproduce**
 - Code/Link to Repo:

**Expected behavior**
If `os.system(constants.INSTALL_BUN)` fails, exit with an error code

**Screenshots**

**Specifics (please complete the following information):**
 - Python Version: 3.11
 - Reflex Version: 0.2
 - OS: linux/amd64 (docker)
 - Browser (Optional):
 
**Additional context**

**Comment by siddhantgoel** [comment]
(I'm happy to submit a patch if you like.)

**Comment by masenf** [comment]
this isn't the only place we're swallowing potentially useful errors and exit codes. see #1285 as well.

> (I'm happy to submit a patch if you like.)

🥺 if we could only be so lucky 🙏
