### ISSUE TITLE
Support missing props for Heading

### ISSUE THREAD

**Issue by picklelo** [reflex-dev/reflex#1377]
We are missing some important props such as the `as` prop which lets you set the element type. Heading should probably inherit from `rx.Box` based on these Chakra docs: https://chakra-ui.com/docs/components/heading

**Comment by rahulsingh03** [comment]
I think this Issue should be marked  as closed. The **rx.heading()** has a "as_"  prop which accepts the element type, it has "h2" tag as default value.
This was solved in #1416 PR.

**Comment by masenf** [comment]
Thanks for pointing this out!
