### ISSUE TITLE
Allow linebreaks in rx.text()

### ISSUE THREAD

**Issue by markthepixel** [reflex-dev/reflex#1406]
**Description**
When writing content (manually or dynamically) I want to be able to put in a line-break without having to use a more complex foreach loop or separate tags. Additionally, by having to do a workaround (e.g. using html or markdown) the default classes from the `<p>` will be missing.

**Rational**
While this seems trivial, it seems to be common in discord and I myself have experiences a few times. Additionally, content stored in the database that isn't use full html or full markdown still use line breaks to convey ideas and insights. Therefore it's reasonable to want this functionality from the mask text tags (more than just `rx.text()`, for example `rx.heading()`.

**Work Around**
If you're interested in a `<p>` tag with a line break you have a few options,
1. If dynamic, you can use a loop and `rx.text()` inside it
2. You can manually type out `rx.text()` tags for each
3. You can use an markdown (`\n\n`) or html tag (`<br>`) [e.g.  `rx.html("foo<br/>bar", element="p")`]

**Proposed Solution**
In a perfect world you'd add a prop for `linebreak` and allow me to set it to either `\n`, `\n\n`, or `<br>` within the existing `rx.text()` tag. This would allow me to do more with less code.

**Comment by masenf** [comment]
There is quite a bit of detail here, but I'm still unclear on what the ask is. Can you provide an example? Based on my interpretation, I'm thinking you want something like

```python
rx.text("""foo
bar
baz""")
```

to render out the same as

```python
rx.html("foo<br/>bar<br/>baz", element="p")
```

**Comment by samcloudcode** [comment]
To add to this, rx.text() does not generate new lines as expected. This causes issues in rx.markdown as well given the paragraphs are rendered as rx.text(),

For example, I start with:
'This is text with a new line:
new line'

It renders as:
'This is text with a new line: new line'

If I give it the text:
'This is text with a new line:

new line'

It renders as:
'This is text with a new line: 
new line'

**Comment by picklelo** [comment]
`rx.markdown` is fixed now and can be used to render text with multiple line breaks as well. Closing this issue as there's a few solutions available.
