### ISSUE TITLE
Move bun and nvm configs to ~/.reflex folder

### ISSUE THREAD

**Issue by picklelo** [reflex-dev/reflex#1407]
When a user runs `reflex init` we install bun for them in the `~/.bun` directory. After #1381 is implemented, we will end up also creating a `~/.nvm` directory by default.

Instead, we should create a single `~/.reflex` directory in the user's home folder, and include these as subfolders `~/.reflex/.bun` and `~/.reflex.nvm`

This will make it easier to manage all of reflex's dependencies in one directory.

**Comment by TaiJuWu** [comment]
Great idea!
