### ISSUE TITLE
Keep bun and node versions fixed within reflex

### ISSUE THREAD

**Issue by picklelo** [reflex-dev/reflex#1408]
Currently we use the user's default `node` installation and allow the user to specify a `bun_path` in the `rxconfig.py`. We should hide these dependencies and handle them under the hood.

The user shouldn't need to ever manage node or bun settings. Fixing the version will also make the package more reliable as we can control when to upgrade versions.

**Comment by milochen0418** [comment]
@picklelo 
The developer has their nodejs developing the environment with some specific version. 
When doing this way, you need to ensure no side effects on their original environment. 
At least the path of `which node` would not be changed after installing reflex.
