### ISSUE TITLE
Event handler chaining is non-deterministic.

### ISSUE THREAD

**Issue by stuz5000** [reflex-dev/reflex#1422]
To reproduce `reflex run`:
```
import reflex as rx

class State2(rx.State):
    text: str

    def f1(self):
        print("f1")
    def f2(self, arg):
        print(f"f2 {arg}")

    def onClick(self):
        print("---")
        yield State2.f1()
        yield State2.f1()

        yield State2.f2(123)  
        yield State2.f1()

def index():
    return rx.box(
        rx.button("Confirm", on_click=State2.onClick),
    )

app = rx.App(state=State2)
app.add_page(index)
app.compile()
```

Smash the click button many time and see the following:
```
[Updating App] Applying changes and refreshing. Time: 2023-07-25 14:39:08.065674
---
f1
f1
---
f1
f1
---
f1
f1
---
f1
f1
f1
---
f1
f2 123
---
f1
f1
---
f1
f1
---
f1
---
f1
f1
```

Four bugs:
- f1 is never executed 3 times
- sometimes f2 is executed, sometimes not
- sometimes f1 is just executed once before f2, sometimes twice
- sometimes f1 is executed just once, and nothing else

Behavior is similarly broken with just
```
    def onClick(self):
        print("---")
        yield State2.f1()
        yield State2.f2(123)  
```
... where f2 sometimes do not execute.

Switching all methods to `async def` - no change in behavior.

Event handler arguments makes no difference. Fails as above:
```
class State2(rx.State):
    async def f1(self):
        print("f1")

    async def f11(self):
        print("f11")

    async def onClick(self):
        print("---")
        yield State2.f1()
        yield State2.f11()
```
---------------
reflex==0.2.0
python 3.10

**Comment by stuz5000** [comment]
The following seems to work fine:

```
class State2(rx.State):
    text: str

    async def f1(self):
        print("f1")
    async def f11(self):
        print("f11")
    async def f2(self, arg):
        print(f"f2 {arg}")

    async def onClick(self):
        print("---")
        return [State2.f1(), State2.f1(), State2.f2(123), State2.f1()]
```

**Comment by Lendemor** [comment]
I'm investigating this issue.

What is worthy to note is that yielding an event will not execute it immediately, but rather append it at the end of the event queue, and will be executed after current event handler (and other event in the loop) have finished running.

The following code is deterministic : 
```python
class State(rx.State):
    def f1(self):
        print("f1")

    def f2(self, value):
        print(f"f2 {value}")

    async def onClick(self):
         self.f1()
         self.f1()
         await self.f2(123)
         self.f1()
```

If you want to trigger and send update to frontend between some calls, use a line with an empty `yield` .

**Comment by masenf** [comment]
Data point: unable to reproduce this on 0.2.3:

```console
---
f1
f1
f2 123
f1
---
f1
f1
f2 123
f1
---
f1
f1
f2 123
f1
---
f1
f1
f2 123
f1
```

**Comment by stuz5000** [comment]
Yes -- the reason I did this was because of another issue:

self.isBusy = False
yield
try:
   await self.long_action()
finally:
   self.isBusy = True
   yield

Didn't result in a busy-spinner being updated correctly, but it did work if
I do:

return [
   State.set_busy(),
   State.long_action(
   State.unset_busy(),
]
---

This was with 0.2.0.
I'll retry with 0.2.3

**Comment by Lendemor** [comment]
Following code tested on the related PR : 

```python
class State(rx.State):
    busy: bool = False

    async def long_action(self):
        await asyncio.sleep(10)

    async def onClick(self):
        self.busy = True
        yield

        try:
            await self.long_action()
        finally:
            self.busy = False
            yield


@rx.page()
def index():
    return rx.vstack(
        rx.button("Click here", on_click=State.onClick),
        rx.cond(
            State.busy,
            rx.circular_progress(is_indeterminate=True),
            rx.text("Not busy"),
        ),
        height="100vh",
    )
```

Display correctly the spinner

**Comment by stuz5000** [comment]
> Data point: unable to reproduce this on 0.2.3:

I still see this after upgrading to 0.2.3

```
$ pip freeze | grep reflex
reflex==0.2.3
```

(Code modified to print time between events)
```
f2 123
f1
--- dt=-0.182
f1                   # ******
f1
--- dt=-0.186
f1
f1
f2 123
f1
--- dt=-0.202
f1
f1
f2 123
f1
--- dt=-0.176
f1
f1
f2 123
f1
--- dt=-0.494
f1
f1
f2 123
f1
--- dt=-0.272
f1
f1
f2 123
f1
--- dt=-0.812
f1                             # ******
f2 123
f1
--- dt=-0.932
f1
f1
f2 123
f1
```
