### ISSUE TITLE
Add more common var operations

### ISSUE THREAD

**Issue by picklelo** [reflex-dev/reflex#1426]
Currently we only support a very limited set of var operations: https://reflex.dev/docs/api-reference/var

We should support all the common javascript functions. For example it should be possible to do something like

```python
rx.cond(State.my_list.contains("value"), "a", "b")
```

**Comment by nick-youngblut** [comment]
In the docs at https://reflex.dev/docs/state/vars/, there is a broken link: https://reflex.dev/docs/state/docs/api-reference/var/

**Comment by picklelo** [comment]
In the future we will allow user-defined custom var operations instead.
