### ISSUE TITLE
Clean up configuration

### ISSUE THREAD

**Issue by picklelo** [reflex-dev/reflex#1433]
We need to make all the config params consistent in how we load them and pass them through the program. Currently some params such as `timeout` are note being respected in the config

**Comment by danik292** [comment]
Okay in which in which file is stored  configuration information?

**Comment by picklelo** [comment]
It's currently in `reflex/config.py` and the constants are in `reflex/constants.py`.

**Comment by danik292** [comment]
Ok I am going to check it

**Comment by danik292** [comment]
What exactly should I do?
