### ISSUE TITLE
Input default_value not updating after state change

### ISSUE THREAD

**Issue by samcloudcode** [reflex-dev/reflex#1436]
**Describe the bug**
When linking a input to a state variable, it seems the following two options are available:
1) value=variable, on_change=[function to update state variable]; or
2) default_value=variable, on_blur=[function to update state variable];

For several reasons, the 2) is often preferable, however when changing variable, default_value is sometimes updated, and other times not.

**To Reproduce**
https://github.com/samcloudcode/Reflex_bug_report.git
## Behaviour 1:
a) On initial site load (or after adding a new List item), changing first input box works as expected: input below and Content field changes on any change
b) On initial site load, changing second input box works as expected: input above and Content field changes on any blur
After testing b), the behaviour of a) changes. When you change the first input field, the second one (linked to default_value) no longer updates, unless you reload the page.

## Behaviour 2:
a) Save to json
b) Change some input fields, retrieve from json 
⇒ value + on_change works as expected
⇒ default_value + on_blur works as expected
c) Repeat, retrieve from json:
⇒ value + on_change works as expected
⇒ default_value + on_blur does not update unless you reload page

## Behaviour 3:
a) Change the index of an item under Single item test (first input box) ⇒ works as expected
b) Change the default_value + on_blur input box, then a) does not work as expected

**Specifics (please complete the following information):**
 - Python Version: 3.11
 - Reflex Version:"==0.2.3a7"
 - OS: "Windows"
 - Browser: "Chrome"

**Comment by picklelo** [comment]
With the merging of #1484 we should now be able to use controlled inputs (`value` + `on_change`) without any performance hits. We will update the docs to indicate this as the preferred way to deal with inputs, instead of using `rx.set_value`.

**Comment by picklelo** [comment]
@samcloudcode This is actually expected behavior it turns out. Once you've typed into the input, the `default_value` prop won't work anymore, which is why we see this behavior.
