### ISSUE TITLE
Update Google Font docs

### ISSUE THREAD

**Issue by markthepixel** [reflex-dev/reflex#1449]
**Describe the bug**
Confirm a the CSS sheet from Google Fonts is required; if it is updated, the docs to reflect that resource is needed and where to get it from Google Fonts's site.

**Page in docs that needs updating:**
https://reflex.dev/docs/styling/custom-stylesheets

**Example of someone getting confused for added context**
https://discord.com/channels/1029853095527727165/1134283973086945291

**Comment by picklelo** [comment]
Docs are updated now
