### ISSUE TITLE
Any way to make Reflex faster?

### ISSUE THREAD

**Issue by evandeng2009** [reflex-dev/reflex#1464]
**Describe the bug**
app.js and index.js is bigger than 1MB and take the most of the page loading time.  How to make it download faster? Right now I have a proxy standing before Reflex app.

**To Reproduce**
 - Code/Link to Repo:

**Expected behavior**

**Screenshots**

**Specifics (please complete the following information):**
 - Python Version:3.7
 - Reflex Version:0.1.34
 - OS: 
 - Browser (Optional):
 
**Additional context**

**Comment by Alek99** [comment]
Are you running in dev or prod mode just check the app.js on the deployed reflex.dev and its around 256kb, but locally in dev mode it was much larger

**Comment by Alek99** [comment]
This ticket should also reduce page size for specific apps with larger state https://github.com/reflex-dev/reflex/issues/1465

**Comment by evandeng2009** [comment]
Run with --env prod does make app.js and index.js much smaller.  Yes @Alek99 , page size is worthy of thinking about it as my pressure test tolds me that my app can accept only a few users simultaneously while it just has very little data to be loaded, but my bandwith 10Mb/s is full.
