### ISSUE TITLE
Factor out State in Every JS File

### ISSUE THREAD

**Issue by Alek99** [reflex-dev/reflex#1465]
Right now the compiles reflex code has:

```js
const [state, setState] = useState(...)
```

in every compiled js file. We should factor this out into a single file to reduce compiled file size.

I noticed this on rxweb when we had an image in our state and see the contents of the .web x2 the size it could be if we factor this out.

**Comment by Alek99** [comment]
This would also significantly improve compile times for apps like rxweb as a result

**Comment by picklelo** [comment]
Merged in #1599
