### ISSUE TITLE
`v0.2.3` breaks `bun_path` without warning

### ISSUE THREAD

**Issue by worldofgeese** [reflex-dev/reflex#1470]
**Describe the bug**  
As of Reflex version `v0.2.3`, the support for specifying a custom `bun_path` has been dropped, breaking compatibility with non-FHS compliant distros like Guix System and NixOS. When trying to run Reflex, it fails due to this missing support, even when manual workarounds are attempted, such as manually creating the `bun` path or touching an executable `bun`.

**To Reproduce**  
1. On a Guix System or NixOS (or other non-FHS compliant distros), upgrade Reflex to `v0.2.3`.
2. Try to run Reflex with a custom `bun_path`.
3. Observe the errors indicating the absence of the `bun` executable in the specified path, even if the path and executable are manually created.

**Expected behavior**  
Reflex should respect the custom `bun_path` and allow users to use their own Bun installation. In environments where Reflex's default method of managing Bun isn't feasible, users should be able to provide their own path, disabling built-in checks and installations, allowing Reflex to just use what's provided without guarantees.

**Specifics (please complete the following information):**  
 - Python Version: 3.11
 - Reflex Version: 0.2.3
 - OS: Guix System and NixOS (non-FHS compliant distros)
 
**Additional context**  
The removal of `bun_path` support impacts users of non-FHS compliant distros significantly. Reflex's decision to manage its own Bun installation and dependencies makes it incompatible with these systems due to their unique file system hierarchy and dependency management. It's crucial for Reflex to allow flexibility for users in such environments to specify custom paths for dependencies. This used to work in version `v0.2.2` and its removal in `v0.2.3` has rendered Reflex unusable for a segment of its user base.

For logs and additional info, please begin reading from issue https://github.com/reflex-dev/reflex/issues/574#issuecomment-1657737762

cc @ElijahAhianyo @Alek99

**Comment by picklelo** [comment]
Thanks for bringing this up. We intended to simplify the user configuration, but you make a good point about maintaining flexibility. We will bring back the `bun_path` option for the next release.

Did you face any other issues with the `~/.reflex` directory creation? We are also managing our own node package in there, would you need the option to specify your node path also?

**Comment by worldofgeese** [comment]
@picklelo thank you so much! I really appreciate it.

> Did you face any other issues with the ~/.reflex directory creation? We are also managing our own node package in there, would you need the option to specify your node path also?

If I run `tree` against the `.nvm` directory inside `.reflex` it looks like everything's in the right place. I do have the required `node` version installed. 

<details>

```console
/home/worldofgeese/.reflex/.nvm/
├── alias
│   ├── default
│   └── lts
│       ├── *
│       ├── argon
│       ├── boron
│       ├── carbon
│       ├── dubnium
│       ├── erbium
│       ├── fermium
│       ├── gallium
│       └── hydrogen
├── bash_completion
├── CODE_OF_CONDUCT.md
├── CONTRIBUTING.md
├── Dockerfile
├── GOVERNANCE.md
├── install.sh
├── LICENSE.md
├── Makefile
├── nvm-exec
├── nvm.sh
├── package.json
├── PROJECT_CHARTER.md
├── README.md
├── rename_test.sh
├── ROADMAP.md
├── test
│   ├── common.sh
│   ├── fast
│   │   ├── Aliases
│   │   │   ├── circular
│   │   │   │   ├── nvm_resolve_alias
│   │   │   │   ├── nvm_resolve_local_alias
│   │   │   │   ├── setup
│   │   │   │   └── teardown
│   │   │   ├── lts
│   │   │   │   ├── 'nvm alias' should ensure LTS alias dir exists
│   │   │   │   ├── setup_dir
│   │   │   │   └── teardown_dir
```

</details>

Where immutable systems like NixOS/Guix System break down is typically around any system path expectations. As my `node` is coming from Nixpkgs, any virtually managed environments spawned by it should generally *just work*. Where dependencies require loaders and system libraries is where it gets real hairy.

I'll just put this bit from my comment in the other issue here, should it be an easy enough fix. I can manage with the current `v0.2.2` level of friction: the most important request is a workaround to run Reflex exists. Again, tremendous thanks for agreeing to put `bun_path` back! ❤️ 

> Ideally, users should be able to provide their own Bun path, disable version checks, and disable Reflex's built-in method for installing Bun to run in atypical environments. In other words, disable all Bun-related checks and sourcing and just run whatever is provided at bun_path without guarantees.

**Comment by worldofgeese** [comment]
@picklelo it looks like this missed the v0.2.4 milestone, can it be added to v0.2.5's?

**Comment by ElijahAhianyo** [comment]
@worldofgeese I'm taking this up, there should be a PR for this soon

**Comment by worldofgeese** [comment]
@ElijahAhianyo great! Happy to help you test or whatever else you need from me.

**Comment by worldofgeese** [comment]
@ElijahAhianyo I'll be back home tomorrow: will test then

**Comment by kraanzu** [comment]
It also looks like its installing nodejs in .local/share/relfex/...

How did you tackle that @worldofgeese ? I cant seen to find an option which overrides it
