### ISSUE TITLE
data_table: allow customization of the search bar

### ISSUE THREAD

**Issue by Lendemor** [reflex-dev/reflex#1474]
when using `search=True` in `data_table`, we need to be able to customize the search bar (style/ functionality )

**Comment by Alek99** [comment]
We will probably have to switch libraries if we want todo this.


Or they will need to make there own out of the table + input component

**Comment by picklelo** [comment]
this is now covered in the [table recipes](https://reflex.dev/docs/library/datadisplay/table#sorting-and-filtering-(searching))
