### ISSUE TITLE
Invalid link Should have an error message 

### ISSUE THREAD

**Issue by Alek99** [reflex-dev/reflex#1486]
**Describe the bug**

Right now if an invalid link is passed in you have to see the error in the browser, instead we should catch this during compile time.

**To Reproduce**
 - Code/Link to Repo:
```python
rx.link(
      rx.text("Roadmap"),
      href="",
 )
```

This error message in the browser
```
Server Error
Error: Failed prop type: The prop `href` expects a `string` or `object` in `<Link>`, but got `undefined` instead.
This error happened while generating the page. Any console logs will be displayed in the terminal window.
```

**Expected behavior**

Should thow an error message in the terminal during compile time like "invalid hrek passed in rx.link ..."

**Screenshots**

![Screenshot 2023-07-31 at 6 11 16 PM](https://github.com/reflex-dev/reflex/assets/38776361/2782795c-7021-4ef0-bca9-c77e6b05e818)

**Comment by Alek99** [comment]
If its a relative path we could even inspect the valid pages compiled

**Comment by Alek99** [comment]
Could also extend this to image src

**Comment by danik292** [comment]
@Alek99  please close it it was resolved via different PRs
