### ISSUE TITLE
reflex export should fail if zipping fails

### ISSUE THREAD

**Issue by jackie-pc** [reflex-dev/reflex#1506]
We call `os.system` to create fronted.zip or backend.zip (or both).

If zip is not available, reflex export terminates with exit code 0.  This should not be the case.

We should take this opportunity to simply migrate this logic to [Python](https://docs.python.org/3/library/zipfile.html) itself.  This removes the dependency on `zip` CLI altogether and will be fully portable across OSes by design.  When we do this migration, we should ensure we propagate any errors and failures properly to `reflex` CLI invoker.

**Comment by martinxu9** [comment]
tracking this internally as REF-264
