### ISSUE TITLE
Failed to clone nvm repo. Please report this!

### ISSUE THREAD

**Issue by raven-black-dream** [reflex-dev/reflex#1507]
**Describe the bug**

Running "reflex init" on a newly created directory gives the following error:

reflex init --loglevel debug
───────────────────────────────── Initializing Base45Reflex ──────────────────────────────────
Debug: Running command: ['/home/evan/.reflex/.bun/bin/bun', '-v']
Debug: Running command: ['/home/evan/.reflex/.nvm/versions/node/v18.17.0/bin/node', '-v']
[13:53:36] Initializing the web directory.                                       console.py:81
Debug: Downloading https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh
Debug: Running command: ['bash', '/tmp/tmp1e44lg70']
Debug: Installing https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh
Debug: => Downloading nvm from git to '/home/evan/.reflex/.nvm'
Debug: 
Debug: => Cloning into '/home/evan/.reflex/.nvm'...
Debug: fatal: invalid branch name: init.defaultBranch = 
Debug: Failed to clone nvm repo. Please report this!
Error: Error during Installing https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh
Error: Run in with --loglevel debug to see the full error.

**To Reproduce**
 - Code/Link to Repo:

" mkdir Base45Reflex
  cd Base45Reflex
  reflex init "

**Expected behavior**
Initialize the project

**Screenshots**

**Specifics (please complete the following information):**
 - Python Version: 3.11.4
 - Reflex Version: 0.2.3
 - OS: Ubuntu 22.04.2
 - Browser (Optional):
 
**Additional context**

**Comment by milochen0418** [comment]
> fatal: invalid branch name: init.defaultBranch =

Is it helpful for you?
https://stackoverflow.com/questions/64349920/git-error-fatal-invalid-branch-name-init-defaultbranch

**Comment by raven-black-dream** [comment]
That did in fact help. Thank you.
