### ISSUE TITLE
"Strongly Advising" Windows Subsystem for Linux (WSL) for "optimal performance" is sub-optimal nomenclature

### ISSUE THREAD

**Issue by Pebaz** [reflex-dev/reflex#1511]
**Describe the bug**
When a user initializes a new Reflex project on Windows using `reflex init`, a warning shows up that says:

```
Warning: We strongly advise using Windows Subsystem for Linux (WSL) for optimal performance with reflex.
```

This is sub-optimal because it seems to show that the Reflex project doesn't care about Windows users, which goes against many of the values adhered to by free software advocates. A better wording is needed like: "Windows is not supported but we're working on it".

To see Linux projects hold Windows users in contempt has always felt unprofessional to me. The thing is, if a project can support Windows, it can support anything.

I'm sure you want Windows users to feel appreciated, welcomed, and valued and I know it will take time to fully support Windows but until then there needs to be less-confrontational wording in an official advisory.

**To Reproduce**

Run `reflex init` on a Windows host.

**Expected behavior**

There is no technical reason why Reflex cannot run on Windows so I expected it to run on Windows just fine or have Windows support planned.

**Screenshots**
N/A

**Specifics (please complete the following information):**
Not applicable to issue other than the OS is Windows and Reflex version `0.2.3`.
 
**Additional context**
I'm extremely excited about how professional this project is but there needs to be more inclusive wording to not alienate users simply on account of their OS when there's no technical reason not to (eventually) provide support for all major platforms.

**Comment by Alek99** [comment]
We do support windows but one of our dependencies bun (a faster replacement for node) doesn't yet. 

So on non windows systems we are able to replace node with bun, hence the performance improvement. Once this becomes available for windows we will be able to make this improvement available for our windows users.

**Comment by Tooblippe** [comment]
It seems Bun is available for windows? But on the meantime how do i silence this warning?
