### ISSUE TITLE
The rxconfig.py seems doesn't work.

### ISSUE THREAD

**Issue by ClarenLee** [reflex-dev/reflex#1513]
**Describe the bug**
Seems rxconfig.py does't work with me,and Reflex  always works on port 3000.

**To Reproduce**
I  installed reflex(0.2.3) on my Windows,and  i cloned the reflex-examples to run the **twitter** example and it works on port 3000. Then i modify the rxconfig.py as follow:
```python
import reflex as rx

config = rx.Config(
    app_name="twitter",
    api_url='http://localhost:5000',
    db_url="sqlite:///reflex.db",
    env=rx.Env.DEV,
)
```
After excuting **reflex run**,it works still on port 3000,as the log shows below:
```
───────────────────────────────────────────────── Starting Reflex App ──────────────────────────────────────────────────
Compiling:  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 3/3 0:00:00
───────────────────────────────────────────── Installing frontend packages ─────────────────────────────────────────────
───────────────────────────────────────────────────── App Running ──────────────────────────────────────────────────────
Compiling:  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 3/3 0:00:00
App running at: http://localhost:3000
```
I have tried to run  the example **todo** with the same content of rxconfig.py,and the same result came out as follow:
```
───────────────────────────────────────────────── Starting Reflex App ──────────────────────────────────────────────────
Compiling:  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 1/1 0:00:00
───────────────────────────────────────────────────── App Running ──────────────────────────────────────────────────────
Compiling:  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 1/1 0:00:00
App running at: http://localhost:3000
```

Then i  repeat this on my ubuntu server,but still the same result as follow:
```
# cat rxconfig.py
import reflex as rx

class TestConfig(rx.Config):
    pass

config = TestConfig(
    app_name="Test",
    api_url="http://120.26.15.224:8000",
    # api_url="localhost:8000",
    #bun_path="/root/.reflex/.bun/bin/bun",
    db_url="sqlite:///reflex.db",
    #env=rx.Env.DEV,
)
# reflex run --env prod
───────────────────────────────────────────────────────────────────── Starting Reflex App ─────────────────────────────────────────────────────────────────────
Compiling:  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 1/1 0:00:00
Creating Production Build:  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 9/9 0:00:43
───────────────────────────────────────────────────────────────────────── App Running ─────────────────────────────────────────────────────────────────────────
App running at: http://localhost:3000
Compiling:  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 1/1 0:00:00
```

**Expected behavior**
If there anything wrong with my steps,please figure it out.
I expect to host reflex on my own server and i need the right way,thanks.

**Specifics (please complete the following information):**
Win:
 - Python Version:Python 3.9.9
 - Reflex Version:0.2.3
 - OS: Win11
 
Ubuntu Server:
- Python : 3.8
- Reflex Version : 0.2.3
- OS: Ubuntu  20.04.6 LTS

**More**
How can i gracefully stop the reflex task after i have excuted "reflex run"?

**Comment by ElijahAhianyo** [comment]
To run the frontend on a different port, you should set the `frontend_port` to the desired port number

**Comment by masenf** [comment]
as mentioned, the frontend port is controlled by `frontend_port` config key or `reflex run --frontend-port 3333` when running the service.

check out the docs for more information on the configuration knobs: https://reflex.dev/docs/api-reference/config/

> How can i gracefully stop the reflex task after i have excuted "reflex run"?

you should be able to send the reflex python process a `SIGINT` to stop the frontend and backend. if this isn't working, then we need a separate issue (#1515) to investigate that. i have noticed on windows that sometimes two CTRL-C are needed to actually stop the server, but do not reproduce this on mac or linux.

Finally, when running for production, you WILL want to `reflex run --env prod`, which makes things a lot faster.

I'm going to close this issue for now, but feel free to reopen or open new issues if you encounter further problems.

**Comment by ClarenLee** [comment]
> To run the frontend on a different port, you should set the `frontend_port` to the desired port number. The `api_url` is used by frontend to communicate with your backend server(this should typically be the url of your backend server)

Now it works , thanks.

**Comment by ClarenLee** [comment]
> as mentioned, the frontend port is controlled by `frontend_port` config key or `reflex run --frontend-port 3333` when running the service.
> 
> check out the docs for more information on the configuration knobs: https://reflex.dev/docs/api-reference/config/
> 
> > How can i gracefully stop the reflex task after i have excuted "reflex run"?
> 
> you should be able to send the reflex python process a `SIGINT` to stop the frontend and backend. if this isn't working, then we need a separate issue (#1515) to investigate that. i have noticed on windows that sometimes two CTRL-C are needed to actually stop the server, but do not reproduce this on mac or linux.
> 
> Finally, when running for production, you WILL want to `reflex run --env prod`, which makes things a lot faster.
> 
> I'm going to close this issue for now, but feel free to reopen or open new issues if you encounter further problems.

It works now ,thanks.
