### ISSUE TITLE
reflex run does not stop when CTRL-C is pressed (windows)

### ISSUE THREAD

**Issue by masenf** [reflex-dev/reflex#1515]
**Describe the bug**
On windows, `reflex run` command does not seem to stop when `CTRL-C` is pressed. Often need to `CTRL-C` a second time to exit the process.

**To Reproduce**
```console
reflex init
reflex run
```

Then press CTRL-C... it says the app is stopped, but it's still accessible

```console
────────────────────────────────────────── Initializing repro_ctrl_c_not_stop ──────────────────────────────────────────
[11:52:00] Initializing the web directory.                                                                 console.py:81
[11:52:01] Initializing the app directory.                                                                 console.py:81
Success: Initialized repro_ctrl_c_not_stop

(VENV-rel) C:\Users\masenf\code\reflex-dev\repro-ctrl-c-not-stop>reflex run
Warning: We strongly advise using Windows Subsystem for Linux (WSL) for optimal performance with reflex.
───────────────────────────────────────────────── Starting Reflex App ──────────────────────────────────────────────────
Compiling:  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 1/1 0:00:00
───────────────────────────────────────────────────── App Running ──────────────────────────────────────────────────────
App running at: http://localhost:3000
Compiling:  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 1/1 0:00:00
[12:00:01] Reflex app stopped.                                                                             console.py:81
```

Press CTRL-C a second time to get back to the prompt

```console
[12:01:34] Reflex app stopped.                                                                             console.py:81
```

**Expected behavior**
KeyboardInterrupt should exit the app and all subprocesses

**Specifics (please complete the following information):**
 - Python Version: 3.11.4
 - Reflex Version: 0.2.3
 - OS: windows 11 (NOT WSL)

**Comment by ClarenLee** [comment]
> **Describe the bug** On windows, `reflex run` command does not seem to stop when `CTRL-C` is pressed. Often need to `CTRL-C` a second time to exit the process.
> 
> **To Reproduce**
> 
> ```
> reflex init
> reflex run
> ```
> 
> Then press CTRL-C... it says the app is stopped, but it's still accessible
> 
> ```
> ────────────────────────────────────────── Initializing repro_ctrl_c_not_stop ──────────────────────────────────────────
> [11:52:00] Initializing the web directory.                                                                 console.py:81
> [11:52:01] Initializing the app directory.                                                                 console.py:81
> Success: Initialized repro_ctrl_c_not_stop
> 
> (VENV-rel) C:\Users\masenf\code\reflex-dev\repro-ctrl-c-not-stop>reflex run
> Warning: We strongly advise using Windows Subsystem for Linux (WSL) for optimal performance with reflex.
> ───────────────────────────────────────────────── Starting Reflex App ──────────────────────────────────────────────────
> Compiling:  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 1/1 0:00:00
> ───────────────────────────────────────────────────── App Running ──────────────────────────────────────────────────────
> App running at: http://localhost:3000
> Compiling:  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 1/1 0:00:00
> [12:00:01] Reflex app stopped.                                                                             console.py:81
> ```
> 
> Press CTRL-C a second time to get back to the prompt
> 
> ```
> [12:01:34] Reflex app stopped.                                                                             console.py:81
> ```
> 
> **Expected behavior** KeyboardInterrupt should exit the app and all subprocesses
> 
> **Specifics (please complete the following information):**
> 
> * Python Version: 3.11.4
> * Reflex Version: 0.2.3
> * OS: windows 11 (NOT WSL)

And i noticed CTRL-C seems do not really end the reflex task on Windows even the log shows it's exited, cause  i have tried the reflex-examples of **twitter** ,when i  end it with CTRL-C pressing,the terminal log shows that done . but when i execute **reflex run** again,the twitter example web page can be accessed,but all of the function are broken,like nothing happen when i click any of the buttons. In this case ,i would reboot my computer and the **twitter** example would run as right.

**Comment by ClarenLee** [comment]
@masenf In my case, i can stop reflex with CTR-C pressed **ONCE**. 

But i noticed CTRL-C seems do not really end the reflex task on Windows even the log shows it's exited, cause i have tried the reflex-examples of twitter ,when i end it with CTRL-C pressing,the terminal log shows that done . but when i execute reflex run again,the twitter example web page can be accessed,but all of the function are broken,like nothing happen when i click any of the buttons. In this case ,i would reboot my computer and the twitter example would run as right.

**Specifice**
- Python Version : 3.9.9
- Reflex Version : 0.2.3
- OS : Windows 11 (NOT WSL)

**Comment by picklelo** [comment]
I believe this is resolved now. We can reopen if it persists.
