### ISSUE TITLE
Got error on `reflex init`

### ISSUE THREAD

**Issue by jellydn** [reflex-dev/reflex#1525]
**Describe the bug**

I tried to run `reflex init` with `poetry` then got below error.

```sh
❯ poetry run reflex init --loglevel debug
─────────────────────────────────────────────────────────────── Initializing simple_chat ────────────────────────────────────────────────────────────────
Debug: Running command: ['/Users/huynhdung/.reflex/.bun/bin/bun', '-v']
Debug: Running command: ['/Users/huynhdung/.reflex/.nvm/versions/node/v18.17.0/bin/node', '-v']
[13:32:44] Initializing the web directory.                                                                                                  console.py:81
Debug: Downloading https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh
Debug: Running command: ['bash', '/var/folders/rz/6r6_41fx38b7f5c2p2jbqqzh0000gn/T/tmp9pkx80d8']
Debug: Installing https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh
Debug: => nvm is already installed in /Users/huynhdung/.reflex/.nvm, trying to update using git
Debug: 
Debug: => => Compressing and cleaning up git repository
Debug: 
Debug: => nvm source string already in /Users/huynhdung/.zshrc
Debug: => bash_completion source string already in /Users/huynhdung/.zshrc
Debug: => You currently have modules installed globally with `npm`. These will no
Debug: => longer be linked to the active version of Node when you install a new node
Debug: => with `nvm`; and they may (depending on how you construct your `$PATH`)
Debug: => override the binaries of modules installed with `nvm`:
Debug: 
Debug: /Users/huynhdung/Library/Application Support/fnm/node-versions/v18.17.0/installation/lib
Debug: ├── @antfu/ni@0.21.5
Debug: └── yarn@1.22.19
Debug: => If you wish to uninstall them at a later point (or re-install them under your
Debug: => `nvm` Nodes), you can remove them from the system Node as follows:
Debug: 
Debug:      $ nvm use system
Debug:      $ npm uninstall -g a_module
Debug: 
Debug: => Close and reopen your terminal to start using nvm or run the following to use it now:
Debug: 
Debug: export NVM_DIR="$HOME/.reflex/.nvm"
Debug: [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
Debug: [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
Debug: Running command: ['bash', '-c', '. /Users/huynhdung/.reflex/.nvm/nvm.sh && nvm install 18.17.0']
Debug: 
Error: Error during 
Error: Run in with --loglevel debug to see the full error.
⠙% 
```

I guess it's related with #1381.

**To Reproduce**
 - It seems that's installed `nvm` but I'm using [Schniz/fnm: 🚀 Fast and simple Node.js version manager, built in Rust](https://github.com/Schniz/fnm)

**Expected behavior**

**Screenshots**

**Specifics (please complete the following information):**
 - Python Version: 3.7
 - Reflex Version: 0.2.3
 - OS: Mac OSX
 - Browser (Optional):
 
**Additional context**

**Comment by masenf** [comment]
Can you provide any more information about your setup? I'm unable to repro here on macOS 13.5.

```console
rm -rf ~/.reflex
brew install fnm
mkdir my-app
cd my-app
poetry init
...
poetry run reflex init --loglevel debug
```
and it just works for me.

Did i need to install or activate some stuff with `fnm` first? Or are there some `PATH` changes you have on your system that I might be missing?

**Comment by jellydn** [comment]
Thanks @masenf I think you missed to set the node version after ran `brew install fnm`.

```sh
> fnm ls
* v16.20.0 default
* v18.17.0 lts-latest
* system
> node -v
v18.17.0
```
Could you try to reproduce again?

**Comment by jellydn** [comment]
> Did i need to install or activate some stuff with fnm first? 
Yes, you need to active `fnm` with your shell, e.g: https://github.com/Schniz/fnm#zsh

> Or are there some PATH changes you have on your system that I might be missing?
Correct, it will add to your PATH.

**Comment by jellydn** [comment]
I believe that this issue might be resolved if we disable the automatic installation of Node.js/NVM and 'bun.' For example, we could use the command poetry run reflex init --loglevel debug --nvm off --bun -off to turn off these features.

For instance: `poetry run reflex init --loglevel debug --nvm off --bun -off`

I have installed `nodejs` and `bun` on my machine so `reflex` no need to install them again.

```sh
❯ node -v
v18.17.0
❯ bun --version
0.7.1
❯ deno --version
deno 1.35.3 (release, aarch64-apple-darwin)
v8 11.6.189.12
typescript 5.1.6
❯ fnm ls
* v16.20.0 default
* v18.17.0 lts-latest
* system
```

**Comment by ElijahAhianyo** [comment]
@jellydn The point of abstracting the node and bun install is to allow reflex manage its own dependencies(whether or not they already exist on the host machine) to eradicate incompatibilities. The `~/.reflex` dir is created just for that. 
However, I tried replicating the issue reported with the steps but it worked just fine for me. I am going to close this issue now, Feel free to re-open or open another issue if need be.
