### ISSUE TITLE
error on reflex run

### ISSUE THREAD

**Issue by rados4y** [reflex-dev/reflex#1527]
**Describe the bug**
Cannot start reflex application. "Reflex run" fails.

**To Reproduce**
pipenv install reflex
pipenv shell
mkdir my_app
cd my_app
reflex init
reflex run

**Expected behavior**
App is started

**Screenshots**
`⠋ Installing base frontend packages(playground) rados4y@rados4y-pc:~/Documents/vs_workspace/playground/my_app$ reflex run --loglevel debug
────────────────────────────────────────────────────────────────────────────────── Starting Reflex App ──────────────────────────────────────────────────────────────────────────────────
Compiling:  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 1/1 0:00:00
Debug: Running command: ['/home/rados4y/.reflex/.bun/bin/bun', 'install', '--loglevel', 'silly']
Debug: Installing base frontend packages
Error: Error during Installing base frontend packages
Error: Run in with --loglevel debug to see the full error.`

`(playground) rados4y@rados4y-pc:~/Documents/vs_workspace/playground/my_app$ /home/rados4y/.reflex/.bun/bin/bun  install --loglevel silly

error: MissingPackageJSON
bun could not find a package.json file.`

**Specifics (please complete the following information):**
 - Python Version: 3.10.12
 - Reflex Version: 0.2.3
 - OS: Linux rados4y-pc 5.15.0-76-generic #83-Ubuntu SMP Thu Jun 15 19:16:32 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
 - Browser (Optional):
 
**Additional context**

**Comment by nevdelap** [comment]
I'm getting the same thing.

In a newly created DigitalOcean Droplet...

```
# apt-get install -y git python3.10 python3-pip unzip
# pip install --root-user-action=ignore reflex
# mkdir my_app
# cd my_app/
# reflex init
──────────────────────────────────────────────────────────────────────────────────────────────── Initializing my_app ────────────────────────────────────────────────────────────────────────────────────────────────
[03:25:32] Initializing the web directory.                                                                                                                                                              console.py:81
           Initializing the app directory.                                                                                                                                                              console.py:81
Success: Initialized my_app
# reflex run --loglevel debug
──────────────────────────────────────────────────────────────────────────────────────────────── Starting Reflex App ────────────────────────────────────────────────────────────────────────────────────────────────
Compiling:  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 1/1 0:00:00
Debug: Running command: ['/root/.reflex/.bun/bin/bun', 'install', '--loglevel', 'silly']
Debug: Installing base frontend packages
Debug: bun install v0.7.0 (aa1ad7f0)
Error: Error during Installing base frontend packages
Error: Run in with --loglevel debug to see the full error.
⠙ Installing base frontend packages bun install v0.7.0 (aa1ad7f0)

# /root/.reflex/.bun/bin/bun install --loglevel silly

error: MissingPackageJSON
bun could not find a package.json file.
root@pmj:~/my_app#
```

**Comment by ElijahAhianyo** [comment]
> I'm getting the same thing. These are my first minutes of trying reflex and I've never used bun, but I ran up the twitter example and am just trying to put it into a droplet and got the same thing.
> 
> In a newly created Ubuntu 22.03 DigitalOcean Droplet...
> 
> ```
> # apt-get install -y git python3.10 python3-pip unzip
> # pip install --root-user-action=ignore reflex
> # mkdir my_app
> # cd my_app/
> # reflex init
> ──────────────────────────────────────────────────────────────────────────────────────────────── Initializing my_app ────────────────────────────────────────────────────────────────────────────────────────────────
> [03:25:32] Initializing the web directory.                                                                                                                                                              console.py:81
>            Initializing the app directory.                                                                                                                                                              console.py:81
> Success: Initialized my_app
> # reflex run --loglevel debug
> ──────────────────────────────────────────────────────────────────────────────────────────────── Starting Reflex App ────────────────────────────────────────────────────────────────────────────────────────────────
> Compiling:  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 1/1 0:00:00
> Debug: Running command: ['/root/.reflex/.bun/bin/bun', 'install', '--loglevel', 'silly']
> Debug: Installing base frontend packages
> Debug: bun install v0.7.0 (aa1ad7f0)
> Error: Error during Installing base frontend packages
> Error: Run in with --loglevel debug to see the full error.
> ⠙ Installing base frontend packages bun install v0.7.0 (aa1ad7f0)
> 
> # /root/.reflex/.bun/bin/bun install --loglevel silly
> 
> error: MissingPackageJSON
> bun could not find a package.json file.
> #
> ```
> 
> Just experimenting to see if I can find anything useful to add. Running the bun install inside the .web directory so that it can find the package.json it seems something is killing it? 😕
> 
> ```
> # cd .web
> # /root/.reflex/.bun/bin/bun install --loglevel debug
> bun install v0.7.0 (aa1ad7f0)
>   📦 Installing [606/801] Killed
> # /root/.reflex/.bun/bin/bun install --loglevel debug
> bun install v0.7.0 (aa1ad7f0)
> Killed
> # /root/.reflex/.bun/bin/bun install --loglevel debug
> bun install v0.7.0 (aa1ad7f0)
>   🚚 @next/swc-linux-x64-gnu... Killed
> # /root/.reflex/.bun/bin/bun install --loglevel debug
> bun install v0.7.0 (aa1ad7f0)
> Killed
> # /root/.reflex/.bun/bin/bun install --loglevel debug
> bun install v0.7.0 (aa1ad7f0)
> Killed
> # /root/.reflex/.bun/bin/bun install --loglevel debug
> bun install v0.7.0 (aa1ad7f0)
>   🚚 @next/swc-linux-x64-musl... Killed
> #
> ```
> 
> Figured it out. My droplet had 512MB memory. Increasing it to 1GB solved the problem. 🤪

@rados4y can you try this solution out and confirm if it works for you?

**Comment by ElijahAhianyo** [comment]
closing this now, feel free to re-open or open another issue if you have further issues
