### ISSUE TITLE
Can we support reflex to show `system's info` in `--loglevel debug` 

### ISSUE THREAD

**Issue by milochen0418** [reflex-dev/reflex#1530]
**Describe the bug**

The reflex is dependent on many things. 
NodeJS, bun, nvm, OS, PATH, git,  unzip, pythonl, reflex  
But many versions of them may be different.  

If the user can use `reflex --sysinfo` to collect all the correct information quickly.
(By the suggestion, it would be better to show system's information in `--loglevel debug`)

There are 3 good points for this command
- **Bug reproducing**: The User can just paste it when they want to report the bug.  
  It may be helpful for developers to reproduce bugs. 
- **Good for growing up developer community**: It's better to share code on the internet.
  If we have reflex --sysinfo and put the result in the READMD.md, it will help people to build the community and share runnable code easier. 

I saw many examples shared from the showcases channel. 
It looks okay from the video but we cannot run the source code. 
 

 

**To Reproduce**
 - Code/Link to Repo:

**Expected behavior**

**Screenshots**

**Specifics (please complete the following information):**
 - Python Version:
 - Reflex Version:
 - OS: 
 - Browser (Optional):
 
**Additional context**

**Comment by picklelo** [comment]
Good idea. Maybe we can also just have it print all the system info for any command you use if you specify `--loglevel debug`.

**Comment by milochen0418** [comment]
It sounds better. To show this information in `--loglevel debug` would be nice. 
And maybe the running process can also get the browser-side's information and show it in `--loglevel debug`.
