### ISSUE TITLE
rx.cond(state.test_false and True evaluates to True

### ISSUE THREAD

**Issue by iseletsk** [reflex-dev/reflex#1534]
**Describe the bug**
rx.cond incorrectly calculates False and True combination

**To Reproduce**
set a variable:
MyState.test_false=False

rx.cond(MyState.test_false and True, rx.text("True"), rx.text("False")) --> will evaluate to true (wrong)
rx.cond(True and MyState.test_false, rx.text("True"), rx.text("False")) --> will evaluate to false (correct)

note that rx.cond(False and True --> evaluates correctly

**Expected behavior**
It should evaluate to False.

**Screenshots**

**Specifics (please complete the following information):**
 - Python Version: 3.9.6
 - Reflex Version: 0.2.3
 - OS: MacOS X
 - Browser (Optional): Version 115.0.5790.114 (Official Build) (arm64)

 
**Additional context**

**Comment by picklelo** [comment]
@iseletsk When using vars, you have to use the `&` operator instead of `and`, and the `|` operator instead of `or`. This is because Python does not allow overriding the default `and`/`or` operators. See here: https://reflex.dev/docs/library/layout/cond/#multiple-conditions

**Comment by iseletsk** [comment]
That is unfortunate and a mine trap that a lot of users will step into.
If and/or functionality cannot be implemented at parity with Python, maybe at least some warning/error can be generated.
People don't read, and it is this kind of issue that will cause hours of debugging, drive developers nuts, and cause them not to get back to using the library again.
