### ISSUE TITLE
navbar docs: inaccurate

### ISSUE THREAD

**Issue by nick-youngblut** [reflex-dev/reflex#1545]
**Describe the bug**

The [navbar docs](https://reflex.dev/docs/recipes/navbar/) state:

> The navbar will be a simple horizontal bar that contains a logo and a list of links to the different pages of the app.

However, the provided code does not generate a list of links.

Moreover, the same docs state:

> We will also use the `top= 0` and `z_index="1` props to make sure the navbar is always on top of the screen and above the other components on the page.

However, the code below is `z_index="5",`

**To Reproduce**

N/A

**Expected behavior**

N/A

**Screenshots**

N/A

**Specifics (please complete the following information):**
 - Python Version: 3.9
 - Reflex Version: 0.2.3

**Comment by abuharish02** [comment]
I think we have to fix z_index="5" to "1" and add code for link of different page.

**Comment by abuharish02** [comment]
<b>This is the fix of this issue. </b> 
import reflex as rx

def navbar():
    return rx.box(
        rx.flex(direction="row", align_items="center", padding="10px"),
        rx.image(src="logo.png", width="50px", height="50px"),
        rx.space(10),
        rx.link("Home", href="/home"),
        rx.space(10),
        rx.link("About", href="/about"),
        rx.space(10),
        rx.link("Services", href="/services"),
        rx.space(10),
        rx.link("Contact", href="/contact"),
        rx.flex_grow(1),
    )

**Comment by nick-youngblut** [comment]
@abuharish02 do you mean `rx.spacer` instead of `rx.space`? Also, it seems that `rx.flex_grow` doesn't exist, or at least I can't find it in the docs and I get the error: `AttributeError: module 'reflex' has no attribute 'flex_grow'`

**Comment by picklelo** [comment]
I've updated the navbar recipe, let me know if it's still not working.
