### ISSUE TITLE
State Utility Method get_client_ip() does not return the client IP.

### ISSUE THREAD

**Issue by Square07** [reflex-dev/reflex#1551]
**Describe the bug**
When the on_click event in the button occurs, it tries to call any function defined in State. 
Within that function, I want to call Utility Method get_client_ip in State and log the IP of the client that caused the web event. 
Only 127.0.0.1 is logged, not the client's IP. (Of course, the web event occurred on a PC other than local.) 

I don't know if this is a bug or if it's misconfigured.

**To Reproduce**
<Part of the State code>

``` python
<Part of the button code>
def logging_client_ip(self):
        logger.filelogV("Client IP", self.get_client_ip())
```
``` python
<Part of the button code>
def detail():
    return rx.center(
            rx.vstack(
                rx.button("refresh", bg="blue", color="black", size="lg", on_click=[State.logging_client_ip],)
            )
    )
```

I attach a part of the code.
There is no special code. 
It just calls any function that uses the get_client_ip() method in State.

The code I'm developing is not much different.

**Expected behavior**
The method call should return the IP value of the client that ran the event, not the localhost IP (127.0.0.1).

**Screenshots**
-

**Specifics (please complete the following information):**
 - Python Version: 3.9.13
 - Reflex Version: 0.2.2
 - OS: Client - Windows 10 / Server - Windows Server 2019
 - Browser (Optional): Google Chrome, Naver Whale
 
**Additional context**
-

**Comment by masenf** [comment]
Fixed by https://github.com/reflex-dev/reflex/pull/2808

Please reopen if issues persists in reflex 0.4.5+
