### ISSUE TITLE
Pynecone test page doesn't work (404 page) on Firefox for Linux Mint

### ISSUE THREAD

**Issue by EugeneSandford** [reflex-dev/reflex#156]
**Describe the bug**

The page is blank

**To Reproduce**
 - Code/Link to Repo:

pip install pynecone-io
mkdir toto_app
cd toto_app
pc init 
pc run

**Expected behavior**

The first html page for Pynecone

**Screenshots**

![Capture d’écran du 2022-12-21 09-59-27](https://user-images.githubusercontent.com/54905607/208994365-425ed0d5-a70e-48a4-b128-66015e5c5388.png)

** Specifics (please complete the following information):**
 - Python Version:
Python 3.11.0

 - Pynecone Version:
0.1.10

 - OS: 
 Results of 'uname -a' :
Linux Linux-IdeaPad 5.4.0-135-generic #152-Ubuntu SMP Wed Nov 23 20:19:22 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

 - Browser (Optional):
Mozilla Firefox for Linux Mint 
version 107.0.1 (64 bits)

**Additional context**
Created one environement via Conda in wihich I install pynecone-io via pip
'pip install pynecone-io' 

pip -- version
pip 22.3.1 from /home/tif/anaconda3/envs/Pyne/lib/python3.11/site-packages/pip (python 3.11)

**Comment by picklelo** [comment]
Thanks for reporting, we will investigate. Does it work on any other browser?

**Comment by Alek99** [comment]
Got it we mostly were testing on Ubuntu Ill have to see if I can recreate in linux mint

**Comment by Alek99** [comment]
Were you getting any node/bun error aswell?

**Comment by matt-grain** [comment]
I don't know if this is the same issue but may be, on Ubutnu and macOS I could not use python 3.11, I needed to revert to 3.8

````python
 File ".venv/lib/python3.11/site-packages/pynecone/state.py", line 120, in __init_subclass__
    cls._set_default_value(prop)
  File ".venv/lib/python3.11/site-packages/pynecone/state.py", line 255, in _set_default_value
    default_value = prop.get_default_value()
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.11/site-packages/pynecone/var.py", line 626, in get_default_value
    if issubclass(type_, str):
       ^^^^^^^^^^^^^^^^^^^^^^
TypeError: issubclass() arg 1 must be a class

````

**Comment by Alek99** [comment]
> I don't know if this is the same issue but may be, on Ubutnu and macOS I could not use python 3.11, I needed to revert to 3.8
> 
> ```python
>  File ".venv/lib/python3.11/site-packages/pynecone/state.py", line 120, in __init_subclass__
>     cls._set_default_value(prop)
>   File ".venv/lib/python3.11/site-packages/pynecone/state.py", line 255, in _set_default_value
>     default_value = prop.get_default_value()
>                     ^^^^^^^^^^^^^^^^^^^^^^^^
>   File ".venv/lib/python3.11/site-packages/pynecone/var.py", line 626, in get_default_value
>     if issubclass(type_, str):
>        ^^^^^^^^^^^^^^^^^^^^^^
> TypeError: issubclass() arg 1 must be a class
> ```

Hm what's the code that causes this I can take a look

**Comment by EugeneSandford** [comment]
> Thanks for reporting, we will investigate. Does it work on any other browser?
> 
> Also, was there any error output on the terminal?

Hi,

I have tested with Brave and with Google Chrome, and it works.
![image](https://user-images.githubusercontent.com/54905607/209268584-e47becf8-979b-44ea-a22e-37662b91593d.png)

It doesn't work only for Firefox.

If you want to investigate further, you will find blow a screen of my terminal.

Thanks for replying me

**Comment by EugeneSandford** [comment]
Here is the screen :
![image](https://user-images.githubusercontent.com/54905607/209269966-78b1213c-945c-4165-85cb-593f5b6997c9.png)

**Comment by EugeneSandford** [comment]
> 

Hi again,

For me, Python 3.11 works, at least for Google Chrome and Brave, as they have shown the default page.
If it can help you.

Regards

**Comment by EugeneSandford** [comment]
I have updated my title to 'Firefox for Linux Mint'
