### ISSUE TITLE
Suggestion: docs on using Font Awesome icons

### ISSUE THREAD

**Issue by nick-youngblut** [reflex-dev/reflex#1560]
**Describe the bug**

For reflex users that are not familiar with creating web apps, it would be helpful to include docs on how to use Font Awesome icons in a reflex app. 

**To Reproduce**

N/A

**Expected behavior**

N/A

**Screenshots**

N/A

**Specifics (please complete the following information):**

N/A
 
**Additional context**

N/A

**Comment by picklelo** [comment]
We have many icons available now through Lucide: https://reflex.dev/docs/library/datadisplay/icon/
