### ISSUE TITLE
rx.redirect - redirect to wrong url

### ISSUE THREAD

**Issue by Judt00** [reflex-dev/reflex#1562]
**Describe the bug**

I'm trying to use `rx.redirect()` to redirect url to some endpoints, and found that the behavior is difference between `http` and `https`.

For example, `rx.redirect("https://ip:port/api/test")` will redirect url to `https://ip/:port/api/test`, there is a redundant slash between `ip` and `:port`, but redirect the http url is without any problem.

**Specifics (please complete the following information):**
 - Python Version: 3.9.13
 - Reflex Version: 0.2.4
 - OS: ubuntu 20.04
 - Browser (Optional):

**Comment by londonjob** [comment]
I cannot recreate the error (under windows). I may not be familiar enough with reflex so error might be on my side here. Can someone confirm the bug?

**Comment by picklelo** [comment]
I'm also not seeing this error. Here is a small test app:

```python
"""Welcome to Reflex! This file creates a counter app."""
import random

import reflex as rx


class State(rx.State):

    def click(self):
        return rx.redirect("http://localhost:8000/ping")

def index() -> rx.Component:
    return rx.button("Redirect", on_click=State.click)

# Add state and page to the app.
app = rx.App()
app.add_page(index, title="Counter")
app.compile()
```

I tried with an HTTPS url and confirmed that it also works.
Feel free to re-open if anyone is still seeing this issue.
