### ISSUE TITLE
Headers are empty when backend-port cli option is used

### ISSUE THREAD

**Issue by bgoosmanviz** [reflex-dev/reflex#1564]
**Describe the bug**
Headers are empty when backend-port cli option is used

**To Reproduce**
```
from reflex.state import State

import reflex as rx


class State(rx.State):
    @rx.var
    def headers(self):
        return str(self.get_headers())


def index() -> rx.Component:
    return rx.fragment(
        rx.color_mode_button(rx.color_mode_icon(), float="left"),
        rx.vstack(
            rx.box(State.headers),
            spacing="1.5em",
            font_size="1em",
            padding_top="10%",
        ),
    )

app = rx.App()
app.add_page(index)
app.compile()
```

```
reflex run --backend-port 8010
```

**Expected behavior**
Expect to see my headers

**Screenshots**
N/A

**Specifics (please complete the following information):**
 - Python Version: 3.10.12 and 3.11.4
 - Reflex Version: 0.2.4
 - OS: Mac
 - Browser (Optional): Arc/Chrome
 
**Additional context**

**Comment by ElijahAhianyo** [comment]
You should consider setting your `api_url` to point to your backend url (ie `api_url = "http://localhost:8010"` or equivalent)
