### ISSUE TITLE
number_input components with convenience setter do not respect State int variable

### ISSUE THREAD

**Issue by amcraig** [reflex-dev/reflex#1577]
**Describe the bug**
I have a State variable of type int. 
I have this bound to a number_input with input_mode="numeric" by using the convenience setter. 

When I check the type of the State variable in the backend after an on_change event set to the convenience setter `set_my_var` was triggered by clicking on the frontend increment arrow, my State variable gets cast to a string

**To Reproduce**
Follow above.

**Expected behavior**
I would expect the number_input component or the convenience setter bound to a state variable of type int to respect the typing.

**Screenshots**

**Specifics (please complete the following information):**
 - Python Version: 3.10.12
 - Reflex Version: 0.2.4
 - OS: Darwin (M1)
 - Browser (Optional): Chrome
 
**Additional context**

**Comment by masenf** [comment]
This is working in 0.5.3! Please reopen if issues persist
