### ISSUE TITLE
Some TailwindCSS text utility classes are broken

### ISSUE THREAD

**Issue by jdoss** [reflex-dev/reflex#1579]
**Describe the bug**
If you follow the documentation to enable TailwindCSS and try it out on a new Reflex project the TailwindCSS text utility classes do not work. Even https://reflex.dev/docs/styling/overview/#tailwind shows the example `Hello World` text without the `text-blue-500` color. It is black.

![image](https://github.com/reflex-dev/reflex/assets/8195/cce1c7c7-a7f3-47bc-93e3-4bb6d315871d)

It should look like this:

![image](https://github.com/reflex-dev/reflex/assets/8195/c0266858-de0e-4986-acc7-86bc9de79171)

Also, [Text Decoration](https://tailwindcss.com/docs/text-decoration#class-reference) classes do not work as well. 

Things like this work on `rx.menu_item`:

```
class_name="hover:text-white hover:bg-green-700"
```
![image](https://github.com/reflex-dev/reflex/assets/8195/e0df72c7-3f99-410e-b70d-6c620e67e5b7)

but if you add 

```
class_name="hover:text-white hover:bg-green-700 hover:no-underline"
```
the underline on hover remains.  None of the above classes work on `rx.link` components. 

Here's a full example:

```python
"""Welcome to Reflex! This file outlines the steps to create a basic app."""
from rxconfig import config

import reflex as rx

docs_url = "https://reflex.dev/docs/getting-started/introduction"
filename = f"{config.app_name}/{config.app_name}.py"


class State(rx.State):
    """The app state."""

    pass


def index() -> rx.Component:
    return rx.fragment(
        rx.color_mode_button(rx.color_mode_icon(), float="right"),
        rx.vstack(
            rx.heading(
                "Welcome to Reflex!",
                font_size="2em",
                class_name="block px-3 py-1 text-xxl leading-6 heading-red-900",
            ),
            rx.box("Get started by editing ", rx.code(filename, font_size="1em")),
            rx.link(
                "Check out our docs!",
                href=docs_url,
                border="0.1em solid",
                padding="0.5em",
                border_radius="0.5em",
                class_name="block px-3 py-1 hover:no-underline hover:text-white hover:bg-green-700 text-xxl leading-6 text-gray-900",
            ),
            rx.box("Hello World", class_name="text-4xl text-center text-blue-500"),
            spacing="1.5em",
            font_size="2em",
            padding_top="10%",
        ),
    )


# Add state and page to the app.
app = rx.App()
app.add_page(index)
app.compile()
```

I downgraded to Reflex 0.1.34, the release which added TailwindCSS support, and the behavior is still the same.

**Comment by jdoss** [comment]
This comment might explain why TailwindCSS text color classes are not working https://github.com/chakra-ui/chakra-ui/issues/634#issuecomment-1340162385

**Comment by picklelo** [comment]
Tailwind should work better with the new Radix components now.
