### ISSUE TITLE
TypeError: 'datetime.datetime' object is not iterable

### ISSUE THREAD

**Issue by PlutarcoII** [reflex-dev/reflex#1589]
**Describe the bug**
I'm getting an error when a list of class objects with a datetime value is returned by state. 

File "/usr/local/lib/python3.11/site-packages/reflex/.templates/jinja/web/pages/index.js.jinja2", line 11, in block 'export'
    const [{{state_name}}, {{state_name|react_setter}}] = useState({{initial_state|json_dumps}})
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/reflex/utils/format.py", line 491, in json_dumps
    return json.dumps(obj, ensure_ascii=False, default=list)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
TypeError: 'datetime.datetime' object is not iterable

**To Reproduce**

```
class TipoDoctosVucem(rx.Model):
		id = Column(
				BigInteger, 
				primary_key=True,
				)
		activo : bool
		fecha_creo : datetime
		fecha_modifico : datetime
		usuario_creo_id : int
		usuario_modifico_id : int
		clave : int
		descripcion :str
		nombre :str

```

```
class State(rx.State):
    """The app state."""
    tipo_doctos_vucem: list[TipoDoctosVucem] = []

    @rx.var
    def get_tipos_doctos_vucem(self) -> list[TipoDoctosVucem]:
    """Get all types of documents from the database."""
      with rx.session() as session:
        self.tipo_doctos_vucem = session.query(TipoDoctosVucem).fetchall()
        print( self.tipo_doctos_vucem )
        # print values correctly
        return self.tipo_doctos_vucem 

```
**Expected behavior**
I would be nice, return all values without error. 
I was trying to solve the issue and I got this link.. https://stackoverflow.com/a/36142844

**Screenshots**

**Specifics (please complete the following information):**
 - Python Version:  Python v3.11
 - Reflex Version: v0.2.4
 - OS: Linux 18.04.6 LTS
 - Browser (Optional): Chrome Versión 115.0.5790.170 (Build oficial) (64 bits)
 
**Additional context**

**Comment by wassafshahzad** [comment]
@PlutarcoII  this should be fixed by the following PR as well #1619 but please assign it to me so that I  can investigate this issue aswell.

**Comment by wassafshahzad** [comment]
@PlutarcoII Could you try it again using main branch.I believe this will be resolved

**Comment by wassafshahzad** [comment]
@PlutarcoII Please try to reproduce it with the latest version.

**Comment by PlutarcoII** [comment]
hello @wassafshahzad,

Thanks for your response... Probably, I'm doing something wrong... 
because I have a different error now with reflex 0.2.6


 File "/usr/local/lib/python3.11/site-packages/reflex/app.py", line 522, in compile
    compile_results.append(compiler.compile_contexts(self.state))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/reflex/compiler/compiler.py", line 217, in compile_contexts
    return output_path, _compile_contexts(state)
                        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/reflex/compiler/compiler.py", line 84, in _compile_contexts
    initial_state=utils.compile_state(state),
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/reflex/compiler/utils.py", line 129, in compile_state
    return format.format_state(initial_state)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/reflex/utils/format.py", line 379, in format_state
    return {k: format_state(v) for k, v in value.items()}
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/reflex/utils/format.py", line 379, in <dictcomp>
    return {k: format_state(v) for k, v in value.items()}
               ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/reflex/utils/format.py", line 379, in format_state
    return {k: format_state(v) for k, v in value.items()}
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/reflex/utils/format.py", line 379, in <dictcomp>
    return {k: format_state(v) for k, v in value.items()}
               ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/reflex/utils/format.py", line 383, in format_state
    return [format_state(v) for v in value]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/reflex/utils/format.py", line 383, in <listcomp>
    return [format_state(v) for v in value]
            ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/reflex/utils/format.py", line 379, in format_state
    return {k: format_state(v) for k, v in value.items()}
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/reflex/utils/format.py", line 379, in <dictcomp>
    return {k: format_state(v) for k, v in value.items()}
               ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/reflex/utils/format.py", line 404, in format_state
    raise TypeError(
TypeError: State vars must be primitive Python types, or subclasses of rx.Base. 
Got var of type <class 'datetime.datetime'>.



Is datetime a primitive accepted value in return of @rx.var when class **TipoDoctosVucem** has a datetime field?

```
class State(rx.State):
    """The app state."""
    tipo_doctos_vucem: list[TipoDoctosVucem] = []

    @rx.var
    def get_tipos_doctos_vucem(self) -> list[TipoDoctosVucem]:
    """Get all types of documents from the database."""
      with rx.session() as session:
        self.tipo_doctos_vucem = session.query(TipoDoctosVucem).fetchall()
        print( self.tipo_doctos_vucem )
        # print values correctly
        return self.tipo_doctos_vucem 

```

I was checking Primitive Types and datetime is not listed... 
It means, I need to change all datetime time values to STR values?   

https://github.com/reflex-dev/reflex/blob/main/reflex/utils/types.py
PrimitiveType = Union[int, float, bool, str, list, dict, set, tuple]
StateVar = Union[PrimitiveType, Base, None]
StateIterVar = Union[list, set, tuple] 
....

Here is my class, when I changed datetime values to str values, everything goes fine.
```
class TipoDoctosVucem(rx.Model):
		id = Column(
				BigInteger, 
				primary_key=True,
				)
		activo : bool
		fecha_creo : datetime  # Error
		fecha_modifico : datetime #Error
		# fecha_creo : str = datetime.now().isoformat()   # works perfectly
		# fecha_modifico : str = datetime.now().isoformat()   # works perfectly
		usuario_creo_id : int
		usuario_modifico_id : int
		clave : int
		descripcion :str
		nombre :str

```

**Comment by wassafshahzad** [comment]
Thanks will.look into it

**Comment by wassafshahzad** [comment]
@PlutarcoII PR is up
