### ISSUE TITLE
Unable to get Reflex CLI working

### ISSUE THREAD

**Issue by mariascedasticity** [reflex-dev/reflex#1595]
Hi,

I'm unable to get the Reflex CLI working properly in my environment. When I try to run any reflex command like reflex --help or reflex init, I get errors saying it's not a valid command.

I'm running:

macOS 13.4.1 (c)
Python 3.11.3
pip 22.2.1
browser: Arc

Steps I've tried:

Installing reflex-cli via pip and pipx, brew
Creating a new virtual environment
Reinstalling reflex-cli in the activated virtualenv
Using full path to reflex
Ensuring virtualenv bin directory is on PATH

Output of diagnostics:
```

pip list:
reflex-cli 1.3.3

which reflex  
/Users/gmaria/willowhealth/willow_health/llm_project/llm_pet_project/venv/bin/reflex

reflex --help
'build' is not a reflex command. See 'reflex --help'.
```

Do you have any advice on other things I could try or reasons this might be happening? I'm unable to initialize or deploy Reflex projects due to the CLI commands not being recognized.

**Comment by ElijahAhianyo** [comment]
Hi @mariascedasticity the reflex cli comes with the reflex package, I believe what you want to do is install reflex via `pip install reflex`. Also make sure to install reflex in a virtual environment(poetry, venv, pyenv, etc)

**Comment by mariascedasticity** [comment]
I thought I tried it as well, but now it's working. Thanks!
