### ISSUE TITLE
Making a version of rx.redirect that opens a new tab

### ISSUE THREAD

**Issue by Anga205** [reflex-dev/reflex#1596]
because currently, returning rx.redirect edits the existing tab, i wanted a version that will open a new tab with the link, while keeping the old tab active, a developer on the discord told me to create an issue
![image](https://github.com/reflex-dev/reflex/assets/74541474/a79178ce-f3f1-4a5d-b1cf-29d53985115f)

**Comment by Anga205** [comment]
bump

**Comment by Anga205** [comment]
bump

**Comment by Lendemor** [comment]
Solved by #1902
