### ISSUE TITLE
pyproject.toml: repository.url for this project is wrong

### ISSUE THREAD

**Issue by jenisys** [reflex-dev/reflex#1598]
**Describe the bug**
By inspection, the [pyproject.toml — repository](https://github.com/reflex-dev/reflex/blob/59132e533ba11a98fcdtoml43b850223da8effd6ecc7/pyproject.toml#L12) value is WRONG:

* Current value: `"https://github.com/pynecone-io/pynecone"` (redirects to: https://github.com/reflex-dev/reflex)
* SHOULD BE: `"https://github.com/reflex-dev/reflex"`

**To Reproduce**
 - Inspect the `repository` URL value in the `pyproject.toml` file

**Expected behavior**
`repository` value should be the URL of this Git repository.

**Specifics (please complete the following information):**
 - Reflex Version: Current HEAD of the Git repository (fingerprint: [59132e533ba11a98fcd43b850223da8effd6ecc7](https://github.com/reflex-dev/reflex/commit/59132e533ba11a98fcd43b850223da8effd6ecc7); after `v0.2.4`)

**Comment by ElijahAhianyo** [comment]
Ah good catch, would you be kind to put a PR for this?

**Comment by jenisys** [comment]
Yes, I will do that
