### ISSUE TITLE
[REF-675] Stop click propagation

### ISSUE THREAD

**Issue by jpbaltazar** [reflex-dev/reflex#1621]
Is there a way of stopping the propagation of "onClick" events?

I have a button that sits on top of a clickable hstack, when I click  the button, the hstack also gets clicked.

My current workaround is to have a variable to prevent the double click but this obviously makes the code messier than it has to be.

Any way of preventing the double click?

[https://github.com/reflex-dev/reflex/pull/1891](https://github.com/reflex-dev/reflex/pull/1891)

<sub>From [SyncLinear.com](https://synclinear.com) | [REF-675](https://linear.app/reflex-dev/issue/REF-675/stop-click-propagation)</sub>

**Comment by masenf** [comment]
Ah this is fun. It's not really supported, but it could be...

In the meantime, here is a little hackaround that I believe does what you want:

```python
import reflex as rx


class State(rx.State):
    def on_click(self):
        print("clicked")

    def on_click_outer(self):
        print("clicked outer")


def with_stop_propagation(event):
    compiled_event_chain = rx.components.tags.Tag.format_prop(rx.event.EventChain(events=[event()]))
    stop_propagation_chain = "".join(
        [
            compiled_event_chain.replace("=> Event", "=> {_e.stopPropagation(); Event"),
            "}",
        ]
    )
    return rx.vars.BaseVar(
        name=stop_propagation_chain,
        type_=rx.event.EventChain,
    )


def index() -> rx.Component:
    return rx.vstack(
        rx.button("Click me", on_click=with_stop_propagation(State.on_click)),
        on_click=State.on_click_outer,
        padding_top="10%",
    )


# Add state and page to the app.
app = rx.App()
app.add_page(index)
app.compile()
```

This is in no way pretty, and string manipulates javascript code, so I'm not trying to claim this as a "solution".

I think Reflex could provide this `rx.stop_propagation` method for users officially, but will have to discuss the design with the team, and work out all of the edge cases (lambdas, multiple events, bare Var chains, etc).

Thanks for raising this issue.

**Comment by ZeD4805** [comment]
Updated for commit [829a7751b5ef263d5af77107001cbb33a60bda4e](https://github.com/reflex-dev/reflex/commit/829a7751b5ef263d5af77107001cbb33a60bda4e)

```
import reflex as rx
from reflex.utils import format


class State(rx.State):
    def on_click(self):
        print("clicked")

    def on_click_outer(self):
        print("clicked outer")


def with_stop_propagation(event):
    compiled_event_chain = format.format_prop(rx.event.EventChain(events=[event()]))
    stop_propagation_chain = "".join(
        [
            compiled_event_chain.replace("=> Event", "=> {_e.stopPropagation(); Event"),
            "}",
        ]
    )
    return rx.vars.BaseVar(
        name=stop_propagation_chain,
        type_=rx.event.EventChain,
    )


def index() -> rx.Component:
    return rx.vstack(
        rx.button("Click me", on_click=with_stop_propagation(State.on_click)),
        on_click=State.on_click_outer,
        padding_top="10%",
    )


# Add state and page to the app.
app = rx.App()
app.add_page(index)
app.compile()
```

**Comment by masenf** [comment]
We'll try to get this one in the core framework for the next-next release 0.2.8

**Comment by jpbaltazar** [comment]
@masenf Can I get an update for this solution?

 I don't quite know how to update this to v0.2.8 tbh and it kinda broke some of my setup. 

I'm updating for the cool rx.background stuff :)

**Comment by jpbaltazar** [comment]
Nevermind, found out on my own:


```python
def with_stop_propagation(event):
    compiled_event_chain = format.format_prop(rx.event.EventChain(events=[event()], args_spec=None))
    if isinstance(compiled_event_chain, str):
        stop_propagation_chain = "".join(
            [
                compiled_event_chain.replace("=> Event", "=> {_e.stopPropagation(); Event}")
            ]
        )
        return rx.vars.BaseVar(
            name=stop_propagation_chain,
            type_=rx.event.EventChain,
        )

**Comment by masenf** [comment]
@jpbaltazar this is going to break again in 0.2.9 next week because we changed `Event` to `addEvents`. I'll see if I can just get this into the core framework so it can be an actual supported feature.

**Comment by masenf** [comment]
@jpbaltazar I opened a PR to bring this into the core framework. Please let me know if you have any comments on the proposed API over in the PR #1891

**Comment by jpbaltazar** [comment]
@masenf Hi thank you for dedicating time on this issue!

I only have a question: how would it work for cases where I have two components that require `OnClick` that sit one on top of the other? would I need to wrap one of them in some other component which would have a `rx.stopPropagation`?

**Comment by masenf** [comment]
@jpbaltazar `rx.stop_propagation` can be used as an event handler when you otherwise wouldn't have one. Otherwise, all event handlers will have `.stop_propagation` now, so when specifying an `on_click`, you can add `.stop_propagation` to the end and the click wont pass down to the parent component.

**Comment by jpbaltazar** [comment]
Oh that's great! That totally works for me

**Comment by masenf** [comment]
@jpbaltazar thanks for your patience on this one; will be in the next release for sure, 0.3.2

**Comment by jpbaltazar** [comment]
Haha thank you! Good to know I wasn't forgotten
