### ISSUE TITLE
[REF-2924] plotly function not showing the charts

### ISSUE THREAD

**Issue by AManTw** [reflex-dev/reflex#1630]
[Status]
The plotly function is not displaying the charts properly.
And the reflex log shows 

> import statsmodels.api as sm
> ModuleNotFoundError: No module named 'statsmodels'

[Solution]
After install statsmodels, plotly function works properly.

It  would be kind to add  "statsmodels" in requirement.txt 
:)

<sub>[REF-2924](https://linear.app/reflex-dev/issue/REF-2924/plotly-function-not-showing-the-charts)</sub>

**Comment by Lendemor** [comment]
The line of code coming from plotly, I believe this issue should be opened in [Plotly.py](https://github.com/plotly/plotly.py/issues) instead.

We could add statsmodels in our requirements, but it would be better if dependencies are managed where they should.

**Comment by adejumoridwan** [comment]
Hi, I will like to take this issue

**Comment by resilient-maximus** [comment]
Hi, I would like to take this issue up.

**Comment by Preetraj2002** [comment]
!assign

**Comment by Sivasanthosh07** [comment]
@masenf  assign me this issue :)

**Comment by masenf** [comment]
@Sivasanthosh07 what is your plan for addressing this issue?

keep in mind that reflex no longer directly installs plotly, and instead suggests that the user install it when trying to use plotly functionality.

**Comment by picklelo** [comment]
We don't have plotly builtin anymore - should be installed separately.
