### ISSUE TITLE
Drawer close_on_esc and close_on_overlay_click don't work

### ISSUE THREAD

**Issue by jpbaltazar** [reflex-dev/reflex#1659]
Expected behaviour: Drawer closes after either pressing 'esc' or clicking the overlay

Note: I've tried both together and individually, they do not close the drawer.

Minimal example:

```
import reflex as rx

class DrawerState(rx.State):
    show_right: bool = False

    def right(self):
        self.show_right = not (self.show_right)

def index():
    return rx.box(
        rx.button(
            "Show Right Drawer", on_click=DrawerState.right
        ),
        rx.drawer(
            rx.drawer_overlay(
                rx.drawer_content(
                    rx.drawer_header("Confirm"),
                    rx.drawer_body(
                        "Do you want to confirm example?"
                    ),
                    rx.drawer_footer(
                        rx.button(
                            "Close", on_click=DrawerState.right
                        )
                    ),
                    bg="rgba(0, 0, 0, 0.3)",
                )
            ),
            is_open=DrawerState.show_right,
            close_on_esc=True,
            close_on_overlay_click=True,
        ),
    )

# Add state and page to the app.
app = rx.App()
app.add_page(index)
app.compile()
```

**Comment by wassafshahzad** [comment]
I can pick this up

**Comment by wassafshahzad** [comment]
Please assign this to me

**Comment by jpbaltazar** [comment]
Thank you for your solution!

Just a question, will `DrawerState.right` be assigned because of the `on_close` prop?

**Comment by wassafshahzad** [comment]
No. As per the [Chakra UI documentation](https://chakra-ui.com/docs/components/drawer/props#:~:text=onClose,required) onClose expects a callback. This callback is used by the closeOnEsc and closeOnOverlayClick to change the state of drawer. Is you see the provided example Drawer.show_right is the state while  Drawer.right is a callback used to change it.

**Comment by jpbaltazar** [comment]
Yeah I missed that, thank you!
