### ISSUE TITLE
Move format_prop to format.py

### ISSUE THREAD

**Issue by picklelo** [reflex-dev/reflex#1666]
Currently the static method `format_prop` is within the Tag class, making it hard to reuse. It should be moved to the `utils/format.py` file.

**Comment by masenf** [comment]
@ElijahAhianyo You may want to base your code on https://github.com/reflex-dev/reflex/pull/1636, where I have already moved _some_ of `format_prop` functionality out of the `Tag` class... this would give a head start and help avoid merge conflicts.

**Comment by masenf** [comment]
Fixed via #1714
