### ISSUE TITLE
Echoing `DB_URL` environment variable may leak secrets

### ISSUE THREAD

**Issue by masenf** [reflex-dev/reflex#1667]
**Describe the bug**
In reflex-0.2.5, overriding the config with environment variables logs a message to the console containing the value. Since the `DB_URL` likely contains the database credentials, it shouldn't be echoed to the logs.

**To Reproduce**
```shell
DB_URL=postgresql+psycopg2://postgres:secret@db/postgres reflex run
```

```console
Info: Overriding config value db_url with env var DB_URL=postgresql+psycopg2://postgres:secret@db/postgres
```

**Specifics (please complete the following information):**
 - Python Version: 3.11.4
 - Reflex Version: 0.2.5
 - OS: -
 - Browser (Optional): -

**Comment by shashank40** [comment]
Picking this up

**Comment by masenf** [comment]
Thank you 🙏

**Comment by shashank40** [comment]
Can this be reviewed?
https://github.com/reflex-dev/reflex/pull/1681
