### ISSUE TITLE
rx.upload select path instead of file

### ISSUE THREAD

**Issue by Jogenist** [reflex-dev/reflex#1673]
It would be cool if we could select and upload paths in addition to the current file upload (rx.upload).
Currently only files can be uploaded. The path of the file to be uploaded can also be read, but a file must always be selected for upload. The selection of a (remote) path without files is currently not possible. Maybe this is would be an easy and useful extension.

**Comment by masenf** [comment]
This is supported in 0.3.3+ if an entire directory is dropped on the react dropzone component that is part of `rx.upload`... but there isn't a cross-browser / cross-platform way to have the UI file picker allow selection of directories.

Similar to #2079
