### ISSUE TITLE
First-class way to use local storage with State

### ISSUE THREAD

**Issue by gmurthy-slanglabs** [reflex-dev/reflex#1677]
Hello, thanks for the project!

This not really a bug report, but more of a request for information.

We would like to store some data that is returned by the back-end into local storage. But there doesn't seem to be a first-class way to do this as far as I can tell. 

All of the examples show that `rx.set_local_storage()` being called directly by local event handlers like this: 
```
on_click=rx.set_local_storage("key", "value")`
```

What we're interested in is something like this:
```
on_click=State.call_backend_api, # works fine
# write the response to local storage, not sure how?
```

Can you please give me some pointers? Thanks!

**Comment by Lendemor** [comment]
I think this PR #1629 by @masenf will cover what you want, it should be released relatively soon.

Once it is, let us know any feedback you have about it.
