### ISSUE TITLE
Is it possible to render hyperlinks as part of a text area?

### ISSUE THREAD

**Issue by hwchase17** [reflex-dev/reflex#168]
eg with markdown syntax or html anything like that?

**Comment by Alek99** [comment]
Everything for textarea gets rendered in a a string. For trying to do this I would use text or markdown component.

With text

pc.text("Hello ", pc.link("World", href=your_url))

With Markdown you could do it as a normal markdown link.

**Comment by Alek99** [comment]
There has been some request to add an editable markdown component which we are looking into aswell.
