### ISSUE TITLE
Reflex init command not running without any error or trace back

### ISSUE THREAD

**Issue by SMITH-10** [reflex-dev/reflex#1680]
Reflex init command not working in terminal also tried using virtual environment need help asap

**Expected behavior**
App compiling should come

![Screenshot 2023-08-18 120614](https://github.com/reflex-dev/reflex/assets/102793814/e6b1b336-3292-4430-9e8e-ace04c14e2c4)

**Comment by joyboy008** [comment]
what version of node do you have?

**Comment by ElijahAhianyo** [comment]
@SMITH-10 what version of reflex are you running?

**Comment by SMITH-10** [comment]
latest version 


> @SMITH-10 what version of reflex are you running?

**Comment by SMITH-10** [comment]
> what version of node do you have?

LTS

**Comment by adhami3310** [comment]
Closing as it couldn't be reproduced.
