### ISSUE TITLE
is_selected not work in rx.tab

### ISSUE THREAD

**Issue by ltm920716** [reflex-dev/reflex#1683]
**Describe the bug**
Hi,  I want to get a automatic switching effect in rx.tab， but param ‘is_selected’ seems not work，perhaps my code was written incorrectly

**To Reproduce**
```
rx.tabs(
            rx.tab_list(
                rx.tab(
                    "Pipelines",
                    is_selected=False,   # State.selected_p
                    custom_attrs={'isSelected': False}
                ),
                rx.tab(
                    "New",
                    is_selected=True,   # State.selected_n
                    custom_attrs={'isSelected': True}
                )
            ),
            rx.tab_panels(
                rx.tab_panel(
                    node_list()
                ),
                rx.tab_panel(
                    rx.cond(
                        State.init_node_page,
                        new_node_page(),
                        init_prompt_page()
                    )
                )
            ),
            align="center",
            is_fitted=True
        ),
```

![image](https://github.com/reflex-dev/reflex/assets/12007227/f18feefa-46bc-4b88-b6d9-3c6260f83b10)

**Expected behavior**
In my test code，I think it should show the ‘New’ Panel， that is right？

 
**Additional context**
actually，I want to do some operation in the ‘New’ panel, and then I expect it could automatic switch to the ‘Pipeline’ panel when I  click ‘done’ button，I want to control this behavior by is_selected, but it not work

**Comment by pmxiao** [comment]
same requirement, do you get a solution?

**Comment by ltm920716** [comment]
@pmxiao not yet

there is a 'default_index' param in rx.tabs could show fix index page onloading first，
about  ’ is_selected‘ param in rx.tab，I think that could be done by custom another component to implement this

by the way，I noticed that reflex can not deal with long-time async call，it means UI will be blocked before current action done，so wait until new update 

https://github.com/reflex-dev/reflex/pull/1676 
https://github.com/reflex-dev/reflex/issues/1340

**Comment by masenf** [comment]
The new radix tabs component (introduced in 0.3.0) supports setting the active tab with the controlled `value` prop: https://reflex.dev/docs/library/disclosure/tabs/

Each tab has an `id` and when that `id` is set for `value`, the given tab content will be selected and displayed, this can be controlled via state.
