### ISSUE TITLE
version node 18.17.0 None

### ISSUE THREAD

**Issue by joyboy008** [reflex-dev/reflex#1688]
**Describe the bug**
i wanna build one project, and i cant because node version 18.17.0 is not found my actually version is 18.17.1 and the page of node not fount a version 18.17.0

**To Reproduce**
(venv) C:\Users\gogodance\OneDrive\Desktop\pythonProjects\hello_reflex>reflex init --loglevel debug
Info: Overriding config value username with env var USERNAME=gogodance
Info: Overriding config value username with env var USERNAME=gogodance
───────────────────────────────────────────────────── System Info ─────────────────────────────────────────────────────
Debug: Config file: 'C:\\Users\\gogodance\\OneDrive\\Desktop\\pythonProjects\\venv\\Lib\\site-packages\\reflex\\config.py'
Debug: Config: app_name='' loglevel=<LogLevel.INFO: 'info'> frontend_port=3000 backend_port=8000
api_url='http://localhost:8000' deploy_url='http://localhost:3000' backend_host='0.0.0.0' db_url='sqlite:///reflex.db'
redis_url=None telemetry_enabled=True bun_path='C:\\Users\\gogodance\\AppData\\Local\\reflex\\.bun\\bin\\bun'
cors_allowed_origins=['*'] tailwind=None timeout=120 next_compression=True event_namespace=None frontend_packages=[]
rxdeploy_url=None username='gogodance'
Debug: Running command:
['C:\\Users\\gogodance\\AppData\\Local\\reflex\\fnm\\node-versions\\v18.17.0\\installation\\node.exe', '-v']
Debug: [Reflex 0.2.6 with Python 3.11.2 (PATH: C:\Users\gogodance\OneDrive\Desktop\pythonProjects\venv\Scripts\python.exe)]
Debug: [Node None (Expected: 18.17.0)
(PATH:C:\Users\gogodance\AppData\Local\reflex\fnm\node-versions\v18.17.0\installation\node.exe)]
Debug: [FNM 1.35.1 (Expected: 1.35.1) (PATH: C:\Users\gogodance\AppData\Local\reflex\fnm\fnm.exe)]
Debug: [OS Windows 10.0.19045]
Debug: Using package installer at: C:\Users\gogodance\AppData\Local\reflex\fnm\node-versions\v18.17.0\installation\npm
Debug: Using package executer at: C:\Users\gogodance\AppData\Local\reflex\fnm\node-versions\v18.17.0\installation\npm
────────────────────────────────────────────── Initializing hello_reflex ──────────────────────────────────────────────
Debug: Skipping bun installation on Windows.
Debug: Running command: ['powershell', '-Command', '& "C:\\Users\\gogodance\\AppData\\Local\\reflex\\fnm\\fnm.exe" install
18.17.0 --fnm-dir "C:\\Users\\\\AppData\\Local\\reflex\\fnm"']

**Specifics (please complete the following information):**
 - Python Version: 3.11.2
 - Reflex Version: 0.2.6
 - OS: Windows 10 pro 64 bits10.0
 - Browser (Optional):

**Comment by ElijahAhianyo** [comment]
Hi @joyboy008 Are these the complete logs? I'm curious to see the logs after the line: 
```
Debug: Running command: ['powershell', '-Command', '& "C:\Users\gogodance\AppData\Local\reflex\fnm\fnm.exe" install
18.17.0 --fnm-dir "C:\Users\\AppData\Local\reflex\fnm"']```

**Comment by joyboy008** [comment]
> Hi @joyboy008 Are these the complete logs? I'm curious to see the logs after the line: 
> ```
> Debug: Running command: ['powershell', '-Command', '& "C:\Users\gogodance\AppData\Local\reflex\fnm\fnm.exe" install
> 18.17.0 --fnm-dir "C:\Users\\AppData\Local\reflex\fnm"']```

Yes is a all logs
Firts im created a virtual enviroment and try run this comand: reflex init

**Comment by picklelo** [comment]
Reflex doesn't require node to be pre-installed anymore.
