### ISSUE TITLE
No docs on including rx.upload in rx.form

### ISSUE THREAD

**Issue by nick-youngblut** [reflex-dev/reflex#1689]
Feature request: 

A file upload is common in webforms, but the [rx.upload docs](https://reflex.dev/docs/library/forms/upload/) do not show how to integrate rx.upload into rx.form -- particularly with combing `handle_upload` and `handle_submit` execution. Otherwise, one would have to use 2 separate buttons (1 for file upload and 1 for form submission), instead of just 1 button for the entire process. 

It would be great if the [form docs](https://reflex.dev/docs/library/forms/form/) included an example form with all other components in the `Form` section of the docs (e.g., Slider, RadioGroup, Upload, etc)

**Comment by Spartan-71** [comment]
Hey @Lendemor I would like to work on this issue. Plz assign me.

**Comment by picklelo** [comment]
@Spartan-71 thanks for the investigation. I'll close this ticket for now, but maybe we can find a way to handle this in the future.
