### ISSUE TITLE
not able to install reflex

### ISSUE THREAD

**Issue by TanishJain19** [reflex-dev/reflex#1691]
![Screenshot 2023-08-27 203942](https://github.com/reflex-dev/reflex/assets/143339515/2d4fcbb9-015f-4242-b1f3-bd163c34de4b)
![Screenshot 2023-08-27 204011](https://github.com/reflex-dev/reflex/assets/143339515/da2cca9b-01a1-4299-94a2-8c9c8235aad0)

**Comment by ElijahAhianyo** [comment]
sounds like you may need to upgrade your setuptools. Can you try the suggestion here https://stackoverflow.com/a/40888720
