### ISSUE TITLE
Dependencies Bug

### ISSUE THREAD

**Issue by Alva19** [reflex-dev/reflex#1693]
When i use the command: reflex run, it puts an error of Install base frontend packages, it recommends me use the command with --loglevel debug, but doesn't give me more information and the problem continues, so i can't deploy my projects
`reflex run --loglevel debug
───────────────────────────────────────────────────── System Info ──────────────────────────────────────────────────────Debug: Config file: '/mnt/c/Users/Checo/Portafolio/python_web/rxconfig.py'
Debug: Config: app_name='python_web' loglevel=<LogLevel.INFO: 'info'> frontend_port=3000 backend_port=8000
api_url='http://localhost:8000' deploy_url='http://localhost:3000' backend_host='0.0.0.0' db_url='sqlite:///reflex.db'
redis_url=None telemetry_enabled=True bun_path='/home/angel/.reflex/.bun/bin/bun' cors_allowed_origins=['*']
tailwind=None timeout=120 next_compression=True event_namespace=None frontend_packages=[] rxdeploy_url=None
username=None
Debug: Running command: ['/home/angel/.reflex/.nvm/versions/node/v18.17.0/bin/node', '-v']
Debug: Running command: ['/home/angel/.reflex/.bun/bin/bun', '-v']
Debug: [Reflex 0.2.6 with Python 3.10.12 (PATH: /mnt/c/Users/Checo/Portafolio/python_web/venv/bin/python3)]
Debug: [Node 18.17.0 (Expected: 18.17.0) (PATH:/home/angel/.reflex/.nvm/versions/node/v18.17.0/bin/node)]
Debug: [NVM 0.39.1 (Expected: 0.39.1) (PATH: /home/angel/.reflex/.nvm/nvm.sh)]
Debug: [Bun 0.7.0 (Expected: 0.7.0) (PATH: /home/angel/.reflex/.bun/bin/bun)]
Debug: [OS Linux Ubuntu 22.04.2 LTS]
Debug: Using package installer at: /home/angel/.reflex/.bun/bin/bun
Debug: Using package executer at: /home/angel/.reflex/.nvm/versions/node/v18.17.0/bin/npm
Debug: Unzip path: /usr/bin/unzip
───────────────────────────────────────────────── Starting Reflex App ──────────────────────────────────────────────────Compiling:  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 1/1 0:00:00
Debug: Running command: ['/home/angel/.reflex/.bun/bin/bun', 'install', '--loglevel', 'silly']
Debug: Installing base frontend packages
Debug: bun install v0.7.0 (aa1ad7f0)
Debug:  Resolving dependencies
Debug:
Debug: error: ConnectionRefused downloading package manifest autoprefixer
Debug:
Debug: error: ConnectionRefused downloading package manifest postcss
Debug:
Debug: error: ConnectionRefused downloading package manifest tailwindcss
Debug:
Debug: error: ConnectionRefused downloading package manifest next-sitemap
Debug:
Debug: error: ConnectionRefused downloading package manifest react-debounce-input
Debug:
Debug: error: ConnectionRefused downloading package manifest universal-cookie
Debug:  Resolved, downloaded and extracted [36]
Debug: error: autoprefixer@^10.4.14 failed to resolve
Debug: error: postcss@^8.4.24 failed to resolve
Debug: error: tailwindcss@^3.3.2 failed to resolve
Debug: error: next-sitemap@^4.1.8 failed to resolve
Debug: error: react-debounce-input@^3.3.0 failed to resolve
Debug: error: universal-cookie@^4.0.4 failed to resolve
Installing base frontend packages failed with exit code 1
bun install v0.7.0 (aa1ad7f0)
 Resolving dependencies

error: ConnectionRefused downloading package manifest autoprefixer

error: ConnectionRefused downloading package manifest postcss

error: ConnectionRefused downloading package manifest tailwindcss

error: ConnectionRefused downloading package manifest next-sitemap

error: ConnectionRefused downloading package manifest react-debounce-input

error: ConnectionRefused downloading package manifest universal-cookie
 Resolved, downloaded and extracted [36]
error: autoprefixer@^10.4.14 failed to resolve
error: postcss@^8.4.24 failed to resolve
error: tailwindcss@^3.3.2 failed to resolve
error: next-sitemap@^4.1.8 failed to resolve
error: react-debounce-input@^3.3.0 failed to resolve
error: universal-cookie@^4.0.4 failed to resolve
Run with --loglevel debug  for the full log.`

**Comment by masenf** [comment]
I've been noticing intermittent problems with npm in the last day or so. Are you still experiencing this?

**Comment by picklelo** [comment]
Closing for now
