### ISSUE TITLE
error installing on PS-Win11

### ISSUE THREAD

**Issue by saimach2002** [reflex-dev/reflex#1699]
I am trying to initialize a template app in Reflex, but received a syntax error 

  File "C:\Users\saima\venv\python310\lib\site-packages\kafka\producer\simple.py", line 54
    return '<SimpleProducer batch=%s>' % self.async
                                              ^^^^^
SyntaxError: invalid syntax

**Specifics (please complete the following information):**
 - Python Version: 3.10
 - Reflex Version: 
 - OS: Windows 3.11 (PSVersion   5.1.22621.1778)
 - Browser (Optional): Chrome

**Comment by ElijahAhianyo** [comment]
what reflex version are you running? Would also be really helpful if you could show the full logs

**Comment by saimach2002** [comment]
Thanks, i fix they issue
