### ISSUE TITLE
Better error Message Foreach

### ISSUE THREAD

**Issue by Alek99** [reflex-dev/reflex#1702]
When testing the below code I recieved the error
```
  File "/Users/alekpetuskey/Desktop/Open Source/pynecone/reflex/components/tags/iter_tag.py", line 76, in render_component
    assert len(args) == 2
```

```python
class Job(rx.Model, table=True):
    """The customer model."""
    tag: str
    date: str
    status: int
    results: str

class State(rx.State):
    """The app state."""
    ...
    @rx.var
    def get_users(self) -> list[Job]:
        """Get all users from the database."""
        with rx.session() as session:
            self.users = session.query(Job).all()
            print(self.users)
            return self.users


def show_jobs():
    return ...


....
def past_jobs() -> rx.Component:
   ....
       rx.tbody(
          rx.foreach(State.get_users, show_jobs)
     )
```

To fix I added an arg to the show job function but based on the error message a new user wouldn't find this 
```python

def show_jobs(user: Job):
    return ...
```

**Comment by picklelo** [comment]
We've improved the error message here now.

**Comment by amballa** [comment]
I'm getting this same error when using trying to iterate through a State attribute with foreach. What am I doing wrong here with this barebone function?

`class State2(State1):
    urls: list[str] = []

    @rx.background
    async def get_urls(self, project: Project):
        pass

    @rx.background
    async def download_all(self):
        async with self:
            rx.foreach(VideoState.data, self.get_capture_urls)`
