### ISSUE TITLE
reflex run Error on Mac

### ISSUE THREAD

**Issue by darwinharianto** [reflex-dev/reflex#1712]
based on this conversations, I created an issue here
https://discord.com/channels/1029853095527727165/1145874339166699560

**Describe the bug**

/anaconda3/envs/createautoml/lib/python3.11/site-packages/psutil/_psosx.py", line 503, in connections
    rawlist = cext.proc_connections(self.pid, families, types)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: proc_pidinfo(PROC_PIDLISTFDS) 2/2 syscall failed

this seems to be caused by Mac doesnt have a certain method from psutil
https://stackoverflow.com/questions/71124472/is-psutil-net-connections-unavailable-for-osx

To mitigate this error, I changed except that exception and just pass it, it can run without problem after that

**To Reproduce**
 - Code/Link to Repo:

**Expected behavior**
No error

**Specifics (please complete the following information):**
 - Python Version: 3.11
 - Reflex Version: latest to issue created
 - OS: MAC OS
 - Browser (Optional):
 
**Additional context**

**Comment by picklelo** [comment]
Closing this for now - feel free to reopen if others hit this.
