### ISSUE TITLE
Stylesheets not loading any route other than the root (/)

### ISSUE THREAD

**Issue by MindSetFPS** [reflex-dev/reflex#1740]
**Describe the bug**
When importing stylesheets as stated in [the docs](https://reflex.dev/docs/styling/custom-stylesheets/#local-stylesheets), they only load in the base route (http://localhost:3000).

However, when navigating to other routes, the frontend concatenates the current route to the css url.
Let's say, you are in http://localhost:3000/profile/reflex
The frontend will request the stylesheets to http://localhost:3000/profile/reflex/css/styles.css

**Expected behavior**
The frontend should request the styles to http://localhost:3000/css/styles.css regardless of where in the site you are.

**Specifics (please complete the following information):**
 - Python Version: 3.11.4
 - Reflex Version: reflex==0.2.5a1
 - OS: Fedora Linux 38 (Workstation Edition)
 - Browser (Optional): Firefox 116.0.3

**Comment by masenf** [comment]
Docs updated to strongly suggest the use of a leading slash when specifying stylesheets and assets.
