### ISSUE TITLE
npm ERR when reflex run

### ISSUE THREAD

**Issue by sertemo** [reflex-dev/reflex#1741]
**Describe the bug**
Error when typing *reflex run*

**To Reproduce**
 - Code/Link to Repo:
 - $ reflex run

**Screenshots**

![image](https://github.com/reflex-dev/reflex/assets/119494713/8dd87e4f-6a4f-4699-98f2-800a52d1683a)

**Specifics (please complete the following information):**
 - Python Version: 3.11
 - Reflex Version: 0.2.6
 - OS: Windows 10

**Comment by ElijahAhianyo** [comment]
cant make much of the logs, can you show logs for when you run in debug mode (`reflex run --loglevel debug`)?

**Comment by adhami3310** [comment]
I cannot reproduce the issue. In any case you are still hitting this, please provide the versions of NPM/NodeJS.
