### ISSUE TITLE
is_read_only props on rx.select is not working

### ISSUE THREAD

**Issue by Judt00** [reflex-dev/reflex#1754]
**Describe the bug**
is_read_only props on rx.select is not working

**To Reproduce**
```
class State(rx.State):
   select: str = ""

def index():
    return rx.box(
        rx.select(
            ["A", "B"],
            on_change=State.set_select,
            is_read_only=True,
        )
    )
```

**Expected behavior**
The component itself should be set to read-only

**Specifics (please complete the following information):**
- Python Version: 3.9.13
- Reflex Version: 0.2.6
- OS: ubuntu 20.04

**Comment by wassafshahzad** [comment]
@Lendemor  I will pick this up

**Comment by wassafshahzad** [comment]
@Judt00 I looked into this issue and unfortunately passing the readonly attribute to the underlying html element, it does not do anything. The <select> tag does not respond to readonly. The isReadOnly Prop was removed from Chakra UIs documentation but was added again for some reason. To make it readonly it is better to use is-disabled prop.

## Refrences
- https://github.com/chakra-ui/chakra-ui/issues/2381
- https://github.com/chakra-ui/chakra-ui/issues/6005
- [select tags attribute list](https://www.w3schools.com/tags/tag_select.asp#:~:text=Attributes-,Attribute,-Value)

@masenf We need to update the documentation accordingly.

**Comment by masenf** [comment]
> We need to update the documentation accordingly.

Is the suggestion to just remove the `is_read_only` prop from `Select` component? Or are there other places in the docs where it is suggested?

**Comment by wassafshahzad** [comment]
I think we should remove it from the documentation.
Kindly see the following references
- https://github.com/chakra-ui/chakra-ui/issues/6005#issuecomment-1128028313
- https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select#attributes

Chakra UI also removed it form its documentation but added it again for some reason.

**Comment by masenf** [comment]
Seems like we should remove the `is_read_only` prop entirely, if it doesn't actually work right?

**Comment by wassafshahzad** [comment]
> Seems like we should remove the `is_read_only` prop entirely, if it doesn't actually work right?

I can create a PR for that if you want

**Comment by masenf** [comment]
Sounds good, appreciate it.
