### ISSUE TITLE
`rx.script()` adds an element to <body> instead of <head>

### ISSUE THREAD

**Issue by simicvm** [reflex-dev/reflex#1763]
**Describe the bug**
I am trying to add Google Analytics script to my web app using `rx.script()` component. My file `gtag.js` is defined in `assets` folder. However, the tag shows up in the `<body>` section instead of `<head>` section of the `index.html` file. 

I try adding it in 2 different ways, but both result in the same outcome.

1. Add script to `add_page`:
```python
app = rx.App(state=State, stylesheets=["stylesheet.css"])
app.add_page(
    index,
    title="My App",
    description="Test google analytics",
    image="/card.png",
    on_load=State.do_something,
    meta=meta,
    script_tags=[rx.script(src="/gtag.js")],
)
app.compile()
```

2. Add script to `index`:
```python
def index():
    return rx.vstack(
        rx.script(src="/gtag.js"),
        rx.text("Hello")
)
```

The `gtag.js` file I use is this:
```js
window.dataLayer = window.dataLayer || [];
function gtag() { dataLayer.push(arguments); }
gtag('js', new Date());
gtag('config', 'G-MYTAGID...');
```
 
**Expected behavior**
Appropriate script tag shows up in the `<head>` section.

**Screenshots**
<img width="583" alt="image" src="https://github.com/reflex-dev/reflex/assets/13484398/dd8f3afe-c387-4aea-bfa8-c2113591243e">

**Specifics (please complete the following information):**
 - Python Version: 3.11
 - Reflex Version: 0.2.6 (and 0.2.4)
 - OS: macOS Ventura 13.5.1 
 - Browser (Optional): Safari, Chrome

**Comment by simicvm** [comment]
this is my current workaround. just put it in the `html` component. seems to be tracking fine.
```python
def index():
    return rx.vstack(
        rx.html(
            """<script>// Create a script element for the gtag.js library
var scriptTag = document.createElement('script');
scriptTag.async = true;
scriptTag.src = 'https://www.googletagmanager.com/gtag/js?id=G-MYTAGID...';

// Append it to the head element
document.head.appendChild(scriptTag);

// Once the script is loaded, initialize gtag
scriptTag.onload = function() {
  // Create another script element for inline code
  var inlineScript = document.createElement('script');

  // Add your gtag inline code
  inlineScript.text = `
    window.dataLayer = window.dataLayer || [];
    function gtag() { dataLayer.push(arguments); }
    gtag('js', new Date());
    gtag('config', 'G-MYTAGID...');
  `;

  // Append the inline script to the head element
  document.head.appendChild(inlineScript);
};</script>
"""
        ),
```

**Comment by masenf** [comment]
The default behavior of `next/script` (what `rx.script` is based on) is to add the inline scripts to the `<body>` tag. It is possible to use the plain html `<script>` tag (at `rx.el.script`) along with the `head_components` prop to get a script tag into the `<head>` without other hacks. The code looks like this

```
app = rx.App(head_components=[rx.el.script("console.log(`Hello, Reflex from head!`)")])
```
