### ISSUE TITLE
How can I build apps that can be integrated with SSO login using this app ?

### ISSUE THREAD

**Issue by milan-sahu-kavak** [reflex-dev/reflex#1772]
Hello Team 

We are trying  to build some internal apps. But We would like to know how we can integrate SSO login funcionality from here ? The current documentation does not have any details .

**Comment by martinxu9** [comment]
Which SSO provider are y'all working with? 

We are working on a tutorial type of docs with some popular auth provider as examples to integrate into a reflex built app.

In the mean time, if your SSO provider has a prebuilt React component, you could follow https://reflex.dev/docs/advanced-guide/wrapping-react/ here to make it a component to use in your reflex App. I have tried wrapping some providers, very straightforward. There's also ones that requires adding some custom code. We could definitely help with your specific case.

**Comment by milan-sahu-kavak** [comment]
We are using google SSO here . Thanks for the doc. Let me check on the documentation on react wrapper .

**Comment by picklelo** [comment]
We have a guide for this now: https://reflex.dev/blog/2023-10-25-implementing-sign-in-with-google/

As well as a custom component implementing it: https://pypi.org/project/reflex-google-auth/

**Comment by imliuruiqi** [comment]
Hi. Any idea for Azure Active Directory? Is it possible to add login with Azure AD using reflex?
