### ISSUE TITLE
The value before on_load event is displayed for a moment

### ISSUE THREAD

**Issue by Evenzel** [reflex-dev/reflex#1776]
rx.text shows "A" briefly before showing "C"
Is it possible to make rx.text stop displaying "A" briefly and display "C" immediately?

**To Reproduce**
```python
import reflex as rx

class TestState(rx.State):    
    test_temp: str = "A"
    def test_init(self):
        self.test_temp = "C"        

def test():
    return rx.vstack(
        rx.text(TestState.test_temp),
    )

app = rx.App(state=TestState)
app.add_page(test, route="/test", on_load= TestState.test_init)
app.compile()
```

**Specifics (please complete the following information):**
 - Python Version: 3.11.4
 - Reflex Version: 0.2.6
 - OS: Windows 11
 - Browser (Optional): Chrome

**Comment by masenf** [comment]
```python
    return rx.vstack(
        rx.cond(TestState.is_hydrated, rx.text(TestState.test_temp)),
    )
```

if you avoid showing the value until `is_hydrated` gets set, then it shouldn't flicker.

**Comment by Evenzel** [comment]
Thank you! masenf
