### ISSUE TITLE
[REF-559] Wrapping local React component throws error

### ISSUE THREAD

**Issue by picklelo** [reflex-dev/reflex#1787]
Create a local react component in `assets/test.js`

```js
export function Test() {
  return <p>Test</p>;
}
```

Then try to reference it from an app

```python
import reflex as rx

class Test(rx.Component):
    library = "../public/test.js"
    tag = "Test"

    name: rx.Var[str]

test = Test.create

def index() -> rx.Component:
    return rx.fragment(
        test()
    )

app = rx.App()
app.add_page(index)
app.compile()
```

This is throwing an error in 0.2.7, while it was working in 0.2.6. We should fix this and add a test for this.

<sub>[REF-559](https://linear.app/reflex-dev/issue/REF-559/wrapping-local-react-component-throws-error)</sub>

**Comment by wassafshahzad** [comment]
@picklelo. I can take a look at this

**Comment by masenf** [comment]
https://github.com/reflex-dev/reflex/blob/fca5815a37b86efcda18980157e3cbec093f8bc1/reflex/app.py#L526

This line probably needs to check for startswith `/` _or_ `.` to catch local paths.

**Comment by wassafshahzad** [comment]
> Collaborator

Will update it today.
