### ISSUE TITLE
Wrap React PDF for more advanced manipulation

### ISSUE THREAD

**Issue by Lendemor** [reflex-dev/reflex#1789]
We could wrap  this lib to provide more advanced PDF manipulation (limited to display):
 https://www.npmjs.com/package/react-pdf

**Comment by sgaseretto** [comment]
Apparently it can also support displaying annotations from PDFs: https://github.com/wojtekmaj/react-pdf/blob/main/packages/react-pdf/README.md#support-for-annotations

**Comment by picklelo** [comment]
This should be a 3rd party component now - closing this issue for now.
