### ISSUE TITLE
multi-select does not work

### ISSUE THREAD

**Issue by signup2k** [reflex-dev/reflex#1791]
Multi-select does not work, neither with the example listed on  document's `selector` section, nor with the example code I copy and run on local machine.   

update::

I find the multselect.py and select.py both in the reflex component. 
The example given in the document, use `rx.select` only, even with multiselect example.

When I check the select.py file, the props in Select Class does not have `is_multi`, `close_menu_on_select`, etc. Which can be found in multiselect.py file.

But when I use rx.multi_select(), the Error message will be 

11, in <lambda>
    lambda e0: [Var.create_safe(f"{e0}.map(e => e.value)", is_local=True)]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joeyjiang/opt/anaconda3/envs/py311/lib/python3.11/site-packages/reflex/vars.py", line 238, in __bool__
    raise TypeError(
TypeError: Cannot convert Var 'true' to bool for use with `if`, `and`, `or`, and `not`. Instead use `rx.cond` and bitwise operators `&` (and), `|` (or), `~` (invert).

And I guess, the reflex mixed the select.py and multiselect.py when create Select instance (because in both select.py and multiselect.py file, the class name are the same `Select`).

I dont know how to fix this.

**Comment by signup2k** [comment]
I find the multselect.py and select.py both in the reflex component. 
The example given in the document, use `rx.select` only, even with multiselect example.

When I check the select.py file, the props in Select Class does not have `is_multi`, `close_menu_on_select`, etc. Which can be found in multiselect.py file.

But when I use rx.multi_select(), the Error message will be 

11, in <lambda>
    lambda e0: [Var.create_safe(f"{e0}.map(e => e.value)", is_local=True)]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joeyjiang/opt/anaconda3/envs/py311/lib/python3.11/site-packages/reflex/vars.py", line 238, in __bool__
    raise TypeError(
TypeError: Cannot convert Var 'true' to bool for use with `if`, `and`, `or`, and `not`. Instead use `rx.cond` and bitwise operators `&` (and), `|` (or), `~` (invert).

And I guess, the reflex mixed the select.py and multiselect.py when create Select instance (because in both select.py and multiselect.py file, the class name are the same `Select`).

I dont know how to fix this.

**Comment by masenf** [comment]
@signup2k see #1861... this component is going to need a lot more work to make it nice, but _that_ PR makes it functional

**Comment by signup2k** [comment]
@masenf  Thank you for your detail explaination.  #1861 works for me now. But as you said, this component do need a lot more work to make it nice.

**Comment by signup2k** [comment]
@masenf Thank you for your detail explaination. https://github.com/reflex-dev/reflex/pull/1861 works for me now. But as you said, this component do need a lot more work to make it nice.
