### ISSUE TITLE
Connection Error Displayed Upon Server Restart

### ISSUE THREAD

**Issue by seekerquest** [reflex-dev/reflex#1796]
**Describe the bug**
Upon file modification and server restart, this message keep getting displayed and slows down dev process. how can this be stopped ?

***Connection Error***
Cannot connect to server: timeout. Check if server is reachable at http://localhost:8000

**To Reproduce**
```shell
reflex run
```
**Expected behavior**
Page reload should not display this message.
**Screenshots**

**Specifics (please complete the following information):**
 - Python Version: 3.10.4
 - Reflex Version: 0.2.7
 - OS: Win11
 - Browser [(Optional):]()
 
**Additional context**

**Comment by masenf** [comment]
if you don't want the overlay when the websocket is down, you can pass

```
app = rx.App(overlay_component=None)
```

I'm curious about this part though

> this message keep getting displayed and slows down dev process

The message _should_ only be displayed when the backend is disconnected, which means that the app would be non-interactive for the same amount of time. Are you finding that the app takes longer to restart with the modal pop up?

**Comment by eldjoko** [comment]
Thank you! this seems to have resolved the issue. i no longer see a popup every single time the page refreshes.

This also seems to make the button `on_click` event handler work as well. Related to #1514

**Comment by masenf** [comment]
The default `overlay_component` displays any websocket connection errors very visibly, so that when the page is "non-interactive" it's clear why.

Without the connection modal, the websocket can just be down and the user wont really notice, other than the buttons and other interactivity just don't work.

I'm not sure how removing the overlay component could have much effect on #1514. Is that very reproducible? Because sometimes it can take a bit for the backend to get ready, and the frontend would be unresponsive until then. So if that were the case, then you'd see the connection error popup, instead of the buttons just not working.

**Comment by ekreutz** [comment]
Just chiming in to say that I also have this problem.

I just tried Reflex for the very first time, and installed it in a fresh Python (3.11) environment.

All I get is this:

```
Connection Error
Cannot connect to server: websocket error. Check if server is reachable at http://localhost:8000
```

![image](https://github.com/reflex-dev/reflex/assets/9801173/9fdfd63d-51a7-452c-b68e-9dd943722bf6)

And that's on a brand new project with zero customization. Hiding the modal seems like a bad solution, tucking the problem away...

**Comment by masenf** [comment]
@ekreutz were you able to bring up http://localhost:8000/ping and get the `"pong"` response? Did the modal go away after some time (<2 minutes usually)?

**Comment by 99hats** [comment]
Hi there,
I'm getting the 

Connection Error
Cannot connect to server: websocket error. Check if server is reachable at http://localhost:8000

On a very simple hello world app with backend_port = 3040

I'm not sure if it is related, as a workaround, I'm sticking with port 8000 but it means I can only have one reflex instance on this server.

**Comment by masenf** [comment]
@99hats if you change the `backend_port`, then you must also change the `api_url` to point to that port.

The `api_url` should be a publicly accessible URL where the backend is running that the frontend will connect to.

If you're hosting the backend on `example.com:3040`, then set `api_url="http://example.com:3040"`

**Comment by 99hats** [comment]
@masenf Thank you so much for your help. I must have glanced through the documentation too quick.

**Comment by gbrandt1** [comment]
hello, 

i'm having this issue as well, using ubu2004 in WSL2. i can reach the API just fine in the browser and use it eg. via the swagger UI. i can also use it with curl from the shell. but the frontend itself cannot reach the URL it displays. i tried using localhost, IP, DNS name, forwarding the API port in VSCode (it's auto-forwarded but i also tried user forward). i disabled IPv6 everywhere ... nothing helps, running out of ideas. what else can i try?

**Comment by masenf** [comment]
@gbrandt1 when you open the dev tools, network tab in your browser do you see anything regarding the `/event?EIO=4&transport=websocket` connection?

<img width="935" alt="image" src="https://github.com/reflex-dev/reflex/assets/1524005/41ae8c5a-bdd7-4f3f-b1c5-9c3a4f1c2692">

**Comment by gbrandt1** [comment]
yes, i see that it fails:

![image](https://github.com/reflex-dev/reflex/assets/17267871/c10962f1-ea8c-41bd-9da6-7031bcb542a6)

**Comment by masenf** [comment]
That double backslash is a bit suspicious. What are you using as `api_url`? It shouldn't have a trailing slash.

**Comment by gbrandt1** [comment]
I did have a backslash which i removed now. Now i'm using

api_url="http://localhost:8000"

but it doesn't help:

![image](https://github.com/reflex-dev/reflex/assets/17267871/62042279-8c7e-4426-a02e-cda2bf167c13)

**Comment by gbrandt1** [comment]
Hi @masenf, 
just to let you know after rebooting Windows and restarting reflex it works now. not sure if it was an issue with WSL networking or I didn't properly refresh things after removing the trailing backslash.
Thanks for the help!

**Comment by Roman-Hahnair** [comment]
I also got those wired timeout and websocket errors. In my case, it turned out that I was developing on reflex 0.3.1, but it was 0.2.9 (or something like this) on the VM where I'm hosting the app. 

I've updated the lib to 0.3.2 on the VM, manually deleted the .web dir, reinitialized the app, and now it works.

**Comment by ZaneH** [comment]
I have this issue with a brand new project as well. I'm noticing that this "issue" only happens in my Brave browser. If I open `localhost:3000` in Chrome, I never get this error message.

## Brave

<img width="651" alt="SCR-20231129-mzfv" src="https://github.com/reflex-dev/reflex/assets/8400251/17308e3c-a38c-49c6-bc93-80f443794d69">

## Chrome

<img width="555" alt="SCR-20231129-mzdt" src="https://github.com/reflex-dev/reflex/assets/8400251/b9628c11-f2c7-4abe-b73b-6429a2abc7f0">

**Comment by ZaneH** [comment]
> I have this issue with a brand new project as well. I'm noticing that this issue only happens in my Brave browser. If I open `localhost:3000` in Chrome, I never get this error message. I should also mention: I've disabled ad-block and Brave Shields on localhost. Same result.
> 
> I haven't really experienced anything like this before (with Brave), hopefully it's fixable.

Update: This seems to have been resolved. I can use reflex with Brave now.

**Comment by fumi-arai** [comment]
I encountered the same issue while working on the tutorial. I ran `reflex run` on Ubuntu in WSL2 and opened the app in the Brave browser on Windows. This issue did not occur when I opened it in Edge. Additionally, running `reflex run --backend-port 3050` resolved the issue in Brave as well. The status of Brave Shields (enabled/disabled) did not affect the result.

**Comment by Lendemor** [comment]
If the issue is specific to Brave browser I'm not sure this is something we have to fix on our side, if everything work for all other browsers.
