### ISSUE TITLE
rx.tooltip label does not disappear with checked rx.checkbox

### ISSUE THREAD

**Issue by Jogenist** [reflex-dev/reflex#1801]
**Describe the bug**
When using rx.tooltip on a rx.checkbox, the label does not disappear until something else is clicked on. 

**To Reproduce**
 - create rx.tooltip on a rx.checkbox
 - hover over rx.checkbox with mouse to display the label
 - move cursor away from rx.checkbox

**Expected behavior**
When moving the cursor away from rx.checkbox, the label of rx.tooltip should disappear. 
(Same behaviour as using rx.tooltip with rx.button, rx.text, etc.)

**Specifics (please complete the following information):**
 - Python Version: 3.10.5
 - Reflex Version: 0.2.7
 - OS: Windows 10 Enterprise

**Comment by Lendemor** [comment]
Tested with 
```python
rx.tooltip(
    rx.checkbox(),
    content="This is a tooltip",
)
```
Does not happens anymore.
