### ISSUE TITLE
[REF-674] Var name in component id weirdness

### ISSUE THREAD

**Issue by jpbaltazar** [reflex-dev/reflex#1802]
Hi

Sorry in advance for the not very descriptive issue name but I'm not sure how to better describe it.

I've stumbled on a weird issue. Essentially I'm doing some conditional menus on a form (for example, the frequency of some event after asking if the event happens) and I need to retrieve these values on the submission.

I'm actually trying to acquire a number from a number_input component with this, but every time I use one of the options I've marked with 'does not work' I get the following error:

```
TypeError: Cannot convert Var '(("_" + _) + "_option")' to bool for use with `if`, `and`, `or`, and `not`. Instead use `rx.cond` and bitwise operators `&` (and), `|` (or), `~` (invert). 
```

I'm able to do this with select but not number_input, and if I try it with select I can't use fstrings or I'll get the same error.

I've made an example that emulates my current process:

```python
import reflex as rx

class State(rx.State):
    """The app state."""

    var: str = ""

    parameters_state: dict[str, str] # key -> state 

    def change_parameter(self, key, new_state):
        self.parameters_state[key] = new_state

    @rx.var
    def keys(self) -> list[str]:
        return ["parameters1", "parameters2"]

    def print_dict(self, form_data: dict):
        print(form_data)

def fn(key: str):
    return rx.vstack(
        rx.text(f"hello {key}"),
        rx.select(
            ["on", "off"],
            id="_" + key + "_state",
            default_value="off",
            on_change=lambda new_state: State.change_parameter(key, new_state)
        ),
        rx.cond(
            State.parameters_state[key] == "on",
            
            # works
            rx.select(
                ["option1", "option2"],
                id="_"+ key + "_option",
            ),

            # does not work
            # rx.select(
            #     ["option1", "option2"],
            #     id=f"_{key}_option",
            # ),

            # does not work
            #rx.number_input(
            #    id="_" + key + "_option",
            #),
        )
    )

def index() -> rx.Component:
    return rx.vstack(

        rx.form(
            rx.foreach(
                State.keys,
                fn,
            ),
            on_submit=State.print_dict,
        ),

        spacing="1.5em",
        font_size="2em",
        padding_top="10%",
    )


app = rx.App()
app.add_page(index)
app.compile()

```

<sub>[REF-674](https://linear.app/reflex-dev/issue/REF-674/var-name-in-component-id-weirdness)</sub>

**Comment by masenf** [comment]
This seems like #1490, in that the code is trying to assign dynamic ID to form elements, and we do not currently have a way to handle that.

**Comment by jpbaltazar** [comment]
@masenf Could I request that as a feature? I think dynamic ids could be useful

**Comment by adhami3310** [comment]
This has been fixed in main. It will work in 0.6.0 which is releasing soon.
