### ISSUE TITLE
OSError (Errno 86) when running Reflex v0.2.7 on Apple M1 

### ISSUE THREAD

**Issue by divin** [reflex-dev/reflex#1803]
**Describe the bug**
When starting a new project with the latest Reflex version I can't initialise the project, `reflex init` gives this error 
`OSError: [Errno 86] Bad CPU type in executable: '/Users/divin/Library/Application Support/reflex/fnm/fnm'` on my MacBook with M1 Chip.  assume there is some problem with `fnm`, but according to the project page it should be compatible with Apple chips.

* `arch` gives me this `arm64`
* `python -c 'import platform; print(platform.machine())'` also `arm64`

**To Reproduce**
```bash
conda create --name test python=3.10
conda activate test
pip install reflex
mkdir test
cd test
reflex init
```

**Expected behavior**
No issues starting a new project.

**Specifics (please complete the following information):**
 - Python Version: 3.10
 - Reflex Version: 0.2.7
 - OS: macOS 13.5.2 (22G91)

**Comment by masenf** [comment]
Can you try the following command

```
/usr/sbin/softwareupdate --install-rosetta --agree-to-license
```

**Comment by tboulogne** [comment]
Hello @divin 

Got problem to start reflex on mac mini M1. Aftert upgrading all packages in package.json, works well.
So git it a try.

Regards

**Comment by divin** [comment]
> Can you try the following command
> 
> ```
> /usr/sbin/softwareupdate --install-rosetta --agree-to-license
> ```

Thanks @masenf for installing Rosetta and making it work! The package manager Reflex used before was a bit nicer in this respect as it runs natively on Apple silicon and there was no need to install Rosetta. Let's see if `fnm` will also be updated to run natively 😄

I took the opportunity and created a [PR](https://github.com/reflex-dev/reflex-web/pull/200) for the Reflex website to add this information.

Should I close the issue or leave it open until my PR is merged (or rejected)?

**Comment by masenf** [comment]
addressed via https://github.com/reflex-dev/reflex-web/pull/200
