### ISSUE TITLE
Data Table behavior is inconsistent when empty

### ISSUE THREAD

**Issue by PedroDaumas** [reflex-dev/reflex#1830]
**Describe the bug**
The data table element will sometimes return a text saying "No matching records found" and other times just empty rows when you have an empty list, or a state with the value being an empty list.

**To Reproduce**
Steps to reproduce the behavior: create a data table with data=[] and reload the page a few times.
 - Code/Link to Repo:

`rx.data_table(data=[], columns=["A", "B"])`

**Expected behavior**
Everytime the data_table has no data it should return the text "No matching records found", no matter how many times you reload

**Screenshots**
![image](https://github.com/reflex-dev/reflex/assets/20216082/8dc4b4fb-b9bf-4b56-9fa6-d166c1812e80)
![image](https://github.com/reflex-dev/reflex/assets/20216082/933cceba-8fc5-4da7-ac38-61147e912374)

**Specifics (please complete the following information):**
 - Python Version: 3.8
 - Reflex Version: 0.2.7
 - OS: Docker container (Linux)
 - Browser (Optional): Chrome
 
**Additional context**

**Comment by RyleyGG** [comment]
Thank you for submitting this bug report. PR https://github.com/reflex-dev/reflex/pull/1894 resolves this.

**Comment by adhami3310** [comment]
This issue seems to be in gridjs/gridjs-react
