### ISSUE TITLE
[REF-647] `deepcopy` on rx.Model not working

### ISSUE THREAD

**Issue by jpbaltazar** [reflex-dev/reflex#1841]
Hi I've been using `deepcopy` to transform some complex rx.Model entities onto dictionaries of primitives and I've verified it works up until version 2.7 but after some recent commit it stops working.

A minimal example to reproduce this issue:

```
from copy import deepcopy

import reflex as rx

class MyModel(rx.Model):
    s: str

class State(rx.State):
    """The app state."""

    my_model : MyModel = MyModel(**{"s":"hello"})

    def print_deepcopy(self):
        print(deepcopy(self.my_model))

def index() -> rx.Component:
    return rx.vstack(
        rx.button("Button", on_click=State.print_deepcopy)
    )

# Add state and page to the app.
app = rx.App()
app.add_page(index)
app.compile()
```

<sub>From [SyncLinear.com](https://synclinear.com) | [REF-647](https://linear.app/reflex-dev/issue/REF-647/deepcopy-on-rxmodel-not-working)</sub>

**Comment by masenf** [comment]
Fairly sure this was introduced via #1748, which wraps `list`, `dict`, `set`, and `Base` in `wrapt.ObjectProxy` to enable more efficient change tracking.

When I run the provided code (with slight modifications), I get

```console
Traceback (most recent call last):
  File "/Users/masenf/code/reflex-dev/VENV-repro-6/lib/python3.11/site-packages/reflex/state.py", line 816, in _process_event
    events = fn(**payload)
             ^^^^^^^^^^^^^
  File "/Users/masenf/code/reflex-dev/repro-1841/repro_1841/repro_1841.py", line 14, in print_deepcopy
    print(deepcopy(self.my_model))
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/copy.py", line 153, in deepcopy
    y = copier(memo)
        ^^^^^^^^^^^^
NotImplementedError: object proxy must define __deepcopy__()
```

Sounds like I need to make the new `MutableProxy` compatible with `__deepcopy__` and add a test case.

Thank you @jpbaltazar for reporting this issue on pre-release code so we can get it fixed! 🙏

**Comment by jpbaltazar** [comment]
Thank you so much for solving this in record time! I'm glad to be able to at least contribute to this project in this way :)
