### ISSUE TITLE
[REF-676] Script Tag Render In _document.js

### ISSUE THREAD

**Issue by Alek99** [reflex-dev/reflex#1862]
The script tag should have an option render in the document js 

for example if I wanted two load a bokeh script it would look like so:

```
import { Head, Html, Main, NextScript } from "next/document"
import { ColorModeScript } from "@chakra-ui/react"



export default function Document() {
  return (
    <Html>
  <Head>
          <script src="https://cdn.bokeh.org/bokeh/release/bokeh-3.2.2.min.js"></script>
        </Head>
  <body>
  <ColorModeScript initialColorMode={`light`}/>
  <Main/>
  <NextScript/>
</body>
</Html>
  )
}
```

<sub>[REF-676](https://linear.app/reflex-dev/issue/REF-676/script-tag-render-in-documentjs)</sub>

**Comment by Alek99** [comment]
Will allow the implementation of bokeh graphing lib and ability to add things like google Analytics

**Comment by masenf** [comment]
Is rx.script insufficient for this use case?

**Comment by Alek99** [comment]
I tried that but the script needs to be in the document.js so be probably need a way to enable rx.script to write to there
