### ISSUE TITLE
[REF-690] Changed dict values are not reflected in foreach

### ISSUE THREAD

**Issue by Evenzel** [reflex-dev/reflex#1874]
**Describe the bug**
Changed dict values are not reflected in foreach
Entering a value in editable changes #2 but leaves #1 unaffected.

**To Reproduce**
```python
import reflex as rx

class State(rx.State):
    dict_list: list[dict[str,str]] = [{"name": "A", "age": "10"}, {"name": "B", "age": "20"}]
    test_value: str = '0'

    def update_value(self, name: str, new_age: str):
        for item in self.dict_list:
            if item['name'] == name:
                item['age'] = new_age #1
        self.test_value = new_age #2
        print(self.dict_list)

        
def test(item: dict[str,str]):
    return rx.hstack(
        rx.text(item['name']),
        rx.text(item['age']), #1                
        rx.text(State.test_value), #2
        rx.editable(
            rx.editable_preview(),
            rx.editable_input(),
            placeholder="age input",
            default_value= item['age'],            
            on_change= lambda new_age: State.update_value(item['name'], new_age),
            width="100%",
        ),
    )

def index():
    return rx.box(rx.foreach(State.dict_list, test))

app = rx.App(state=State)
app.add_page(index)
app.compile()
```

**Expected behavior**

#1 and #2 should be the same since they both follow the new_age value.

**Screenshots**

**Specifics (please complete the following information):**
 - Python Version: 3.11.4
 - Reflex Version: 0.2.8
 - OS: Windows 10
 - Browser (Optional): Chrome
 
**Additional context**

<sub>[REF-690](https://linear.app/reflex-dev/issue/REF-690/changed-dict-values-are-not-reflected-in-foreach)</sub>

**Comment by masenf** [comment]
Thanks for the repro case. I have identified the issue in a recent change and will submit a fix.
