### ISSUE TITLE
[REF-697] Support per-component State

### ISSUE THREAD

**Issue by masenf** [reflex-dev/reflex#1877]
Currently `State` is global across the app and all components can access it... however it's not currently possible to define reusable reflex components that have their own per-component independent state.

Why would you want this? For example if I'm defining a widget, like a counter, and I want to place multiple counters in the app, then each counter needs its own state so they don't interfere with each other.

This can be achieved in 0.2.8 by using a `dict` in the state and keying each component into it, but it's not very clean. It would be nice if a component could define "local" state that was only part of that instance of the component.

How might this look?

```python
def my_counter() -> rx.Component:
    class CounterState(rx.LocalState):
        count: int = 0

        def increment(self):
            self.count += 1

    return rx.vstack(
        rx.heading(CounterState.count),
        rx.button("Increment", on_click=CounterState.increment),
    )

def index():
    return rx.vstack(
        my_counter(),
        my_counter(),
        my_counter(),
    )
```

In this example, each counter should get its own copy of `CounterState` and operate independently.

Other API suggests are welcome at this point, since the feature still needs to be designed.

<sub>[REF-697](https://linear.app/reflex-dev/issue/REF-697/support-per-component-state)</sub>

**Comment by include** [comment]
Hi @masenf - just saw this State topic floating around and I was wondering if the https://github.com/reflex-dev/reflex/issues/1771 would be also something that cloud be addressed on this thread?

**Comment by masenf** [comment]
@include #1771 is already fixed in `main`, you can try out `reflex==0.2.10a1` and see if it's working for you

**Comment by include** [comment]
@masenf working flowless :) thank you very much!

**Comment by dstalzjohn** [comment]
Is it correct, that it is currently not possible to use two different counter which share code (a reusable component with different states). 

I think in plain react it would look something like this:
```
const Counter = () => {
  const [count, setCount] = useState(0);

  const handleIncrement = () => setCount(count + 1);
  const handleDecrement = () => setCount(count - 1);

  return (
    <div>
      <span>Current Count: {count}</span>

      <div className="buttons">
        <button onClick={handleIncrement}>Increment</button>
        <button onClick={handleDecrement}>Decrement</button>
      </div>
    </div>
  );
};
```

**Comment by dstalzjohn** [comment]
Maybe it would be nice to write an own component like this:

```
class Counter(rx.UserComponent):
    count: int = rx.use_state(0)

    def handle_increment(self):
        self.count += 1

    def build(self) -> rx.Component:
        return rx.vstack(
        rx.heading(CounterState.count),
        rx.button("Increment", on_click=self.handle_increment),
    )
```

**Comment by benedikt-bartscher** [comment]
With my recent PRs something like this is already possible:

```python

class Counter:
    count: int = 0

    def handle_increment(self):
        self.count += 1

   @classmethod
    def render(cls) -> rx.Component:
        return rx.vstack(
        rx.heading(cls.count),
        rx.button("Increment", on_click=cls.handle_increment),
    )

class CounterOne(Counter, rx.State):
  pass
```

**Comment by TimChild** [comment]
Is this anywhere in the docs? (re-usable component with state and event handlers built-in)

If not, it should be!

**Comment by picklelo** [comment]
@TimChild this was added recently:https://reflex.dev/docs/substates/component-state/
