### ISSUE TITLE
Cannot Debug Reflex App in VS Code -  Error: "No module named reflex"

### ISSUE THREAD

**Issue by fatherofinvention** [reflex-dev/reflex#1880]
### Describe the bug

When trying to debug my Reflex app using VS Code, using the **[provided debugging documentation here](https://github.com/reflex-dev/reflex/blob/41872dfdc97a7facd076f60bd56ba0cd320705e4/docs/DEBUGGING.md#L4)**, an error message is shown indicating that the `reflex` module could not be found: ***"No module named reflex"***.

---

### To Reproduce

1. Setup the project using PyEnv for Python 3.11.5 and Poetry for dependency management.

2. Use the following `launch.json` configuration in VS Code for debugging:

   ```json
   {
       "version": "0.2.0",
       "configurations": [
           {
               "name": "Reflex App",
               "type": "python",
               "request": "launch",
               "module": "reflex",
               "args": "run --env dev",
               "justMyCode": true,
               "cwd": "${fileDirname}/.."
           }
       ]
   }
   ```

3. Execute `poetry shell` while in the project directory. _I have also tried skipping this step and running the command below outside of poetry shell, just to test, without any luck._

4. Run `python -m reflex run --env dev` in the terminal.

5. Start debugging in VS Code using the "Reflex App" configuration.

6. Get error message.

**Expected Behavior**

I expected to run my Reflex application using the above command, then in VS Code start debugging using the "Reflex App" configuration above, allowing me to halt on breakpoints and step through code.

I noticed that when I click Start Debugging, a new Python Debug Console opens up with a different PID than the **python3** one that I ran the `python -m reflex run --env dev` commandin. Could this have something to do with the error and if so, how do I resolve it?

---

### Screenshots

![CleanShot 2023-09-27 at 16 12 22@2x](https://github.com/reflex-dev/reflex/assets/24985048/09acd41a-d4ae-43fe-90bc-b6e5bacde08c)

![CleanShot 2023-09-27 at 16 13 12@2x](https://github.com/reflex-dev/reflex/assets/24985048/98653c22-d5a5-4cd9-9eed-dcf7e73582a5)

![CleanShot 2023-09-27 at 16 22 03@2x](https://github.com/reflex-dev/reflex/assets/24985048/c23ac9f9-aa74-43d9-8dfe-999c1ae816b6)

---

### Specifics (please complete the following information):

- Python Version: 3.11.5
- Reflex Version: 0.2.8 (latest)
- OS: Ubuntu 22.04.3 LTS
- VS Code Version: 1.83.0-insider
- Browser: Not applicable to this issue report

---

### Additional context

Poetry was installed in a Python 3.10 environment and `pyenv` was set to use Python 3.11.5. Despite these configurations, the module couldn't be found when debugging was initiated.

**Comment by masenf** [comment]
Glad to see you got it working, and thanks for coming back and providing breadcrumbs for the next person.

Given the complexity of different project structures, it's hard to provide reliable instructions that will work in every case and configuration. I've typically found the vscode launch config to work when vscode can "see" the correct python virtualenv with reflex installed.

When you're working on your project files, is vscode able to resolve the `reflex` imports?
