### ISSUE TITLE
checkbox refresh failed

### ISSUE THREAD

**Issue by ltm920716** [reflex-dev/reflex#1882]
**Describe the bug**
the checkbox refresh failed in complex operation

**To Reproduce**
state.py
```
selected_history_item: List[ChatRunRecord] = []

def set_select_history_item(self, val, node_item: ChatRunRecord):
        if self.selected_history_item and (self.history_node_name != self.selected_history_item[0].get('node_name')):
            self.selected_history_item = []

        if val:
            if len(self.selected_history_item) == 1:
                consistant_ = self.consistant_compare(self.selected_history_item[0], node_item)
                if not consistant_:
                    self.compare_error = True
                    return
            self.selected_history_item.append(node_item)
        else:
            self.selected_history_item.remove(node_item)

        if len(self.selected_history_item) > 2:
            self.selected_history_item.remove(node_item)
            self.check_max_compare = True
```

view.py
```
rx.tbody(
  rx.foreach(
      HistoryState.query_history_by_name, 
      lambda item, index: rx.tr(
                              rx.td(item.node_name),
                              rx.td(item.node_version),
                              rx.td(item.dataset),
                              rx.td(rx.checkbox(name=str(index), id=str(index), color_scheme="green", 
                                                on_change=lambda val: HistoryState.set_select_history_item(val, item),
                                                is_checked=HistoryState.selected_history_item.contains(item)
                                                )
                                  )
                          )
      ),
  width="100%"
  )
  ```

**Expected behavior**
the box should be checked when corresponded item in selected_history_item
 
**Screenshots**
![image](https://github.com/reflex-dev/reflex/assets/12007227/43c5d259-db40-4461-bd00-55dfee89b523)

 
**Additional context**
actually，checkbox is worded normally when only using on_change handler，I need add some logical to control the is_checked property, then the box can not be checked anymore, the val value to set_select_history_item always be true，I think somewhere not refresh correctly

**Comment by ltm920716** [comment]
I change my code following
![image](https://github.com/reflex-dev/reflex/assets/12007227/894c9efe-effc-431b-b0db-4b5421dc1b3c)

![image](https://github.com/reflex-dev/reflex/assets/12007227/125e72ba-6490-4654-9280-f7c3c2801eed)
can not refresh correctly

**Comment by ltm920716** [comment]
it seems  that ```contains``` operation can not refresh immediately

**Comment by ltm920716** [comment]
I make it by __getitem__ the another bool list

**Comment by masenf** [comment]
Checking `contains` with a complex object (`ChatRunRecord`) is not likely to work.

It would be more reliable to use a simple key/id in `selected_history_item` to mark whether a particular object is selected and then get the complex object out of a different `dict` using that key.
