### ISSUE TITLE
Add timeout to GitHub actions 

### ISSUE THREAD

**Issue by Alek99** [reflex-dev/reflex#1893]
Earlier today I noticed some actions were taking a really long time probably a results of my pr https://github.com/reflex-dev/reflex/actions/runs/6360632822/job/17274517595. 

In general though we should decide on a maximum timeout so they don't run for a long time, example mine running for longer than 40 minutes.

**Comment by Kamalkoranga** [comment]
Hey @Alek99, what should be maximum timeout?
