### ISSUE TITLE
[REF-723] Progress Display for rx.upload

### ISSUE THREAD

**Issue by Anga205** [reflex-dev/reflex#1896]
**Describe the bug**
rx.upload allows a user to upload files to a reflex app but buffers a bunch when large files are being selected to upload (expectedly), however as it stands now, reflex apparently does not have any support for progress display, like a progress bar that shows how much of the selected data has been uploaded vs how much is left

**To Reproduce**
this issue is not reproduceable as it is a request for a new feature

**Expected behavior**
a method, any method, to allow the end user to track how much of a file has been uploaded and how much is left

![image](https://github.com/reflex-dev/reflex/assets/74541474/63adf230-08fd-4fda-a4b2-f09d3345476e)

<sub>[REF-723](https://linear.app/reflex-dev/issue/REF-723/progress-display-for-rxupload)</sub>

**Comment by Anga205** [comment]
bump

**Comment by masenf** [comment]
The code is done and in review, but we're a small team.
