### ISSUE TITLE
New rx.menu() API does not work correctly

### ISSUE THREAD

**Issue by iron3oxide** [reflex-dev/reflex#1903]
**Describe the bug**
When using `rx.menu()`, I have to provide at least the arguments `button` and `items`, which are both type-hinted as `Unknown`. When I provide an avatar as the button and a list of strings as the items, the resulting menu only contains one item (named after all the strings combined) which is also unusable. 

**To Reproduce**
 ```python
def avatar_menu():
    return rx.menu(button=rx.avatar(name="Max Hustemann"), items=["A", "B", "C"])
```

**Expected behavior**
A menu that contains the selectable items A, B and C.

**Specifics (please complete the following information):**
 - Python Version: 3.11.5
 - Reflex Version: 0.2.8
 - OS: Fedora 
 - Browser (Optional): Brave
 
**Additional context**
I suspect this happens because no `MenuItem` is ever created for each item and a `MenuList` is instead used directly. Also, I'd suggest to type hint the items as a `List`.

**Comment by Lendemor** [comment]
After the PR, the following : 
```python
def avatar_menu():
    return rx.menu(
        button=rx.avatar(name="Max Hustemann"), items=[rx.menu_item("A"), "B", "C"]
    )
```
Will show a properly working menu.

**Comment by Evenzel** [comment]
ㅔ0
