### ISSUE TITLE
pc.responsive_grid column component can't take in a list of vars

### ISSUE THREAD

**Issue by DPetuskey** [reflex-dev/reflex#191]
**Describe the bug**
I try to pass in a State variable based on some user input  into the "columns" component of pc.responsive_grid and I get a typeError. It expects a List[int] type but when I pass in a List of integers that are state vars it errors.

TypeError: Invalid var passed for prop columns, expected type pynecone.var.Var[typing.List[int]], got value [BaseVar(name='size', type_=<class 'int'>, state='state', is_local=False, is_string=False)] of type <class 'list'>.

**Expected behavior**
Expect my pc.responsive_grid to update column size based on input into a State var. 

**Screenshots**
<img width="1440" alt="Screen Shot 2022-12-29 at 5 42 08 PM" src="https://user-images.githubusercontent.com/98362056/210026346-26f53987-6ed3-4a98-9a53-77711c8138ce.png">

** Specifics (please complete the following information):**
 - Python Version: 3.11
 - Pynecone Version: 1.10
 - OS: 
 - Browser (Optional):
 
**Additional context**

**Comment by Alek99** [comment]
Got it, I can fix this for the next release

**Comment by ElijahAhianyo** [comment]
closing this as it was fixed
