### ISSUE TITLE
Throw an error at compile time for rx.input

### ISSUE THREAD

**Issue by martinxu9** [reflex-dev/reflex#1911]
**Describe the bug**

Running into this error as title and the page does not render. But it compiles.

**To Reproduce**
 - Code/Link to Repo:
```
rx.input("Enter invitation code")
```

**Expected behavior**

**Screenshots**
<img width="999" alt="image" src="https://github.com/reflex-dev/reflex/assets/15661672/82c45c44-7630-4c5e-95d1-ef68bf10025a">

**Specifics (please complete the following information):**
 - Python Version: 3.11
 - Reflex Version: 2.8
 - OS: MacOS
 - Browser (Optional): Chrome
 
**Additional context**
Turns out it should have been `rx.input(placeholder="Enter invitation code")` instead. Think compile should error out instead of on the web page.

**Comment by Technmad** [comment]
I want to contribute. Please assign me the issue @martinxu9

**Comment by martinxu9** [comment]
Thanks @Technmad

**Comment by martinxu9** [comment]
Cc @Lendemor @masenf

**Comment by masenf** [comment]
New radix `rx.input` treats children as slots

```
rx.input("foo")
```

becomes 

![image](https://github.com/reflex-dev/reflex/assets/1524005/12e21565-6479-48c4-8b33-6daba87effc8)
