### ISSUE TITLE
Refelx db init command error

### ISSUE THREAD

**Issue by ironwod** [reflex-dev/reflex#1913]
**Describe the bug**
When running 'reflex db init' command the following error appear.:

> Traceback (most recent call last):
>   File "/home/XXX/.local/share/virtualenvs/web_server-RG1fDWNH/bin/reflex", line 8, in <module>
>     sys.exit(cli())
>              ^^^^^
> File "/home/XXX/.local/share/virtualenvs/web_server-RG1fDWNH/lib/python3.11/site-packages/typer/main.py", line 214, in __call__
>     return get_command(self)(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> File "/home/XXX/.local/share/virtualenvs/web_server-RG1fDWNH/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
>     return self.main(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/XXX/.local/share/virtualenvs/web_server-RG1fDWNH/lib/python3.11/site-packages/click/core.py", line 1078, in main
>     rv = self.invoke(ctx)
>          ^^^^^^^^^^^^^^^^
>   File "/home/XXX/.local/share/virtualenvs/web_server-RG1fDWNH/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/XXX/.local/share/virtualenvs/web_server-RG1fDWNH/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/XXX/.local/share/virtualenvs/web_server-RG1fDWNH/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/XXX/.local/share/virtualenvs/web_server-RG1fDWNH/lib/python3.11/site-packages/click/core.py", line 783, in invoke
>     return __callback(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/XXX/.local/share/virtualenvs/web_server-RG1fDWNH/lib/python3.11/site-packages/typer/main.py", line 532, in wrapper
>     return callback(**use_params)  # type: ignore
>            ^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/XXX/.local/share/virtualenvs/web_server-RG1fDWNH/lib/python3.11/site-packages/reflex/reflex.py", line 321, in makemigrations
>     prerequisites.get_app()
>   File "/home/XXX/.local/share/virtualenvs/web_server-RG1fDWNH/lib/python3.11/site-packages/reflex/utils/prerequisites.py", line 116, in get_app
>     return __import__(module, fromlist=(constants.APP_VAR,))
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> ModuleNotFoundError: No module named '.'

It looks like, that the init script ignores `app_name` parameter in rxconfig.py file.

**To Reproduce**

Running in virtual environment (pipenv) with following rxconfig.py file. I did not set any ENV with app name and not using any CLI flags.
 
```
import reflex as rx
from os import environ, isfile

def read_env(var):
    if isfile(f".env/{var}"):
        with open(f".env/{var}", "r") as f:
            return f.read().strip()
    if var in environ:
        return environ[var]

    raise ValueError(f"ENV {var} not found")

class WebserverConfig(rx.Config):
    pass

config = WebserverConfig(
    app_name="hadr",
    db_config=rx.Config(
        engine="mariadb",
        username=read_env("DB_USER"),
        password=read_env("DB_PW"),
        host=read_env("DB_HOST"),
        port=3306,
        database="Hadr"
    ),
)

```

**Expected behavior**
Initialize database and create alembic.ini file

**Specifics (please complete the following information):**
 - Python Version: 3.11
 - Reflex Version: 0.2.6
 - OS: Manjaro 23.0.2 Uranos
 - Browser (Optional):

**Comment by Lendemor** [comment]
Is the issue still happening in latest version (0.2.9) ?

**Comment by picklelo** [comment]
Closing this, feel free to reopen if it still persists.
