### ISSUE TITLE
Cannot change Icon Size/Width/Height

### ISSUE THREAD

**Issue by Alek99** [reflex-dev/reflex#1918]
You cannot change the Icon size.

```python
rx.icon(
       tag="hamburger",
       size="4em", #change this
       color="#1A1060",
 )
```
 
 Also tried changing width/height to no affect

**Comment by PranaviB** [comment]
It looks like chakra-ui library supports different prop for icon sizes, could you please give it a try with the snippet below
 
 ```python
 rx.icon(
        tag="hamburger",
        boxSize="4em",
        color="#1A1060",
  )
```

<img width="300" alt="Screenshot 2023-10-07 at 9 31 41 PM" src="https://github.com/reflex-dev/reflex/assets/7920197/daeeba96-3f4a-45d3-ba24-5c174c1ccf1f">

**Comment by shubhalgupta** [comment]
please assign me this issue!

**Comment by ironspec07** [comment]
sounds intresting , can you please assign this to me @Alek99

**Comment by Alek99** [comment]
@shubhalgupta Are you still interested otherwise I'll assign to @ironspec07

**Comment by PranaviB** [comment]
@Alek99 Wasn't the issue resolved with the snippet I shared above? Are we looking to implement the 'size' key? 
I am sorry I might have misunderstood, can you please shed some light?

**Comment by picklelo** [comment]
@PranaviB just tested you solution - seems to work well. Closing this issue
