### ISSUE TITLE
Invalid path: ['state']

### ISSUE THREAD

**Issue by nbowisdar** [reflex-dev/reflex#1933]
When I run the code from a [tutorial](https://reflex.dev/docs/tutorial/frontend/) I get this error:

![image](https://github.com/reflex-dev/reflex/assets/78906490/0a9acb46-b450-4189-bf11-06649f8fff0a)

python Version - python3.11.4 or 3.12.0

Platform: Windows

**Comment by ElijahAhianyo** [comment]
Ive ran the example and it works for me, just to re-confirm, can you post your version of the code as well as what reflex version youre running?

**Comment by ElijahAhianyo** [comment]
I noticed this error comes up when you dont define a state and tends to look up the default state name which has now been removed. This should be fixed in the current release
