### ISSUE TITLE
Can't run Reflex if Project is located on an external Volume

### ISSUE THREAD

**Issue by divin** [reflex-dev/reflex#1935]
**Describe the bug**
I recently updated to macOS Sonoma (clean install) and it seems there is some issue now with Reflex. I installed Reflex in a new Python 3.11 Environment (also had to install Rosetta due to FNM), `reflex init` works fine but when I try `reflex run` then I get the following error

```bash
Debug: Running command: ['/Users/divin/Library/Application 
Support/reflex/fnm/node-versions/v18.17.0/installation/bin/npm', 'run', 'dev']
Debug: Starting frontend
Debug: 
Debug: > dev
Debug: > next dev
Debug: 
Debug: sh: next: command not found
Starting frontend failed with exit code 127

> dev
> next dev

sh: next: command not found
Run with --loglevel debug  for the full log.
```

It seems `next` is not installed or can't be found. I tried installing it within the Reflex NPM environment but it didn't worked.
Here is the full-log: [message.txt](https://github.com/reflex-dev/reflex/files/12837823/message.txt)

**To Reproduce**
On a clean install of macOS Sonoma with a new Python 3.11 environment with Reflex installed run this:

```bash
mkdir test
cd test
reflex init
reflex run
```

**Expected behavior**
That `reflex run` does work.

**Specifics (please complete the following information):**
 - Python Version: 3.11 (3.10 also does not work)
 - Reflex Version: 0.2.8
 - OS: 14.0 (23A344) (macOS Sonoma)
 - Browser (Optional): Safari

**Comment by divin** [comment]
**Update**: The problem persists in Reflex 0.2.9

**Comment by masenf** [comment]
@divin is your project on an external volume? I'm able to reproduce this issue if my reflex project is on a separate disk image. Seems related to https://github.com/oven-sh/bun/issues/362

Will try to upgrade our bun version to see if the new release fixes this.

**Comment by divin** [comment]
Hi @masenf, thank you very much for having a look at this! You are correct, the project lies on a external drive. I didn’t expected that this is the issue! 🤯
