### ISSUE TITLE
pc run doesn't work - Got exception: can't create new thread at interpreter shutdown

### ISSUE THREAD

**Issue by MenachemBerkovich** [reflex-dev/reflex#1944]
I run the command 'pc run' but I got the error message: 'Node.js version 16.8.0 or higher is required to run Pynecone' even though node was successfully installed.
After researching this bug, I found that it was because:
```python
if not check_node_version():
```
in pynecone\utils\prerequisites.py.get_package_manager() -  line 79, returns False.
This occurs when this is called in pynecone\utils\exec.py.run_frontend - line 86:
```python
    run_process_and_launch_url(
        [prerequisites.get_package_manager(), "run", "dev"], loglevel
    )
```
And then:
```python
result = subprocess.run(
            ["node", "-v"], stdout=subprocess.PIPE, stderr=subprocess.PIPE
        )
```
which is inside check_node_version function (- called by get_package_manager) raises the exception of: can't create new thread at interpreter shutdown....
this happens immediately after:
```python
    console.rule("[bold green]App Running")
    os.environ["PORT"] = get_config().frontend_port if port is None else port
```
executed.

Is there a way to solve this problem? Or maybe it's related to the new version of python 12 and it's thread management?

 - Python Version: 3.12
 - Reflex Version: pynecone last
 - OS: windows 11
Thanks.

**Comment by ElijahAhianyo** [comment]
Hey @MenachemBerkovich, Pynecone is now shipped and maintained as reflex, I would advice you install reflex(`pip install reflex`). You can also check out the [docs](https://reflex.dev/docs/getting-started/installation/) for more.

**Comment by MenachemBerkovich** [comment]
@ElijahAhianyo I went back to Python 3.11 and now it's fine,
This may be related to the fact that in Python 3.12 GIL became optional for threads
