### ISSUE TITLE
I can't use a object in cell's table

### ISSUE THREAD

**Issue by oecarrillo** [reflex-dev/reflex#1948]
**Describe the bug**
When I use a datatable, I can ti use a rx object

**To Reproduce**
 - Code/Link to Repo:

**Expected behavior**
If I want to use a select in a cell, I receive an error

**Screenshots**

**Specifics (please complete the following information):**
 - Python Version: 3.1
 - Reflex Version: 0.2
 - OS: Linux
 - Browser (Optional): Firefox
 
**Additional context**

**Comment by Lendemor** [comment]
It is not supported.
We are working on implementing a better datatable, which (hopefully) should allow us for this kind of use case.

**Comment by picklelo** [comment]
You should use the core `rx.table` for any custom components needed in a table cell.
