### ISSUE TITLE
-bash: reflex: command not found 

### ISSUE THREAD

**Issue by RacoonIsBetter** [reflex-dev/reflex#1951]
I ran pip install reflex and then contined to follow the tutorial on the github it said run reflex init so i ran and it says that the command isn't found is the a fix or something I missed?

**Comment by masenf** [comment]
See if this discussion can help: https://github.com/orgs/reflex-dev/discussions/1804

If you're not using a virtualenv and the "user-local scripts" directory is not on your PATH, then running `reflex` cannot find where it is installed. `python3 -m reflex` is usually a quick workaround.

**Comment by RacoonIsBetter** [comment]
Thanks it worked.
