### ISSUE TITLE
rx.data_table offset glitch (visible empty df -> populated df) any time an element refreshes

### ISSUE THREAD

**Issue by mwcoleman** [reflex-dev/reflex#1957]
**Describe the bug**
When using rx.data_table and supplying a dataframe, the data is correctly displayed on the page. However, if any component updates, the data_table re-populates. This creates a glitching kind of effect where for a short time (say <.5s) there is an empty table present before it populates, offsetting all components below. Not sure how one might get around this?

**Specifics (please complete the following information):**
 - Python Version: 3.9
 - Reflex Version: 0.2.7
 - OS: Ubuntu 22.04
 - Browser (Optional): Firefox

**Comment by masenf** [comment]
You might try displaying a skeleton where the datatable would be while it's loading

```python
import time

import reflex as rx


class State(rx.State):
    data: list = []
    columns: list[str] = ["First Name", "Last Name"]

    def load_data(self):
        time.sleep(5)
        self.data = [
            ["Lionel", "Messi", "PSG"],
            ["Christiano", "Ronaldo", "Al-Nasir"],
        ]


def index():
    return rx.vstack(
        rx.skeleton_text(
            rx.data_table(
                data=State.data,
                columns=State.columns,
            ),
            is_loaded=State.is_hydrated,
            no_of_lines=10,
        ),
        rx.button("Other page content"),
    )


app = rx.App()
app.add_page(index, on_load=State.load_data)
app.compile()
```

**Comment by masenf** [comment]
i do also see what you're saying about other components refreshing and making the datatable refresh.

for that, we have a new datatable component in the works, which shouldn't have these kind of issues, hopefully in the next release.

otherwise, i think putting the datatable inside a `rx.box` with a specific height might be sufficient for avoid the glitching where page elements move around.

**Comment by mwcoleman** [comment]
That sounds like a good option, I'll give it a shot (bit new to UI side of things). Thanks
