### ISSUE TITLE
[REF-1821] Support for Direct Data Download in rx.download

### ISSUE THREAD

**Issue by ebonura-fastly** [reflex-dev/reflex#1965]
### Issue Description:
In the context of data science applications, it's essential to provide users with the ability to download data for further analysis and reporting. As we evaluate transitioning internal tools from Streamlit to Reflex, we've found that the rx.download function currently only supports downloading files through a URL. This is a limitation for use-cases where data is generated on-the-fly, like creating a .csv, .html or .pdf file for the user to download locally.

### Current Behavior:
```
rx.button("Download", on_click=rx.download(url="path/to/file"))
```

### Desired Behavior:
It would be invaluable if rx.download could also support a data parameter to enable the direct download of dynamically generated content.
```
my_csv = df.to_csv().encode('utf-8')
rx.button("Download", on_click=rx.download(data=my_csv, filename="output.csv"))
```
### Workaround:
The current workaround is to save the generated file to a cloud bucket and then use rx.download to fetch and deliver it to the user. This process introduces unnecessary complexity, particularly around authentication.

<sub>[REF-1821](https://linear.app/reflex-dev/issue/REF-1821/support-for-direct-data-download-in-rxdownload)</sub>

**Comment by berkorbay** [comment]
I have found a workaround with `call_script` but it somehow freezes all the other elements (e.g. select / dropdown menu) and triggers. 

In this example you should create a subfolder named `data` under `assets` folder. But you can rearrange the function in any way that you like. For the JS code see [here](https://stackoverflow.com/a/54091100/3608936).

```python
class XState(rx.State):
    selected: str = "the_file_name"

    async def download_data(self):
        ## Save dataframe to a temporary xlsx file and return the path to the file
        filename = self.selected.split(" ")[0].lower()
        url = f"/data/{filename}.xlsx"
        self.df.to_excel("assets/" + url, index=False)
        yield rx.call_script(f"window.location.assign('{url}')")
```

Btw, it is really a must. If you can quickly come up with something like Streamlit's [download button](https://docs.streamlit.io/library/api-reference/widgets/st.download_button) it will be appreciated.

**Comment by picklelo** [comment]
Thanks for raising this - we will prioritize this ticket in the upcoming releases.
