### ISSUE TITLE
An import is missing in tutorial

### ISSUE THREAD

**Issue by LuisRodrigoEspadaHIdalgo** [reflex-dev/reflex#1969]
**Describe the bug**
In the tutoriall chatbot, missing the "import reflex as rx", in the State file, in the reference code that can be seen on the web.(Thanks for the project, it's excellent)

**Screenshots**

![image](https://github.com/reflex-dev/reflex/assets/49884250/7fe87606-2bb3-4867-9ba6-b6c6336ffaa9)

![image](https://github.com/reflex-dev/reflex/assets/49884250/5d19cb24-a497-4bce-b930-61b2331fed0b)

**Specifics (please complete the following information):**
 - Python Version:
 - Reflex Version:
 - OS:Windows 
 - Browser (Optional):Edge

**Comment by HeetVekariya** [comment]
@masenf i can work on this issue, can you please assign it to me.

**Comment by masenf** [comment]
https://github.com/reflex-dev/reflex-web

**Comment by HeetVekariya** [comment]
@masenf Should i make PR on this repo or here https://github.com/reflex-dev/reflex-web ?

**Comment by HeetVekariya** [comment]
@masenf I have made the PR : https://github.com/reflex-dev/reflex-web/pull/269 in the reflex-web repo.

**Comment by masenf** [comment]
fixed by https://github.com/reflex-dev/reflex-web/pull/269

**Comment by masenf** [comment]
The change will be live next time we redeploy the website.

**Comment by HeetVekariya** [comment]
That was too fast :+1: 
Thank you @masenf
