### ISSUE TITLE
Audio "playing" flag is the wrong type.

### ISSUE THREAD

**Issue by romankouz** [reflex-dev/reflex#1983]
**Describe the bug**
Audio "playing" flag is the wrong type.

**To Reproduce**
```
from reflex import rx

def play_audio():
    audio.playing = True

button = rx.button('Play', onClick=play_audio)
audio = rx.audio(
    url="https://www.learningcontainer.com/wp-content/uploads/2020/02/Kalimba.mp3",
    playing=False,
)

rx.render(button, audio)
```

**Expected behavior**
I expected to be able to switch the flag from False to True and instead got: "TypeError: Invalid var passed for prop playing, expected type <class 'str'>, got value False of type <class 'bool'>."

**Screenshots**
![image](https://github.com/reflex-dev/reflex/assets/58533981/18a73f12-c37f-4269-a865-db393e097b6e)

**Specifics (please complete the following information):**
 - Python Version: 3.11.5
 - Reflex Version: 0.2.8
 - OS: Windows 11
 - Browser (Optional):
 
**Additional context**

**Comment by Lendemor** [comment]
You have to use State if you want to control the displayed component.

```python
class State(rx.State):
    playing: bool = False
    
    def play_audio(self):
        self.playing = True

@page(route="/")
def index():
    return rx.fragment(
        rx.audio(
            url="https://...",
            playing=State.playing
        ),
        rx.button("Play", on_click=State.play_audio)
    )
```

**Comment by romankouz** [comment]
Thanks for the detailed reply! This addresses the bug I was getting, but I still think the docs should be clear that this is a bool and not a string, right?

**Comment by masenf** [comment]
Yeah the type needs to be fixed on that prop:

https://github.com/reflex-dev/reflex/blob/864a66b20d9c26bbb4fbf674171857e288ab455a/reflex/components/libs/react_player.py#L23-L24

Good first issue, if you wanted to contribute a PR.

**Comment by romankouz** [comment]
My apologies, I missed this comment. Thanks for such a quick fix. Will contribute a PR next time if I find something ;)
