### ISSUE TITLE
Spinner prop type misspecified for IconButton

### ISSUE THREAD

**Issue by romankouz** [reflex-dev/reflex#1989]
**Describe the bug**
IconButtons cannot have custom spinners because the spinner prop type appears to be mis specified.

**To Reproduce**
```
@page(route="/")
def index():
    return rx.center(
    rx.IconButton(
        'Loading...',
        loading=True,
        spinner=rx.spinner(
            color="lightgreen",
            thickness=5,
            speed="1.5s",
            size="xl",
        )
    )
)
```

**Expected behavior**
I expected for the button spinner to change in design when inserting a custom spinner.

**Screenshots**
![image](https://github.com/reflex-dev/reflex/assets/58533981/a0de5391-6c64-4c61-b782-16c5fcfcf95e)
Notice how the spinner is mandated to be a string when it should be a spinner component (at least based on bot message reply).
![image](https://github.com/reflex-dev/reflex/assets/58533981/ba915238-d310-4650-842c-21fcadd266ea)

**Specifics (please complete the following information):**
 - Python Version: 3.11.5
 - Reflex Version: 0.2.8
 - OS: Windows 11
 - Browser (Optional):

**Additional context**
Attempting to pass a spinner yields the following error:

![image](https://github.com/reflex-dev/reflex/assets/58533981/d8c0aa53-9846-4c49-9b9c-e28e2fe93477)

**Comment by Lendemor** [comment]
Component as props are not supported yet, so the bot suggestion is wrong.
The docs will always prevail over the bot, he can help, but should not be considered as the "reference".

**Comment by romankouz** [comment]
Thanks for the response! However, that still leaves me with the question of what can go into "spinner" argument? The docs unfortunately do not tell me what kind of string the prop needs.

**Comment by Lendemor** [comment]
I don't think `spinner` can be used at the moment, until we support component as props.

**Comment by picklelo** [comment]
The new core components have a `loading` prop that shows a spinner. Closing this issue as we won't be able to support the original.
