### ISSUE TITLE
mac server bug

### ISSUE THREAD

**Issue by ltm920716** [reflex-dev/reflex#2007]
**Describe the bug**
App running at: http://localhost:3000
Starting frontend failed with exit code 1

> dev
> next dev

- ready started server on 0.0.0.0:3000, url: http://localhost:3000
- [36minfo[39m Using wasm build of next-swc
- [33mwarn[39m Attempted to load @next/swc-darwin-x64, but it was not installed
assertion failed : BasicBlock requested for unrecognized address
(BuilderBase.h:550 block_for_offset)
 Run with --loglevel debug  for the full log.

**To Reproduce**
 - Code/Link to Repo:
 ```reflex run```

**Expected behavior**
server normal

**Screenshots**
![image](https://github.com/reflex-dev/reflex/assets/12007227/d43853c8-b11d-4fa8-b2ed-2ecc0eb220dd)

**Comment by ElijahAhianyo** [comment]
can you show logs for when you run in debug mode(`reflex run --loglevel debug`)? Aside that, are you running an M1/M2? If yes, have you tried running this command `/usr/sbin/softwareupdate --install-rosetta --agree-to-license` from the docs?

**Comment by ltm920716** [comment]
hello，
the log by `--loglevel debug` is the same
I am running on M1. 
I updated reflex from 0.2.8 to 0.2.9 today and have not found above errors so far. 

If the same error occurs again, I will report here again，thanks！

**Comment by ElijahAhianyo** [comment]
sure, closing this now, feel free to reopen or open another issue if you face any more issues
