### ISSUE TITLE
user does not stay login

### ISSUE THREAD

**Issue by shabane** [reflex-dev/reflex#2008]
**Describe the bug**

hello. i was writing my web app with reflex, i made login from, user can login and singup with no problem. but there is a problem that the user does not stay login. if user open the site in new tab, it is not login.
i was thought i write the code with problem, so i run the twitter clone of your example. the problem was the same for that too.

**Expected behavior**
User should be login at each time it open the site.

**Specifics (please complete the following information):**
 - Python Version: Python 3.11.3
 - Reflex Version: 0.2.7
 - OS: Manjaro Linux x86_64
 - Browser (Optional): Microsoft Edge Version 116.0.1938.76 (Official build) (64-bit)

**Comment by Lendemor** [comment]
State is tied to a tab.

If you want to share information between tabs (such as user being logged in, a shopping cart, etc...) you have to define a var stored in local storage :
```
rx.Cookie
```
or
```
rx.LocalStorage
```

Doing so will let the state of the new tab access the local storage data when it is opened, and then your user will stay logged in.

**Comment by shabane** [comment]
thank you very much, i will test this.

**Comment by shabane** [comment]
i tested it. the problem now is that the cookie do not set.
the document use the cookie like this:
```python
on_change=ClientStorageState.set_my_cookie,
```
this was work fine for me on the test. 

but i code it like this:
```python
# base.py
class State(rx.State):
    user: rx.Cookie = ''"


# auth.py
class SinginState(State):
     def handel_singin(self):
        State.user = self.username
```

**Comment by shabane** [comment]
@Lendemor 

sorry to bother you, this is a real problem for me now im working on a project that this part is missing now, and the problem did not resolve for days.

the cookie does not set, any idea why?

**Comment by kumaraguru1735** [comment]
@Lendemor
Hi I have the same issue, so I cannot able to develope my entire management system, 
Plz give example in github for cookie storage using rx.Cookie or rx.LocalStorage
So it is very much useful to new bees

**Comment by masenf** [comment]
replace `State.user = self.username` with `self.user = self.username`.

If you set an attribute on the `State` class, it won't set the cookie for an individual user, which needs to be on an instance of the `State` (`self`)
