### ISSUE TITLE
using domain name in api_url

### ISSUE THREAD

**Issue by danisvaliev001** [reflex-dev/reflex#2024]
**Describe the bug**
unable to use domain name in api_url value

**To Reproduce**
put
```
api_url="http://your-domain.com:8000"
```
run separately:
```
reflex run --env prod --frontend-only
reflex run --env prod --backend-only
```

**Expected behavior**
the backend is accessible for frontend

**Screenshots**
<img width="1440" alt="screen 2023-10-24 at 15 11 36" src="https://github.com/reflex-dev/reflex/assets/62111184/b8fb93b9-5712-450a-ae33-407cc0e5c1bf">

**Specifics (please complete the following information):**
 - Python Version: 3.11.4
 - Reflex Version: 0.2.9
 - OS: tried to run frontend on macOS and Fedora Linux
 - Browser (Optional): Chrome, Edge, Safari, DuckDuckGo
 
**Additional context**
works well with ip that linked to my domain name. Pinging my domain return this ip.

**Comment by Lendemor** [comment]
Are you using a reverse proxy or directly accessing the server?
Does your firewall allow traffic on port 8000?
What error in devtools console do you have?

**Comment by danisvaliev001** [comment]
> Are you using a reverse proxy or directly accessing the server? Does your firewall allow traffic on port 8000? What error in devtools console do you have?

I use directly, don't use reverse-proxy.

firewall allow traffic on port 8000, because I have got 404 when try to acces to backend via domain name in browser. Also tried another non-privileged port, 9000.

error in screenshot (have tried to run on 4000 port, same on default 3000):
<img width="1440" alt="screen 2023-10-24 at 16 22 07" src="https://github.com/reflex-dev/reflex/assets/62111184/d69e0b57-aa6e-4834-a378-9dda140dca96">

**Comment by danisvaliev001** [comment]
Addition:
I have runned frontend with `--frontend only` parameter. And backend with `--backend-only`.

**Comment by Lendemor** [comment]
The screenshot you attached show you are using port 9000 for backend, but you are mentioning port 8000?
Is it a typo ?

**Comment by danisvaliev001** [comment]
I configured reverse-proxy already and now it works fine.

Thank you!

**Comment by danisvaliev001** [comment]
I configured reverse-proxy with TLS termination already and now it works fine.

Thank you!
