### ISSUE TITLE
[REF-1066] How can I upload an entire directory?

### ISSUE THREAD

**Issue by 1qh** [reflex-dev/reflex#2079]
I really want to be able to upload a folder that contains multiple files and subfolders. How can I achieve that?

Thanks a lot!

<sub>[REF-1066](https://linear.app/reflex-dev/issue/REF-1066/how-can-i-upload-an-entire-directory)</sub>

**Comment by masenf** [comment]
This actually is possible today, if you drop a directory onto the upload dropzone, then it will add all the files... however Reflex currently does not save the files paths, only the name, so the hierarchy information is lost.

I'm currently working on the upload code, and have changed all of the `f.name` references to `f.path || f.name`, so hopefully this should "just work" in the next release.

That said, I couldn't find out a way to support selecting a directory in the OS-specific select a file dialog. It seems to only work with drag/drop.

**Comment by 1qh** [comment]
Yes, I really want to implement a simple logic: select a folder, then save it to server's hard disk (like upload a folder to google drive). I really hope it would be possible in the next release.

Thank you for your response!
