### ISSUE TITLE
[REF-2928] Support to change chart color

### ISSUE THREAD

**Issue by alisaycl96** [reflex-dev/reflex#2080]
**Describe the bug**
After switch to use new graphing library 'Recharts', found that Pie chart does not support `color_scale` parameters anymore.
Currently, the `fill` parameter only support to change the whole graph but not color by key value of data.

**Expected behavior**
Would like to change the chart color for different keys in data. Take below image for example,
<img width="206" alt="截圖 2023-10-30 下午3 47 23" src="https://github.com/reflex-dev/reflex/assets/54022557/bd52bd66-19d5-485f-b4e4-64a7b6cd7c0c">

**Specifics (please complete the following information):**
 - Python Version: 3.9.9
 - Reflex Version: 0.2.9
 - OS: MacOS
 - Browser (Optional): chrome

<sub>[REF-2928](https://linear.app/reflex-dev/issue/REF-2928/support-to-change-chart-color)</sub>

**Comment by Lendemor** [comment]
Feels like a convenient feature to have :+1:

**Comment by StephanHeijl** [comment]
I would like to add my support for this request. The Pie chart that is provided by ReCharts appears to be a downgrade in terms of functionality when compared to pre 0.3.0.

**Comment by serasinfin** [comment]
Hello, I had the same case.
In this project I saw that the color could be modified for each value, like the following:

`data01 = [
 {"name": "Sent", "value": 400, "fill": "rgba(2, 220, 130, 1.0)"},
 {"name": "Failed", "value": 100, "fill": "rgba(241, 50, 66, 1.0)"},
]`
![Captura de pantalla 2024-08-20 a la(s) 1 24 01 p m](https://github.com/user-attachments/assets/4c728231-fa35-4000-a6a4-367120a974dc)
🔗 https://dashboard-new.reflex.run/
 🔗 https://github.com/reflex-dev/templates/blob/main/dashboard/dashboard/views/charts.py

**Comment by Lendemor** [comment]
Added this PR improving the docs for PieChart : https://github.com/reflex-dev/reflex-web/pull/947
