### ISSUE TITLE
web issue

### ISSUE THREAD

**Issue by sergioarze** [reflex-dev/reflex#2093]
**Describe the bug**
a 404 error when you click on "gallery" in the footer section 

**To Reproduce**
 - Code/Link to Repo:
 - When you click on " gallery" in the footer of the web page.

**Screenshots**
![imagen](https://github.com/reflex-dev/reflex/assets/114198072/5e69067f-8e5c-41e0-85e6-b3e9ff9e4f6a)

**Comment by kisharnath** [comment]
Can I work on this issue?

**Comment by picklelo** [comment]
@kisharnath just assigned you to it!

**Comment by picklelo** [comment]
This is working now.
