### ISSUE TITLE
[REF-1072] Add more layout examples to the docs

### ISSUE THREAD

**Issue by masenf** [reflex-dev/reflex#2101]
The docs should have more examples on how to layout the root of the page for those less familiar with css/flexbox or who just want to get started more quickly by picking a layout visually and getting the code for it.

Based on #2100 

<sub>[REF-1072](https://linear.app/reflex-dev/issue/REF-1072/add-more-layout-examples-to-the-docs)</sub>

**Comment by include** [comment]
In fact this is what is pushing me back - lack of time/motivation to "design" initial layout. people like us would benefit a lot with this presets.

**Comment by picklelo** [comment]
We now have a [layout overview](https://reflex.dev/docs/styling/layout/) and are working on [recipes](https://reflex.dev/docs/recipes-overview/) to make the UI/layout aspects easier.
