### ISSUE TITLE
The location of the edit window in DataEditor is strange.

### ISSUE THREAD

**Issue by Evenzel** [reflex-dev/reflex#2107]
**Describe the bug**
When I try to edit data in the DataEditor on the doc page, the edit window appears in the wrong location.

**Screenshots**
![image](https://github.com/reflex-dev/reflex/assets/144013972/02551650-bc03-4ea2-9392-887db0f0ce17)

**Specifics (please complete the following information):**
 - Python Version: 3.11.4
 - Reflex Version: 0.3.1
 - OS: Windows 11
 - Browser (Optional): Chrome

**Comment by Lendemor** [comment]
Fixed in #2094
