### ISSUE TITLE
[REF-1104] MutableProxy not transparent

### ISSUE THREAD

**Issue by jq6l43d1** [reflex-dev/reflex#2123]
MutableProxy is intended to be transparent but it isn't.

Reflex version: 0.3.1

Here is a code example that demonstrates the bug:

```
import reflex as rx
from typing import List
from pprint import pprint
import json

class State(rx.State):

    a_list: List[str] = ["a", "b", "c"]

    def my_function(self):
        
        # This doesn't work.
        # It will print something like:
        # <MutableProxy at 0x7f7d38217180 for list at 0x7f7d3950af80>
        pprint(self.a_list)

        # This will print: <class 'reflex.state.MutableProxy'>
        print(type(self.a_list))
        
        # This works
        pprint(list(self.a_list))

        # This works too
        print(json.dumps(self.a_list, indent=4))

def index() -> rx.Component:
    return rx.Fragment()

app = rx.App()
app.add_page(index, on_load=State.my_function)
app.compile()
```

Here is another example that will trigger this bug. If you declare a conversation for OpenAI as a state variable like so:

![](https://uploads.linear.app/9513bc1c-787d-499b-8c86-46952ab7013c/a277c252-70a5-4425-9620-9db097cf810e/87f4632a-f7ca-46b4-9a04-c1205af084ed?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzk1MTNiYzFjLTc4N2QtNDk5Yi04Yzg2LTQ2OTUyYWI3MDEzYy9hMjc3YzI1Mi03MGE1LTQ0MjUtOTYyMC05ZGIwOTdjZjgxMGUvODdmNDYzMmEtZjdjYS00NmI0LTlhMDQtYzEyMDVhZjA4NGVkIiwiaWF0IjoxNjk4OTg1Mjk2LCJleHAiOjE2OTkwNzE2OTZ9.S8z8BwFvHTu_X6pCNZKr3RSTsmJcelgs6e4BHfQ2krc)

When the code runs you will get an error:

![](https://uploads.linear.app/9513bc1c-787d-499b-8c86-46952ab7013c/429df0da-4b2c-4b85-8ee6-c81c93fe824c/3f8315a8-d56d-4ff3-9fac-44f1b20689f1?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzk1MTNiYzFjLTc4N2QtNDk5Yi04Yzg2LTQ2OTUyYWI3MDEzYy80MjlkZjBkYS00YjJjLTRiODUtOGVlNi1jODFjOTNmZTgyNGMvM2Y4MzE1YTgtZDU2ZC00ZmYzLTlmYWMtNDRmMWIyMDY4OWYxIiwiaWF0IjoxNjk4OTg1Mjk2LCJleHAiOjE2OTkwNzE2OTZ9.HVeTNMjD-BqsWA_o8Rem8Jt903Cq0DEnEyJCXCOAZdk)

<sub>From [SyncLinear.com](https://synclinear.com) | [REF-1104](https://linear.app/reflex-dev/issue/REF-1104/mutableproxy-not-transparent)</sub>

**Comment by masenf** [comment]
As a workaround, event handlers may use the `self.get_value(field_name)` method on `rx.State` to get the non-reactive original value of the field instead of a MutableProxy. The non-reactive value is intended for read-only / serialization use cases, and changes to the original value will not trigger delta updates to the client.
