### ISSUE TITLE
Not Closing Dev Mode Properly Windows

### ISSUE THREAD

**Issue by Alek99** [reflex-dev/reflex#2145]
As seen on discord:
![image](https://github.com/reflex-dev/reflex/assets/38776361/36c55019-ae5b-42d7-8640-fae14c17bad5)

```
i had one reflex app running on ports 3001/8001 and another on 3000/8000, I think the logs were showing up on the other terminal.
when i closed both and restarted only one it seemed to work 
```

Seems like there may be a situation on windows where the local host 3000 is not closing properly.

**Comment by picklelo** [comment]
This should be resolved now.
