### ISSUE TITLE
[REF-1626] Allow string fomatting in rx.html component

### ISSUE THREAD

**Issue by abdullahkhalids** [reflex-dev/reflex#2155]
**Describe the bug**
Currently, the `rx.html` component `src` is not formatted.

**To Reproduce**
Compile this app

```
from rxconfig import config
import reflex as rx

class State(rx.State):
    """The app state."""

    myvar: str = "Blue"


def index() -> rx.Component:
    return rx.fragment(
	rx.heading(
            f"The number is {State.myvar}"
            ), #works as expected
        rx.html(
            f"The number is {State.myvar}"
            ), #doesn't work
    )

app = rx.App()
app.add_page(index)
app.compile()
```

**Expected behavior**
The html format string should be processed correctly.

**Screenshots**

![image](https://uploads.linear.app/9513bc1c-787d-499b-8c86-46952ab7013c/7a9a2074-267c-4f20-9ce8-af35104e748c/9ee098b5-6402-4206-aab7-15c99364d1b1?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzk1MTNiYzFjLTc4N2QtNDk5Yi04Yzg2LTQ2OTUyYWI3MDEzYy83YTlhMjA3NC0yNjdjLTRmMjAtOWNlOC1hZjM1MTA0ZTc0OGMvOWVlMDk4YjUtNjQwMi00MjA2LWFhYjctMTVjOTkzNjRkMWIxIiwiaWF0IjoxNzA0NzI4NjMzLCJleHAiOjE3MDQ4MTUwMzN9.9DUU0skoP2cG6xWUJliLpIacseMRCOxpEBhmz8VVcaE)

**Specifics (please complete the following information):**

* Python Version: 3.10.12
* Reflex Version: 0.3.2
* OS: Debian testing
* Browser (Optional):

<sub>From [SyncLinear.com](https://synclinear.com) | [REF-1626](https://linear.app/reflex-dev/issue/REF-1626/allow-string-fomatting-in-rxhtml-component)</sub>

**Comment by masenf** [comment]
potentially fixed by #2149

**Comment by ipcloudlive** [comment]
I am using multiline text like this
```
return rx.html(
"""
<h1> Hello {State.text1}</h1>
<h1> Bye {State.text2}</h1>
""")
```

**Comment by masenf** [comment]
Thanks for the update, will investigate.

**Comment by adhami3310** [comment]
This is fixed with the new immutable var system.
