### ISSUE TITLE
How to get the mouse position?

### ISSUE THREAD

**Issue by chuong98** [reflex-dev/reflex#2180]
I am working on a project, that let a user upload an image, and then click on the image to draw several polygons for ROI:
- Whenever the user left-click, I will store the mouse coordinate,
- and when user enter or right-click, I will close the polygon.
Can you provide a minimal example for this problem. Thank you.

**Comment by masenf** [comment]
Does this discussion help at all? https://github.com/orgs/reflex-dev/discussions/1996

**Comment by chuong98** [comment]
thank you, I follow your links and it is almost works. 
My remaining problem is how to get the top-left and bottom-right corner of an image, so that I can subtract and scale it?
Here is my current code:

`class DOMClickEvent(rx.Base):
    clientX: int
    clientY: int


def click_coordinate_signature(e: DOMClickEvent):
    return [e.clientX, e.clientY]


class CoordinateImage(rx.Image):
    def get_event_triggers(self) -> dict[str, Any]:
        return {
            **super().get_event_triggers(),
            rx.constants.EventTriggers.ON_CLICK: click_coordinate_signature
        }

@template(route="/test", title="Test", image="/car_icon.png")
def test():
    """The main view."""
    return rx.vstack(

        rx.heading(State.coordinates.to_string()),
        CoordinateImage.create(
            src="/25671809.jpg", 
            on_click=State.update_coordinates,
        )
    )
`

**Comment by masenf** [comment]
@chuong98 maybe you want to grab `offsetX` and `offsetY` instead of the `client*` variants: https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/offsetX

There are several coordinates available from MouseEvent that might be more appropriate for your use: https://developer.mozilla.org/en-US/docs/Web/API/Element/click_event

**Comment by chuong98** [comment]
Thanks, I tried replacing `clientX` with `offsetX` but I get null result.

**Comment by chuong98** [comment]
@masenf can you give me the hint how to appropriately get the `offsetX` or get the `even.currentTarget.getBoundingClientRect()`

**Comment by maintain0404** [comment]
@chuong98 
I found how to get `offsetX`. Use `nativeEvent`.

```python
class NativeEvent(rx.Base):
    offsetX: int
    offsetY: int


class DOMClickEvent(rx.Base):
    nativeEvent: NativeEvent


def click_coordinate_signature(e: DOMClickEvent):
    return [e.nativeEvent.clientX, e.nativeEvent.clientY]


class CoordinateImage(rx.Image):
    def get_event_triggers(self) -> dict[str, Any]:
        return {
            **super().get_event_triggers(),
            rx.constants.EventTriggers.ON_CLICK: click_coordinate_signature
        }

@template(route="/test", title="Test", image="/car_icon.png")
def test():
    """The main view."""
    return rx.vstack(

        rx.heading(State.coordinates.to_string()),
        CoordinateImage.create(
            src="/25671809.jpg", 
            on_click=State.update_coordinates,
        )
    )
```

**Comment by pgclarke** [comment]
This solution isn't working for me (Reflex 0.4.9) because I get an error when trying to subclass an rx component such as rx.image. Any update or other solution available to get the offset from, and extent of, an image when clicked?

**Comment by masenf** [comment]
@pgclarke we moved some of the imports around since this code snippet was published.

You should be able to get the class for any of the lowercase create methods via the `.__self__` attribute, like

```python
class CoordinateImage(rx.image.__self__)
    ...
```

Alternatively, you can do a deep import

```python
from reflex.components.el.elements.media import Img

class CoordinateImage(Img):
    ...
```

**Comment by pgclarke** [comment]
@masenf Thank you, the `rx.image.__self__` solution works for me!

As a bonus, I found I can also get the modifier key (e.g. shift key) status by adding `shiftKey` after `offsetY` in the class definition of `NativeEvent` and the function definition of `click_coordinate_signature`.

One more related point, can I get the size of the image through the event handler? That will enable me to calculate the position relative to the image. I think @chuong98, the OP, also asked the same question.

**Comment by pgclarke** [comment]
@masenf  That works nicely for me! Thank you so much!
