### ISSUE TITLE
Typing rapidly in documentation example results in corrupted data

### ISSUE THREAD

**Issue by kkinder** [reflex-dev/reflex#2197]
**Describe the bug**
When you type rapidly in the [state example](https://reflex.dev/docs/tutorial/adding-state/), certain keystrokes are "lost" as you type, presumably because a race condition occurs when multiple state inputs are sent to the server in rapid successiong.

**To Reproduce**
To reproduce, simply visit the [state docs](https://reflex.dev/docs/tutorial/adding-state/) and type rapidly into a bound input field. Here's a screencast:

https://github.com/reflex-dev/reflex/assets/1115018/136118ad-5d78-4736-a8ee-22e79b74e153

**Expected behavior**
There should be some kind of debouncing technique, or perhaps a nonce sent with each state update that is used to determine which one is most recent. Either way, the example docs should produce something that's usable.

**Specifics (please complete the following information):**
 - Python Version: 3.9.6
 - Reflex Version: 0.3.4
 - OS: macOS 14.1.1
 - Browser (Optional): Either Safari 17.1 or Chrome
 
**Additional context**

I think this should be easy to reproduce if you add some random network latency to your browser settings.

**Comment by Lendemor** [comment]
Input have been debounced for a while now, closing this.
