### ISSUE TITLE
[Feature Request] More sound playing options

### ISSUE THREAD

**Issue by lemuriandezapada** [reflex-dev/reflex#2207]
Currently sounds can only be played through the included player in rx.audio
However this requires that either the sounds be located locally on the app machine (which is fine if you have a small number of mp3's you might be working with) or linked via some http url from elsewhere (which is not entirely super secure)

In case you have your sounds stored in some database somewhere and send it over via some urllib request there is currently no way to directly handle it. (write it to disk first and play it from there? Feels redundant). 

Also the available props don't have access to more fine grained control of the sound. Such as setting the cursor back to the beginning or somewhere in the middle. You have to engage in dirty tricks with the playing and loop props. Assuming you're not using exclusively the visual part of the audio component.

**Comment by masenf** [comment]
Can you use a data uri? How big of audio files are you dealing with?

There is also an example on this page https://reflex.dev/docs/api-reference/browser_javascript/ for playing an audio file using the JavaScript APIs directly via rx.call_script

**Comment by lemuriandezapada** [comment]
They're small. A few seconds each. 
But I have tens of thousands. Easily several GB. And my usecase would prefer they start playing as quickly as possible once a button is pressed.
I was hoping I could avoid learning javascript but thanks. I'll check out that example too

**Comment by masenf** [comment]
If you have audio data stored in your database or something, you can set the audio URL to a base64 data uri it will play it. To restart from the beginning, clear the URL and reset it again.

Here is some sample code (I'm loading from disk here, but the `owl_sound_effect` could just be bytes from anywhere).

```python
import base64
from pathlib import Path

import reflex as rx


owl_sound_effect = Path("assets/owl.mp3").read_bytes()


def convert_to_data_url(data, mime_type: str = "audio/mpeg"):
    base64_data = base64.b64encode(data).decode("utf-8")
    return f"data:{mime_type};base64,{base64_data}"


class State(rx.State):
    audio_clip: str = ""
    playing: bool = False

    def play_clip(self):
        self.audio_clip = ""
        yield
        self.audio_clip = convert_to_data_url(owl_sound_effect)
        self.playing = True



def index() -> rx.Component:
    return rx.fragment(
        rx.color_mode_button(rx.color_mode_icon(), float="right"),
        rx.vstack(
            rx.heading("Sound effect!"),
            rx.button("Play", on_click=State.play_clip),
            rx.audio(url=State.audio_clip, playing=State.playing, width="100%"),
        ),
    )


app = rx.App()
app.add_page(index)
app.compile()
```

**Comment by lemuriandezapada** [comment]
Oh you can play base64 directly. That definitely looks like a useful workaround. 
I'll give it a try tomorrow

**Comment by masenf** [comment]
Does not seem to be any actionable work remaining so considering this as fixed. Please reopen with specific requests if any remain.
