### ISSUE TITLE
[REF-1285] Markdown - CodeBlock

### ISSUE THREAD

**Issue by Sarctiann** [reflex-dev/reflex#2217]
The codeblock component is not changing the theme ("light", "dark") based on the color_mode

[This is my project](https://github.com/Sarctiann/python_reflex/tree/main/python_reflex)

**To Reproduce**

1. Use a markdown component
2. pass a code block like:

   ```
   {
       "message": "hello world"
   }
   ```
3. change the color mode to dark
4. **the code block is still light**

**Expected behavior**
Ideally, the codeblock component should change themes on its own.

However, if we tried to conditionally pass the theme by assigning it to `component_map` *(the rx.markdown prop)*
like this:

![image](https://uploads.linear.app/9513bc1c-787d-499b-8c86-46952ab7013c/bbd12646-f56f-4171-97f1-7aee1d83dae9/d68c88c0-d49f-4a4a-9fe5-2c3e99f14961?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzk1MTNiYzFjLTc4N2QtNDk5Yi04Yzg2LTQ2OTUyYWI3MDEzYy9iYmQxMjY0Ni1mNTZmLTQxNzEtOTdmMS03YWVlMWQ4M2RhZTkvZDY4Yzg4YzAtZDQ5Zi00YTRhLTlmZTUtMmMzZTk5ZjE0OTYxIiwiaWF0IjoxNzAxMTExMTk4LCJleHAiOjE3MDExOTc1OTh9.8vbmrW8TLun5C-Qzf4eHdqJrc1J2x70Pii_ghR8uAbc)

this is what happen:

![image](https://uploads.linear.app/9513bc1c-787d-499b-8c86-46952ab7013c/4ed5559e-d8fb-443f-8c2b-3d310bb84ea1/3bc09886-0b2e-46b8-b46b-b74755cff20f?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzk1MTNiYzFjLTc4N2QtNDk5Yi04Yzg2LTQ2OTUyYWI3MDEzYy80ZWQ1NTU5ZS1kOGZiLTQ0M2YtOGMyYi0zZDMxMGJiODRlYTEvM2JjMDk4ODYtMGIyZS00NmI4LWI0NmItYjc0NzU1Y2ZmMjBmIiwiaWF0IjoxNzAxMTExMTk4LCJleHAiOjE3MDExOTc1OTh9.1MnUC0rKsS9NEs0ADNYGi6TlwDnCEH5a7dm7tte3SQA)

**Expected Code Generation:**

![image](https://uploads.linear.app/9513bc1c-787d-499b-8c86-46952ab7013c/d9a7f0fb-5dd1-4593-9e12-830507f637ed/a0d9396d-2076-4ba8-a34e-32fd2a31f29b?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzk1MTNiYzFjLTc4N2QtNDk5Yi04Yzg2LTQ2OTUyYWI3MDEzYy9kOWE3ZjBmYi01ZGQxLTQ1OTMtOWUxMi04MzA1MDdmNjM3ZWQvYTBkOTM5NmQtMjA3Ni00YmE4LWEzNGUtMzJmZDJhMzFmMjliIiwiaWF0IjoxNzAxMTExMTk4LCJleHAiOjE3MDExOTc1OTh9.iQH5bIjOfQ7LSiI_VaR6QQ4YTeYOj74eTB1lR3dn9jI)

![image](https://uploads.linear.app/9513bc1c-787d-499b-8c86-46952ab7013c/700bf462-eeb6-4200-84b9-18b6024767a5/bf4a08d2-ec5a-41a5-8de9-6e04feaa91a0?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzk1MTNiYzFjLTc4N2QtNDk5Yi04Yzg2LTQ2OTUyYWI3MDEzYy83MDBiZjQ2Mi1lZWI2LTQyMDAtODRiOS0xOGI2MDI0NzY3YTUvYmY0YTA4ZDItZWM1YS00MWE1LThkZTktNmUwNGZlYWE5MWEwIiwiaWF0IjoxNzAxMTExMTk4LCJleHAiOjE3MDExOTc1OTh9.\_4-SrHDFFc-Xa3D_AbAgb8exgTNcbx58zg5y83RBr0k)

**System Info:**

|  |  |
| -- | -- |
| Python Version: | 3.11.6 |
| Reflex Version: | 0.3.2 |
| OS: | MacOS Sonoma 14.1.1 |

<sub>From [SyncLinear.com](https://synclinear.com) | [REF-1285](https://linear.app/reflex-dev/issue/REF-1285/markdown-codeblock)</sub>

**Comment by Lendemor** [comment]
Hello,
thanks for the bug report.

Could you check if it also happens with the latest version `0.3.4` ?

**Comment by Sarctiann** [comment]
You are welcome. In deed, the bug persists on `0.3.4`
