### ISSUE TITLE
AdminDash : Not being served - 404 /admin when setting up AdminDash

### ISSUE THREAD

**Issue by albertsola** [reflex-dev/reflex#2220]
**Describe the bug**
Get 404 on /admin when attempting to use AdminDash / starlette-admin

**To Reproduce**

$ reflex init
$ relfex db init
$ reflex run

When I visit http://localhost:3000/ I get the index Hello world (Expected)
When I visit http://localhost:3000/admin I get 404 Not found

Code:

```
#rxconfig.py
import reflex as rx

config = rx.Config(
    app_name="reflex_admin",
    db_url="sqlite:///reflex_admin.db",
    enable_admin=True,
)
```

```
# reflex_admin/reflex_admin.py
import reflex as rx


def index() -> rx.Component:
    return rx.text("Hello, world!")


class User(rx.Model, table=True):
    username: str
    password: str


app = rx.App(admin_dash=rx.AdminDash(models=[User]))
app.add_page(index)
app.compile()
```

**Expected behavior**

I expect starlette-admin to be available in the endpoint http://localhost:3000/admin/

**Screenshots**

![image](https://github.com/reflex-dev/reflex/assets/667186/eac7a3d0-74b5-4b55-a8f1-2f51d5f8ac54)

![image](https://github.com/reflex-dev/reflex/assets/667186/0909f0dc-ac00-4bda-941c-041163d2cfb1)

**Specifics (please complete the following information):**
 - Python Version: Python 3.11.6
 - Reflex Version:  reflex==0.3.4
 - OS: Ubuntu 23.10 (mantic)
 - Browser (Optional): Chrome Version 119.0.6045.159 (Official Build) (64-bit)
 
**Additional context**

Not applicable.

**Comment by masenf** [comment]
AdminDash is served from the backend, port 8000 by default. See output on console.
