### ISSUE TITLE
wrapping react component error -- Global CSS cannot be imported from within node_modules

### ISSUE THREAD

**Issue by benwilks** [reflex-dev/reflex#2222]
Trying to wrap the react-virtualized component and getting this error. Any ideas on how to address this?

> ./node_modules/react-virtualized/styles.css
Global CSS cannot be imported from within node_modules.
Read more: https://nextjs.org/docs/messages/css-npm

**Comment by thrix** [comment]
@benwilks howdy, did you resolve this problem somehow?
