### ISSUE TITLE
Border radius does not affect Video component

### ISSUE THREAD

**Issue by dodeca-6-tope** [reflex-dev/reflex#2229]
**Describe the bug**
`border_radius` does not affect Video component

**To Reproduce**
 - Code/Link to Repo:

**Expected behavior**

**Screenshots**

**Specifics (please complete the following information):**
 - Python Version:
 - Reflex Version:
 - OS: 
 - Browser (Optional):
 
**Additional context**

**Comment by masenf** [comment]
Add `overflow="hidden"` to the `rx.video` component.

```
import reflex as rx


def index() -> rx.Component:
    return rx.hstack(
        rx.video(url="https://www.youtube.com/watch?v=eXtaM4QM4hk", border_radius="10px"),
        rx.video(url="https://www.youtube.com/watch?v=eXtaM4QM4hk", border_radius="10px", overflow="hidden"),
        padding="20px",
    )


app = rx.App()
app.add_page(index)
app.compile()
```

![image](https://github.com/reflex-dev/reflex/assets/1524005/4d0fd071-f9c1-4b00-b80c-1546d0263add)

**Comment by dodeca-6-tope** [comment]
Great, thanks!
