### ISSUE TITLE
_hover style not detected in reflex 0.3.4

### ISSUE THREAD

**Issue by lokune** [reflex-dev/reflex#2233]
**Describe the bug**
_hover styling somehow broken in reflex 0.3.4. I upgraded my project  (from 0.3.2) and _hover style is not detected. 
Example I have _hover={"bg": accent_dark} but that's not working after upgrading.

**To Reproduce**

Add the following style to a button. The background color is supposed to change to the specified background color on hover but that's not the behavior.

 `main_button_style = dict(
    bg="#5535d4",
    color="#fff",
    px="4",
    py="2",
    h="auto",
    w="100%",
    _hover={"bg": "#4c2db3"},
)`

**Expected behavior**
The background color is supposed to change to specified color (specified by `_hover`)

**Screenshots**

Button before hover, is fine.
<img width="228" alt="button" src="https://github.com/reflex-dev/reflex/assets/12757919/a15d0488-cf47-4452-9786-c66b7fce3ceb">

On hover, the style is different than specified.
<img width="278" alt="on_hover (different style than specified)" src="https://github.com/reflex-dev/reflex/assets/12757919/67ebe264-9f1d-4c10-b1f3-d6373cdb0d5e">

**Specifics (please complete the following information):**
 - Python Version: Python 3.11.6
 - Reflex Version: 0.3.4
 - OS: MacOS Sonoma 14.0
 - Browser (Optional): Chrome

**Comment by picklelo** [comment]
Thanks for reporting! This should be fixed by #2205 and resolved in the next release
