### ISSUE TITLE
Frontend not displaying on localhost:3000 when initializing Reflex app without sudo on Linux Mint

### ISSUE THREAD

**Issue by daichow** [reflex-dev/reflex#2244]
**Describe the bug**
Issue: When running the Reflex app on localhost without sudo on a Linux Mint system, the frontend doesn't display at localhost:3000, while only the backend appears at localhost:8000. Running with sudo resolves the issue, but the I prefer not to use it.

**To Reproduce**
 - Initialize the app with reflex init and reflex run.
 -  Frontend doesn't display on localhost:3000 without sudo, only the backend appears at localhost:8000.

**Expected behavior**
The frontend should display on localhost:3000 without the need for sudo on linux mint, maintaining package isolation in a venv.

**Screenshots**

#### verbose reflex run screenshots
![image](https://github.com/reflex-dev/reflex/assets/33791954/0edd6317-65db-4674-b68b-866c29bb9740)
![image](https://github.com/reflex-dev/reflex/assets/33791954/34b662b0-b802-430e-84ea-44d886f92c4b)
![image](https://github.com/reflex-dev/reflex/assets/33791954/f1577485-aa07-4fd7-81cf-d98ce4119718)

#### screenshots incoming for reflex init --loglevel debug
![image](https://github.com/reflex-dev/reflex/assets/33791954/bfc3297b-889a-4222-b6b8-f75e91894152)
![image](https://github.com/reflex-dev/reflex/assets/33791954/95deb030-507e-469b-9c45-8fdd0b6a2393)

**Specifics (please complete the following information):**
 - Python Version: Python 3.10.12 
 - Reflex Version: 0.3.4
 - OS: Linux Mint
 - Browser (Optional): Firefox 
 
**Additional context**
I talked about this problem on discord with the staff in a separate thread.

**Comment by daichow** [comment]
I wanted to say that I may have fixed the issue after playing around with some stuff and found out that it is an issue with the .web folder with the compiled javascript. Here were my sequence of commands:

```bash
cd .web/
rm -rf next.config.js 
rm -rf .next/
npm install react@latest
npm audit fix--force
bun run dev # this worked but then I had to reinstall the reflex stuff
cd ..
reflex run # finally working!

```

My .web/node_modules/react/index.js went from this:

```js
'use strict';

if (process.env.NODE_ENV === 'production') {
  module.exports = require('react/cjs/react.production.min.js');
} else {
  module.exports = require('react/cjs/react.development.js');
}
```
to this:

```js
'use strict';

if (process.env.NODE_ENV === 'production') {
  module.exports = require('./cjs/react.production.min.js');
} else {
  module.exports = require('./cjs/react.development.js');
}
```

And the following error got resolved when I ran `bun run dev`:

```bash
bun run dev
$ next dev
   ▲ Next.js 14.0.1
   - Local:        http://localhost:3000

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './cjs/react.development.js' is not defined by "exports" in /home/daichow/Documents/code/reflex/chatapp/.web/node_modules/react/package.json imported from /home/daichow/Documents/code/reflex/chatapp/.web/node_modules/react/index.js
    at exportsNotFound (node:internal/modules/esm/resolve:294:10)
    at packageExportsResolve (node:internal/modules/esm/resolve:641:9)
    at trySelf (node:internal/modules/cjs/loader:558:34)
    at Module._resolveFilename (node:internal/modules/cjs/loader:1121:24)
    at /home/daichow/Documents/code/reflex/chatapp/.web/node_modules/next/dist/server/require-hook.js:54:36
    at Module._load (node:internal/modules/cjs/loader:985:27)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at mod.require (/home/daichow/Documents/code/reflex/chatapp/.web/node_modules/next/dist/server/require-hook.js:64:28)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (/home/daichow/Documents/code/reflex/chatapp/.web/node_modules/react/index.js:6:20) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}
```

**Comment by masenf** [comment]
i believe this is now working, please reopen if you're still having issues
