### ISSUE TITLE
Unable to opt-out of telemetry 

### ISSUE THREAD

**Issue by nih23** [reflex-dev/reflex#2299]
**Describe the bug**
Reflex seems to send usage data to posthog.com even if this feature is explicitly disabled in rxconfig.py. 

```python
import reflex as rx

config = rx.Config(
    app_name="webui",
    telemetry_enabled=False
)
```

I noticed that the library is always communicating with posthog.com once.I turned on logging of my ML applications employing reflex. The issue occurs in development and production mode: 

```
2023-12-15 11:14:35,428:DEBUG:Starting new HTTPS connection (1): app.posthog.com:443
2023-12-15 11:14:35,639:DEBUG:https://app.posthog.com:443 "POST /batch/ HTTP/1.1" 200 None
```

**To Reproduce**
 - run any project based on reflex, e.g. https://github.com/reflex-dev/reflex-chat
 - turn off telemetry according to documentation https://reflex.dev/docs/advanced-guide/telemetry/

**Expected behavior**
There should be *no* communication with posthog.com once telemetry is disabled.

**Specifics (please complete the following information):**
 - Python Version: 3.9.9
 - Reflex Version: 0.3.6
 - OS: Mac OS 12.6.3

**Comment by Alek99** [comment]
I'm not able to recreate this when I set it to False it doesn't send anything for me

**Comment by Alek99** [comment]
Is this still an issue for you?

**Comment by picklelo** [comment]
We have tests to catch this now, please reopen if you still see this.
