### ISSUE TITLE
Feature: Adding contributors section to the README.md file. 

### ISSUE THREAD

**Issue by kalyani2003** [reflex-dev/reflex#2323]
There is no Contributors section in readme file .
As we know Contributions are what make the open-source community such an amazing place to learn, inspire, and create.
The Contributors section in a README.md file is important as it acknowledges and gives credit to those who have contributed to a project, fosters community and collaboration, adds transparency and accountability, and helps document the project's history for current and future maintainers. It also serves as a form of recognition, motivating contributors to continue their efforts.
![contributors](https://github.com/reflex-dev/reflex/assets/84217977/9553da5c-082f-46fd-a53b-63485f3b62dc)

**Comment by kalyani2003** [comment]
@picklelo  Kindly assign me this issue, I want to work on it. Thank You!

**Comment by picklelo** [comment]
@kalyani2003 that sounds great, assigned you!
