### ISSUE TITLE
Issues with Reflex Init

### ISSUE THREAD

**Issue by Alexpel7** [reflex-dev/reflex#2325]
**Describe the bug**
After installing Reflex in the virtual environment (venv), when I try to run 'reflex init,' it consistently fails.

**Screenshots**
<img width="1512" alt="Captura de pantalla 2023-12-21 a las 16 54 23" src="https://github.com/reflex-dev/reflex/assets/124504861/a45fdaa2-747c-43a6-9dff-d358c58b9547">

**Specifics (please complete the following information):**
 - Python Version: Python 3.11.3
 - Reflex Version: 0.3.7
 -  fnm Version: fnm 1.35.1
 - OS: 14.2
 - Mac chip: Apple M1 Pro
 
**Additional context**
I have tried installing and uninstalling Reflex several times, restarting the computer, experimenting with different terminals, and I always encounter the same error.

I am following the steps from the documentation:

1 - mkdir link_bio
2 - cd link_bio
3 - python3 -m venv .venv
4 - source .venv/bin/activate
5 - pip install reflex
6 - reflex init

**Comment by Alek99** [comment]
Interesting I also have an M1 and can't seem to recreate.

**Comment by kevin05m** [comment]
Yeah, I the same problem, my Mac about is M2 matchbook Air 2023, and I not idea because is the problem, when I ejecute reflex init

**Comment by picklelo** [comment]
Have you done the Rosetta upgrade as mentioned in the docs? https://reflex.dev/docs/getting-started/installation/

```
/usr/sbin/softwareupdate --install-rosetta --agree-to-license
```

**Comment by kevin05m** [comment]
Oh my problem is de upgrade rosetta, nice, I already run my program god
