### ISSUE TITLE
'editable' field in Data Editor is not working

### ISSUE THREAD

**Issue by AnubisXHyperX** [reflex-dev/reflex#2337]
**Describe the bug**
The 'editable' field in Data editor is not working, lets me edit and even sends the data back when on_cell_edited called

**To Reproduce**
 - Code/Link to Repo:
``` 
cols: List[dict] = [
        {'title': 'ID', 'type': 'int', 'editable': False},
        {'title': 'Date', 'type': 'datetime'},
        {'title': 'Seller', 'type': 'str'},
        {'title': 'Product', 'type': 'str'},
        {'title': 'Cartons', 'type': 'int'},
        {'title': 'Weight', 'type': 'int'},
        {'title': 'Pallet', 'type': 'bool'},
 ]
self.new_data.append([i.id, i.date, i.seller, i.product, i.cartons, i.weight, bool(i.pallet)])
rx.data_editor(
          overscroll_x=0,
          overscroll_y=0,
          on_cell_edited=TodayState.get_edited_cell,
          columns=TodayState.cols,
          data=TodayState.new_data,
)
```

**Expected behavior**
id column should not be editable

**Screenshots**

**Specifics (please complete the following information):**
 - Python Version: 3.10.5
 - Reflex Version: 0.3.7
 - OS: Mac OS Sonoma 14.2.1
 - Browser (Optional): Safari
 
**Additional context**

**Comment by Lendemor** [comment]
Should be fixed by #2338
