### ISSUE TITLE
[REF-1560] Bare SQLAlchemy support

### ISSUE THREAD

**Issue by benedikt-bartscher** [reflex-dev/reflex#2340]
Hey reflex team, I hope you all enjoyed your free time during Christmas :)

I stumbled about some issues with sqlmodel and decided to go with bare sqlalchemy without sqlmodel for now. A simple serializer function with reflex's `@serializer` decorator seems to work fine, and my sqlalchemy models even work when exposed directly as a reflex state variable.
However, since my sqlalchemy models do not inherit from `rx.Model` they are not discovered by `reflex db` commands and hence not included in my alembic migrations etc. I cannot inherit from `rx.Model` since sqlalchemy has many compatibility problems with pydantic (see f.e. https://github.com/sqlalchemy/sqlalchemy/discussions/10243 and https://github.com/pydantic/pydantic/issues/7129).

Would you accept a PR which tries to make bare sqlalchemy models work better with reflex? Maybe 2 different `rx.Model` subclasses, one with pydantics BaseModel for sqlmodel and one without for sqlalchemy? Or a simple bare minimal Mixin class which just "marks" all reflex models to be discovered (registered) for migrations etc.?

<sub>[REF-1560](https://linear.app/reflex-dev/issue/REF-1560/bare-sqlalchemy-support)</sub>

**Comment by masenf** [comment]
I would definitely support changes to have reflex support sqlalchemy models directly; both as Vars (2348) as well as in the makemigrations scripts

**Comment by benedikt-bartscher** [comment]
I added a draft PR which provides a ModelRegistry to register models to reflex.
There are 3 ways to register a model:

```python
ModelRegistry.register(model)

@ModelRegistry.register
class Base(DeclarativeBase):
  ...

class Base(DeclarativeBase, ModelRegistryMixin):
  ...
```

Do you like this approach or prefer a different implementation?

**Comment by picklelo** [comment]
Looks like we've merged many improvements for support here. We can make more specific issues if we need more enhancements here.
