### ISSUE TITLE
State Mixin with Computed Vars

### ISSUE THREAD

**Issue by benedikt-bartscher** [reflex-dev/reflex#2345]
**Describe the bug**
State Mixins are working fine, except for computed vars (methods decorated with `@rx.var`). The decorator seems to "convert" the method to a ComputedVar too early which results in reflex not being able to find the correct subclass. Maybe it's possible to defer the ComputedVar creation to f.e. `__init_subclass__` to mitigate this?

**Additional context**
I found this issue and some other Problems with `rx.State` while developing a rather complex django-like ModelAdmin for reflex where i needed Generic States. Generic States with "nested" `rx.State` inheritance do not work because reflex evaluates the generic vars/functions at the Parent State which does not resolve the Generic vars. This is why i tried State Mixins (which seem to work except for computed vars). Should i open a seperate Issue for Generic States? Do you even want to support complex use cases like this?

**To Reproduce**
The following code showcases a working example with "real" State inheritance (ParentState + SubState) and one with a StateMixin which does not inherit from `rx.State`.
```python
import reflex as rx


class StateMixin:
    base: str = "StateMixin base"

    @rx.var
    def computed(self) -> str:
        return "StateMixin computed"


class ParentState(rx.State):
    base: str = "ParentState base"

    @rx.var
    def computed(self) -> str:
        return "ParentState computed"


class SubState(ParentState):
    pass


class SubStateMixin(rx.State, StateMixin):
    pass


def index() -> rx.Component:
    return rx.vstack(
        # working fine
        rx.heading(SubState.base),
        rx.heading(SubState.computed),
        rx.heading(SubStateMixin.base),
        # not working
        rx.heading(SubStateMixin.computed),
    )


app = rx.App()
app.add_page(index)
app.compile()
```

**Current behavior**
```
Server Error
ReferenceError: computed is not defined

This error happened while generating the page. Any console logs will be displayed in the terminal window.
Source
pages/index.js (45:3) @ computed

  43 | </Heading>
  44 | <Heading>
> 45 | {computed}
     | ^
  46 | </Heading>
  47 | </VStack>
  48 | <NextHead>
```

**Expected behavior**
Computed Vars defined in StateMixins are working in subclasses.

**Specifics (please complete the following information):**
 - Python Version: 3.11
 - Reflex Version: 0.3.7
 - OS: Linux 6.6.8-arch1-1
 - Browser (Optional): Chromium

**Comment by masenf** [comment]
> The decorator seems to "convert" the method to a ComputedVar too early which results in reflex not being able to find the correct subclass. Maybe it's possible to defer the ComputedVar creation to f.e. __init_subclass__ to mitigate this?

Looking through the code, the `computed_vars` for a given state are determined by iterating through `__dict__`... but that will not contain any key/values from parents/mixin classes 

```python
        cls.computed_vars = {
            v._var_name: v._var_set_state(cls)
            for v in cls.__dict__.values()
            if isinstance(v, ComputedVar)
        }
```

To enable mixins to actually work, I think there are two things that need to happen:

1. The mixin should inherit from `rx.Base`, so that the fields defined in the mixin are treated as actual fields in the state that mixes it
2. The `rx.BaseState.__init_subclass__` should recursively check up the `__mro__` for non-State classes that define `ComputedVar` values in their `__dict__` and include those as `computed_vars`.

**Comment by benedikt-bartscher** [comment]
I just implemented your suggestions, they work flawless, even with a complicated inheritance structure. Should we really check the whole `__mro__`? In my tests, it works with  `__bases__` aswell.

**Comment by masenf** [comment]
`__mro__` is necessary if you want to make child mixins also work

```python
class MixinA:
    @rx.var
    def mixin_a(self) -> str:
        return "mixin"


class MixinB(MixinA):
    @rx.var
    def mixin_b(self) -> str:
        return "other_mixin"


class State(rx.State, MixinB):
    pass
```

**Comment by benedikt-bartscher** [comment]
Thank you, I missed that case. I updated the PR to use `__mro__` instead of `__bases__`

**Comment by benedikt-bartscher** [comment]
We could also use `inspect.getmro` instead [docs](https://docs.python.org/3/library/inspect.html#inspect.getmro)
