### ISSUE TITLE
Problem installing with pip using virtual environment

### ISSUE THREAD

**Issue by EirikurJonsson** [reflex-dev/reflex#2347]
**Describe the bug**
When creating a new project I initiate a new virtual environment using 

```bash
python -m venv .env
```

From here I start the virtual environment and pip install reflex

I get a huge install for where pip refers me to this error:

INFO: pip is looking at multiple versions of python-dateutil to determine which version is compatible with other requirements. This could take a while.

AND

INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. See https://pip.pypa.io/warnings/backtracking for guidance. If you want to abort this run, press Ctrl + C.

It creates this error for multiple different pacakages and I am unable to install this.

I have been able to do this out side of a virtual environment - which is great - love reflex - but I was not expecting this.

**To Reproduce**

1. python -m venv .env
2. source .env/bin/activate
3. pip install reflex

OR
1. python -m venv .env
2. source .env/bin/activate
3. pip install -r requrirements.txt (make sure reflex==0.3.7 is in the txt)

**Expected behavior**
Just a normal pip install behaviour

**Screenshots**
![Screenshot 2024-01-01 213204](https://github.com/reflex-dev/reflex/assets/30151177/ac21335c-ac97-416c-8a92-f4f43a4f3fcb)

**Specifics (please complete the following information):**
 - Python Version: 3.10.12
 - Reflex Version: 0.3.7
 - OS: Windows 11 BUT running it on WSL2 Ubuntu 22.04.3 LTS
 - Browser (Optional): 
 
**Additional context**

**Comment by karndeb** [comment]
Had the same issue. I only had to update the pip version.

**Comment by mikimejias** [comment]
Hello, I also had the same problem, I couldn't install reflex on Windows and I also had the same problem on Ubuntu.
Trying on Ubuntu, I updated to python version 3.12.1 and the latest version of pip. I created the folder where I was going to mount the virtual environment (venv). I created it under the name ".venv" as the documentation says and ran the pip install reflex command and everything was installed fine.

After that, I tested again in Windows. I worked with python 3.8.10 and the latest version of pip. I created the folder where I am going to save everything and inside I created the .venv environment, I activated it and executed the command `pip install reflex` but the problem still persisted, I realized that it was searching for all those things from the cache, I suspended the operation and I executed the command `pip install reflex --no-cache-dir` and it was finally installed.

I had not realized that detail and I was able to install it.

I hope it helps you.

**Comment by EirikurJonsson** [comment]
Fantastic - sorry for the late reply.

Well I sourced the virtual environment and updated pip and it installed - This is just bad practice but I never remember to update pip after creating my .env - Regradless it worked with just

```bash
source .env/bin/activate
python -m pip install --upgrade pip
pip install reflex OR
pip install reflex --no-cache-dir
```
I guess this closes the issue - thanks for all the responses
