### ISSUE TITLE
Instantiate State copies to reuse logic

### ISSUE THREAD

**Issue by mnesarco** [reflex-dev/reflex#2362]
**Describe the bug**
I have a State class, lets say a basic counter State with count var and increment method.

```python
class Counter(rx.State):
  count : int = 0
  def increment(self):
    self.count += 1
```

I want to put two counters in the page, so i want to instantiate the encapsulated state logic twice:

```python
Counter1 = Counter()
Counter2 = Counter()

# So I can use it in two places

def index() -> rx.Component:
    return rx.fragment(
        rx.vstack(
            rx.heading(Counter1.count, font_size="2em"),
            rx.heading(Counter2.count, font_size="2em"),
            rx.button('Btn1', on_click=Counter1.increment),
            rx.button('Btn2', on_click=Counter2.increment),
            spacing="1.5em",
            font_size="2em",
            padding_top="10%",
        ),
    )

```

But it does not work:

```
  File ".venv/lib/python3.11/site-packages/reflex/components/component.py", line 379, in _create_event_chain
    events = call_event_fn(value, arg_spec)  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.11/site-packages/reflex/event.py", line 780, in call_event_fn
    raise ValueError(f"Lambda {fn} returned an invalid event spec: {e}.")
ValueError: Lambda functools.partial(<function Counter.inc at 0x7f396beb9bc0>, Counter({'state.counter': {'count': 1}})) returned an invalid event spec: None.


```

**To Reproduce**
 - See the description above

**Expected behavior**
There should be a way to reuse the state class.

**Specifics (please complete the following information):**
 - Python Version: 3.11.0
 - Reflex Version: 0.3.7
 - OS: Linux Mint 21
 - Browser (Optional): Chrome

**Comment by benedikt-bartscher** [comment]
States are not meant to be instantiated by users. You can try https://github.com/reflex-dev/reflex/pull/2351 to create 2 independent States inheriting from the same State mixin to reuse your logic

**Comment by Alek99** [comment]
Agree with Benedikts and closing.
