### ISSUE TITLE
[REF-2923] Is plotly.graph_objects.FigureWidget suported to be used on rx.Plotly components?

### ISSUE THREAD

**Issue by LuisOlivaresJ** [reflex-dev/reflex#2365]
**Describe the bug**

I would like to use an instance of plotly.graph_objects.FigureWidget **instead** plotly.graph_objects.Figure, and pass it to a plotly component. But I am not sure if FigureWidget is supported.

The output error is:
TypeError: Invalid var passed for prop data, expected type reflex.vars.Var[plotly.graph_objs._figure.Figure], got value FigureWidget...

**To Reproduce**
```
import reflex as rx
import plotly.graph_objects as go

fig = go.FigureWidget()

class State(rx.State):
    pass

def index():
    return rx.vstack(
        rx.plotly(data=fig)
    )


app = rx.App()
app.add_page(index)

app.compile()
```

**Specifics (please complete the following information):**
 - Python Version: 3.11.5
 - Reflex Version: 0.3.7
 - OS: Ubutnu 22.04.3 LTS
 - Browser (Optional): Firefox
 

<sub>[REF-2923](https://linear.app/reflex-dev/issue/REF-2923/is-plotlygraph-objectsfigurewidget-suported-to-be-used-on-rxplotly)</sub>

**Comment by Alek99** [comment]
As of now I believe we only support poorly graphs not widgets. I'll put a feature request tag for this.

**Comment by berkorbay** [comment]
I can confidently say that at least axis and title texts are not displayed. You can see it on [your own tutorial](https://reflex.dev/docs/library/graphing/plotly/).

For reference, both [streamlit](https://docs.streamlit.io/library/api-reference/charts/st.plotly_chart) and [shinypy](https://shiny.posit.co/py/components/outputs/plot-plotly/index.html) support this widget. Perhaps there is a quick way to integrate it?

![Screenshot 2024-01-31 at 09 07 24](https://github.com/reflex-dev/reflex/assets/5690139/a172ea7d-50b8-4391-9c47-44de9f923c5c)

**Comment by picklelo** [comment]
We have a fix for the missing titles and axes coming next release: https://github.com/reflex-dev/reflex/pull/3394
