### ISSUE TITLE
Question: Support for front-end frameworks other than React?

### ISSUE THREAD

**Issue by chrisgeli** [reflex-dev/reflex#2372]
I just stumbled across Reflex and it looks pretty cool. Apologies if that's a beginner's question but I couldn't find this in the docs: 

Is there's anything specific about React that makes it the preferred (or maybe even only supported/supportable) choice of libraries? What about...

 * SolidJS
 * Vue.js
 * Svelte

or others?

**Comment by Alek99** [comment]
Hello, React has the most libraries and biggest ecosystem that's why we chose it. Would be interested to hear advantages of the other frameworks you listed. Libraries like svelte are nice for coding ergonomics but the user doesn't see this at the end of the day because its just compiled code

**Comment by webcoderz** [comment]
React-native would be nice then can do PWAs with reflex :)

**Comment by chrisgeli** [comment]
I have used React-Native in the past for cross-platform app development so that would be interesting, but for the web, nowadays I would probably choose SolidJS for performance, lack of virtual DOM and "coding ergonomics"... but I'm not a web dev by profession, so I might be missing other promising front-end libraries.

@Alek99 When I was looking at the docs, it was not clear to me, but it sounds like Reflex is hardwired to React (as in, it won't ever support anything else), is that true?

**Comment by picklelo** [comment]
@chrisgeli Currently we do use React, but our base compiler should be able to compile down to any other framework with a few tweaks. It would be great to make reflex more modular so we compile down to different frontend frameworks.

**Comment by picklelo** [comment]
closing this for now, but this is something we can revisit in the future.
