### ISSUE TITLE
ResolutionTooDeepError after running pip install 

### ISSUE THREAD

**Issue by Yummy-Yums** [reflex-dev/reflex#2376]
**Describe the bug**
I tried installing requirements after initializing a reflex folder but it takes a long  time to find a compatible version of some requirements (platformdirs) . throws the below 

**To Reproduce**
- run _reflex init_
- run _python -m pip install -r requirements.txt_

**Expected behavior**
Second command should run successfully 
```
_INFO: pip is looking at multiple versions of platformdirs to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of pipdeptree to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of jinja2 to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of httpcore to determine which version is compatible with other requirements. This could take a while.
Collecting httpcore==1.*
  Using cached httpcore-1.0.1-py3-none-any.whl (76 kB)
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. See https://pip.pypa.io/warnings/backtracking for guidance. If you want to abort this run, press Ctrl + C.
ERROR: Exception:
Traceback (most recent call last):
  File "/home/eliasderby/Desktop/python/oss/chatapp/venv/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 165, in exc_logging_wrapper
    status = run_func(*args)
  File "/home/eliasderby/Desktop/python/oss/chatapp/venv/lib/python3.10/site-packages/pip/_internal/cli/req_command.py", line 205, in wrapper
    return func(self, options, args)
  File "/home/eliasderby/Desktop/python/oss/chatapp/venv/lib/python3.10/site-packages/pip/_internal/commands/install.py", line 339, in run
    requirement_set = resolver.resolve(
  File "/home/eliasderby/Desktop/python/oss/chatapp/venv/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 94, in resolve
    result = self._result = resolver.resolve(
  File "/home/eliasderby/Desktop/python/oss/chatapp/venv/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 481, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/home/eliasderby/Desktop/python/oss/chatapp/venv/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 392, in resolve
    raise ResolutionTooDeep(max_rounds)
pip._vendor.resolvelib.resolvers.ResolutionTooDeep: 2000000_
```
**Screenshots**

**Specifics (please complete the following information):**
 - Python Version: 3.10.12 & 3.8
 - Reflex Version: 0.3.8
 - OS: PopOS/Ubuntu
 - Browser (Optional):
 
**Additional context**

**Comment by chrisgeli** [comment]
What is your Pip version (`pip -V`)?

I had a similar issue, `pip install reflex` took over 90 minutes and eventually crashed with a `ResolutionTooDeep` exception.

Then I upgraded pip from version `23.0.1` to `23.3.2` (within the venv, run `pip install -U pip`) and after that, the installation of `reflex` ran through smoothly.

Hope that helps.

**Comment by Yummy-Yums** [comment]
> What is your Pip version (`pip -V`)?
> 
> I had a similar issue, `pip install reflex` took over 90 minutes and eventually crashed with a `ResolutionTooDeep` exception.
> 
> Then I upgraded pip from version `23.0.1` to `23.3.2` (within the venv, run `pip install -U pip`) and after that, the installation of `reflex` ran through smoothly.
> 
> Hope that helps.

my pip version was 22.0.2 , I upgraded it as you recommended above and it works @chrisgeli 


should I close this issue as _won't fix_ ?  @ElijahAhianyo
