### ISSUE TITLE
Bug: is_backend_variable does not exclude dunder prefixed attrs

### ISSUE THREAD

**Issue by benedikt-bartscher** [reflex-dev/reflex#2381]
**Describe the bug**
`is_backend_variable` does not exclude attrs prefixed with dunder (`__`)

**To Reproduce**
```python
import reflex as rx


class State(rx.State):
    state_attr: int = 1
    _state_attr: int = 1
    __state_attr: int = 1

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        print(self._backend_vars)
        print(self.backend_vars)


def index() -> rx.Component:
    return rx.text("Hello, world!")


app = rx.App()
app.add_page(index)
```

Log output:
```bash
{'_state_attr': 1, '_State__state_attr': 1}
{'_state_attr': 1, '_State__state_attr': 1}
Compiling: ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 9/9 0:00:00
```

**Expected behavior**
State attrs starting with dunder (`__`) are not interpreted as backend vars.

**Specifics (please complete the following information):**
 - Python Version: 3.11.6
 - Reflex Version: 0.3.8
 - OS: arch linux
 - Browser (Optional):

**Comment by ElijahAhianyo** [comment]
from your logs, `__state_attr` is excluded which is the expected results. vars with a single leading  underscores are considered backend vars, read more here : https://reflex.dev/docs/state/vars#backend-only-vars . 
Closing this now, feel free to report any other issues.

**Comment by benedikt-bartscher** [comment]
Here is another example:

```python
import reflex as rx


class State(rx.State):
    state_attr: int = 1
    _state_attr: int = 1
    __dunder_attr: int = 1

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        print(self._backend_vars)
        print(self.backend_vars)


def index() -> rx.Component:
    return rx.text("Hello, world!")


app = rx.App()
app.add_page(index)
```

Log:
```log
──────────────────────────────────────────────────────────────────────────── Starting Reflex App ─────────────────────────────────────────────────────────────────────────────
{'_state_attr': 1, '_State__dunder_attr': 1}
{'_state_attr': 1, '_State__dunder_attr': 1}
Compiling: ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 9/9 0:00:00
```

**Comment by masenf** [comment]
`_State__dunder_attr` should not be considered a backend var, but yet it is in `backend_vars`.

i think this is a real bug

**Comment by benedikt-bartscher** [comment]
I am sorry, the first example didn't make this clear enough, cause the variable names are too close together. Could you reopen this for me if you consider this as a bug? Thanks in advance.
