### ISSUE TITLE
Customizable Reflex.DIR

### ISSUE THREAD

**Issue by nico525** [reflex-dev/reflex#2388]
Hi,
In our current working environment, we are not allowed to execute batch scripts based on the appdata directory. Would it be possible to customize the `Reflex.DIR` constant (derived from PlatformDirs) based on an environment varialbe (if set?)

I would like to just set an environment variable called i.e. REFLEX_DIR which is considered prior `PlatformDirs(MODULE_NAME, False).user_data_dir`, e.g. via `os.environ.get("REFLEX_DIR", PlatformDirs(MODULE_NAME, False).user_data_dir)`
This would make the reflex installation more flexible and I would not have to manually fix the constants.base file

Thanks, Nico

**Comment by Alek99** [comment]
This is an interesting feature, I haven't considered this use case before, thanks for bringing it up. We will look into this.
