### ISSUE TITLE
Missing Link For Read More:

### ISSUE THREAD

**Issue by Yummy-Yums** [reflex-dev/reflex#2390]
Missing Link After _Read More_  ;  _Fast Refresh had to perform a full reload_ functionality Debug Message

![Screenshot from 2024-01-12 14-05-42](https://github.com/reflex-dev/reflex/assets/77977520/d6922bcc-11e7-4f0c-8510-12f83ea3af8b)

**Comment by Alek99** [comment]
Hi, can you share your code?

**Comment by Yummy-Yums** [comment]
@Alek99 This is not a particular code issue I think, as you can see in the screenshot it's a _SyntaxError_ . I picked the code from the chat example in the _reflex-dev-examples_ folder

**Comment by picklelo** [comment]
This message is from Next.js - not sure if we can modify it. Closing this issue for now.
