### ISSUE TITLE
[REF-1673] In the elements, the hyphen "-" is removed from the "custom_attr" when compiling.

### ISSUE THREAD

**Issue by cllatser** [reflex-dev/reflex#2397]
**Describe the bug**

Hello everyone, I need to pass a class with a hyphen as a custom attribute. When compiling, I see in the inspector that the name has been passed without the hyphen "-". I don't know if it's a bug or not. Thank you very much.

**Screenshots**

![reflex](https://uploads.linear.app/9513bc1c-787d-499b-8c86-46952ab7013c/d6d03dee-52c1-4db5-acf1-edf02cb5da9c/1acbc73c-22e2-4a5a-9d21-72ebc4ec75bd?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzk1MTNiYzFjLTc4N2QtNDk5Yi04Yzg2LTQ2OTUyYWI3MDEzYy9kNmQwM2RlZS01MmMxLTRkYjUtYWNmMS1lZGYwMmNiNWRhOWMvMWFjYmM3M2MtMjJlMi00YTVhLTlkMjEtNzJlYmM0ZWM3NWJkIiwiaWF0IjoxNzA1NDM3MTU4LCJleHAiOjE3MDU1MjM1NTh9.wLfbO2wYiFUveHkqQdrEYvnmLSnUIqriTDbgVqZh2Pc)

![reflex-div](https://uploads.linear.app/9513bc1c-787d-499b-8c86-46952ab7013c/54943197-4d67-4dc4-ba8f-666f8240ac28/42efa612-eb17-436b-8f8f-54a1f240bc29?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzk1MTNiYzFjLTc4N2QtNDk5Yi04Yzg2LTQ2OTUyYWI3MDEzYy81NDk0MzE5Ny00ZDY3LTRkYzQtYmE4Zi02NjZmODI0MGFjMjgvNDJlZmE2MTItZWIxNy00MzZiLThmOGYtNTRhMWYyNDBiYzI5IiwiaWF0IjoxNzA1NDM3MTU4LCJleHAiOjE3MDU1MjM1NTh9.1lELpDxW67eU9ABbhy_GI3fv0Z6N-pAN6CV6PzRlJHc)

**Specifics (please complete the following information):**

* Python Version: 3.11.2
* Reflex Version: 0.3.8
* OS: Debian 12
* Browser (Optional): All

<sub>From [SyncLinear.com](https://synclinear.com) | [REF-1673](https://linear.app/reflex-dev/issue/REF-1673/in-the-elements-the-hyphen-is-removed-from-the-custom-attr-when)</sub>

**Comment by wassafshahzad** [comment]
I would like to work on this.
