### ISSUE TITLE
Background error

### ISSUE THREAD

**Issue by juanppdev** [reflex-dev/reflex#2398]
**Describe the bug**
I have a problem, and that is that when I try to change the background to another color, it stays in the default color which is white.

**Expected behavior**
I am trying to set the background to gray and it does not work.

**Specifics (please complete the following information):**
 - Python Version: 3.12.0
 - Reflex Version: 0.3.8
 - OS: Windows 11
 - Browser (Optional): Edge

**Comment by kumaraguru1735** [comment]
Set like this
```
style = {
    "font_family": "Arial, sans-serif",
    "height": "100vh",
    "width": "100vw",
    "margin": "0px",
    "font_size": "16px",
    "color": "white",
    "background":"#232d4d",
    "display": "flex",
    "align_items": "center",
    "justify_content": "center",
}

app = rx.App(style=style)
app.add_page(index, "/")
```
