### ISSUE TITLE
Avoid package installs at every compilation

### ISSUE THREAD

**Issue by kumaraguru1735** [reflex-dev/reflex#2413]
**Describe the bug**
Packages like Tailwind and ChakraUI are installed  every time it's compiling

**Comment by Alek99** [comment]
This is fixed and will be available in the next release of Reflex

**Comment by kumaraguru1735** [comment]
can u plz share the commit id ? plz

**Comment by Alek99** [comment]
Release should be out in a couple days with the fix. If you want to try it before, try pulling the latest main and running locally and your problem should be fixed.

**Comment by Alek99** [comment]
> can u plz share the commit id ? plz

https://github.com/reflex-dev/reflex/pull/2400
