### ISSUE TITLE
Radix checkbox

### ISSUE THREAD

**Issue by SamilErd** [reflex-dev/reflex#2519]
**Describe the bug**
The checkbox just disappears when unchecked, and reappears ( at least on the docs ) when clicked elsewhere, in my app it didn't reappear.

**Expected behavior**
a Non disappearing checkbox.

**Screenshots**
checked :
![image](https://github.com/reflex-dev/reflex/assets/44496436/07909652-00f8-440c-94c7-c362a1ca38ac)

unchecked:
![image](https://github.com/reflex-dev/reflex/assets/44496436/1060a108-b985-4427-a4f5-fc8732c623a2)

clicked elsewhere:
![image](https://github.com/reflex-dev/reflex/assets/44496436/d97323ea-d8f5-491c-922e-37537c7f215f)

**Specifics (please complete the following information):**
 - Browser (Optional): Opera GX
 
**Additional context**

**Comment by masenf** [comment]
This is the same issue caused by `focus-visible` style rules that were in place for chakra. We see similar problem with the radix select component as well. Definitely need to fix.

**Comment by picklelo** [comment]
This is resolved now.
