### ISSUE TITLE
Feature Request: rx.download temporary files

### ISSUE THREAD

**Issue by carlosabadia** [reflex-dev/reflex#2520]
**Feature Request**

Hello team!
Would it be possible for `rx.download` to work with temporary files?

Thanks

**Comment by masenf** [comment]
We currently have an implementation in #2493 that works by passing data directly from the State, would that work for your use case? Currently it doesn't work with binary files, but that's the next step.

**Comment by carlosabadia** [comment]
I'm using the library fpdf2 to create a PDF and want users to download it.  

Passing the State var but facing `TypeError: State vars must be primitive Python types, Plotly figures, Pandas dataframes, or subclasses of rx.Base. Found var "pdf" with type <class 'fpdf.fpdf.FPDF'>`

**Comment by viswanadula8828** [comment]
Can I know if this implementation can be used now or still working on it?

**Comment by masenf** [comment]
still in progress, and unfortunately didn't make it into the latest 0.3.10 release.

you can track it here https://github.com/reflex-dev/reflex/pull/2493

**Comment by picklelo** [comment]
#2493 is merged now
