### ISSUE TITLE
[REF-1894] Feature Request passing css prop to rx.desktop_only() component

### ISSUE THREAD

**Issue by kumaraguru1735** [reflex-dev/reflex#2525]
I need to use css props like this
```
rx.desktop_only(
   width="480px",
 ),
 ```
 or at least like this
 ```
rx.desktop_only(
  rx.spacer(
       ml="16em",
   ),
),
```

<sub>[REF-1894](https://linear.app/reflex-dev/issue/REF-1894/feature-request-passing-css-prop-to-rxdesktop-only-component)</sub>

**Comment by kumaraguru1735** [comment]
### **for responsive css styling**

**### for mobile_only**
`height=["20px", "none", "none", "none"]`

**### for desktop_only**
`height=["none", "none", "none", "20px"]`

**### for tablet_only**
`height=["none", "20px", "20px", "none"]`

**### for tablet_and_desktop**
`height=["none", "20px", "20px", "20px"]`

**### for mobile_and_tablet**
`height=["20px", "20px", "20px", "none"]`

**Comment by kumaraguru1735** [comment]
so can we create a function like this
`css_desktop_only()`

**Comment by Yummy-Yums** [comment]
can you elaborate more on this? @kumaraguru1735 .
@picklelo does wrapping dektop_only() with the props passed as param for height and with work for this scenario?

**Comment by kumaraguru1735** [comment]
@Yummy-Yums for responsive CSS styling refer https://github.com/reflex-dev/reflex/issues/2525#issuecomment-1931270179

**Comment by Yummy-Yums** [comment]
> @Yummy-Yums for responsive CSS styling refer [#2525 (comment)](https://github.com/reflex-dev/reflex/issues/2525#issuecomment-1931270179)

umm.. your 3rd comment is a bit unclear , maybe @picklelo , you can help me out here ? per my understanding ,  you want to  pass exact width/height to desktop_only () without passing that as a list; display= [..,..]?

**Comment by TommyDew42** [comment]
Yes I'm also interested in taking this work but not 100% sure what we are looking for here. I think I understand `desktop_only()` but need some clarification on the responsive css feature

**Comment by picklelo** [comment]
I'm also unsure actually. @kumaraguru1735 what was you original use case?

I try something like this and it works well for me. `rx.desktop_only` and the other responsive functions already are just `rx.box`, so they should support any of those props. I don't know if there's anything left to be done here.

```python
 rx.desktop_only(
    rx.button("hi", width="100%"),
    width="20px",
)
```

**Comment by ElijahAhianyo** [comment]
closing this for now. @kumaraguru1735  Feel free to reopen if you have any comments
