### ISSUE TITLE
HTML/Components inside table cells?

### ISSUE THREAD

**Issue by pb376** [reflex-dev/reflex#2536]
Hi,

I'm trying to display (1) a badge component and (2) a small snippet of html inside different cells per row of a table, but cannot figure out how to do so or if it is indeed possible. I've tried both datatables and vanilla tables but have not had any luck (i.e. when I try to use a badge I hit i.e. `Unhandled Runtime Error
Error: Objects are not valid as a React child (found: object with keys {children...`, and when I try to insert HTML it of course is just being printed unrendered.) If anybody could help point me in the right direction it would be greatly appreciated. Thanks!

EDIT - Turns out I had just fatfingered something when testing html and badges with vanilla tables (`rx.td(rx.badge(...))` and `.html` both work), so that's cleared up - but, am still interested to learn if using components within cells is possible for datatables.

**Comment by picklelo** [comment]
I don't think it's possible within the `rx.data_table` - if you want to have custom components, you will need to use `rx.table`
