### ISSUE TITLE
[REF-1893] Update `httpx`

### ISSUE THREAD

**Issue by benglewis** [reflex-dev/reflex#2545]
**Describe the bug**
Currently you cannot install the latest Jupyter Notebook and Reflex since `reflex-hosting-cli` requires `httpx: '>=0.24.0,<0.25.0'` and `jupyterlab` requires `httpx: '>=0.25.0'`

**To Reproduce**
- Just install `reflex-hosting-cli` (the latest version or the latest version of `reflex` which installs this as a dependency) and then install `jupyterlab` of version `4.1.0`.

**Expected behavior**
A simple change to `reflex-hosting-cli` to require `'>=0.24.0,<0.26.0'` would resolve this issue (which is already the value used in the `reflex` package).

**Specifics (please complete the following information):**
 - Python Version: 3.11.7
 - Reflex Version: 0.3.10
 - OS: MacOS
 - Browser (Optional): N/A

<sub>[REF-1893](https://linear.app/reflex-dev/issue/REF-1893/update-httpx)</sub>

**Comment by martinxu9** [comment]
`reflex-hosting-cli` is updated to `0.1.8` and tested with installing `jupyterlab=4.1.0` successfully
