### ISSUE TITLE
[REF-1940] reflex run Installing base frontend packages  Resolving dependencies

### ISSUE THREAD

**Issue by tamfrancisco** [reflex-dev/reflex#2561]
**Describe the bug**

**To Reproduce**
 - Code/Link to Repo:

**Expected behavior**

**Screenshots**

**Specifics (please complete the following information):**
 - Python Version:
 - Reflex Version:
 - OS: 
 - Browser (Optional):
 
**Additional context**

<sub>[REF-1940](https://linear.app/reflex-dev/issue/REF-1940/reflex-run-installing-base-frontend-packages-resolving-dependencies)</sub>

**Comment by tamfrancisco** [comment]
Compiling: ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 15/15 0:00:00
⠙ Installing base frontend packages  Resolving dependencies

**Comment by tamfrancisco** [comment]
python 3.10
reflex 0.3.10

**Comment by picklelo** [comment]
What OS are you on?

**Comment by tamfrancisco** [comment]
Linux mint 20

**Comment by tamfrancisco** [comment]
![image](https://github.com/reflex-dev/reflex/assets/117541629/e62c59d6-21dd-4906-bdb0-2e24d4b46c3b)

thinking all thime
![Selección_043](https://github.com/reflex-dev/reflex/assets/117541629/32042171-7885-46b3-8a5f-030b884eb554)

**Comment by tamfrancisco** [comment]
linux mint 21.1  
![image](https://github.com/reflex-dev/reflex/assets/117541629/2a8d018e-7d3c-440f-bac3-68e75768476a)

**Comment by kumaraguru1735** [comment]
Is it stuck on installing the base package?
can you please give me the output for 
```reflex run --loglevel debug```

**Comment by tamfrancisco** [comment]
anyone knows a possible solutions i have tested the same instalation en Ubuntu and we have the same proble thinking about dependecies all time.

**Comment by thphuc** [comment]
Got this issue on MacOS Sonoma 14.4.1 today too! 😐

**Comment by jiangguantian** [comment]
I met the same question on Windows 10 at reflex v0.5.7.  anyone can give some help?

**Comment by Lendemor** [comment]
Based on the logs we saw, it's either:
- an issue on the npm server being unavailable (which will usually resolve itself with time)
- an issue with the network where user is working

Neither of those being solvable by Reflex, I'll close this issue.

**Comment by ndendic** [comment]
Hi guys, I have the same issue after upgrading existing working v0.5.10 app to v0.6.0
![image](https://github.com/user-attachments/assets/5ac9b2f9-72b6-4271-9cce-df7b72265d42)
I'm working on Ubuntu Windows Linux subsystem (WSL); Python 3.11.9

When I downgrade back to 0.5.10 it works fine again..

**Comment by Nickszy** [comment]
+1
