### ISSUE TITLE
[REF-1928] Investigate Backend routes on Windows

### ISSUE THREAD

**Issue by picklelo** [reflex-dev/reflex#2567]
Backend routes may not be working on Windows: [https://discord.com/channels/1029853095527727165/1205593702723231804](https://discord.com/channels/1029853095527727165/1205593702723231804)

<sub>From [SyncLinear.com](https://synclinear.com) | [REF-1928](https://linear.app/reflex-dev/issue/REF-1928/investigate-backend-routes-on-windows)</sub>

**Comment by ElijahAhianyo** [comment]
Closed because the issue seem to have been fixed in main and pre-release `0.4.0a1`
