### ISSUE TITLE
Function called with onload is called multiple times

### ISSUE THREAD

**Issue by jod35** [reflex-dev/reflex#2609]
I am faced with a problem where the function I call with on_load in my page is being called a lot of times. This function is to help me fetch data from my back-end API. Many API requests are being made as shown in this example.

**To Reproduce**
![Screenshot from 2024-02-14 17-30-56](https://github.com/reflex-dev/reflex/assets/47812529/10294e67-05a4-4687-807b-6db5f0e34af1)
![Screenshot from 2024-02-14 17-31-20](https://github.com/reflex-dev/reflex/assets/47812529/a2075992-c747-4835-a09a-fcdba716c026)

**Expected behavior**
Running `reflex run` works normally but when the application is run, I get a lot of GET requests being made to the API.
.

**Specifics (please complete the following information):**
 - Python Version: 3.10.1
 - Reflex Version: 0.3.10
 - OS: Ubuntu Linux
 - Browser (Optional): Firefox
 .

**Comment by masenf** [comment]
Is it possible to post a minimal example that reproduces this?

**Comment by jod35** [comment]
Turns out one function I was calling in the on_load function was the source of the problem
