### ISSUE TITLE
Dynamic number of lines in line chart

### ISSUE THREAD

**Issue by vhunyad** [reflex-dev/reflex#2632]
**Describe the bug**
I wanted to use a line chart with multiple lines, where the exact nr of lines is coming from another variable. Moreover, the colors should come from a third variable. If I use manual lines, it works, so the dataset is OK.
I got the following error:
TypeError: Invalid var passed for prop data_key, expected type typing.Union[str, int], got value year of type typing.Any.

**To Reproduce**
```
rx.recharts.line_chart(
                rx.foreach(['2020','2021','2022','2023'], lambda year:
                    rx.recharts.line(
                        data_key=year, 
                        # stroke="#777777", 
                    ),                
                ),
                rx.recharts.x_axis(data_key="m"),
                rx.recharts.y_axis(),
                data=[{'m': 1, '2011': 0, '2012': 370, '2013': 323, '2014': 311, '2015': 415, '2016': 230, '2017': 230, '2018': 317, '2019': 177, '2020': 201, '2021': 194, '2022': 206, '2023': 240, '2024': 288}, {'m': 2, '2011': 0, '2012': 372, '2013': 353, '2014': 276, '2015': 336, '2016': 215, '2017': 208, '2018': 256, '2019': 160, '2020': 188, '2021': 175, '2022': 186, '2023': 236, '2024': 0}]
# data originally comes from a @cached_var
            ),
```
**Expected behavior**
Using foreach for lines in line chart

**Screenshots**

**Specifics (please complete the following information):**
 - Python Version: 3.9.2
 - Reflex Version: 0.3.10
 - OS: Debian 11
 - Browser (Optional):
 
**Additional context**

**Comment by vhunyad** [comment]
I got the exact error message, so I consider it not supported.
ValueError: The component `LineChart` only allows the components: `XAxis`, `YAxis`, `ReferenceArea`, `ReferenceDot`, `ReferenceLine`, `Brush`, `CartesianGrid`, `Legend`, `GraphingTooltip`, `Line` as children. Got `Foreach` instead.

**Comment by picklelo** [comment]
I think this is a bug - we should be able go support this

cc @ElijahAhianyo this should work in the next release right?

**Comment by ElijahAhianyo** [comment]
> I think this is a bug - we should be able go support this
> 
> cc @ElijahAhianyo this should work in the next release right?

Yes thats correct. This should work in the next release. Tested the code with the `reflex-0.4.0` branch and the issue doesnt persist. 
@vhunyad  as for the type error: `TypeError: Invalid var passed for prop data_key, expected type typing.Union[str, int], got value year of type typing.Any.`, `Foreach` works with state vars and not constants. You should move `['2020','2021','2022','2023']` into a state Var to get it to work or use a normal `for` statement. Closing this for now

**Comment by vhunyad** [comment]
Thanks for the quick action. The vars actually are in a state var, I just copied samples here for quick example.

**Comment by vhunyad** [comment]
@ElijahAhianyo In the new realease can the color code come from a state var as well? Because if color can not be automated, then it will be all the same.

**Comment by vhunyad** [comment]
Perfect, thanks
