### ISSUE TITLE
Barchart tooltip hides the actual bar

### ISSUE THREAD

**Issue by vhunyad** [reflex-dev/reflex#2634]
**Describe the bug**
The tooltip fully covers the bar in case of both white and dark theme.

**To Reproduce**
```
rx.recharts.bar_chart(
                rx.recharts.bar(
                    rx.recharts.label_list(data_key="plus", position="top"),
                    data_key="plus", 
                    # stroke="#8884d8", 
                    fill="#3333FF",
                ),
                rx.recharts.x_axis(data_key="Y"),
                rx.recharts.y_axis(),
                # rx.recharts.legend(),
                rx.recharts.graphing_tooltip(),
                # width=600,
                height=500,
                margin={"left": 0,"right": 0,"top": 20,"bottom": 0},
                data=TransactionState.chart_y,
)
```
**Expected behavior**

**Screenshots**
![image](https://github.com/reflex-dev/reflex/assets/17292468/9d4f0a90-a2c5-42ae-8a19-9e65cd468529)

**Specifics (please complete the following information):**
- Python Version: 3.9.2
- Reflex Version: 0.3.10
- OS: Debian 11
 - Browser (Optional): Chrome 121.0.6167.161 and Edge 121.0.2277.112
 
**Additional context**

**Comment by masenf** [comment]
place the `graphing_tooltip()` as the first child, then the bar and other components will stack on top of it

**Comment by vhunyad** [comment]
It works, thanks. I did not know it defines the layer order, it might be worth to mention it in the docs.
