### ISSUE TITLE
ThemPanel button 'CopyTheme' gives runtime error

### ISSUE THREAD

**Issue by vhunyad** [reflex-dev/reflex#2649]
**Describe the bug**
ThemPanel button 'CopyTheme' gives runtime error

**To Reproduce**
press Copy Theme button

**Expected behavior**

**Screenshots**
![image](https://github.com/reflex-dev/reflex/assets/17292468/09fad719-5ebb-41ab-a43b-276f1c283cd7)

**Specifics (please complete the following information):**
 - Python Version:
 - Reflex Version: 0.4.0
 - OS: debian 11
 - Browser (Optional):
 
**Additional context**

**Comment by Lendemor** [comment]
This error doesn't happens in main.
Closing this.
