### ISSUE TITLE
[REF-1994] rx.theme(appearance='dark') freezes whole app

### ISSUE THREAD

**Issue by vhunyad** [reflex-dev/reflex#2650]
[https://github.com/reflex-dev/reflex/pull/2654](https://github.com/reflex-dev/reflex/pull/2654)

**Describe the bug**
In case of dark, without any styles, app freezes, automatically opening themepanel is not responding.

**To Reproduce**

```
app = rx.App(
    theme=rx.theme(appearance='dark'),
    )
```

**Expected behavior**

**Screenshots**

**Specifics (please complete the following information):**

* Python Version: 3.9.2
* Reflex Version: 0.4.0
* OS: debian 11
* Browser (Optional):

**Additional context**

<sub>From [SyncLinear.com](https://synclinear.com) | [REF-1994](https://linear.app/reflex-dev/issue/REF-1994/rxthemeappearance=dark-freezes-whole-app)</sub>

**Comment by vhunyad** [comment]
If I keep it on 'light', it starts and I also can change to dark on ThemePanel. Only default dark produces this.

**Comment by kevinkoech357** [comment]
Experienced the same issue too. Debian 12, Chrome Browser, Python version=3.11.2, Reflex=0.4.0.

**Comment by ericfeunekes** [comment]
To add another version of the bug when running Reflex 0.4.1: when I set `appearance=dark` it just stays in light mode. But when I add a theme_panel in the app it starts up in dark mode but freezes the page.

**Comment by masenf** [comment]
This got closed accidentally when a related bug was fixed 😔
