### ISSUE TITLE
[REF-1995] Radix Accordion generated with foreach and external function does not have unique value

### ISSUE THREAD

**Issue by vhunyad** [reflex-dev/reflex#2652]
**Describe the bug**
It shows up correctly, but after clicking on any item, all items open at the same time and the whole accordion freezes. No error message on console or backend.
This has worked with Chakra accordion.

**To Reproduce**

```
    @rx.cached_var
    def accordion(self) -> list[str]: 
        return ['item1','item2','item3']

def accordion_level1(name) -> rx.Component:
    return rx.accordion.item(
        header=name,
        content=name,
    )

rx.accordion.root(
    rx.foreach(State.accordion,accordion_level1)),
),
```

**Expected behavior**
Working like chakra accordion.

**Screenshots**

**Specifics (please complete the following information):**

* Python Version: 3.9.2
* Reflex Version: 0.4.0
* OS: debian11
* Browser (Optional):

**Additional context**

[https://github.com/reflex-dev/reflex/pull/2663](https://github.com/reflex-dev/reflex/pull/2663)

<sub>From [SyncLinear.com](https://synclinear.com) | [REF-1995](https://linear.app/reflex-dev/issue/REF-1995/radix-accordion-generated-with-foreach-and-external-function-does-not)</sub>

**Comment by vhunyad** [comment]
Setting the accordion.item.value to a unique value solves the issue. Might be worth to mention in the docs.

**Comment by masenf** [comment]
This was introduced here https://github.com/reflex-dev/reflex/pull/2616/files#diff-820ba7d7b749dd4c726797c6c9802ee557bb45d16d28fa10ffef0f2c1c59e159R490-R491

We need a better default, users shouldn't have to know this.
