### ISSUE TITLE
Trying to pass streaming chatbot response

### ISSUE THREAD

**Issue by andsty** [reflex-dev/reflex#2655]
Hi i am trying to create a chatbot with this client
import json
import time
from dify_client import ChatClient

api_key = "axxxxxxxx"

# Initialize ChatClient
chat_client = ChatClient(api_key)

# Create Chat Message using ChatClient
chat_response = chat_client.create_chat_message(inputs={}, query="Hello", user="user_id", response_mode="streaming")
chat_response.raise_for_status()

for line in chat_response.iter_lines(decode_unicode=True):
    line = line.split('data:', 1)[-1]
    if line.strip():
        line_json = json.loads(line.strip())
        answer = line_json.get('answer')
        if answer:
            # Print each non-None chunk next to the previous one, with a delay
            print(answer, end='', flush=True)  # Ensure immediate printing without newline
            time.sleep(0.1)  # Delay before processing the next chunk
i pass the client in my state.py file however i haven't managed to return the response in streaming format. is waiting for the response to finish and then print it.
Here is my state.py file
import reflex as rx
import os
import json
import time
from dify_client import ChatClient

api_key = os.environ["API_KEY"]

class State(rx.State):
    # The current question being asked.
    question: str = ""

    # Keep track of the chat history as a list of (question, answer) tuples.
    chat_history: list[tuple[str, str]] = []

    # Use a property to trigger UI updates. 
    # This can be a simple string that you append messages to.
    live_update: str = ""

    def answer(self):
        # Initialize ChatClient with the API key
        chat_client = ChatClient(api_key)

        # Create Chat Message using ChatClient
        chat_response = chat_client.create_chat_message(inputs={}, query=self.question, user="user_id", response_mode="streaming")
        chat_response.raise_for_status()

        # Process the streaming response
        for line in chat_response.iter_lines(decode_unicode=True):
            line = line.split('data:', 1)[-1]
            if line.strip():
                line_json = json.loads(line.strip())
                chunk = line_json.get('answer')
                if chunk:
                    # Directly update the live_update state with the new chunk
                    self.live_update += chunk
                    # Optionally simulate the delay for a real-time effect
                    time.sleep(0.001)  # Adjusted to 1ms delay as per requirement

        # Once all chunks are processed, you might want to do some cleanup or final updates
        self.finalize_response()

    def finalize_response(self):
        # Append the complete interaction to the chat history
        self.chat_history.append((self.question, self.live_update))

        # Clear the question and live_update for the next interaction
        self.question = ""
        self.live_update = ""

Any idea? thanks in advance

**Comment by ericfeunekes** [comment]
Pretty sure you need to `yield` after updating `self.live_update += chunk`. 

See [this page](https://reflex.dev/docs/events/yield_events/) in the docs.

**Comment by picklelo** [comment]
Agreed, if you put a `yield` it should work. Feel free to reopen if it's still an issue.
