### ISSUE TITLE
reflex.number_input missing in 0.4.10

### ISSUE THREAD

**Issue by ChristophGreger** [reflex-dev/reflex#2656]
**Describe the bug**
I'm using `rx.number_input` in a project. Everything works fine in version 0.3.10. However after updating to 0.4.0 i get the following Error on running `reflex run`: `File "test.py", line 6, in cell
    return rx.number_input(
           ^^^^^^^^^^^^^^^
  File "/Users/myname/Desktop/Reflex/venv/lib/python3.11/site-packages/reflex/__init__.py", line 221, in __getattr__
    raise AttributeError(f"module 'reflex' has no attribute {name}") from None
AttributeError: module 'reflex' has no attribute reflex.number_input
`

**To Reproduce**
 - Code/Link to Repo: https://github.com/ChristophGreger/AlgoPage.git 
 - Branche: CNF
 - Version is still on 0.3.10 as 0.40 not working

**Expected behavior**
It should just work as in 0.3.10

**Specifics (please complete the following information):**
 - Python Version: 3.11
 - Reflex Version: 0.4.0
 - OS: Sonoma 14.2.1
 - Browser (Optional):

**Comment by masenf** [comment]
The number input is not supported in the core library in 0.4.0+.

You can continue to use the chakra number input via `rx.chakra.number_input` or you can use the native number input provided by the browser via `rx.input(type="number")`
