### ISSUE TITLE
[REF-1996] Setting radix accordion.root.color_scheme gives javascript warning

### ISSUE THREAD

**Issue by vhunyad** [reflex-dev/reflex#2657]
**Describe the bug**
client.js:2 Warning: React does not recognize the `colorScheme` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `colorscheme` instead. If you accidentally passed it from a parent component, remove it from the DOM element.

**To Reproduce**

```
rx.accordion.root(
        rx.accordion.item(
            header="First Item",
            content=The First accordion item's content",
            font_size="3em",
            value="item_1",
        ),
        rx.accordion.item(
            header="Second Item",
            content="The second accordion item's content",
            font_size="3em",
            value="item_2",
        ),
        rx.accordion.item(
            header="Third item",
            content="The third accordion item's content",
            font_size="3em",
            value="item_3",
        ),
        collapsible=True,
        color_scheme='indigo',
    )
```

**Expected behavior**

**Screenshots**

**Specifics (please complete the following information):**

* Python Version: 0.9.2
* Reflex Version: 0.4.0
* OS: debian 11
* Browser (Optional):

**Additional context**

[https://github.com/reflex-dev/reflex/pull/2664](https://github.com/reflex-dev/reflex/pull/2664)

<sub>From [SyncLinear.com](https://synclinear.com) | [REF-1996](https://linear.app/reflex-dev/issue/REF-1996/setting-radix-accordionrootcolor-scheme-gives-javascript-warning)</sub>

**Comment by masenf** [comment]
Thanks for reporting, will fix it up for 0.4.1
