### ISSUE TITLE
Problem with width and height elements V.0.4.0

### ISSUE THREAD

**Issue by H4cKer54N** [reflex-dev/reflex#2661]
**Describe the bug**

I'm having trouble implementing the width. It seems that it only accepts integer values and doesn't allow percentages or vh or vw units. Also, changing its attributes using style={"width":"100%"} is not permitted. Therefore, I can't scale the elements to 100% of their container, also the w doesn't work, only works width like attribute.

**To Reproduce**

```
import reflex as rx
@rx.page("login")
def login():
    return rx.chakra.center(
        rx.card(
            rx.chakra.vstack(
                rx.heading("Inicio de sesión", size="8"),
                rx.divider(),
                rx.chakra.input(placeholder="Correo", w="100%"),
                rx.input(placeholder="Contraseña", type="password",w="100%"),
                rx.button("Iniciar sesión", color="teal", w="100%"),
                rx.link("¿Olvidaste tu contraseña?", color="teal"),
                w="100%",
            ),
        ),
        w="100vw",
        h="100vh",
    )
```
None of these works:
```
rx.input(placeholder="Contraseña", type="password",width="100vw"),
rx.input(placeholder="Contraseña", type="password",width="100%"),
rx.input(placeholder="Contraseña", type="password",w="100vw"),
rx.input(placeholder="Contraseña", type="password",w="100%"),
rx.input(placeholder="Contraseña", type="password",style={"width":"100%"}),
```
This works but  they seem to be use pixels 
```
rx.input(placeholder="Contraseña", type="password",width=100),
```

**Expected behavior**
I'm waiting for the element to expand to 100% of its parent, but it's not working.

**Screenshots**
![image](https://github.com/reflex-dev/reflex/assets/134620146/3c9beb00-4942-4bf6-bfa4-3382ff333dc5)

**Specifics (please complete the following information):**
 - Python Version:  3.11.6
 - Reflex Version: 0.4.0
 - OS: Ubuntu 23.10
 - Browser (Optional): Brave
 
**Additional context**

I'm seeing that the new element is being wrapped by a div, which is preventing its child, the input, from obtaining these parameters. In the case of the Chakra input, it was placed directly in the DOM without a wrapping div.
![image](https://github.com/reflex-dev/reflex/assets/134620146/3ae08609-4ed6-463b-8d6c-16cb0f4f7003)
![image](https://github.com/reflex-dev/reflex/assets/134620146/b10373e7-7b16-46e4-a1d4-c91f6cf2dcc8)

**Comment by wassafshahzad** [comment]
Can I look into this
