### ISSUE TITLE
"Backend Vars cannot be accessed on the frontend" falsely triggered

### ISSUE THREAD

**Issue by abulvenz** [reflex-dev/reflex#2681]
**Describe the bug**
Subclassing states with backend variables raises exception since commit
https://github.com/reflex-dev/reflex/commit/f9d219407fa30558bf4eba9d39664efc46eba0b9

**To Reproduce**
```python
import reflex as rx

class State(rx.State):
    _hello: str = "No hello, Reflex!"

class SubState(State):
    pass

app = rx.App()
```
**Expected behavior**
Compile

**Specifics (please complete the following information):**
 - Python Version: 3.12.2
 - Reflex Version: main
 - OS: arch
 - Browser (Optional): Any

**Comment by Lendemor** [comment]
problematic merge got reverted, closing this
