### ISSUE TITLE
Shadowing computed vars

### ISSUE THREAD

**Issue by benedikt-bartscher** [reflex-dev/reflex#2686]
**Describe the bug**
Currently, shadowing computed vars in substates leads to unexpected/undocumented behavior. The parent computed vars always take precedence.

**To Reproduce**
```python
import reflex as rx


class State(rx.State):
    @rx.var
    def computed(self) -> int:
        return 0


class SubState(State):
    @rx.var
    def computed(self) -> int:
        return 5


def index() -> rx.Component:
    return rx.center(
        rx.text("Computed: ", State.computed),
        rx.text("Sub Computed: ", SubState.computed),
    )

app = rx.App()
app.add_page(index)
```

**Current behavior**
```
Computed: 0
Sub Computed: 0
```

**Expected behavior**
Either disallow shadowing computed vars or define and test an expected behavior.

**Comment by masenf** [comment]
Note: any "expected behavior" would have to include how to handle other event handlers and computed vars defined on either `State` or `SubState` accessing the shadowed var.

```python
import reflex as rx


class State(rx.State):
    @rx.var
    def computed(self) -> int:
        return 0

    def handle_click(self):
        print(self.computed)


class SubState(State):
    @rx.var
    def computed(self) -> int:
        return 5

    def handle_click2(self):
        print(self.computed)


def index() -> rx.Component:
    return rx.center(
        rx.button("State.handle_click", on_click=State.handle_click),
        rx.button("SubState.handle_click", on_click=SubState.handle_click),
        rx.button("SubState.handle_click2", on_click=SubState.handle_click2),
    )


app = rx.App()
app.add_page(index)
```

Currently, click any of the above buttons prints `0`... but i would sort of expect the latter two to print `5`, since they are associated with the SubState.

**Comment by Lendemor** [comment]
Reflex now raises `reflex.utils.exceptions.ComputedVarShadowsStateVar` when this happens.
