### ISSUE TITLE
Server Error :: ReferenceError: ChakraImage is not defined

### ISSUE THREAD

**Issue by deivisaherreraj** [reflex-dev/reflex#2703]
**Describe the bug**
When I am implementing the **Ant Design FloatButton** component, that is, I have the **float_button.py** file where I create the component:

```
import reflex as rx
from website_frontend.styles.colors import Color

class FloatButton(rx.Component):
    library = "antd"
    tag = "FloatButton"
    icon: rx.Var[rx.chakra.Image]
    href: rx.Var[str]
    target = "_blank"
    badge = {"dot": True, "color": Color.PRIMARY.value}

float_button = FloatButton.create
```

And in my **footer.py** file I call it like this:

```
import reflex as rx
import datetime
import website_frontend.constants as const
from website_frontend.styles.styles import Size
from website_frontend.styles.colors import Color, TextColor
from website_frontend.components.float_button import float_button

def footer() -> rx.Component:
    return rx.chakra.vstack(
		# Otro codigo....
        float_button(
            icon=rx.chakra.Image(src="/icons/donate.svg"),
            href=const.COFFEE_URL
        ),
        margin_bottom=Size.BIG.value,
        padding_bottom=Size.VERY_BIG.value,
        padding_x=Size.BIG.value,
        spacing=Size.ZERO.value,
        color=TextColor.FOOTER.value
    )
```
But I am getting this error as if some package was missing to be installed or it was not imported correctly:

_Server Error
ReferenceError: ChakraImage is not defined

This error happened while generating the page. Any console logs will be displayed in the terminal window._

**To Reproduce**
 - Code/Link to Repo: https://github.com/deivisaherreraj/website

**Expected behavior**
That an icon could be painted in the lower right corner of the page. See image 3 attached.

**Screenshots**
![Captura_1](https://github.com/reflex-dev/reflex/assets/9270977/373a12b1-1c95-45eb-9f39-fa9e4c6b83a8)
![Captura_2](https://github.com/reflex-dev/reflex/assets/9270977/3d439a32-d9dc-4d19-b09c-3b95192d93d6)
![Captura_3](https://github.com/reflex-dev/reflex/assets/9270977/b95e75b5-31ba-4170-998a-ccd59814e94b)

**Specifics (please complete the following information):**
 - Python Version: 3.10.7
 - Reflex Version: 0.4.1
 - OS: Windows 10
 - Browser (Optional): N/A
 
**Additional context**
N/A

**Comment by mouredev** [comment]
Hi,

Please, use "icon: rx.Var[rx.el.Img]"

**Comment by deivisaherreraj** [comment]
> Hi,
> 
> Please, use "icon: rx.Var[rx.el.Img]"

Excellent, thank you very much, it worked perfectly for me.

![Captura](https://github.com/reflex-dev/reflex/assets/9270977/98b3a6e2-143c-4675-859d-5a3324c62b51)

**Comment by MundowatRicardo** [comment]
Mi solución: 
En navbar.py

float_button(
icon=rx.el.Img(src="/icons/cafe.webp"),
href=const.COFFEE_URL # Añadir la URL de la página de donaciones.
),

En ant_components.py

class FloatButton(rx.Component):
library = "antd"
tag = "FloatButton"
icon:rx.Var[rx.el.Img]
href:rx.Var[str]
target="_blank"
badge = {"dot": True, "color": Color.PRIMARY.value}

float_button = FloatButton.create
