### ISSUE TITLE
Allow set_clipboard to copy text from the state

### ISSUE THREAD

**Issue by booqoffsky** [reflex-dev/reflex#2720]
Reflex: 0.4.1
The following code causes an error: `on_click=rx.set_clipboard(State.clipboard_text)`

Error:
```
Unhandled Runtime Error
TypeError: Cannot read properties of undefined (reading 'writeText')

Source
utils/state.js (152:24) @ writeText


  150 | if (event.name == "_set_clipboard") {
  151 |   const content = event.payload.content;
> 152 |   navigator.clipboard.writeText(content);
      |                      ^
  153 |   return false;
  154 | }
  155 |
```

It would be great if it were possible to copy text from a variable from the state. Or somehow initialize a copy to the clipboard event on the server side:
```
def on_click_my_button(self):
    # some logic
    rx.set_clipboard(text)
```

**Comment by ElijahAhianyo** [comment]
can you provide a bit more code on how you're using `rx.set_clipboard`? Also do you get the issue when you run `reflex init` and the `reflex run` again?

**Comment by lichaohero** [comment]
> I set up https and now this code works. Thanks for the help!

I have the same problem.How do you set up https?Could you tell me?Thank you very mush.

**Comment by booqoffsky** [comment]
> How do you set up https?

 Locally, you can try this:
 
 1) Install https://github.com/caddyserver/caddy
 2) Create Caddyfile
 ```
# backend
localhost {
    reverse_proxy :8000
}

# frontend
localhost:5555 {
    reverse_proxy :3000
}
```
3) Run `reflex run`
4) Run `sudo caddy run`
5) Open https://localhost:5555/

You may need to enable chrome://flags/#allow-insecure-localhost
