### ISSUE TITLE
using darkreader.org extensions causes 'Unhandled Runtime Error'

### ISSUE THREAD

**Issue by jq6l43d1** [reflex-dev/reflex#2723]
**Describe the bug**
Using darkreader.org extensions on a Reflex site will cause an 'Unhandled Runtime Error'

**To Reproduce**
Enable a darkreader.org extension on a Reflex site. Even the 'blank' template that can be created with 'reflex init' will produce this error.

**Expected behavior**
The darkreader.org extension should work without error.

**Screenshots**
![2024-02-26_11-21](https://github.com/reflex-dev/reflex/assets/110377310/adfe174d-de52-4fb2-b987-c6540cc97b34)

**Specifics (please complete the following information):**
 - Python Version: 3.11.6
 - Reflex Version: 0.4.1
 - OS: Ubuntu 23.10

**Comment by masenf** [comment]
It should work in `--env prod` mode. The hydration errors are just a warning in dev mode that the server rendered html does not match the html DOM on the client. If you're using an extension that modifies the DOM, then it's almost guaranteed to give this hydration warning.

**Comment by jq6l43d1** [comment]
Gotcha. I will close this issue. Thanks.
