### ISSUE TITLE
Allow custom JS code

### ISSUE THREAD

**Issue by picklelo** [reflex-dev/reflex#273]
The user should be able to give a string of custom JS code that will be compiled to the top of the page.

**Comment by TommyDew42** [comment]
I can also work on this. How would the feature look like in code? Sth like this?:
```py
app = pc.App()
app.add_page(index, custom_js_scripts=[js_code_str_1, js_code_str_2])
```

**Comment by FHU-yezi** [comment]
> I can also work on this. How would the feature look like in code? Sth like this?:
> ```py
> app = pc.App()
> app.add_page(index, custom_js_scripts=[js_code_str_1, js_code_str_2])
> ```

Maybe add a pc.script function? and we can choose where the script should be placed.

**Comment by TommyDew42** [comment]
Interestingly we have already had a [pc.script](https://github.com/pynecone-io/pynecone/blob/f22c67e48c9156ae0616611e3561f8b97fe8bb56/pynecone/components/base/document.py#L30-L33). It looks to me it's a nextjs [script](https://nextjs.org/docs/basic-features/script) object.

**Comment by TommyDew42** [comment]
I'll suggest we rename the [pc.script](https://github.com/pynecone-io/pynecone/blob/f22c67e48c9156ae0616611e3561f8b97fe8bb56/pynecone/components/base/document.py#L30-L33) to `NextScript` instead. I think this component is only used internally in the framework so it's probably fine. And create a `Script` component.

**Comment by jq6l43d1** [comment]
This would be an awesome feature to have.
