### ISSUE TITLE
rx.input.on_blur gives JS warning missing on_change

### ISSUE THREAD

**Issue by vhunyad** [reflex-dev/reflex#2734]
**Describe the bug**
Warning: You provided a `value` prop to a form field without an `onChange` handler. This will render a read-only field. If the field should be mutable use `defaultValue`. Otherwise, set either `onChange` or `readOnly`.

**To Reproduce**
`
rx.input(
            value=VarState.name,
            on_blur=VarState.set_name
        ),
`

**Expected behavior**
Accept on_blur without on_change as in the example https://reflex.dev/docs/library/forms/input/#using-event-handlers

**Specifics (please complete the following information):**
 - Python Version: 3.9.2
 - Reflex Version: 0.4.2
 - OS: debian 11
 - Browser (Optional):

**Comment by vhunyad** [comment]
This was caused by the value property, not because of the on_blur.

**Comment by masenf** [comment]
`default_value` should be used with `on_blur`

if you need to set the value programmatically, assign an `id` to the input and `return rx.set_value(id, "new value")` from an event handler (or event trigger)
