### ISSUE TITLE
Feature Request: A new component-specific event trigger "on_file_select"

### ISSUE THREAD

**Issue by Anga205** [reflex-dev/reflex#2737]
**Describe the feature**
this event would trigger as soon as a new file(s) as been selected in an rx.upload component, this would make things possible like, instantly uploading files that have been dragged and dropped into the website

**Comment by masenf** [comment]
I think this would be a good one for an outside contributor to pick up; essentially we just need to plumb through the `onDropAccepted` callback of ReactDropzone as an event trigger and allow the user to specify their upload handler.

In the meantime, here is a workaround using `rx.moment`: https://github.com/masenf/rx_shout/blob/94a9fb9c8e91ebb21e52e43614c40462e55beb33/rx_shout/components/image_upload.py#L42-L51

```python
        # Auto-upload after half second.
        rx.moment(
            interval=rx.cond(
                rx.selected_files(UPLOAD_ID) & ~UploadState.is_uploading,
                auto_upload_delay_ms,
                0,
            ),
            on_change=lambda _: UploadState.handle_upload(
                rx.upload_files(
                    upload_id=UPLOAD_ID,
                    on_upload_progress=UploadState.on_upload_progress,
                ),
            ),
            display="none",
        )
```

**Comment by emmakodes** [comment]
I am picking this up

**Comment by Anga205** [comment]
well on_drop is pretty much exactly what this thread asked for, and now that its been added, ill close this issue
