### ISSUE TITLE
Trying to reinstall node when it is installed

### ISSUE THREAD

**Issue by ansuzgs** [reflex-dev/reflex#2752]
**Describe the bug**
When initializing a reflex project with ```reflex init```, it does not check properly if node is already installed. In fact, it check if node is installed but, even if it is installed, reflex tries to reinstall it again.

Analyzing the code I saw that this action is a TODO to be implemented. I would like to try to implement it.

**To Reproduce**
 - Running ```reflex init --loglevel debug``` when node is already installed.

**Expected behavior**
It should skip the installation of node if it is already installed and the version is higher than the required one.

**Screenshots**
There is a partial copy of the output in debug mode.

```
Debug: [Reflex 0.4.0 with Python 3.12.1 (PATH: /home/paos/repos/prueba_reflex/.venv/bin/python3.12)]
Debug: [Node 18.17.0 (Expected: 18.17.0) (PATH:/usr/bin/node)]
Debug: [FNM 1.35.1 (Expected: 1.35.1) (PATH: /home/paos/.local/share/reflex/fnm/fnm)]
Debug: [Bun None (Expected: 1.0.13) (PATH: /home/paos/.local/share/reflex/bun/bin/bun)]
Debug: [OS Linux Ubuntu 22.04.4 LTS]
...
Debug: Installing node
Debug: Installing Node v18.17.0 (x64)
```

**Specifics (please complete the following information):**
 - Python Version: 3.12.1
 - Reflex Version: 0.4.0 (Although it happens also in 0.4.2)
 - OS: Ubuntu 22.04.4 LTS (on WSL)

**Comment by ElijahAhianyo** [comment]
Hi @ansuzgs thanks for reporting this and sure you can pick this up
