### ISSUE TITLE
Trying to reinstall bun when it is installed

### ISSUE THREAD

**Issue by ansuzgs** [reflex-dev/reflex#2753]
**Describe the bug**
When initializing a reflex project with ```reflex init```, it does not check properly if bun is already installed. In fact, it check if bun is installed but, even if it is installed, reflex tries to reinstall it again.

Analyzing the code I saw that it is an issue with the versions check. I would like to fix the error.

**To Reproduce**
 - Running ```reflex init --loglevel debug``` when node is already installed.

**Expected behavior**
It should skip the installation of bun if it is already installed and the version is higher than the required one.

**Screenshots**
There is a partial copy of the output in debug mode.

```
Debug: [Reflex 0.4.2 with Python 3.11.2 (PATH: /home/paos/test_reflex/.venv/bin/python3)]
Debug: [Node 18.19.0 (Expected: 18.17.0) (PATH:/usr/bin/node)]
Debug: [FNM 1.35.1 (Expected: 1.35.1) (PATH: /home/paos/.local/share/reflex/fnm/fnm)]
Debug: [Bun 1.0.29 (Expected: 1.0.13) (PATH: /home/paos/.local/share/reflex/bun/bin/bun)]
Debug: [OS Linux Debian GNU/Linux 12 (bookworm)]
...
Debug: Running command: ['/home/paos/.local/share/reflex/bun/bin/bun', '-v']
Debug: Downloading https://bun.sh/install
```

**Specifics (please complete the following information):**
 - Python Version: 3.11.2
 - Reflex Version: 0.4.2 
 - OS: Debian 12 (on WSL)

**Comment by Alek99** [comment]
Thanks would be happy to accept a pr that fixes this
