### ISSUE TITLE
Python Infinity doesnt translate into Js infinity

### ISSUE THREAD

**Issue by ElijahAhianyo** [reflex-dev/reflex#2757]
using `math.inf` or `float("inf")`/`float("-inf")` renders as a string in Js code (`{"infinity"}`) instead of JS  equivalent `Infinity`

**Comment by wassafshahzad** [comment]
I can take this up

**Comment by wassafshahzad** [comment]
Could you share a reproducible code ? Sine I am getting "inf" and not {"infinity"}

**Comment by wassafshahzad** [comment]
Using the following  code
```
class State(rx.State):
    """The app state."""
    
    values: list = [1,2,3]
    count : int  = float("-inf")
    
    def max(self):
        temp = float("-inf")
        for x in self.values:
            temp = max(temp, x)
        self.count = temp
```
Renders infinity correctly as shown here
![state](https://github.com/reflex-dev/reflex/assets/25094157/97998d30-9ba0-498e-bf71-ccfeb6c5e0c2)

However if we use the following code
```
 rx.heading(f"Welcome to Reflex! {float('inf')}", size="9"),
```
Causes the infinity to render as inf since thats what python returns

**Comment by picklelo** [comment]
@wassafshahzad got it, we can close this issue if everything seems to be working.

**Comment by masenf** [comment]
@ElijahAhianyo do you have a repro that shows the defect in a context where it matters?

f-string with a `float` doesn't seem like it would impact runtime performance at all; passing a float as a prop and having it render incorrectly seems like it _would_ be an issue.

**Comment by ElijahAhianyo** [comment]
I'm not able to repro the issue anymore . The original reproducible code was:

```python
   
class TypeAnimation(rx.Component):
    tag = "TypeAnimation"
    library = "react-type-animation"

    sequence: rx.Var[list]
    speed:rx.Var[int]
    repeat: rx.Var[float]

type_animation= TypeAnimation.create

    class State(rx.State):
        pass


    def index():
        return rx.box(
            type_animation(
                sequence=[
                    "being comfortable",
                    1000
                ],
                speed=200,
                repeat=float("inf"),
                font_family="Mate",
                font_size="5em",
                font_style="italic"

            ),
        )
```

But that looks to be working as expected with the main and current release. Infinity in an f-string rendering as "inf" looks like expected python behavior. Not sure how or if we would want to handle that. We can go ahead and close this issue
