### ISSUE TITLE
[REF-1368] Move common form functionality to rx.el.forms

### ISSUE THREAD

**Issue by masenf** [reflex-dev/reflex#2776]
Allow radix or other components to use form submit functionality without implicitly depending on chakra.

<sub>From [SyncLinear.com](https://synclinear.com) | [REF-1368](https://linear.app/reflex-dev/issue/REF-1368/move-common-form-functionality-to-rxelforms)</sub>

**Comment by picklelo** [comment]
Merged in #2801
