### ISSUE TITLE
[REF-2127] Loosen requirements

### ISSUE THREAD

**Issue by picklelo** [reflex-dev/reflex#2777]
### Discussed in https://github.com/orgs/reflex-dev/discussions/2770

<div type='discussions-op-text'>

<sup>Originally posted by **mahrz24** March  4, 2024</sup>
I really like the looks of reflex dev so far and would like to use it at my company for internal dev tooling to replace streamlit as it would serve the purpose much better.

However, this is currently made impossible by the quite strict down pinning of a lot of dependencies. As we develop the tools in a larger repository I end up in a lot of conflicts. But even with a standalone tool our security policies frequently require me to update to the latest versions of packages that fix some CVEs or other security issues.

While I can see the case for semantic versioning and down pinning to the major version. In reality this only works in a library if you frequently evaluate if there are newer compatible version and are very quick to lift upper bounds. Sadly with reflex this isn't the case. Maybe a better approach would be to open up most upper boundaries and rely on CI pipelines to ensure compatibility with latest version of libraries.</div>

<sub>[REF-2127](https://linear.app/reflex-dev/issue/REF-2127/loosen-requirements)</sub>

**Comment by martinxu9** [comment]
@mahrz24 I can match the requirements between the `reflex-hosting-cli` and `reflex`. For the most part, have been trying to do that. If you have any recommendations for the CLI package and don't mind sharing your findings, I'd happy to merge them in. As far as I remember, there's only a couple of dependencies on the CLI package that are not part of the core reflex
