### ISSUE TITLE
Problem when running ```reflex init``` in Windows 10, .gitignore overwrite.

### ISSUE THREAD

**Issue by cllatser** [reflex-dev/reflex#2788]
**Describe the bug**

Hello, I use Windows for programming, both natively and through WSL2. After going crazy because git was ignoring the .gitignore file, I realized that when performing the `reflex init` command in Windows 10 native, it overwrites the file and changes its encoding type, so Windows git doesn't recognize it and ignores it. Is there any option to prevent it from overwriting the .gitignore file if it already exists?

**Expected behavior**

If the .gitignore file already exists, it should not be overwritten when executing `reflex init`.

**Screenshots**

![git001](https://github.com/reflex-dev/reflex/assets/65849393/89c8d210-2bcb-42f6-88a1-56aa0626808f)
![git002](https://github.com/reflex-dev/reflex/assets/65849393/ad933fbc-ecfc-41b3-9415-4a77fe1f5d76)

**Specifics (please complete the following information):**
 - Python Version: 3.11.8
 - Reflex Version: 0.4.3
 - OS: Windows 10
 - Browser (Optional):

**Comment by picklelo** [comment]
We can definitely support that. Only thing is then users may forget to manually add `.web` and other folders in. Maybe there's a solution where we can keep it overriding, but fix the final encoding type?

Would welcome any contributions to this issue.

**Comment by cllatser** [comment]
I have put in the `initialize_gitignore()` function, when it opens the file to write the parameter` newline='\n'` and it works fine, as expected. I can do a PR but as we know that on Mac there will be no problems.

![newline](https://github.com/reflex-dev/reflex/assets/65849393/cc0e760d-fbe6-4823-b4dc-4e6133ba34bd)

**Comment by picklelo** [comment]
Yes please put a PR - we have integration tests that will catch if it breaks anything

**Comment by picklelo** [comment]
Merged in #2797
