### ISSUE TITLE
Drawer content has a blue ring by default

### ISSUE THREAD

**Issue by Alek99** [reflex-dev/reflex#2790]
**Describe the bug**

By default the drawer has a blue ring.

**To Reproduce**
 - Code/Link to Repo:
 
 ```python
 def sidebar(trigger) -> rx.Component:
    """The sidebar component."""
    return rx.drawer.root(
        rx.drawer.trigger(trigger),
        rx.drawer.overlay(),
        rx.drawer.portal(
            rx.drawer.content(
                rx.vstack(
                    rx.heading("Chats", color=rx.color("mauve", 11)),
                    rx.divider(),
                    rx.foreach(State.chat_titles, lambda chat: sidebar_chat(chat)),
                    align_items="stretch",
                    width="100%",
                ),
                top="auto",
                right="auto",
                height="100%",
                width="20em",
                padding="2em",
                background_color=rx.color("mauve", 2),
            )
        ),
        direction="left",
    )
 ```

**Expected behavior**

By default the drawer should not have a blue ring.
**Additional context**

To fix in the rx.drawer.content set the prop `outline="none"`

**Comment by Yummy-Yums** [comment]
Hey @Alek99 , i repro'd the code you shared and i can't find the blue outline you speak of ? maybe I'm missing something?

![image](https://github.com/reflex-dev/reflex/assets/77977520/238c9c4f-95e7-4e50-bbd5-f72f6f706e3c)

**Comment by Alek99** [comment]
![Screenshot 2024-04-03 at 9 32 29 AM](https://github.com/reflex-dev/reflex/assets/38776361/ef29354a-8215-40ef-9e80-a9f66ea3b617)

I seem to be seeing it on this main site

**Comment by Yummy-Yums** [comment]
doesn't appear on my end

![image](https://github.com/reflex-dev/reflex/assets/77977520/b9138d15-0c0c-4159-b509-d99b612ebbd9)

**Comment by Alek99** [comment]
Maybe its just on safari

**Comment by Yummy-Yums** [comment]
i use linux, POP OS

**Comment by danik292** [comment]
![obrazek](https://github.com/reflex-dev/reflex/assets/116908854/085d6cf7-57bf-4737-9d7d-7ecc29a2ad8f)


Linux mint
firefox

**Comment by danik292** [comment]
@Yummy-Yums  What browser are you using?

**Comment by LucasOcampos** [comment]
Tried reproducing on Windows using Brave and Opera GX, no success.  Doesn't seem to repro here
