### ISSUE TITLE
[BUG] Text Input Field Messes with the Typed Text

### ISSUE THREAD

**Issue by ibehnam** [reflex-dev/reflex#2794]
I have attached a video/gif:

![Kapture 2024-03-05 at 20 56 07](https://github.com/reflex-dev/reflex/assets/58621210/b8a9b74f-0f23-43c7-920b-fe92cd8ffe3b)

In the first example I typed `Hi, please tell me about yourself`, but it got converted to gibberish text. It's worse when I type fast.

Replicated on Safari and Brave/Chrome.

**Comment by Alek99** [comment]
I have a pr coming in that should fix this when we redeploy https://github.com/reflex-dev/reflex-chat/pull/27, was using a controlled component before and switched it to a form
