### ISSUE TITLE
[REF-2196] Create `rx.scroll_to` special event

### ISSUE THREAD

**Issue by picklelo** [reflex-dev/reflex#2834]
We should have a special event handler called `rx.scroll_to("id")` that will scroll to the element with the given id.

The current way to accomplish this is

```python
rx.call_script(f"document.getElementById('{id}').scrollIntoView();")
```

But there should be a simpler API that wraps this.

<sub>[REF-2196](https://linear.app/reflex-dev/issue/REF-2196/create-rxscroll-to-special-event)</sub>

**Comment by Yummy-Yums** [comment]
@picklelo which folder/module does this special event go to? is it same as rx.console_log?
https://reflex.dev/docs/api-reference/special_events/#special-events

**Comment by picklelo** [comment]
@Yummy-Yums yes we can put it in the same folder. I'm thinking this can maybe just be an alias that returns the `call_script` above (i.e. we don't need to modify anything in the Javascript side).

**Comment by Yummy-Yums** [comment]
Will select by ID be enough for this use case? What of using the query
selector i.e. Selecting by Class or that's not necessary for now

**Comment by picklelo** [comment]
The ID should be enough. You can see here for an example of how I've used this: https://github.com/picklelo/reflex-chat/blob/main/custom_components/reflex_chat/chat.py#L75

**Comment by Yummy-Yums** [comment]
@picklelo quick one, i'm using _call_script_ (which already) returns an _EventSpec_ , is it necessary to return to a call_script with code or the first return line is fine. Also, will tests be necessary for this event action ?
![image](https://github.com/reflex-dev/reflex/assets/77977520/c0f05d86-74ea-45e4-8a4a-50de03090f53)

**Comment by picklelo** [comment]
@Yummy-Yums the way you have it in your PR is exactly what I was thinking, we don't need anything on the js side for this function. Will review your PR this weekend.
