### ISSUE TITLE
ValueError: Invalid path: ['on_load_internal_state']

### ISSUE THREAD

**Issue by benglewis** [reflex-dev/reflex#2843]
**Describe the bug**
When trying to execute a Reflex app in a Docker image based on `micromamba`, the app crashes on start. It is unclear why.

**Expected behavior**
The lambda function should call the state event function correctly

**Specifics (please complete the following information):**
 - Python Version: 3.11
 - Reflex Version: 0.4.2
 - OS: Linux (Docker) on amd64 via the official `micromamba` Docker image
 - Browser (Optional): Chrome and Safari

**Comment by picklelo** [comment]
Could you check if the problem persists on reflex 0.4.4?

**Comment by ElijahAhianyo** [comment]
closing this issue. @benglewis feel free to reopen if issue still persist or reopen another issue if you face further issues
