### ISSUE TITLE
[REF-2202] rx.plotly does not expose any Event Triggers

### ISSUE THREAD

**Issue by masenf** [reflex-dev/reflex#2846]
**Describe the bug**
`react-plotly.js` has a lot of event triggers to handle plot interactions... but none of these are exposed in Reflex

Full list of event triggers:
https://github.com/plotly/react-plotly.js/?tab=readme-ov-file#event-handler-props

To enable interactivity of plotly charts, these event triggers should be made available to end users via `Plotly.get_event_triggers`

**Specifics (please complete the following information):**
 - Python Version: 3.11.5
 - Reflex Version: 0.4.4
 
**Additional context**
See discussion https://github.com/orgs/reflex-dev/discussions/2845

<sub>[REF-2202](https://linear.app/reflex-dev/issue/REF-2202/rxplotly-does-not-expose-any-event-triggers)</sub>

**Comment by picklelo** [comment]
Merged in #3397
