### ISSUE TITLE
React Leaflet

### ISSUE THREAD

**Issue by Alek99** [reflex-dev/reflex#2855]
**Describe the Custom Component**
A clear and concise description of what the custom component does.

React Leaflet provides an abstraction of Leaflet as React components. It does not replace Leaflet, only leverages React’s lifecycle methods to call the relevant Leaflet handlers.

- What is the purpose of the custom component?
Provide a way to get some mapping capabilities in reflex.

- What is the expected behavior of the custom component?
Be able to use leaflet plots in reflex

- What are the use cases for the custom component?
Interactive maps

**Specifics (please complete the following information):**
 - Do you have a specific react package in mind? (Optional):
 https://www.npmjs.com/package/react-leaflet
**Additional context**
Add any other context about the custom component here.
https://discord.com/channels/1029853095527727165/1187732846719283230/1187732846719283230

**Comment by picklelo** [comment]
This should be brought in as a third party component.
