### ISSUE TITLE
[REF-2220] reflex run should automatically select new port if default is taken

### ISSUE THREAD

**Issue by picklelo** [reflex-dev/reflex#2857]
Currently if you have one app running, and try to `reflex run` on another app, it asks you to change the port. Instead, we should automatically find the next free frontend and backend ports (3001, 8001) and run it on that.

<sub>[REF-2220](https://linear.app/reflex-dev/issue/REF-2220/reflex-run-should-automatically-select-new-port-if-default-is-taken)</sub>

**Comment by wassafshahzad** [comment]
I would like to take this up.

**Comment by wassafshahzad** [comment]
This update only be used in local development context right ?
