### ISSUE TITLE
[REF-2250] Investigate generic debounce

### ISSUE THREAD

**Issue by picklelo** [reflex-dev/reflex#2872]
Currently the `rx.debounce` works well with inputs and textareas. Is there a way we can generalize this to work for all components such as `rx.slider` or the color picker example in the docs?

Current docs: https://reflex.dev/docs/library/forms/debounce/#debounce

<sub>[REF-2250](https://linear.app/reflex-dev/issue/REF-2250/investigate-generic-debounce)</sub>

**Comment by picklelo** [comment]
Modifying `queueEvents` like this within `utils/state.js` seems to work. We should probably make this a flag though, we mayn't want to do this for all events.

```python
export const queueEvents = async (events, socket) => {
  // Filter out any events already in the queue.
  events = events.filter((event) => {
    for (const queued_event of event_queue) {
      if (queued_event.name === event.name) {
        return false;
      }
    }
    return true;
  });
  event_queue.push(...events);
  await processEvent(socket.current);
};
```

**Comment by masenf** [comment]
fixed in https://github.com/reflex-dev/reflex/pull/3091
