### ISSUE TITLE
pages/index.js fails to update imports

### ISSUE THREAD

**Issue by atishpanday** [reflex-dev/reflex#2875]
**Describe the bug**
While restructuring the code, I tried to re-run the app, only to find the following error: "ReferenceError: RadixThemesHeading is not defined"

**To Reproduce**
I am not sure how the error can be reproduced. What worked for me is:
1) Rewrote some code in a different file and imported it into the reflex_app.py file for rendering. 
2) Ran the `reflex run` command

**Expected behavior**
The app should have simply run as normal, producing the exact same output as before refactoring of the code.

**Screenshots**
<img width="994" alt="Screenshot 2024-03-18 at 12 23 55 PM" src="https://github.com/reflex-dev/reflex/assets/56168565/67a0a50c-f198-4758-9548-cc8c36d9dd37">

[
<img width="730" alt="Screenshot 2024-03-18 at 12 38 44 PM" src="https://github.com/reflex-dev/reflex/assets/56168565/0014e89a-21e9-46d6-ad10-5bbd211a48c7">
](url)

**Specifics (please complete the following information):**
 - Python Version: 3.11.8
 - Reflex Version: 0.4.4
 - OS: macOS Sonoma 14.2.1
 - Browser (Optional): Chrome
 
**Additional context**
The pages/index.py file should automatically update the imports to re-render the app. In my case, the RadixThemesHeading and RadixThemesText from the '@radix-ui/themes' were not automatically updated and had to be done manually.

**Comment by masenf** [comment]
are you using `@rx.memo`?

**Comment by atishpanday** [comment]
> are you using `@rx.memo`?

No, but I created custom components to render different parts of the web page, in the 'React style'. To create these components, I created a separate file and declared a class that extends rx.Component. Inside this class I defined a render function that renders the required component. When I do this, and execute `reflex run`, the pages/index.js did not correctly update the imports. This was the source of error.

**Comment by masenf** [comment]
Can you show the code of your custom `rx.Component` subclass?

Custom components do need to declare their imports, so that reflex knows what imports to include in the page when the component is rendered. Typically a higher-order component would just be a python function that returns a composition of other components. If I see your code, I can make a more specific recommendation.

**Comment by atishpanday** [comment]
> Can you show the code of your custom `rx.Component` subclass?
> 
> Custom components do need to declare their imports, so that reflex knows what imports to include in the page when the component is rendered. Typically a higher-order component would just be a python function that returns a composition of other components. If I see your code, I can make a more specific recommendation.

Sure. Here's how I created the custom class:

reflex_app/my_component.py
`import reflex as rx


class MyComponent(rx.Component):
        def render() -> rx.Component:
                # My code here

`

reflex_app/reflex_app.py:

`
import reflex as rx


from . import my_component.MyComponent

def index() -> rx.Component:
        return MyComponent()

app = rx.App()
app.add_page(index)
`

**Comment by masenf** [comment]
what is the `# My code here` part though?

if you look at the `Component.render` function in the base class, it does not return a component. It's supposed to return a render dict.

If you want to return a Component, then you should override the classmethod `Component.create` and return the `Component` from there. Alternatively you can just define a regular function that returns a `Component` and use that.

```python
def MyComponent(name: str) -> rx.Component:
    return rx.vstack(
        rx.text("Hello"),
        rx.text(name),
    )
```

**Comment by atishpanday** [comment]
> what is the `# My code here` part though?
> 
> if you look at the `Component.render` function in the base class, it does not return a component. It's supposed to return a render dict.
> 
> If you want to return a Component, then you should override the classmethod `Component.create` and return the `Component` from there. Alternatively you can just define a regular function that returns a `Component` and use that.
> 
> ```python
> def MyComponent(name: str) -> rx.Component:
>     return rx.vstack(
>         rx.text("Hello"),
>         rx.text(name),
>     )
> ```

This is the code that I got from the AI in the documentation:


reflex_app/my_component.py
```python
class MyComponent(rx.Component):
    def render() -> rx.Component:
        return rx.Box(
             # other code
        )
```

reflex_app/reflex_app.py
```python
import reflex as rx
from . import my_component

def index() -> rx.Component:
    return my_component.MyComponent()

app = rx.App()
app.add_page(index)
```

The above two codes reproduce the error that I mentioned in the beginning. Is this the wrong way to create a component?

**Comment by picklelo** [comment]
@atishpanday Check out our [component documentation](https://reflex.dev/docs/ui/overview/) - you don't need to subclass `rx.Component` when defining your UI.

**Comment by ElijahAhianyo** [comment]
@atishpanday Please refer to the specified docs as pointed out. Closing this issue for now. Feel free to reopen or raise another issue when you encounter other issues.
