### ISSUE TITLE
Fix some of the lucide icons allowed names

### ISSUE THREAD

**Issue by Lendemor** [reflex-dev/reflex#2882]
Some of the tags allowed for use in lucide `Icon` are missing/wrong.

We need to make sure the values in  `LUCIDE_ICON_LIST` are correct.

**Comment by luccavp12** [comment]
Hey! Just for clarification, are you interested in updating it to the most recent [release](https://github.com/lucide-icons/lucide/releases)? I think there's ~30 more icons compared to what's in `LUCIDE_ICON_LIST` currently.
