### ISSUE TITLE
An error occurred while downloading fnm package: timed out

### ISSUE THREAD

**Issue by nicedouble** [reflex-dev/reflex#2896]
**Describe the bug**
I'm new to relfex,and first use reflex.First install reflex,successful.Second,reflex init ,failed,i retry many times,but always show error:**An error occurred while downloading fnm package: timed out**

**Screenshots**
![bug](https://github.com/reflex-dev/reflex/assets/40421045/9745e080-b776-4590-bdcc-a701a9fdad35)

**Specifics (please complete the following information):**
 - Python Version:3.9
 - Reflex Version:0.4.5
 - OS: win10 64bit
 - Browser (Optional):Chrome
- IDE:Pycharm

**Comment by picklelo** [comment]
@nicedouble if you retry does the error occur consistently?

**Comment by nicedouble** [comment]
@picklelo yes

**Comment by ElijahAhianyo** [comment]
> @picklelo yes

can you run with `reflex init --loglevel debug` and show the output?

**Comment by nicedouble** [comment]
Today i retry,`reflex init` success! Maybe the network issue?
