### ISSUE TITLE
Failed to pip install reflex on macOS 14.4

### ISSUE THREAD

**Issue by pekingduck** [reflex-dev/reflex#2909]
**Describe the bug**
Strictly speaking this is not a bug of reflex, but one of the dependencies, watchdog 2.3.1, failed to build from source during `pip install reflex`. The latest version of watchdog 4.0.0 installs just fine.

**To Reproduce**
 - `pip install reflex`

**Screenshots**
<img width="857" alt="Screenshot 2024-03-24 at 7 17 42 AM" src="https://github.com/reflex-dev/reflex/assets/2597142/e91530f9-9053-4742-9f00-470af9d817b4">

**Specifics (please complete the following information):**
 - Python Version: 3.12.2
 - Reflex Version: 0.4.5
 - OS: macOS 14.4 (Sonoma on Apple M1)

**Comment by ElijahAhianyo** [comment]
Thanks for reporting this. We should look into upgrading to the latest version in the `pyproject.toml`

**Comment by pekingduck** [comment]
Just tried with 3.11.8 and it worked! There's a prebuilt wheel of watchdog 2.3.1 available to Python 3.11 so no compilation was needed.

<img width="637" alt="Screenshot 2024-03-26 at 7 30 49 PM" src="https://github.com/reflex-dev/reflex/assets/2597142/55f8ecd2-5f10-4aa0-ac37-4c9ec42ba446">
