### ISSUE TITLE
One of the links routes to a 404 page on github

### ISSUE THREAD

**Issue by staranbeer** [reflex-dev/reflex#2912]
**Describe the bug**
The `graph traversal` link in the `Build anything, faster` section, when clicked, routes to a 404 page on github.

**Screenshots**

![image](https://github.com/reflex-dev/reflex/assets/62498540/9a9e7180-9197-46f4-8bcb-37e64ab604bc)

**Comment by ElijahAhianyo** [comment]
Thanks @staranbeer  for reporting this, will look into this. However the websote/docs lives in another repo (https://github.com/reflex-dev/reflex-web). Will close this issue and create this there so it's easily tracked
