### ISSUE TITLE
Fully Migrate off Black to Ruff

### ISSUE THREAD

**Issue by dapomeranz** [reflex-dev/reflex#2928]
Reflex is already using Ruff for linting and formatting. Yet their is still a legacy dependency on the black formatter. At this point, Ruff seems to be on course to completely take over as industry standard and the sooner Reflex standardizes the better. I see that the file `scripts/pyi_generator.py` uses the black library to format pyi files but this should be easy to switch over.

Also, it is not possible to use the Ruff VS Code Extension as the pyproject is locked to an older version of Ruff.

**Comment by ElijahAhianyo** [comment]
Hi @dapomeranz thanks for pointing this out. We do have plans of fully migrating to Ruff at some point. The team is currently focused on other high-priority issues at the moment. However, we're open to receiving a PR regarding this from the community.

**Comment by dapomeranz** [comment]
Noting that there is a related PR #2837 
Relevant Discord Conversation:
https://discord.com/channels/1029853095527727165/1061493979889278986/1222242970691174462
