### ISSUE TITLE
rx.input raise error in number type

### ISSUE THREAD

**Issue by panxiaoguang** [reflex-dev/reflex#2942]
**Describe the bug**
when using `type="number"` in `rx.input`, if the value is a class of int, it will raise an error:"TypeError: Invalid var passed for prop value, expected type <class 'str'>, got value steps of type <class 'int'>."

**To Reproduce**

```python
class Paint(rx.State):
    CFG_scale: int = 7
    ......

def index():
    ......
    rx.input(type="number",
             value=Paint.CFG_scale,
             on_change=Paint.set_CFG_scale,
                ),
```

**Expected behavior**
no error

**Comment by masenf** [comment]
even for a number input the value is still a `str` type, due to browser reasons.

you can cast it via `value=Paint.CFG_scale.to(str)`, but you'll also have to cast it back in your `set_CFG_scale`

```python
def set_CFG_scale(self, value: str):
    try:
        self.CFG_scale = int(value)
    except ValueError:
        print(f"{value} was not parsable as an int, ignored")
```

**Comment by panxiaoguang** [comment]
ok, I see
