### ISSUE TITLE
custom_attrs not forwarded to rx.select()

### ISSUE THREAD

**Issue by straygar** [reflex-dev/reflex#2947]
**Describe the bug**
As the title says - custom_attrs not forwarded to rx.select().

**To Reproduce**
```
rx.select(['a', 'b'], custom_attrs={'data-testid': 'foo'})
```

**Expected behavior**
The top-level HTML element (the trigger button) to have the prop `data-testid="foo"`. However, this is not forwarded

**Screenshots**

**Specifics (please complete the following information):**
 - Python Version: 3.10
 - Reflex Version: 0.4.5
 - OS: MacOS
 - Browser (Optional): Firefox/Chrome
 
**Additional context**

I suspect that this is because we're passing the prop to an unrendered `RadixThemesSelect.Root` radix element, so it never ends up on the dom. In my case, putting the prop on the trigger instead would solve the issue, but I don't know enough about Radix UI to be certain.

**Comment by masenf** [comment]
i think adding `custom_attrs` to the list of trigger props should suffice:

https://github.com/reflex-dev/reflex/blob/c9e87d70dfe13ec99c60cc39706187550a287d1e/reflex/components/radix/themes/components/select.py#L209

**Comment by SwarajBaral** [comment]
I would like to take it up. So the only change that this ticket requires is this ?
```python3
for prop in ["placeholder", "variant", "radius", "width", "flex_shrink", "custom_attrs"]
```

**Comment by picklelo** [comment]
@SwarajBaral yes I think that should work. We can validate by checking if in the final HTML that attributes are being passed through.
