### ISSUE TITLE
Shadow isn't working on rx.box

### ISSUE THREAD

**Issue by jq6l43d1** [reflex-dev/reflex#2956]
**Describe the bug**
Shadow isn't working on rx.box. It does work on rx.chakra.box.

**To Reproduce**
```
import reflex as rx

BOX_SHADOW = "0px 10px 20px 0px rgba(0, 0, 0, 0.45)"

def index() -> rx.Component:
    return rx.center(
        rx.hstack(
            rx.chakra.box(
                "Chakra",
                width="200px",
                height="200px",
                bg="lightblue",
                shadow=BOX_SHADOW,
            ),
            rx.box(
                "Radix",
                width="200px",
                height="200px",
                bg="lightblue",
                shadow=BOX_SHADOW,
            ),
            gap="50px",
        ),
        height="100vh",
    )

app = rx.App()
app.add_page(index)
```

**Expected behavior**
There should be a shadow like there is when rx.chakra.box is used.

**Screenshots**
![image](https://github.com/reflex-dev/reflex/assets/110377310/8a82f96e-d39e-4b96-bed2-725968f044e5)

**Specifics (please complete the following information):**
 - Python Version: 3.11.6
 - Reflex Version: 0.4.5

**Comment by picklelo** [comment]
Seems like this was a chakra-specific prop (we could bring it back as an alias if people like).

From 0.4.0 you can specify the `box_shadow` prop:

```python
 rx.box(
    "Radix",
    width="200px",
    height="200px",
    bg="lightblue",
    box_shadow=BOX_SHADOW,
),
```
