### ISSUE TITLE
error: ConnectionRefused downloading package manifest silly

### ISSUE THREAD

**Issue by vincentf123** [reflex-dev/reflex#2960]
**Describe the bug**
error while running `reflex run --loglevel debug`

**To Reproduce**
`reflex run --loglevel debug`

**Expected behavior**
command runs without error

**Screenshots**
![image](https://github.com/reflex-dev/reflex/assets/147273663/41554f1a-ee76-4965-a31d-bf65abb847c5)

**Specifics (please complete the following information):**
 - Python Version: Python 3.11.2 (main, Mar  2 2024, 20:28:50) [GCC 12.2.0] on linux
 - Reflex Version: 0.4.5
 - OS: Parrot OS 6

**Comment by picklelo** [comment]
@vincentf123 if you retry it does it work? Or does it happen consistently?

**Comment by vincentf123** [comment]
It happens consistently.

**Comment by picklelo** [comment]
@vincentf123 This may be coming from one of our dependencies `bun`,  this thread has some discussion with potential solutions: https://github.com/oven-sh/bun/issues/4988

**Comment by ElijahAhianyo** [comment]
> @vincentf123 This may be coming from one of our dependencies `bun`, this thread has some discussion with potential solutions: [oven-sh/bun#4988](https://github.com/oven-sh/bun/issues/4988)

@vincentf123, did disabling ipv6 as a workaround in the thread  here work for you?

**Comment by vincentf123** [comment]
Yes with disabled IPv6 it works.
