### ISSUE TITLE
Reflex deployment cannot connect to server

### ISSUE THREAD

**Issue by dwhdai** [reflex-dev/reflex#2968]
**Describe the bug**
When trying to deploy the starter app (created using `reflex init`, tested that `reflex run` works properly) using `reflex deploy`, I'm getting this error that indicates a backend issue.
<img width="740" alt="image" src="https://github.com/reflex-dev/reflex/assets/16040965/38bf9af9-7f4d-474f-8384-17ab0f46faba">

The logs don't show any obvious error, besides a warning about Node binary. 
<img width="1123" alt="image" src="https://github.com/reflex-dev/reflex/assets/16040965/ed1dfc23-c9ab-402e-b3fe-4bbcb83f51cb">

The link to the failing deployment is https://scrutineer.reflex.run

**To Reproduce**
- install reflex==0.4.5
- initialize blank app using `reflex init`
- test that `reflex run` works properly locally
- use `reflex deploy` to deploy app

**Expected behavior**
App should be deployed and behave similarly as when running locally

**Screenshots**

**Specifics (please complete the following information):**
 - Python Version: 3.11.4
 - Reflex Version: 0.4.5
 - OS: MacOS Sonoma 14.0
 - Browser (Optional): Brave
 
**Additional context**

**Comment by dwhdai** [comment]
think there was something wrong with my python installation. recreated poetry environment and is working now!

**Comment by GilbertoAguirre243** [comment]
how do you resolved the fail? i have the same error
