### ISSUE TITLE
rx.upload failed to upload files with size larger than about 5 MB

### ISSUE THREAD

**Issue by simechnet** [reflex-dev/reflex#2973]
I am not sure this is a bug.

I copied the code from the example of rx.upload in the [reflex doc](https://reflex.dev/docs/library/forms/upload#upload) into my project in order to upload some images. It always uploads successfully when the file size < 1 MB, but failed sometimes when the file size is between 1MB and 5MB, and always failed when the file size > 5MB. 

Whenever I clicked the "Upload" button, the whole page will automatically reloads again. When it is failed, no image file is uploded to the upload_dir, but rx.selected_files() returns the correct file names.

I encounted the problem with reflex 0.4.3, python 3.11 at the dev mode in a docker container. Then I updaged reflex to 0.4.5, but it behaviors the same.

I thought it might due to the upload limitation of the Nginx config, so I add `client_max_body_size 100M;` to the configuration, but the the problem still exists.

so, does anyone encounted the same problem, and how can I resolve it?

**Comment by masenf** [comment]
If you have your upload button inside of an `rx.form`, try adding `type="button"`. Your button might be triggering submit logic which redirects the page and inadvertently cancels the upload.

Anecdotally, i've been able to upload files larger than 70mb with the sample code in the docs.

**Comment by simechnet** [comment]
> If you have your upload button inside of an `rx.form`, try adding `type="button"`. Your button might be triggering submit logic which redirects the page and inadvertently cancels the upload.
> 
> Anecdotally, i've been able to upload files larger than 70mb with the sample code in the docs.

thanks, you saved my life, it works with adding `type="button"`.
