### ISSUE TITLE
[REF-2647] Toast Reflex component! (Sonner)

### ISSUE THREAD

**Issue by ema11412** [reflex-dev/reflex#2981]
The creation of a Toast in reflex would be very useful.

for example

```python

def toast() -> rx.Component:
    """The toast component."""
    return rx.toast(
        tile="Hello, world!",
        status="success",
        duration=5000,
        is_open=State.toast_open,
        position="top-right",
        onClose=State.close_toast,
    )
```

Ref:

* [Chakra](https://chakra-ui.com/docs/components/toast)
* [Tailwind](https://flowbite.com/docs/components/toast/)
* [Radix](https://www.radix-ui.com/primitives/docs/components/toast)

PR : [https://github.com/reflex-dev/reflex/pull/3186](https://github.com/reflex-dev/reflex/pull/3186)

<sub>From [SyncLinear.com](https://synclinear.com) | [REF-2647](https://linear.app/reflex-dev/issue/REF-2647/toast-reflex-component-sonner)</sub>

**Comment by carlosabadia** [comment]
I also suggest [Sonner](https://sonner.emilkowal.ski/) :)

**Comment by masenf** [comment]
i think rather than having the toast declarative, we would probably implement it as an event that you could return from a backend event handler or in response to an event trigger.

```python
rx.button(
    "Toast 🍸",
    on_click=rx.toast(
        tile="Hello, world!",
        status="success",
        duration=5000,
        position="top-right",
        onClose=State.close_toast,
    )
)
```

**Comment by picklelo** [comment]
@masenf Agreed, it serves a similar functionality to `rx.window_alert`

**Comment by Lendemor** [comment]
> I also suggest [Sonner](https://sonner.emilkowal.ski/) :)

Chance are high that we will go with the one from Radix since this it the lib we use as our core one.

Feel free to try wrapping the Sonner one as a 3rd party if you want to.
