### ISSUE TITLE
[REF-2587] Dark/light mode doesnt toggle with overlay component when `appearance`prop is set in `rx.theme` on app level with `rx.color_mode`

### ISSUE THREAD

**Issue by tgberkeley** [reflex-dev/reflex#2992]
**Describe the bug**
Dialog is still in light mode even though the app is now in dark mode

**To Reproduce**
Add an overlay component, in this case an `rx.dialog` to your app and then turn the app into dark mode using an `rx.color_mode.switch`

**Expected behavior**
The dialog would also go to dark mode like the rest of the app

**Screenshots**

![318982332-54afa697-2ec2-4369-a64a-b6a40bd611f9](https://uploads.linear.app/9513bc1c-787d-499b-8c86-46952ab7013c/7ad2b697-12f4-4059-8d63-9195800adcd6/15569dfc-1b15-4844-980b-be188ee16130?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzk1MTNiYzFjLTc4N2QtNDk5Yi04Yzg2LTQ2OTUyYWI3MDEzYy83YWQyYjY5Ny0xMmY0LTQwNTktOGQ2My05MTk1ODAwYWRjZDYvMTU1NjlkZmMtMWIxNS00ODQ0LTk4MGItYmUxODhlZTE2MTMwIiwiaWF0IjoxNzEzMjg4NTI1LCJleHAiOjE3MTMzNzQ5MjV9.R9s6gTTyIhWbN19CmohNRqF7HYjtdfG8rkWr_x4-NUM)

<sub>From [SyncLinear.com](https://synclinear.com) | [REF-2587](https://linear.app/reflex-dev/issue/REF-2587/dialog-is-still-in-light-mode-even-though-the-app-is-now-in-dark-mode)</sub>

**Comment by carlosabadia** [comment]
It seems like this issue also applies to the `rx.drawer` component

**Comment by ElijahAhianyo** [comment]
There's definitely something weird going on with dialog component when appearance is set in `rx.theme`
Minimal repro code:

```python
def index() -> rx.Component:
    return rx.box(
        rx.color_mode.button(rx.color_mode.icon(), size="3", float="right"),
        rx.dialog.root(
            rx.dialog.trigger(rx.button("Open Dialog")),
            rx.dialog.content(
                rx.dialog.title("Welcome to Reflex!"),
                rx.dialog.description(
                    "This is a dialog component. You can render anything you want in here.",
                ),
                rx.dialog.close(
                    rx.button("Close Dialog", size="3"),
                ),
            ),
        ),
        font_family="Inter",
    )


app = rx.App(
    theme=rx.theme(
        appearance="dark", # or appearance='light'
    ),
)
```

If you don't set the appearance, it works normally as expected

**Comment by ElijahAhianyo** [comment]
Can also confirm this behavior happens with all overlay components:

https://reflex.dev/docs/library/overlay/alertdialog/
[Contextmenu](https://reflex.dev/docs/library/overlay/contextmenu/)
[Dialog](https://reflex.dev/docs/library/overlay/dialog/)
[Drawer](https://reflex.dev/docs/library/overlay/drawer/)
[Dropdownmenu](https://reflex.dev/docs/library/overlay/dropdownmenu/)
[Hovercard](https://reflex.dev/docs/library/overlay/hovercard/)
[Popover](https://reflex.dev/docs/library/overlay/popover/)
[Tooltip](https://reflex.dev/docs/library/overlay/tooltip/)
