### ISSUE TITLE
Issue with reflex.dev documentation

### ISSUE THREAD

**Issue by eharvey71** [reflex-dev/reflex#3009]
Path: /docs/tutorial/final-app
The code in the completed app is different from the tutorial code, please correct for consistency.
Make sure you include something about storing the environment variable when using the OpenAI API key. Noobs may not know.

**Comment by Tednoob17** [comment]
Please are you sure with the path that you provide ?

**Comment by mohammed-anwar404** [comment]
Hey there, 
I would like to take up this issue as it is my first time contributing to Open Source on Hacktoberfest. 
Please guide me.

**Comment by picklelo** [comment]
@mohammed-anwar404 just assigned you! Our docs are here in the reflex-web repo: https://github.com/reflex-dev/reflex-web/tree/main/docs/tutorial

The files you need to update should all be in there. Let us know if you have issues!

**Comment by mohammed-anwar404** [comment]
Thanks, Pickleko, I will work on this and if I get stuck anywhere, I will contact you regarding that.

**Comment by picklelo** [comment]
@mohammed-anwar404 we just merged https://github.com/reflex-dev/reflex-web/pull/992 which resolves this issue. We can help you find another ticket to work on!

**Comment by mohammed-anwar404** [comment]
@picklelo its ok, Please help me find another ticket to work on which is a good first one to get started with.
