### ISSUE TITLE
Incorrect formatting of warning about component prop formats

### ISSUE THREAD

**Issue by Sprocketer** [reflex-dev/reflex#3024]
**Describe the bug**
Incorrect formatting of warning about component prop formats - see below

**To Reproduce - see the following `main.py`:**\

```
"""Main page."""

from rxconfig import config

import reflex as rx

DOCS_URL = ""
APP_NAME = config.app_name.title()


class State(rx.State):
    """The app state."""


def index() -> rx.Component:
    return rx.container(
        rx.box(
            rx.heading(
                f"Welcome to {APP_NAME}.",
                size=9
                ),
            )
        )


app = rx.App()
app.add_page(index)
```

The error is that the `size` argument for `heading` should be a string (for whatever reason somebody decided to make it that way when all the options are integers but just configured as strings???), but it has been passed as an integer

The error message however is a bit poor as it does not at all make it clear that the wrong type has been passed.

```
...
ValueError: prop value for size of the `Heading` component should be one of the following: '1','2','3','4','5','6','7','8','9'. Got '9' instead
```

**Expected behavior**

Some sort of error message which also relates to types when an int (or not string for that matter) is passed

**Screenshots**
N/A - just run the code

**Specifics (please complete the following information):**
 - Python Version: 3.10.13
 - Reflex Version: 0.4.6
 - OS: Linux (GH Codespaces) - not relevant however
 - Browser (Optional): Firefox - also not relevant

**Comment by Alek99** [comment]
this was something we have seen before. Under the hood this react component actually takes in a value 1-9 as a string (I know kind of odd). We can switch it to accept a literal 1-9 in the future can cast it to a string internally.

**Comment by Sprocketer** [comment]
> this was something we have seen before. Under the hood this react component and a few others actually takes in a value 1-9 as a string (I know kind of odd). We can switch it to accept a literal 1-9 in the future can cast it to a string internally.

@Alek99 agreed - but the main issue for now is that the error message doesn't differentiate how an integer was entered but a string is needed, and without intellisense or knowing how to peer into the definition I wouldn't be able to quickly solve that - so others may have this issue and not know how to solve it
Easiest way to fix it is probably to check `isinstance(str)` in the `rx.heading()` code for the `size` argument

**Comment by ElijahAhianyo** [comment]
> > this was something we have seen before. Under the hood this react component and a few others actually takes in a value 1-9 as a string (I know kind of odd). We can switch it to accept a literal 1-9 in the future can cast it to a string internally.
> 
> @Alek99 agreed - but the main issue for now is that the error message doesn't differentiate how an integer was entered but a string is needed, and without intellisense or knowing how to peer into the definition I wouldn't be able to quickly solve that - so others may have this issue and not know how to solve it Easiest way to fix it is probably to check `isinstance(str)` in the `rx.heading()` code for the `size` argument

Thanks for reporting this. I believe this should indeed be an easy fix. Will put in a PR for that.
