### ISSUE TITLE
Ctrl-C on windows does not disappear Theme Panel

### ISSUE THREAD

**Issue by JunhaoWang** [reflex-dev/reflex#3040]
**Describe the bug**
Ctrl-C on windows does not disappear Theme Panel

**To Reproduce**
reflex init && reflex run on windows WSL2 linux, then open the link in browser and press ctrl-C would not disappear the theme panel

**Expected behavior**
Ctrl-C should disappear the theme panel.

**Specifics (please complete the following information):**
 - Python Version: 3.10.12
 - Reflex Version: 0.4.6
 - OS: Windows WSL2 Ubuntu 22.04.3
 - Browser (Optional): Chrome

**Comment by Lendemor** [comment]
Shortcut for the theme panel change to `T` in Radix `3.0`.

We will only upgrade to that version of Radix once we move to reflex `0.5.0` because this upgrade lead to breaking changes.
But hopefully this don't take too long.
