### ISSUE TITLE
Issue with f-string

### ISSUE THREAD

**Issue by tgberkeley** [reflex-dev/reflex#3045]
Get a JS error when try to run code:
`rx.code_block(f"{category["name"]}", can_copy=True, language="python")`

error:
```
./pages/docs/gallery.js
Error: 
  x Expected unicode escape
     ,-[/Users/tomgotsman/projects/reflex/examples/reflex-web/.web/pages/docs/gallery.js:101:1]
 101 |   <Spacer/>
 102 |   <Box sx={{"position": "relative"}}>
 103 |   <SyntaxHighlighter customStyle={{"padding": "1em 3.2em 1em 1em"}} language={`python`} style={isTrue(((colorMode) === (`light`))) ? oneLight : oneDark} children={`${category["name"]}`}/>
 104 |   <Button onClick={(_e) => addEvents([Event("_set_clipboard", {content:`${category[\"name\"]}`})], (_e), {})} sx={{"position": "absolute", "top": "0.5em", "right": "0"}}>
     :                                                                                    ^
 105 |   <CopyIcon/>
 106 | </Button>
 107 | </Box>
     `----
```

**Comment by wassafshahzad** [comment]
Could you please share the complete reproducible  example

**Comment by Sprocketer** [comment]
@tgberkeley What version of python are you using? I know using the same types of quotes twice within an f-string (once for defining it, another for some sort of operation inside) was only recently added in 3.12. Using 3.12 this works for me. If you want to use a lesser version, you'd need to use single quotes inside the f-string, or a variable with whatever expression you need and just pass that into the f-string.

**Comment by ElijahAhianyo** [comment]
Looks like a reproducible code I could try is below:

```python

def index() -> rx.Component:
    category = {"name": "random"}
    cat = rx.Var.create(category, _var_is_string=True)
    return rx.center(
        rx.code_block(f'{category["name"]}', can_copy=True, language="python"),
        rx.button("copy", on_click=rx.set_clipboard(f'{cat["name"]}')),
        height="100vh",
    )
```
But this is by syntax is wrong, `category` is a dict and the only way this error shows up is if it is created as a `var` with the `_var_is_string` set to `True` which shouldn't be the case
