### ISSUE TITLE
Display the "Connection Error" Message at a proper time

### ISSUE THREAD

**Issue by simechnet** [reflex-dev/reflex#3059]
Everytime I open the reflex home page, it displays the "Connection Error" message (as shown in the image) and disappears when the page is fully loaded. 
I know it is not a bug, it is due to the lag response of the backend service and slow network. I think it would be better to delay the check of the backend service, so the "Error" message will not show immediately when the frontend page is loading. 

![](https://github.com/reflex-dev/reflex/assets/16507701/5add826f-5566-4b30-9020-839200b2d0ba)

**Comment by picklelo** [comment]
Thanks for raising, this is resolved in the recent release. We will redeploy the website this week and this shouldn't happen anymore.
