### ISSUE TITLE
Issue with reflex.dev documentation

### ISSUE THREAD

**Issue by yashr42** [reflex-dev/reflex#3085]
Path: /docs/library/forms/input

`rx.input(
type="number"
)
`
This option is accepting symbols while it should only be limited to numbers

**Comment by Yummy-Yums** [comment]
@yashr42 I just tried on my end and the only symbol it accepts is the `+` symbol which is useful for adding telephone numbers i.e. with the country code

**Comment by yashr42** [comment]
@Yummy-Yums  - It was accepting hypen (-) as well for me. I was working on something related to phone number input only and noticed it.

**Comment by yashr42** [comment]
There should be a different type for phone numbers like type="telephone"  and type="number"  should only accept numbers. Atleast that's my thought.
