### ISSUE TITLE
[REF-2588] Reflex should clear color cookie

### ISSUE THREAD

**Issue by Alek99** [reflex-dev/reflex#3087]
**Describe the bug**

Right now if you manually edit the cookie in the browser when doing reflex run again the chakra-ui-color-mode cookie does not change. 

**To Reproduce**

Change the cookie in your browser to light/dark and re run the app where your appearance is the opposite in your rx.theme

**Expected behavior**

In development mode should match the appearance  prop in the theme

<sub>[REF-2588](https://linear.app/reflex-dev/issue/REF-2588/reflex-should-clear-color-cookie)</sub>

**Comment by picklelo** [comment]
@ThomasRooney good point. I think we may need to combine this with the change to maintain state between hot reloads and  tie the color mode to the state.

**Comment by masenf** [comment]
Some prior art https://github.com/reflex-dev/reflex/blob/44ad9a73119b5c028f72bde97f61cd2e8dfdd89f/reflex/components/radix/themes/base.py#L260-L272

But i do actually wonder how necessary this ticket is overall.

**Comment by Lendemor** [comment]
Ok I actually see why we need it, I think clearing the value set with color_mode.toggle during dev is fine.

We currently have `"system"` as the default, but if dev want to enforce `appearance="light"` or `appearance="dark"` they have to open the reflex app in incognito tab, which is simple fix but shouldn't be necessary to dev.

Related discord discussion: https://discord.com/channels/1029853095527727165/1252028062757945344

**Comment by Lendemor** [comment]
Ok I actually see why we need it, I think clearing the value set with `color_mode.toggle` during dev is fine.
We currently have "system" as the default, but if dev want to enforce `appearance="light"` or `appearance="dark"` they have to open the website in incognito tab, which is simple fix but shouldn't be necessary to dev.
Related discord discussion: [https://discord.com/channels/1029853095527727165/1252028062757945344](https://discord.com/channels/1029853095527727165/1252028062757945344)
