### ISSUE TITLE
[REF-2589] UnicodeDecodeError occurs after updating to 0.4.8

### ISSUE THREAD

**Issue by Evenzel** [reflex-dev/reflex#3094]
**Describe the bug**
UnicodeDecodeError occurs after updating to 0.4.8

**To Reproduce**
Just execute reflex run

**Expected behavior**

**Screenshots**

![image](https://uploads.linear.app/9513bc1c-787d-499b-8c86-46952ab7013c/629092a8-e5ef-4072-aae9-c258ca955472/0c19f278-0178-4e3f-8f82-34adaacc77a8?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzk1MTNiYzFjLTc4N2QtNDk5Yi04Yzg2LTQ2OTUyYWI3MDEzYy82MjkwOTJhOC1lNWVmLTQwNzItYWFlOS1jMjU4Y2E5NTU0NzIvMGMxOWYyNzgtMDE3OC00ZTNmLThmODItMzRhZGFhY2M3N2E4IiwiaWF0IjoxNzEzMjg5MjU4LCJleHAiOjE3MTMzNzU2NTh9.prrpOjayTZBBkOFFW5oRvb8mjGU7DO_NKsCoglyY8CQ)

**Specifics (please complete the following information):**

* Python Version: 3.11.4
* Reflex Version: 0.4.8
* OS: Windows 10
* Browser (Optional): Chrome

**Additional context**

<sub>From [SyncLinear.com](https://synclinear.com) | [REF-2589](https://linear.app/reflex-dev/issue/REF-2589/unicodedecodeerror-occurs-after-updating-to-048)</sub>

**Comment by ElijahAhianyo** [comment]
Is this on a new or existing project?

**Comment by Evenzel** [comment]
existing project!

**Comment by masenf** [comment]
I posted a PR with a workaround for this, to basically ignore the non-decodable characters
