### ISSUE TITLE
reflex run solution please

### ISSUE THREAD

**Issue by m4teoarg** [reflex-dev/reflex#3095]
**Describe the bug**
archlinux
compiling
Installing base frontend packages failed with exit code -4
Run with --loglevel debug  for the full log.

**Screenshots**
![reflex1](https://github.com/reflex-dev/reflex/assets/140857022/cea26b42-2a72-4a95-98e0-61f592fa8a14)

**Specifics (please complete the following information):**
 - Python Version: Python 3.11.8
 - Reflex Version: 0.4.8
 - OS: archlinux
 - Browser (Optional):

**Comment by masenf** [comment]
Is it working in version 0.4.7?

**Comment by m4teoarg** [comment]
![KOLORO_1713352915991](https://github.com/reflex-dev/reflex/assets/140857022/bbc771b8-a185-4389-bda5-b6192f177ebc)

version 0.4.7 ?

**Comment by ElijahAhianyo** [comment]
> > Is it working in version 0.4.7?
> 
> How do I use version 0.4.7?

```shell
> pip uninstall reflex
> pip install reflex==0.4.7
```

**Comment by m4teoarg** [comment]
it does not work

![Uploading reflex4.png…]()
