### ISSUE TITLE
[REF-2602] if rxconfig.py is not importable reflex fails

### ISSUE THREAD

**Issue by masenf** [reflex-dev/reflex#3106]
Try to import a non-existant module in [rxconfig.py](http://rxconfig.py) and it will say

```
RuntimeError: Cannot get the app module because `app_name` is not set in rxconfig! If this error occurs in a reflex test case, ensure that `get_app` is mocked.
```

Instead of showing the ImportError. This is basically un-debuggable

* If no config, tell them to init (should already be working)
* need to catch on the `get_config` line and raise those exceptions

<sub>From [SyncLinear.com](https://synclinear.com) | [REF-2602](https://linear.app/reflex-dev/issue/REF-2602/if-rxconfigpy-is-not-importable-reflex-fails)</sub>

**Comment by jod35** [comment]
Facing the same issue with Reflex version 0.4.9
