### ISSUE TITLE
Issue with reflex.dev documentation

### ISSUE THREAD

**Issue by angelmre** [reflex-dev/reflex#3122]
Path: /docs/library/forms/upload

```
rx.upload(
    rx.text(
        "Drag and drop files here or click to select files"
    ),
    id="my_upload",
    border="1px dotted rgb(107,99,246)",
    padding="5em",
)
```

The code is wrong it should be:

`border=f"1px dotted rgb(107,99,246)",`

Thank you

**Comment by masenf** [comment]
what is the difference? i don't see any format specifiers in the string so why does it have to be an f-string?

**Comment by angelmre** [comment]
Without the f-string it doesn't work with the f-string it does work.

**Comment by ElijahAhianyo** [comment]
> Without the f-string it doesn't work with the f-string it does work in windows.

when you say it doesn't work, is there a specific error message or unexpected behavior you can point out or share?

**Comment by angelmre** [comment]
I have not been able to reproduce the error again.

When I wrote the original code that was my solution and it worked in my code but now I remove the f-string and it works the same.

I'm sorry for the inconvenience caused

**Comment by picklelo** [comment]
no worries, closing this issue now
