### ISSUE TITLE
[REF-2626] reflex init generates incorrect reflex version in requirements.txt  

### ISSUE THREAD

**Issue by camstuart** [reflex-dev/reflex#3124]
**Describe the bug**
When generating a brand new reflex project with `init` the incorrect reflex version is added to the generated requirements.txt file

**To Reproduce**
```
python -m venv .venv
source .venv/bin/activate
pip install reflex
reflex init
cat requirements.txt # reflex==0.4.5
reflex -v # 0.4.8.post1
```

**Expected behavior**
The output of `reflex -v` should match the version specified in `requirements.txt`

**Specifics (please complete the following information):**
 - Python Version: 3.12.2 (via pyenv)
 - PIP Version: 24.0
 - Reflex Version: 0.4.8.post1
 - OS: Mac 14.4.1
 - Browser (Optional): N/A
 

<sub>[REF-2626](https://linear.app/reflex-dev/issue/REF-2626/reflex-init-generates-incorrect-reflex-version-in-requirementstxt)</sub>

**Comment by ElijahAhianyo** [comment]
@camstuart can you provide more info on how to repro this? I just tried your repro steps and the reflex version was the same as it was in the requirements. Also looking at the code, we seem to get the reflex version from the current interpreter(which should be the activated venv). The only scenario this differs for me is if you run reflex init on an existing project which doesn't rewrite the requirements file. Is this case you're describing?
