### ISSUE TITLE
Issue with reflex.dev documentation - The code in the example on the page and the code in the generated app are different

### ISSUE THREAD

**Issue by jdrumgoole** [reflex-dev/reflex#3129]
Path: /docs/tutorial/frontend

The code in the generated app

```
from rxconfig import config

import reflex as rx

docs_url = "https://reflex.dev/docs/getting-started/introduction/"
filename = f"{config.app_name}/{config.app_name}.py"


class State(rx.State):
    """The app state."""


def index() -> rx.Component:
    return rx.center(
        rx.theme_panel(),
        rx.vstack(
            rx.heading("Welcome to Reflex!", size="9"),
            rx.text("Get started by editing ", rx.code(filename)),
            rx.button(
                "Check out our docs!",
                on_click=lambda: rx.redirect(docs_url),
                size="4",
            ),
            rx.logo(),
            align="center",
            spacing="7",
            font_size="2em",
        ),
        height="100vh",
    )


app = rx.App()
app.add_page(index)
```

Doesn't match what is on the page in the docs.

**Comment by ElijahAhianyo** [comment]
@jdrumgoole The code on the page you referenced is a tutorial on creating a chat app. I am confused what part of the [docs](https://reflex.dev/docs/tutorial/frontend/) has a different code than what is expected. As far as I can tell, the code above is that of when you select the blank template after running `reflex init`

**Comment by mohammed-anwar404** [comment]
Hello, I am Anwar participating in this Hacktoberfest, I have been following the issues on the Reflex GitHub page for contributions.
@jdrumgoole I just wanted to know which part of the docs has that code. 

Paths to check:
1. https://reflex.dev/docs/tutorial/frontend/
2. https://reflex.dev/docs/getting-started/introduction/

both of these links don't have any code as mentioned above. 

@elviskahoro I Just wanted to know if anything needs to be done to close this issue, I would like to contribute to this.

**Comment by elviskahoro** [comment]
@mohammed-anwar404 let's just close this. I think it's a stale issue!
