### ISSUE TITLE
[REF-2629] Bun on windows requires Visual C++ Redistributables

### ISSUE THREAD

**Issue by masenf** [reflex-dev/reflex#3139]
**Describe the bug**
On a fresh windows install: The code execution cannot proceed because MSVCP140.dll was not found.

**👉 Need to install:** [Microsoft Visual C++ 2015 Redistributable Update 3](https://www.microsoft.com/en-us/download/details.aspx?id=53840)

**To Reproduce**

* Create a new "Windows (Windows Server 2022 Datacenter Azure Edition)" VM on Azure.
* Install python 3.12
* Install reflex 0.4.9a2
* Init a new project
* `reflex run`

**Expected behavior**
Bun should install the requested packages. Instead it fails (and without #3138 does not fallback to npm)

**Screenshots**

![image](https://uploads.linear.app/9513bc1c-787d-499b-8c86-46952ab7013c/39139d62-e1a2-485e-9892-45676dbafe57/59bbf38b-7f35-4541-815a-b6682dcd0793?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzk1MTNiYzFjLTc4N2QtNDk5Yi04Yzg2LTQ2OTUyYWI3MDEzYy8zOTEzOWQ2Mi1lMWEyLTQ4NWUtOTg5Mi00NTY3NmRiYWZlNTcvNTliYmYzOGItN2YzNS00NTQxLTgxNWEtYjY2ODJkY2QwNzkzIiwiaWF0IjoxNzEzODE0Mzk3LCJleHAiOjE3MTM5MDA3OTd9.LEt4w89z8B-rZ3ebojEvIO5V4Fm7HtF1531b24yoEhA)

**Specifics (please complete the following information):**

* Python Version: 3.12.3
* Reflex Version: 0.4.9a2
* OS: Windows Server 2022 Datacenter Azure Edition (x64)
* Browser (Optional):

<sub>From [SyncLinear.com](https://synclinear.com) | [REF-2629](https://linear.app/reflex-dev/issue/REF-2629/bun-on-windows-requires-visual-c-redistributables)</sub>

**Comment by ElijahAhianyo** [comment]
Havent been able to repro this with latest bun `v1.1.6` on Server 2022 Datacenter Azure Edition. Perhaps the issue might have fixed upstream in the latest release

**Comment by ElijahAhianyo** [comment]
closing this for now

**Comment by masenf** [comment]
I'm still hitting this on Azure Windows 2022. Except instead of popping up the box, it just silently fails and falls back to npm

**Comment by masenf** [comment]
This is still an issue on a fresh install of Windows 10 22H2

**Comment by ElijahAhianyo** [comment]
can confirm this error now. Installing the visual C++ Redistributables(direct link: https://aka.ms/vs/17/release/vc_redist.x64.exe) makes the issue go away. Perhaps this should be a documentation issue
