### ISSUE TITLE
Shouldn't `App`'s `__init__()` method accept only keywords?

### ISSUE THREAD

**Issue by nautics889** [reflex-dev/reflex#3140]
**In short words**

`*args` in `App `class are not used anywhere, except passing it to base `__init__` (which in it's turns does not accept positional arguments)

**Describe the bug**

[Here in the `App` class](https://github.com/reflex-dev/reflex/blob/0a1ff389203a8eec9ef90e77703ca5b51414c290/reflex/app.py#L163), the `__init__()` method accepts an arbitrary positional argument and then [passes it to the base method](https://github.com/reflex-dev/reflex/blob/0a1ff389203a8eec9ef90e77703ca5b51414c290/reflex/app.py#L179). However, [`__init__()` of Pydantic's `BaseModel`](https://docs.pydantic.dev/latest/api/base_model/#pydantic.BaseModel.__init__) doesn't really accept any positional args (actually never has), only `**kwargs`. And I haven't seen any example where reflex `App` would be called with pos. args, so maybe it shouldn't be there.

Doesn't it make sense to remove passing positional args to the `App` class? It doesn't use them anywhere except pass it up to `super()`'s `__init__` (i. e. `BaseModel`).

**To Reproduce**

```python
>>> from reflex import App
>>> app = App('bar')
Traceback (most recent call last):
    ...
    super().__init__(*args, **kwargs)
TypeError: BaseModel.__init__() takes 1 positional argument but 2 were given
```

**Expected behavior**

An exception that it couldn't take pos. arguments is raised **from the `App` class**, not `BaseModel`.

**Specifics (please complete the following information):**
 - Python Version: 3.12 (doesn't really matter)
 - Reflex Version: v0.4.8.post1
 - OS: Win (doesn't really matter)

**Comment by picklelo** [comment]
Merged in #3141
