### ISSUE TITLE
[REF-2686] Access problem to reflex.dev page

### ISSUE THREAD

**Issue by angelmre** [reflex-dev/reflex#3154]
The main page is marked **_as “It is vulnerable to clickjacking attack_**” by the clickjacker.io page and that means that my company does not let me access it. Can you solve it? 

the errors that the page detects are:
- Missing header
- Missing anti-framing policy

Thank you

<sub>[REF-2686](https://linear.app/reflex-dev/issue/REF-2686/access-problem-to-reflexdev-page)</sub>

**Comment by martinxu9** [comment]
@angelmre thanks so much for reporting this issue to us. I've adjusted our CDN policy so at least it passes the security check on clickjacker.io. Please let us know if you can access our website now within your VPN.
