### ISSUE TITLE
Starting frontend failed with exit code 127

### ISSUE THREAD

**Issue by egonsung** [reflex-dev/reflex#3175]
I've recently updated Reflex to 0.4.9 and when I "reflex run" I come into the following error:

```Starting frontend failed with exit code 127

> dev
> next dev

sh: next: command not found
Run with --loglevel debug  for the full log.
```

When I run with "--loglevel debug", I get this:

```
─────────────────────────────────────────────────────────────────────────────────────────────────────────── App Running ───────────────────────────────────────────────────────────────────────────────────────────────────────────
Debug: Running command: ['/Users/**/Library/Application Support/reflex/fnm/node-versions/v18.17.0/installation/lib/node_modules/npm/bin/npm-cli.js', 'run', 'dev']
Debug: Starting frontend
Debug: 
Debug: > dev
Debug: > next dev
Debug: 
Debug: sh: next: command not found
```

Does anyone know how this is fixed? It was working before the update. Thanks.

**Comment by picklelo** [comment]
Could you try to delete your `.web` folder and try again? `rm -r .web` within your app folder.

**Comment by egonsung** [comment]
> Could you try to delete your `.web` folder and try again? `rm -r .web` within your app folder.

Oh wow that worked! Thanks a lot, I've been searching for a solution all day. Thanks again.
