### ISSUE TITLE
"reflex run" does not hot reload and ^C no longer stops it from running and freezes.

### ISSUE THREAD

**Issue by egonsung** [reflex-dev/reflex#3178]
I've recently come across [this issue](https://github.com/reflex-dev/reflex/issues/3175) and have it solved by removing .web and re-initiating "reflex init" and that has solved it. But, now I have another issue: in the terminal, it no longer recompiles and hot reloads when I make changes, and I cannot cancel it by ^C.

Also, now when I use " reflex run --loglevel", it gives me this error: 
`Error: Option '--loglevel' requires an argument.`

 - Python Version: 3.12.3
 - Reflex Version: 0.3.2
 - OS: MacOS 14.4.1 

Can anyone solve this issue? Thanks

**Comment by picklelo** [comment]
@egonsung You need to pass an option to log level. Try `reflex run --loglevel debug`. 

Are you still unable to stop your app with ctrl+c / seeing hot-reload issues? Is this using the default app?

**Comment by egonsung** [comment]
> @egonsung You need to pass an option to log level. Try `reflex run --loglevel debug`.
> 
> Are you still unable to stop your app with ctrl+c / seeing hot-reload issues? Is this using the default app?

@picklelo Yes, still unable to. I realized I left out "debug", and in the log, the only error is:
`error An unexpected error occurred: "EACCES: permission denied, open '/Users/*/.npmrc'".` 

The app does compile, but when I make changes, it doesn't recompile. I have created a completely separate app with the Reflex template just to test, and it's the same thing.

**Comment by picklelo** [comment]
Could you try this: `rm -r ~/Library/Application\ Support/reflex/ `. This is where Reflex downloads Node to, maybe something they're got messed up. After deleting try to recreate a project.

**Comment by egonsung** [comment]
@picklelo I followed your steps and its the same, even with a completely new project.

**Comment by egonsung** [comment]
@picklelo I have just fixed it. It was a version issue, I believe. I've updated Reflex to 0.4.9, and while working on it with PyCharm, a warning came up saying Reflex version mismatch and to install package. I mistakenly clicked install and it went back to Reflex 0.3.2, and that was the mistake. 

But thanks for the help anyways.
