### ISSUE TITLE
Charka Stepper in Codebase but not documented

### ISSUE THREAD

**Issue by sebastianjanisch** [reflex-dev/reflex#3182]
The chakra stepper component is implemented in reflex (and working, except for the step status icons) but not listed in the documentation.

https://github.com/reflex-dev/reflex/blob/main/reflex/components/chakra/navigation/stepper.py

**Comment by Spartan-71** [comment]
@sebastianjanisch could you please provide the updated documentation link , since the link which you have provided is not valid anymore.

**Comment by picklelo** [comment]
@Spartan-71 The chakra code has moved [here](https://github.com/reflex-dev/reflex-chakra) and this is the [new docs website](https://chakra.reflex.run/introduction/).

**Comment by Spartan-71** [comment]
Hey @elviskahoro I would like to work on this issue.

**Comment by elviskahoro** [comment]
> Hey @elviskahoro I would like to work on this issue.

CC @ElijahAhianyo Can you help scope out what all needs to be done for @Spartan-71

**Comment by Spartan-71** [comment]
In which section of the documentation should the **stepper** component be added ?

**Comment by Spartan-71** [comment]
Hey @picklelo kindly do check my PR : [Link](https://github.com/reflex-dev/reflex-chakra/pull/20)

I am open for changes, if any :)

**Comment by elviskahoro** [comment]
@Spartan-71 i will review this but we're blocked on a bug that I just opened a PR for. Once my PR gets merged I'll need you to rebase on main and then I can review.

See here:
https://github.com/reflex-dev/reflex-chakra/pull/23
