### ISSUE TITLE
rx.upload_files errors when selecting more than specified max_files

### ISSUE THREAD

**Issue by sebastianjanisch** [reflex-dev/reflex#3183]
**Describe the bug**
When passing the `max_files` argument to `rx.upload_files` and subsequently choosing more than the specified number of files in the file browser (or drag&drop) an exception is thrown.

```
Traceback (most recent call last):
  File "/Users/sjanisch/Work/projects/bayesline-projects/bayesline/code/app/reflexgui/.venv/lib/python3.11/site-packages/reflex/state.py", line 1507, in _process_event
    events = await fn(**payload)
                   ^^^^^^^^^^^^^
TypeError: BugState.handle_upload() missing 1 required positional argument: 'files'
```

**To Reproduce**
 - Code/Link to Repo:
https://gist.github.com/sebastianjanisch/3b467f4ba86c739d5d0ef8b449b05c84

**Expected behavior**
I would expect that I cannot select more than the specified number of files in the file browser. 
If that's not possible I would expect to be able to implement some logic to deal with this user input. 

**Screenshots**

**Specifics (please complete the following information):**
 - Python Version: 3.11
 - Reflex Version: 0.4.9
 - OS: 14.2.1 (23C71)
 - Browser (Optional): Chrome
 
**Additional context**

**Comment by masenf** [comment]
before a recent change, this would just be ignored in the frontend without any indication that the user has violated some limit.

to capture this case on the backend, you can add a default for the `files` argument and deduce that the upload was submitted, but no files were passed through either because none or too many were selected

```
class BugState(rx.State):
    def handle_upload(self, files: list[rx.UploadFiles] = []):
        if not files:
            # no files or too many files selected
            ...
```
