### ISSUE TITLE
tailwind.config.js: disabling tailwind's preflight

### ISSUE THREAD

**Issue by seewindcn** [reflex-dev/reflex#3185]
**Describe the bug**
about [tailwind preflight](https://tailwindcss.com/docs/preflight#disabling-preflight), it maybe conflict with other components, like ant-design.

**To Reproduce**
 - Code/Link to Repo:

**Expected behavior**
it can be disable by tailwind.config.js:
```
module.exports = {
  corePlugins: {
    preflight: false,
  }
}
```
**Screenshots**
![ant-design-button](https://p6-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/a97be8cb2c70468cbc74b4955849da56~tplv-k3u1fbpfcp-jj-mark:3024:0:0:0:q75.awebp#?w=3840&h=1628&s=119140&e=gif&f=48&b=f0f9ff)

**Specifics (please complete the following information):**
 - Python Version:
 - Reflex Version:
 - OS: 
 - Browser (Optional):
 
**Additional context**

**Comment by picklelo** [comment]
Do you want this disabled by default? For any specific app, you should be able to set this in your `rxconfig.py`:

```python
import reflex as rx


config = rx.Config(
    app_name="pcweb",
    tailwind={
        "module.exports": {
             "corePlugins": {
                  "preflight": False,
             }
       }
   }
)
```

**Comment by seewindcn** [comment]
yes, but your code doesn't work.
in reflex, web/tailwind.config.js.jinja2:
```
/** @type {import('tailwindcss').Config} */
module.exports = {
	content: {{content|json_dumps}},
	theme: {{theme|json_dumps}},
	plugins: [
	{% for plugin in plugins %}
		require({{plugin|json_dumps}}),
	{% endfor %}
	],
	{% if presets is defined %}
	presets: [
	{% for preset in presets %}
		require({{preset|json_dumps}})
	{% endfor %}
	],
	{% endif %}
	{% if darkMode is defined %}
	darkMode: {{darkMode|json_dumps}},
	{% endif %}
};

```
it do not handle the corePlugins.

**Comment by seewindcn** [comment]
@Alek99 is there any schedule to fix? or could I pull request to fix it?

**Comment by masenf** [comment]
@seewindcn no one on the team is currently working on this issue. 

But if you submit a PR, we will review it and help get it merged in.
