### ISSUE TITLE
Slicing Doesn't work on strings

### ISSUE THREAD

**Issue by Alek99** [reflex-dev/reflex#3187]
**Describe the bug**

```python 
rx.text(category["summary"][:20], size="2", color="#8E8EA8"),
```
![Screenshot 2024-04-29 at 2 48 38 PM](https://github.com/reflex-dev/reflex/assets/38776361/4033a825-985e-4a6e-86f1-9913233f6ed5)

Was trying to limit the description length in the gallery https://github.com/reflex-dev/reflex-web/blob/main/pcweb/pages/docs/gallery.py for more context

**Comment by picklelo** [comment]
Chatted offline - was an issue with the str being null
