### ISSUE TITLE
button event  ValueError: Lambda <function btnon_click at> returned an invalid event spec: True

### ISSUE THREAD

**Issue by NocoleNe** [reflex-dev/reflex#3265]
**Describe the bug**

**To Reproduce**
 - Code/Link to Repo:
 - `def btnon_click ( ):
    print ( "on   click " )
    return True

def index ( ):
    box = rx.button ( "return home" , on_click=btnon_click )
    return box

app = rx.App ( )
app.add_page ( index , route="/" )`

compile error:
 File "E:\dev4\reflextest\.venv\Lib\site-packages\reflex\event.py", line 827, in call_event_fn
    raise ValueError(f"Lambda {fn} returned an invalid event spec: {e}.")
ValueError: Lambda <function btnon_click at 0x000001B75D04D300> returned an invalid event spec: True.

**Expected behavior**

**Screenshots**

**Specifics (please complete the following information):**
 - Python Version:
 - Reflex Version:
 - OS: 
 - Browser (Optional):
 
**Additional context**

**Comment by masenf** [comment]
Event handlers need to be defined inside a subclass of `rx.State`

See https://reflex.dev/docs/state/overview/#example

**Comment by NocoleNe** [comment]
ok, thanks
