### ISSUE TITLE
[REF-2811] `rx.section` default size 3 is "too big"

### ISSUE THREAD

**Issue by masenf** [reflex-dev/reflex#3274]
**Describe the bug**
The nice thing about the `rx.section` (aside from being semantic) is that it adds healthy margins between page content areas... however the default `size="3"` is too much space and does not really look good.

I propose changing the default to `size="2"` so that downstream users don't need to change the not-great-looking default.

**Expected behavior**
The default should "look good"

**Screenshots**
Here is the default section spacing

![image](https://uploads.linear.app/9513bc1c-787d-499b-8c86-46952ab7013c/94160415-ca2c-4eb4-bfa3-6288941729dc/5e50429b-420c-4afe-8b2c-5adeb2870241?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzk1MTNiYzFjLTc4N2QtNDk5Yi04Yzg2LTQ2OTUyYWI3MDEzYy85NDE2MDQxNS1jYTJjLTRlYjQtYmZhMy02Mjg4OTQxNzI5ZGMvNWU1MDQyOWItNDIwYy00YWZlLThiMmMtNWFkZWIyODcwMjQxIiwiaWF0IjoxNzE1MzY2MzEwLCJleHAiOjE3NDY5MDIzMTB9.eYqy-slkWcdVXUlD-p2bfTNvkeS3cnp6q-EL8t7VnO8)

And with `size="2"`

![image](https://uploads.linear.app/9513bc1c-787d-499b-8c86-46952ab7013c/89d48e31-f9bc-41fe-bb35-8bc6d27944e6/1ff2e34d-c1a3-4f69-8691-5d816534ef0c?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzk1MTNiYzFjLTc4N2QtNDk5Yi04Yzg2LTQ2OTUyYWI3MDEzYy84OWQ0OGUzMS1mOWJjLTQxZmUtYmIzNS04YmM2ZDI3OTQ0ZTYvMWZmMmUzNGQtYzFhMy00ZjY5LTg2OTEtNWQ4MTY1MzRlZjBjIiwiaWF0IjoxNzE1MzY2MzEwLCJleHAiOjE3NDY5MDIzMTB9.yoIqP2m0jECkBt6cPsO7Jw6c5J4YW2_U2_tdHMu2gbs)

**Specifics (please complete the following information):**

* Python Version: 3.11.8
* Reflex Version: 0.5.0a1

<sub>From [SyncLinear.com](https://synclinear.com) | [REF-2811](https://linear.app/reflex-dev/issue/REF-2811/rxsection-default-size-3-is-too-big)</sub>

**Comment by kusumdesai** [comment]
Hey @masenf !!
Please assign this to me under GSSoC'24..

**Comment by masenf** [comment]
@kusumdesai check out how we override the size for the radix `Container` component for an example of how this is done.

**Comment by picklelo** [comment]
Merged in #3406
