### ISSUE TITLE
@rx.page doesn't work inside nested folders

### ISSUE THREAD

**Issue by iBuitron** [reflex-dev/reflex#3280]
Nested folders.

![image](https://github.com/reflex-dev/reflex/assets/102157308/3464349a-0ffb-4b58-a45e-59f688ea0928)

when i add the page using `page.add_page(...)` it works when visit `quickBio-home`
![image](https://github.com/reflex-dev/reflex/assets/102157308/8f45547c-c57f-4156-914f-4e774ebd58f5)

but when i use `@rx.page` and visit `/upload` doesn't work (404)
![image](https://github.com/reflex-dev/reflex/assets/102157308/2d5ccdf9-8e68-4766-be43-01eb4f071dc5)

**Specifics (please complete the following information):**
 - Python Version: 3.11
 - Reflex Version: 0.4.9
 - OS: WSL2 Ubuntu 22.04
 - Browser (Optional): Chrome

**Comment by ElijahAhianyo** [comment]
with `rx.page`, you'll need to import the `upload` function in your main file(`quickBio_frontend.py`) to be recognized

**Comment by iBuitron** [comment]
Nice! it works!,

I thought it was a bug, can it be added to the documentation?
https://reflex.dev/docs/pages/routes/
