### ISSUE TITLE
[REF-2824] rx.recharts.polar_radius_axis is missing the `domain` prop

### ISSUE THREAD

**Issue by masenf** [reflex-dev/reflex#3283]
**Describe the bug**
[A clear and concise description of what the bug is.](https://discord.com/channels/1029853095527727165/1076030848928858112/1238880497451667499)

**To Reproduce**
 - Code/Link to Repo:

**Expected behavior**

**Screenshots**

**Specifics (please complete the following information):**
 - Python Version:
 - Reflex Version:
 - OS: 
 - Browser (Optional):
 
**Additional context**

<sub>[REF-2824](https://linear.app/reflex-dev/issue/REF-2824/rxrechartspolar-radius-axis-is-missing-the-domain-prop)</sub>

**Comment by TG199** [comment]
Hi @masenf  I checked the link above that leads to the Discord channel. By my understanding, you've provided the solution of this issue there. The only thing missing to get this resolved is a PR. So I just need to add the following line `    custom_attrs=dict(domain=rx.Var.create([0, 250]))
` to the file `reflex./components/recharts/polar.py` in the component `PolarRadiusAxis(Recharts):`

**Comment by masenf** [comment]
@TG199 All that's needed here is a PR that adds `domain` as a `list[int]` prop to the `PolarRadiusAxis` component.

The `custom_attrs` thing is a hackaround for forcing an attribute to be rendered into the compiled output, even when it's not declared as a prop for the component.

**Comment by picklelo** [comment]
Merged in #3349
