### ISSUE TITLE
[REF-2825] Need a mechanism to catch unhandled errors from event handlers

### ISSUE THREAD

**Issue by masenf** [reflex-dev/reflex#3284]
**Describe the bug**
Currently reflex catches all unhandled exceptions and throws an rx.window_alert; this behavior is not customizable 😔

Related to [https://github.com/orgs/reflex-dev/discussions/2509](https://github.com/orgs/reflex-dev/discussions/2509)

<sub>From [SyncLinear.com](https://synclinear.com) | [REF-2825](https://linear.app/reflex-dev/issue/REF-2825/need-a-mechanism-to-catch-unhandled-errors-from-event-handlers)</sub>

**Comment by benedikt-bartscher** [comment]
related wip: https://github.com/benedikt-bartscher/reflex/pull/5

**Comment by TG199** [comment]
Hi @mansef I'd like to try this out, where do look to understand the current behaviour

**Comment by benedikt-bartscher** [comment]
https://github.com/orgs/reflex-dev/discussions/2509
