### ISSUE TITLE
Reflex command line runs very slow

### ISSUE THREAD

**Issue by ericwb** [reflex-dev/reflex#3286]
**Describe the bug**
Running just `reflex --help` can take 2-4 seconds to execute. This is an unbearable amount of time for command line.

**To Reproduce**
 - Run `time reflex --help`
 - Note the time it took to execute:
```
real	0m2.491s
user	0m2.056s
sys	0m0.138s
```

**Expected behavior**
Command lines should be very snappy in response especially when given no arguments or a simply way to print the help.

**Screenshots**
n/a

**Specifics (please complete the following information):**
 - Python Version: 3.12.1 (saw similar results with 3.11.7)
 - Reflex Version: 0.4.9
 - OS: macOS Sonoma 14.4.1
 - Browser (Optional): n/a
 
**Additional context**

**Comment by ericwb** [comment]
The bulk of the time is a result of the import

`from reflex.custom_components.custom_components import custom_components_cli`

in https://github.com/reflex-dev/reflex/blob/main/reflex/reflex.py#L18

**Comment by masenf** [comment]
Thanks for profiling. I moved the PyiGenerator import into the only function in that file which uses it, and that has shrunk the invoke time significantly.

**Comment by picklelo** [comment]
I think we should also look into lazy imports in the custom components CLI
