### ISSUE TITLE
rx.text() component doesn't preserve data format. 

### ISSUE THREAD

**Issue by HongyuHansonYao** [reflex-dev/reflex#3305]
rx.text("hello           world") renders as "Hello world"
Multiple consecutive whitespace characters (including spaces) are collapsed into a single space when rendered by the browser.
We can preserve the style/format using rx.html component and <pre> tag. 
Users may expect rx.text to preserve formats, we should either improve the text component or docs

**Comment by masenf** [comment]
If users want to preserve whitespace, then they should set `white_space="pre"` css prop

```python
        rx.section(
            rx.heading("This is not pre     formatted"),
            rx.heading("This is pre     formatted", white_space="pre"),
        )
```

![image](https://github.com/reflex-dev/reflex/assets/1524005/d1622a4b-11b0-4084-9fb4-03ba752e98d9)

**Comment by HongyuHansonYao** [comment]
Should we set it as default?

**Comment by HongyuHansonYao** [comment]
Sounds good, I will just make some minor changes to the doc

**Comment by HongyuHansonYao** [comment]
Closed
