### ISSUE TITLE
rx.set_clipboard broken in 0.5.0

### ISSUE THREAD

**Issue by greenseeker** [reflex-dev/reflex#3308]
**Describe the bug**
After updating to 0.5.0, rx.set_clipboard produces a runtime error.

**To Reproduce**
```py
def p_just_copy() -> rx.Component:
    return rx.button("copy", on_click=rx.set_clipboard("AAAAAAAAAAAAA"))

app = rx.App(
    theme=rx.theme(
        appearance="dark"
    )
)

app.add_page(p_just_copy, route="/")
```

Click the copy button to produce the error in the screenshot below.

**Expected behavior**
Set clipboard content to the given text.

**Screenshots**
![image](https://github.com/reflex-dev/reflex/assets/202654/310446c8-ddf5-46f8-8cef-8e3883dccb18)

**Specifics (please complete the following information):**
 - Python Version: 3.11.6
 - Reflex Version: 0.5.0
 - OS: Ubuntu 23.10
 - Browser (Optional): Brave 1.65.126, Firefox 125

**Comment by ElijahAhianyo** [comment]
can you run `reflex init` and if that doesn't fix it, try deleting your `.web` folder and try again

**Comment by greenseeker** [comment]
@ElijahAhianyo no change, unfortunately. Is there any logging that might help?

**Comment by picklelo** [comment]
@greenseeker what browser are you using? It's working on my Chrome and Safari. I wonder if [this](https://stackoverflow.com/questions/51805395/navigator-clipboard-is-undefined) may be related.

**Comment by greenseeker** [comment]
@picklelo reproduced in Brave 1.65.126 and Firefox 125

**Comment by greenseeker** [comment]
Since updating to 0.5.1, I'm no longer having this issue.

**Comment by greenseeker** [comment]
It worked for 2 days, but now getting the same error again, despite no changes to this code.

**Comment by Lendemor** [comment]
Tested on 0.6.0, it's working so closing it.
