### ISSUE TITLE
Taking too much for  " installing front end packages from config". why?

### ISSUE THREAD

**Issue by gokulaknnan** [reflex-dev/reflex#3367]
**Describe the bug**
Taking too much for  " installing front end packages from config". why?
minimum it is taking 30 minutes to start a project. 

**To Reproduce**
 - Code/Link to Repo:

**Expected behavior**

**Screenshots**

**Specifics (please complete the following information):**
 - Python Version: 3.10
 - Reflex Version: 5.1
 - OS: ubuntu 22
 - Browser (Optional): any broser
 
**Additional context**

**Comment by Lendemor** [comment]
Does it happens consistently whenever you make a new repo?
Did you maybe have a bad connection at some point, which could slow the install ?
