### ISSUE TITLE
[REF-2915] Breaking change 0.5.0 -> 0.5.1, inheritance in ComponentState

### ISSUE THREAD

**Issue by mishavanbeek** [reflex-dev/reflex#3368]
**Describe the bug**
Due to a more strict check in the parent classes (here: https://github.com/reflex-dev/reflex/blob/main/reflex/state.py#L758), it seems no longer possible to create a component state, and then have multiple implementations with specific behavior.

**To Reproduce**
The following works in 0.5.0, but not in 0.5.1
```python
import reflex as rx


class MyBaseComponentState(rx.ComponentState):
    a: str = "1"

    def on_increment(self):
        raise NotImplementedError()

    @classmethod
    def get_component(cls, **props) -> rx.Component:
        return rx.box(
            rx.text("hello " + cls.a, **props),
            rx.button("Increment", on_click=cls.on_increment),
        )


class MyComponent(MyBaseComponentState):

    def on_increment(self):
        self.a = str(int(self.a) + 1)


my_component = MyComponent.create


def index() -> rx.Component:
    return rx.box(
        my_component(),
    )


app = rx.App()
app.add_page(index)
```

**Expected behavior**
Expected behavior is that this throw no errors, like in 0.5.0.

**Specifics (please complete the following information):**
 - Python Version: 3.11.6
 - Reflex Version: 0.5.1
 - OS: Mac
 - Browser (Optional): Chrome

<sub>[REF-2915](https://linear.app/reflex-dev/issue/REF-2915/breaking-change-050-051-inheritance-in-componentstate)</sub>

**Comment by masenf** [comment]
Thanks for reporting. A workaround for now is to add `mixin=True` to your subclasses like

```python

class MyComponent(MyBaseComponentState, mixin=True):

    def on_increment(self):
        self.a = str(int(self.a) + 1)
```

I'll see if there's a way we can fix this generally so that subclassing a ComponentState directly does not create a substate.

I think we can treat all ComponentState subclasses as mixin and then pass `mixin=False` inside the `create` classmethod to instantiate "real" classes"

cc @benedikt-bartscher FYI

**Comment by mishavanbeek** [comment]
Many thanks Masen! This works. Your workaround actually also solves another issue I had, that I could not make the base class abstract.
