### ISSUE TITLE
[REF-2955] module 'reflex' has no attribute reflex.serializer

### ISSUE THREAD

**Issue by s4n-cz** [reflex-dev/reflex#3384]
**Describe the bug**
According to the [documentation](https://reflex.dev/docs/wrapping-react/guide/#serializers) it should be possible to define serializer for custom type. When trying this feature I got the following error:
```
AttributeError: module 'reflex' has no attribute reflex.serializer
```

**To Reproduce**
- Create a new project (I started with *dashboard* template)
- Add the following lines of code:
  ```py
  class Foo:
      foo: str = "foo"
      bar: int = 42
  
  
  @rx.serializer
  def serialize_foo(foo: Foo) -> str:
      return f"{foo.foo} {foo.bar}"
  ```

**Expected behavior**
The app should continue to work without any issues and *Foo* should be serializable.

**Screenshots**
n/a

**Specifics (please complete the following information):**
 - Python Version: 3.12.3
 - Reflex Version: 0.5.1
 - OS: Fedora 40
 
**Additional context**
This is a demonstrational example where simple inheritance from `rx.Base` might solve the issue. But I am trying to make it work for a bigger project, where I cannot modify the classes (models in Pydantic v2). So far I am just playing around with different concepts of Reflex and trying to figure out what would work the best for my case.

<sub>[REF-2955](https://linear.app/reflex-dev/issue/REF-2955/module-reflex-has-no-attribute-reflexserializer)</sub>

**Comment by masenf** [comment]
@ElijahAhianyo can you make sure we are exposing `serializer` in the reflex top level with your #3345 import refactor?

I think we intended to expose `serializer`, but maybe just forgot or it got removed. Definitely we should match what is publicly documented.

**Comment by ElijahAhianyo** [comment]
> @ElijahAhianyo can you make sure we are exposing `serializer` in the reflex top level with your #3345 import refactor?
> 
> I think we intended to expose `serializer`, but maybe just forgot or it got removed. Definitely we should match what is publicly documented.

Got it
