### ISSUE TITLE
[REF-2956] New Auto Port Select Feature is Overriding Config

### ISSUE THREAD

**Issue by deanchanter** [reflex-dev/reflex#3385]
**Describe the bug**
The new auto port select feature is overriding the config. When a backend port is in config the app gets confused and loses connectivity.

**To Reproduce**
`config = ReflexappConfig(
    frontend_port=3001,
    backend_port=2000,
    app_name="app",
    api_url="http://localhost:2000", 
     
)`

**Expected behavior**
If ports are in the config fall back to old method of asking the user what to do

**Screenshots**

**Specifics (please complete the following information):**
 - Python Version:3.11
 - Reflex Version:5.1
 - OS: MacOS
 - Browser (Optional):FireFox
 
**Additional context**

<sub>[REF-2956](https://linear.app/reflex-dev/issue/REF-2956/new-auto-port-select-feature-is-overriding-config)</sub>

**Comment by deanchanter** [comment]
It fails most often after a hot reload.

**Comment by masenf** [comment]
Thanks for reporting, we'll look into it.

Is your ideal behavior prompting the user whether to kill or change port? Or if the backend_port is provided in the config and not available, should reflex fail to start?

**Comment by deanchanter** [comment]
Yes

**Comment by masenf** [comment]
I guess that was kind of an xor question... if the port is defined, is your preference that reflex **a) prompts** xor **b) fails**?

**Comment by deanchanter** [comment]
Either is fine with me as long as the other is notified
