### ISSUE TITLE
Vertical orientation on tabs doesn't work

### ISSUE THREAD

**Issue by joaquincardosorios** [reflex-dev/reflex#3403]
When I try to create a vertical tab for my sidebar, it keeps horizontal, I tried even copypasting the example code in documentation

https://github.com/joaquincardosorios/jcardoso_website/blob/main/jcardoso/views/sidebar.py
Here is my code where I try to get vertical tabs

 - Python Version:  3.10.12
 - Reflex Version: 0.4.9
 - Browser (Optional): Chrome

**Comment by picklelo** [comment]
@joaquincardosorios We recently merged a PR #3332 and should be available in the next release coming soon. You can test it out with `pip install reflex==0.5.2a1` to see if it solves your issue.

**Comment by joaquincardosorios** [comment]
It works! Thank you so much
