### ISSUE TITLE
state.js processEvent hang when eventSent then network disconnect

### ISSUE THREAD

**Issue by seewindcn** [reflex-dev/reflex#3404]
**Describe the bug**
when debug, I found serveral times, the web hang;
like this:
![image](https://github.com/reflex-dev/reflex/assets/2747944/d3fb2d00-54f8-436a-ba8b-374c42c2e343)

event_processing is true, and processEvent don't apply event_queue;

**To Reproduce**
maybe Steps to reproduce the behavior:
1. in processEvent, eventSent=true, 
2. backend process kill or network close;
3. reconnect;
4. processEvent hang;

**Expected behavior**
maybe we can set event_processing=true when on connect?

**Comment by picklelo** [comment]
@seewindcn Good find - I think we want to set `event_processing=false` on the reconnect so that it won't block any new events.
