### ISSUE TITLE
[REF-3076] 404 with recomplilation when working on routes

### ISSUE THREAD

**Issue by charlestondance** [reflex-dev/reflex#3416]
When working with pages that are routes auto reloading leads to 404 errors that cannot be recovered without restarting reflex.

**To Reproduce**
I have an event hander in the state for the below page. If i change an invalid variable name to a correct one i can force throwing an attribute error. Switching between valid and invalid 2-3’times throws a 404 and reloading doesnt work. Restarting reflex does

This is my route:
`@rx.page(route="/entity/[entity_id]/")
def entity_editor():`

**Expected behavior**
Editing pages should result in reloading a working reflex app

**Screenshots**

**Specifics (please complete the following information):**
 - Python Version: 3.12
 - Reflex Version: 0.52
 - OS: osx 13.3.1
 - Browser (Optional): firefox
 
**Additional context**
Generally happens often with all sorts of editing, but reporducible with the above

<sub>[REF-3076](https://linear.app/reflex-dev/issue/REF-3076/404-with-recomplilation-when-working-on-routes)</sub>

**Comment by ElijahAhianyo** [comment]
can you provide a minimal reproducible code describing this behavior? I'm kind of having a hard time figuring out what the invalid/valid variable is in this case

**Comment by hragbalian** [comment]
@ElijahAhianyo Here is a minimal example:

```
import reflex as rx

@rx.page(
    route="/mypage/[page_id]", 
    title="Page", 
    )
def mypage():
    return rx.text("Hello world")
```

Navigate to page, e.g. http://localhost:3000/mypage/123/ and hot reload once or twice (maybe three times) and you'll hit the 404.
