### ISSUE TITLE
[REF-3078] Make .web folder configurable via env.

### ISSUE THREAD

**Issue by abulvenz** [reflex-dev/reflex#3445]
Currently `.web` is hard-coded in `constants/base.py`.
There are many solutions when it would be helpful to specify a different folder, e.g. when I use `reflex export` in pre-commits while the dev mode is running. 
Also running tests while running dev mode is sometimes causing the compilation to fail or never end.
The code looks quite clean when I analyzed it for ".web" occurrences, so the feature should not take to much effort.

<sub>[REF-3078](https://linear.app/reflex-dev/issue/REF-3078/make-web-folder-configurable-via-env)</sub>

**Comment by benedikt-bartscher** [comment]
Maybe we should also think about adjusting the default `.web` location for reflex export?

**Comment by Lendemor** [comment]
something like `.web-export` as a default for when we run `reflex export` ?
