### ISSUE TITLE
[REF-3098] DeprecationWarning with blank template

### ISSUE THREAD

**Issue by benedikt-bartscher** [reflex-dev/reflex#3486]
**Describe the bug**

Minimal reflex app emits warning about missing `_var_is_string`.

```log
DeprecationWarning: Creating a Var from a string without specifying _var_is_string has been deprecated in version 0.5.4 Specify _var_is_string=False to create a Var that is
not a string literal. In the future, creating a Var from a string will be treated as a string literal by default. It will be completely removed in 0.6.0
```

Maybe we can add a test for the starter templates which checks for unwanted errors/warnings like these? Blank template should only emit something like this:
```log
Compiling: ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 13/13 0:00:00
App running at: http://localhost:3000
```

**To Reproduce**
 - Create a reflex project with blank template (`reflex init`)
 - `reflex run`

**Expected behavior**
No warnings

**Specifics (please complete the following information):**
 - Python Version: 3.12.4
 - Reflex Version: main branch
 - OS: arch

<sub>[REF-3098](https://linear.app/reflex-dev/issue/REF-3098/deprecationwarning-with-blank-template)</sub>

**Comment by masenf** [comment]
Not reproducing the issue on 0.5.4a3

I think #3470 and #3473 were intended to fix this deprecation warning coming from the framework.

Can you retest on the latest main and reopen if the issue persists?
