### ISSUE TITLE
Conda package request

### ISSUE THREAD

**Issue by owenlamont** [reflex-dev/reflex#350]
I was wondering if we could get Pynecone as a conda package in addition to being on PyPi.

I was thinking on the [conda-forge](https://conda-forge.org/) channel by [submitting the package](https://conda-forge.org/docs/maintainer/adding_pkgs.html) to have a feedstock repo created.

Happy to attempt this myself or support this if there's no objections.

**Comment by Alek99** [comment]
Nice suggestion I don't have previous experience with conda forge so feel free to try this if you have time. Thanks!

**Comment by owenlamont** [comment]
Looks like all the dependencies have Conda packages already so hopefully packaging for Conda should be straight forward. I'll keep you posted how I go @Alek99

**Comment by Alek99** [comment]
> Looks like all the dependencies have Conda packages already so hopefully packaging for Conda should be straight forward. I'll keep you posted how I go @Alek99

Awesome thank you!

**Comment by untitled9074** [comment]
I see that the issue has been closed as completed, but for some reason I cannot find a `reflex` package both in [anaconda](https://anaconda.org/search?q=reflex) and [conda-forge](https://postimg.cc/566ZmHPw) repos. It appears [I am not alone](https://forum.reflex.dev/t/conda-packages-needed-for-installation/449) who struggles to find the package.

As [Richdev](https://forum.reflex.dev/u/Richdev) pointed out, conda package manager is the go to solution in the data science and ML world. Would be awesome to have this option, unless it is a huge burden to setup for the team.

If the package is already installable via conda/mamba, please consider adding the installation instructions to the documentation.
