### ISSUE TITLE
debug reflex app

### ISSUE THREAD

**Issue by Darkstrouk** [reflex-dev/reflex#3502]
Hi, team

I forked from https://github.com/reflex-dev/reflex-chat

so I can't understand how to debug it correctly 

I want to run my app to make frontend started at my localhost:3000 (as a default) and make it possible to debug state.py - to send a massage from front-end and pause front-end to debug back (state.py) 
Im tying to do it in pycharm but it doesn't work

I starting app as reflex run (in vscode or terminal from project root)
then I starting to debug state.py in pycharm (with parameters "run" or "run --no-frontend") - then I sending massage from UI (at localhost:3000) and it just processes (prints logs in terminal) - and that's it! As if reflex doesnt know about debug in pycharm

**Comment by Darkstrouk** [comment]
I also tried to ask ur ai in discord - https://discord.com/channels/1029853095527727165/1070050045870751744/1251955845345050817

but it didn't help me at the end :(

**Comment by ElijahAhianyo** [comment]
Refer to these on how to debug your reflex app:
https://www.youtube.com/watch?v=KQShed3LA64
https://www.youtube.com/watch?v=3fWJYkjmaLU&ab_channel=Reflexion
