### ISSUE TITLE
[REF-3134] K8 Liveness and Readiness probes

### ISSUE THREAD

**Issue by benedikt-bartscher** [reflex-dev/reflex#3506]
Expose a `/health` endpoint which reports the status of the reflex instance. This endpoint should check f.e. redis and postgres connections. This allows to configure liveness and readiness probes in k8 which prevents routing traffic to unhealthy reflex workers.

<sub>[REF-3134](https://linear.app/reflex-dev/issue/REF-3134/k8-liveness-and-readiness-probes)</sub>

**Comment by IamAdiSri** [comment]
Hi, I'd like to work on this. Can someone tell me where these changes need to be made and roughly where to get started with this?

**Comment by Alek99** [comment]
Hi we are not giving much guidance for the bounties as they are meant to be done mostly autonomously, I can still assign if you are interested

**Comment by ai-naymul** [comment]
@Alek99 ,

Could you please assign it to me?

**Comment by ai-naymul** [comment]
And one thing should I include the redis retry decorator that is mentioned in the #3505 
?

**Comment by tumultousRamen** [comment]
Hey @Alek99,
I can take a look into this feature and deliver it over the weekend.

**Comment by benedikt-bartscher** [comment]
@masenf accidentally closed?

**Comment by samarth9201** [comment]
Can I get assigned to this issue?

**Comment by picklelo** [comment]
@samarth9201 just assigned you!
