### ISSUE TITLE
Bug in rx.download() when we pass string with # in data argument

### ISSUE THREAD

**Issue by TinToSer** [reflex-dev/reflex#3528]
**Describe the bug**
When I pass normal string with "#" in it to the data argument in rx.download() method then download happens with a file but it contains string until "#" and string after it is chopped off

**To Reproduce**
 - Code/Link to Repo:
 -  `rx.download(data = "hello # world", filename="demo.txt")`

**Expected behavior**
It should download a file with "hello # world" as its data .

**Screenshots**

**Specifics (please complete the following information):**
 - Python Version:
 - Reflex Version:
 - OS: 
 - Browser (Optional):
 
**Additional context**
But if I encode data then all works fine i.e 
   `rx.download(data = "hello # world".encode(), filename="demo.txt")`

It works all fine

**Comment by masenf** [comment]
Would you mind filling in the Python Version, Reflex Version, and Browser fields in the bug report template?

I do not reproduce the issue on `main` branch (6709b49cfa238cb3ab2c433ccffd4543f4cebb17) on Chrome/Safari/Firefox on macOS 14.5

<summary>

Full code

<details>

```python
import reflex as rx


def index() -> rx.Component:
    return rx.button("DL", on_click=rx.download(data = "hello # world", filename="demo.txt"))


app = rx.App()
app.add_page(index)
```
</details>
</summary>

**Comment by TinToSer** [comment]
- Python Version = 3.11.8
- Reflex Version = 0.4.8

I experimented after your reply with version 0.5.3 and it has no such issues, so it means in later version such issue is not there. I have 0.4.8 and it has the bug as i mentioned

**Comment by picklelo** [comment]
Closing this issue as it's resolved in the latest version.
