### ISSUE TITLE
[REF-3160] [VarOps] It is way too easy to pass incorrect kwargs to `rx.Var._replace`

### ISSUE THREAD

**Issue by masenf** [reflex-dev/reflex#3531]
**Describe the bug**
This `_replace` func accepts arbitrary kwargs, pulls out the ones it recognizes, and passes those off to BaseVar constructor. Meanwhile, any remainin unrecognized kwargs are just jettisoned without any errors.

This means if I pass `_merge_var_data` instead of `merge_var_data`, it silently does the wrong thing.

**To Reproduce**
```python
rx.Var.create("foo")._replace(_this_should_fail=True)
```

**Expected behavior**
The line of code above should raise some TypeError or similar. Instead it returns a new Var with nothing changed.

<sub>[REF-3160](https://linear.app/reflex-dev/issue/REF-3160/[varops]-it-is-way-too-easy-to-pass-incorrect-kwargs-to-rxvar-replace)</sub>

**Comment by Manas1820** [comment]
Hey @masenf 

I noticed in [vars.py](https://github.com/reflex-dev/reflex/blob/main/reflex/vars.py) that the _replace function typically takes class variables of BaseVars, Vars, or ComputedVar as kwargs. I propose a solution to create a custom decorator for verifying kwargs.

In this decorator, we can either pass the class and it will automatically consider the class variables, or we can pass a set of expected kwargs, if the values passes is outside the set it will throw and TypeError. This decorator might be useful at multiple places too .

 Let me know your thoughts on this !
