### ISSUE TITLE
[REF-3164] Hot reload with py3.12 on Windows takes 45+ seconds

### ISSUE THREAD

**Issue by masenf** [reflex-dev/reflex#3536]
**Describe the bug**
Uvicorn 0.24 (needed for py312 compat) does not seem to notice changes in the windows file system in a timely manner, leading to very long hot reload cycles.

**To Reproduce**
* Use python3.12 on windows
* `reflex init` - blank template
* `reflex run`
* Make a change to the main file and save
* Wait 45 - 90 seconds
* See change reflected in browser

**Expected behavior**
Hot reload should be no slower than it is with python 3.11 / uvicorn 0.20.0

**Specifics (please complete the following information):**
 - Python Version: 3.12
 - Reflex Version: 0.5.4
 - OS: Windows 11

<sub>[REF-3164](https://linear.app/reflex-dev/issue/REF-3164/hot-reload-with-py312-on-windows-takes-45-seconds)</sub>

**Comment by masenf** [comment]
The main issue here does not seem to be detecting the change, but rather after the change is detected and the reloader attempts to gracefully terminate the current server process, it seems to hang until all websocket connections are closed.

For example, if a change is made and then the browser is refreshed immediately, the reload only takes 10-15 seconds, which is far shorter than the 45 - ♾️ seconds observed without refreshing.

Implementing our own hot reload in reflex itself seems unlikely to be *better* than what we get from uvicorn, and would still fall victim to this websocket close waiting hang.

uvicorn's implementation

```
    def restart(self) -> None:
        if sys.platform == "win32":  # pragma: py-not-win32
            self.is_restarting = True
            assert self.process.pid is not None
            os.kill(self.process.pid, signal.CTRL_C_EVENT)
        else:  # pragma: py-win32
            self.process.terminate()
        self.process.join()

        self.process = get_subprocess(config=self.config, target=self.target, sockets=self.sockets)
        self.process.start()
```

[https://github.com/encode/uvicorn/blob/d79f285184404694c77f7ca649858e7488270cf7/uvicorn/supervisors/basereload.py#L87C1-L97C29](https://github.com/encode/uvicorn/blob/d79f285184404694c77f7ca649858e7488270cf7/uvicorn/supervisors/basereload.py#L87C1-L97C29)

**Comment by itsmeadarsh2008** [comment]
Here's a Rust version of the provided Python code:
(**This code is theoretical as it is generated by Claude, We can make a binding with PyO3 to reduce time consumption. It's not really that hard to make bindings (We could ask LLM for creation) for it but it will require two more packages `maturin` and `pyo3` respectively. I don't think it matters that much as the writer cares about writing the app**)
```rust
use std::process::{Child, Command};
use std::sync::mpsc::{channel, Sender, Receiver};
use std::thread;
use std::time::Duration;

struct Server {
    process: Option<Child>,
    is_restarting: bool,
    config: Config,
    target: String,
    sockets: Vec<Socket>,
}

impl Server {
    fn restart(&mut self) {
        if cfg!(target_os = "windows") {
            self.is_restarting = true;
            if let Some(ref mut process) = self.process {
                // On Windows, we would use a different method to send Ctrl+C
                // This is a placeholder and may not work as intended
                process.kill().expect("Failed to kill process");
            }
        } else {
            if let Some(ref mut process) = self.process {
                process.kill().expect("Failed to terminate process");
            }
        }

        // Wait for the process to exit
        if let Some(mut process) = self.process.take() {
            process.wait().expect("Failed to wait for process");
        }

        // Start a new process
        self.process = Some(self.get_subprocess());
    }

    fn get_subprocess(&self) -> Child {
        let mut command = Command::new(&self.target);
        // Add configuration and socket setup here
        command.spawn().expect("Failed to start process")
    }
}

// Placeholder structures
struct Config {}
struct Socket {}

fn main() {
    // Example usage
    let mut server = Server {
        process: None,
        is_restarting: false,
        config: Config {},
        target: String::from("your_target_executable"),
        sockets: vec![],
    };

    server.restart();
}
```
