### ISSUE TITLE
@lottiefiles/dotlottie-react: React component for rendering and controlling dotLottie animations in React applications.

### ISSUE THREAD

**Issue by itsmeadarsh2008** [reflex-dev/reflex#3559]
**@lottiefiles/dotlottie-react**
The `@lottiefiles/dotlottie-react` package provides a custom React component for rendering and controlling dotLottie animations in React applications.

- **What is the purpose of the custom component?**
To easily integrate and display dotLottie animations within React projects and
to offer a Reflex-friendly way for beginners to work with dotLottie files, which are a more efficient and feature-rich format compared to traditional Lottie JSON files.
- **What is the expected behavior of the custom component?**
Render dotLottie animations smoothly within React components.
Provide props for controlling animation playback, such as play, pause, loop, and speed.
Allow customization of animation appearance and behaviour through various props.
- **What are the use cases for the custom component?**
Adding engaging animations to user interfaces.
Creating interactive loading indicators.
Enhancing user experience with animated illustrations or icons.
Implementing animated micro-interactions in Reflex-based web applications.

**Specifics (please complete the following information):**
 - **Do you have a specific react package in mind? (Optional)**: More specifically, `@lottiefiles/dotlottie-react` is the best dotlottie react library for this purpose as it maintains compatibility between .lottie (compressed and optimized) and lottie.json (traditional Lottie json)

**Additional context**
Component Library Docs: https://developers.lottiefiles.com/docs/dotlottie-player/dotlottie-react/

**Comment by onexay** [comment]
I have added support for LottieFiles/dotLottie here https://pypi.org/project/reflex-lottiefiles/.

**Comment by itsmeadarsh2008** [comment]
> I have added support for LottieFiles/dotLottie here https://pypi.org/project/reflex-lottiefiles/.

Thanks a lot!!!
