### ISSUE TITLE
Ability to access Cookies and LocalStorage

### ISSUE THREAD

**Issue by FHU-yezi** [reflex-dev/reflex#356]
Since we are able to access query params by use `State.get_query_params()` method in #244 , I am wondering to have access to Cookies and LocalStorage.

Cookies and LocalStorage object's behavior are like a Python dict object. Take Cookies as an example, to set a new cookie:

```python
State.cookies["foo"] = "bar"
```

Set cookie with expire time:

```python
State.cookies.set(key="foo", value="bar", expire_at=datetime.now() + timedelta(days=1))
```

`http-only` param is not supported because we need to use Javascript to do all the actions.

To get a value ( return value is a `Cookie` object ):

```python
State.cookies["foo"]  # Cookie(key="foo", value="bar", expire_time=...)
State.cookies["foo"].value  # "bar"
State.cookies.get("some-key-which-not-exist", "Not Found")  # "Not Found"
```

Clear all Cookies:

```python
State.cookies.clear()
```

**Comment by dwojcik92** [comment]
I would laso like to have this feature. Right now I have fully working register and login buy the state token is in session storage which is not safe.

Wouldn't be easier to store session token in cookie in the first place?

**Comment by jq6l43d1** [comment]
This would be so useful. I have a website that uses Azure AD authentication via the msal python library. because I can't delete the cookie that get's set when a user logs in, they can't really log out. This means users have to use incognito mode when they use my website on a public computer.

**Comment by picklelo** [comment]
We still need a way to read the cookies and local storage
