### ISSUE TITLE
[REF-726] New component from Chakra UI: Toast

### ISSUE THREAD

**Issue by FHU-yezi** [reflex-dev/reflex#358]
referance: [Toast - Charka UI](https://chakra-ui.com/docs/components/toast)

To display a error toast at the bottom of screen:

```python
pc.toast("Something wrong happend", type\_="error")
pc.toast_error("Something wrong happend")
```

Set toast appear place:

```python
pc.toast("Success!", type_="success", place="top_right")
```

<sub>[REF-726](https://linear.app/reflex-dev/issue/REF-726/new-component-from-chakra-ui-toast)</sub>

**Comment by milochen0418** [comment]
## Toast is a nice feature for the application user if we have 
pc.alert() look like it is not enough for us to give a hint to the user when the user types the wrong thing in their input text field.

What if we put the following in UI?
```
return pc.window_alert("The item you entered is duplicated.")
```
That's too strong sometimes. 

But what if we have 
```
pc.window_toast("The item you entered is duplicated.")
```
That would be better and more beautiful. 
I saw there is a toast document on Chakra-ui
https://chakra-ui.com/docs/components/toast
I have no idea how to implement it now. 

If some talent can help with this, that will be so valuable for better user experience quality for Pynecone app. 
That would be nice to have a toast to make a  better user experience on our current example code. 

For the following pull request, we use window_alert  to give the user a hint when the added item is duplicated.
But that is too strong. it would be better if we use toast in this case. 
- https://github.com/pynecone-io/pynecone-examples/pull/67

**Comment by masenf** [comment]
In #1900 from @ltm920716

-----

**Describe the bug**
Sorry for here again，this not a bug，the toast component can not be warped like other react library，could reflex support toast？

**To Reproduce**
```
from __future__ import annotations
from typing import Any, Union

from reflex.components.libs.chakra import ChakraComponent
from reflex.vars import Var


class ToastWindow(ChakraComponent):
    tag = 'useToast'

    position = Var[str]

    duration = Var[int]

    is_closable = Var[bool]

    status = Var[str]

    def get_event_triggers(self) -> dict[str, Union[Var, Any]]:
        return {
            **super().get_event_triggers(),
            "on_close": lambda: [],
            "on_open": lambda: []
        }
    
use_toast = ToastWindow().create
```

**Expected behavior**
could reflex support toast？

**Comment by masenf** [comment]
Here's how it can be done

```python
from typing import Literal
import random

import httpx

import reflex as rx


class ToastProvider(rx.components.libs.chakra.ChakraComponent):
    tag = "useToast"

    def _get_hooks(self) -> str | None:
        return "refs['__toast'] = useToast()"

    @staticmethod
    def show(
        title: str,
        description: str,
        duration: int,
        status: Literal["info", "warning", "success", "error", "loading"] = "info",
    ) -> rx.event.EventSpec:
        return rx.call_script(
            f"""
            refs['__toast']({{
            title: "{title}",
            description: "{description}",
            duration: {duration},
            status: "{status}",
            isClosable: true,
            }})
        """
        )


class State(rx.State):
    counter: int = 0

    def dynamic_toast(self) -> None:
        self.counter += 1
        zen = httpx.get("https://api.github.com/zen").text
        duration = random.randint(3000, 6000)
        return ToastProvider.show(
            f"Your Zen For the Day ☯️ ({self.counter})", zen, duration, status="success"
        )


def index() -> rx.Component:
    return rx.fragment(
        ToastProvider.create(),
        rx.color_mode_button(rx.color_mode_icon(), float="right"),
        rx.vstack(
            rx.heading("Welcome to Reflex! 🥂"),
            rx.button(
                "🍻",
                on_click=ToastProvider.show(
                    "I propose a toast",
                    "To python web frameworks, camraderie, and muscles",
                    3000,
                ),
            ),
            rx.button("🥂", on_click=State.dynamic_toast),
        ),
    )


app = rx.App()
app.add_page(index)
app.compile()
```

**Comment by cyrus0880** [comment]
> Here's how it can be done
> 
> ```python
> from typing import Literal
> import random
> 
> import httpx
> 
> import reflex as rx
> 
> 
> class ToastProvider(rx.components.libs.chakra.ChakraComponent):
>     tag = "useToast"
> 
>     def _get_hooks(self) -> str | None:
>         return "refs['__toast'] = useToast()"
> 
>     @staticmethod
>     def show(
>         title: str,
>         description: str,
>         duration: int,
>         status: Literal["info", "warning", "success", "error", "loading"] = "info",
>     ) -> rx.event.EventSpec:
>         return rx.call_script(
>             f"""
>             refs['__toast']({{
>             title: "{title}",
>             description: "{description}",
>             duration: {duration},
>             status: "{status}",
>             isClosable: true,
>             }})
>         """
>         )
> 
> 
> class State(rx.State):
>     counter: int = 0
> 
>     def dynamic_toast(self) -> None:
>         self.counter += 1
>         zen = httpx.get("https://api.github.com/zen").text
>         duration = random.randint(3000, 6000)
>         return ToastProvider.show(
>             f"Your Zen For the Day ☯️ ({self.counter})", zen, duration, status="success"
>         )
> 
> 
> def index() -> rx.Component:
>     return rx.fragment(
>         ToastProvider.create(),
>         rx.color_mode_button(rx.color_mode_icon(), float="right"),
>         rx.vstack(
>             rx.heading("Welcome to Reflex! 🥂"),
>             rx.button(
>                 "🍻",
>                 on_click=ToastProvider.show(
>                     "I propose a toast",
>                     "To python web frameworks, camraderie, and muscles",
>                     3000,
>                 ),
>             ),
>             rx.button("🥂", on_click=State.dynamic_toast),
>         ),
>     )
> 
> 
> app = rx.App()
> app.add_page(index)
> app.compile()
> ```
> 
>  Screen.Recording.2023-10-05.at.5.45.38.AM.mov

i use you demo script i got this error

AttributeError: module 'reflex' has no attribute 'call_script'

**Comment by cyrus0880** [comment]
> ```python
> dynamic_toast
> ```

i fixed  the new ver is use rx.client_side

but now i try use on state i got this

    raise ValueError(f"Invalid event chain: {value}")
ValueError: Invalid event chain: ${state.main.toast_state.dynamic_toast}

**Comment by alexlausz** [comment]
![Snipaste_2023-12-24_15-42-37](https://github.com/reflex-dev/reflex/assets/32123947/17c3e259-860c-4a02-9e9a-09ff45a22fdd)
Reflex 0.3.7 with Python 3.11.7
Node 18.17.0
Bun 1.0.13

**Comment by masenf** [comment]
@alexlausz try adding the following to ToastProvider

```python

    def _get_imports(self) -> dict[str, rx.utils.imports.ImportVar]:
        _imports = super()._get_imports()
        _imports.setdefault(f"/{rx.constants.Dirs.STATE_PATH}", set()).add(rx.utils.imports.ImportVar(tag="refs"))
        return _imports
```

There are still some recent regressions, for example the 🍻 button no longer works after 0.3.5; will open a separate, more general issue for that problem.

**Comment by alexlausz** [comment]
> @alexlausz try adding the following to ToastProvider
> 
> ```python
>     def _get_imports(self) -> dict[str, rx.utils.imports.ImportVar]:
>         _imports = super()._get_imports()
>         _imports.setdefault(f"/{rx.constants.Dirs.STATE_PATH}", set()).add(rx.utils.imports.ImportVar(tag="refs"))
>         return _imports
> ```
> 
> There are still some recent regressions, for example the 🍻 button no longer works after 0.3.5; will open a separate, more general issue for that problem.

It works. Thank you.

**Comment by juankysoriano** [comment]
And what about showing the toast as the result of background task?

`rx.background`

**Comment by kumaraguru1735** [comment]
when I try to use position , toast itself not working
```
   @staticmethod
    def show(
        title: str,
        description: str,
        duration: int,
        status: Literal["info", "warning", "success", "error", "loading"] = "success",
    ) -> rx.event.EventSpec:
        return rx.call_script(
            f"""
            refs['__toast']({{
            title: "{title}",
            description: "{description}",
            duration: {duration},
            status: "{status}",
            isClosable: true,
            position: top-right,
            }})
        """
        )
```

**Comment by masenf** [comment]
I would assume you need to quote that value, as `top-right` is being interpreted as `top - right`, and i dont think either `top` nor `right` are defined in scope.

Try with `position: "top-right"`
