### ISSUE TITLE
[REF-3219] use hooks.useState will raise: ValueError: Can not compile, the tag useState is used multiple time from react and react

### ISSUE THREAD

**Issue by seewindcn** [reflex-dev/reflex#3604]
**Describe the bug**
use `hooks.useState`, will raise: ValueError: Can not compile, the tag useState is used multiple time from react and react

`hooks._compose_react_imports` function, create ImportVar object with `install=False`; and in banner.py, `ConnectionToaster.add_hooks` create ImportVar object with `install=True`; 

these will make `compler.validate_imports` raise ValueError.

<sub>[REF-3219](https://linear.app/reflex-dev/issue/REF-3219/use-hooksusestate-will-raise-valueerror-can-not-compile-the-tag)</sub>

**Comment by masenf** [comment]
should be a simple enough fix to get rid of the `install=False` in `_compose_react_imports`

**Comment by Lendemor** [comment]
I think `install=False`is correct though (even if we have a special case that exclude installing react dynamically since it's installed during \`init\`)
I'd rather set it to False in \`ConnectionToaster.add_hooks\`

**Comment by Lendemor** [comment]
> We could also merge that patch that moves the install special cases to `ImportVar.__init__` or similar. Then it wouldn't matter how it was specified in different places.

I'd be fine with that, do you have the id of the PR containing that patch if it's waiting/ready for review?
