### ISSUE TITLE
Mouse click event is triggered more slowly on AccordionItem in DrawerBody.

### ISSUE THREAD

**Issue by wbfw109** [reflex-dev/reflex#364]
**Describe the bug**
I have 60+ nestable AccordionItem components and I bind index and click event.
I tested in ```pc run``` (dev environment). (It is not occurred in Production mode)

- in index layout, (mouse down ~ mouse click event) time is between 0.35 and 0.45 seconds.
- but, in DrawerBody,  (mouse down ~ mouse click event) time is between 0.7 ~ 0.8 seconds.

**To Reproduce**
```
class MyState(pc.State):
    mouse_down_start_time: float = 0.0

    def mouse_click_event(self, index: int) -> None:
        print(time.time() - self.mouse_down_start_time)
    def mouse_down_event(self) -> None:
        print("mouse down event")
        self.mouse_down_start_time = time.time()
```

**Expected behavior**
It must be faster even if in DrawerBody.

**Screenshots**
![image](https://user-images.githubusercontent.com/37881026/215163581-9556e550-7fce-4d9d-9a01-44d1b02f4318.png)

**Specifics (please complete the following information):**
 - Python Version: 3.11.0
 - Pynecone Version: pynecone-io = "0.1.13"
 - OS: WSL Ubuntu 22.04 distribution in Windows 11 Version 21H2 (OS Build 22000. 1455)
 - Browser (Optional): Edge Browser
 - Shell: Fish shell
 - Node Version: 18.12.1
 
**Additional context**

**Comment by Alek99** [comment]
Got it we will investigate, thanks for pointing it out
