### ISSUE TITLE
Transform mouse into a cursor by default when hovering over a reflex button

### ISSUE THREAD

**Issue by dentro-innovation** [reflex-dev/reflex#3649]
**Describe the bug**
Not bug but improvement:
Something that I don't understand is why the mouse doesn't transform into a cursor by default when hovering over a reflex button. 
When reflex used chakra the mouse pointer did transform by default

**To Reproduce**
Use any rx.button and hover over it

**Expected behavior**
The mouse pointer transforms into a "hand" icon

**Specifics (please complete the following information):**
 - Python Version: 3.12
 - Reflex Version: 0.5.6 (any since reflex uses radix)
 
**Additional context**
I know that's because the radix button has the cursor set to 'default', but perhaps reflex should change that.

**Comment by masenf** [comment]
Typically (and by default) buttons do not use the "pointer" cursor.

Personally, i think it was kind of weird that chakra used the pointer cursor on their buttons, but i didn't notice it at the time, and my personal feelings aren't really a good way to set defaults for a framework.

So I did some searching and found [this interesting two part article](https://adamsilver.io/blog/buttons-shouldnt-have-a-hand-cursor/) which explains some of the history and semantics of the pointer cursor. It makes the case that buttons and other UI elements that are not explicitly links should not use the pointer cursor on hover.

Ultimately, I don't think reflex will be changing the default cursor for `rx.button` at this point.

But thankfully, if you do want this behavior, it's fairly easy to enable on an app-by-app basis:

```
app = rx.App(style={rx.button: {"cursor": "pointer"}})
```

**Comment by dentro-innovation** [comment]
Thanks for the explanation. Yes I already use this cursor style in all my apps.
