### ISSUE TITLE
Can Chinese developers use pnpm or yarn for package management?

### ISSUE THREAD

**Issue by reigadegr** [reflex-dev/reflex#3700]
In China, the package management tools Bun and npm are too slow to download dependencies and are very unstable, sometimes taking several hours to start a project.

Debug: Running command: ['C:\\Users\\admxcy\\AppData\\Local\\reflex\\bun\\bin\\bun.exe', 'install']
Debug: Installing base frontend packages
Debug: bun install v1.1.10 (5102a944)
Debug: Resolving dependencies
Debug: Resolved, downloaded and extracted [10]
Debug: Saved lockfile
Debug:                                                                                                                                                                                  
Debug: + @radix-ui/react-dialog@1.1.1                                                                                                                                                   
Debug:                                                                                                                                                                                  
Debug: 33 packages installed [323.38s]                                                                                                                                                  
Debug: Running command: ['C:\\Users\\admxcy\\AppData\\Local\\reflex\\bun\\bin\\bun.exe', 'add', '-d', 'tailwindcss@3.3.2']                                                              
Debug: Installing tailwind                                                                                                                                                              
Debug: bun add v1.1.10 (5102a944)
Debug: Saved lockfile

**Comment by bishuitianqing** [comment]
不是下载依赖包慢，而是下载bun.exe慢。依赖包的下载换源就行了，bun.exe只需要下载一次，如果首次不能下载成功，可以自己下载个bun.exe放在提示的目录，也可以通过rxconfig.py指定包管理器的位置。还有就是bun是解释器和编译器，跟包管理器npm或yarn无关！
