### ISSUE TITLE
[REF-3416] FastAPI and Starlette are out of date

### ISSUE THREAD

**Issue by masenf** [reflex-dev/reflex#3715]
**Describe the bug**
Currently FastAPI is pinned `<0.111.0` because this is the version where `fastapi` gains additional dependencies and the original package becomes `fastapi-slim`. Splitting deps with different names across versions is hard to express in poetry. Essentially we want one of `fastapi-slim >=0.111.0` (preferred) _or_ `fastapi >=0.96.0, <0.111.0`, but it's not clear how to do it in poetry.

The starlette pin seems to be coming from fastapi [[1]](https://github.com/tiangolo/fastapi/blob/dc8e194a20208a01bb05d71ac0404925dd44a7dd/pyproject.toml#L44), so we'll have to figure out the 0.111.0 upgrade before we can get the newer starlette.

Not sure if there's anything we can do about these in July 2024.

**Specifics (please complete the following information):**
 - Python Version: 3.12
 - Reflex Version: 0.5.8a1
 - OS: macOS 14
 
**Additional context**
Discovered while running `pip list --outdated` on a fresh install of 0.5.8a1

<sub>[REF-3416](https://linear.app/reflex-dev/issue/REF-3416/fastapi-and-starlette-are-out-of-date)</sub>

**Comment by benedikt-bartscher** [comment]
Related: https://github.com/reflex-dev/reflex/issues/2802
