### ISSUE TITLE
Allow me to branch / rx.cond for mobile and desktop view when using props

### ISSUE THREAD

**Issue by dentro-innovation** [reflex-dev/reflex#3733]
Instead of having to do this:
```
rx.mobile_only(
      rx.button(
          rx.icon("arrow-up"),
          type="submit",
          id="send-button-desktop",
          size="2",  # SIZE 2 HERE
          color=rx.color("gray", 1),
          background_color=rx.color("accent", 9),
      ),
  ),
  rx.tablet_and_desktop(
      rx.button(
          rx.icon("arrow-up"),
          type="submit",
          id="send-button-mobile",
          size="3",   # SIZE 3 HERE
          color=rx.color("gray", 1),
          background_color=rx.color("accent", 9),
      ),
  ),
```

...I want to be able to do something like this:
```
rx.button(
          rx.icon("arrow-up"),
          type="submit",
          id="send-button",
          size=rx.cond(rx.mobile_only, "2", "3"),   # <------
          color=rx.color("gray", 1),
          background_color=rx.color("accent", 9),
      ),
```

**Comment by benedikt-bartscher** [comment]
iirc conditional props should already be possible

**Comment by dentro-innovation** [comment]
yes but not based on whether its mobile or desktop right? I can use state vars for an rx.cond on prop, yes that's possible.

**Comment by adhami3310** [comment]
You should be able to do that with:
```py
size=rx.breakpoints(initial="2", md="3"),
```
More on that: https://reflex.dev/docs/styling/responsive/

**Comment by dentro-innovation** [comment]
Does this also work with the style prop?
```
style=rx.breakpoints(initial='{"scale": "1"}', md='{"scale": "1.3"}')
```

**Comment by adhami3310** [comment]
> Does this also work with the style prop?
> 
> ```
> style=rx.breakpoints(initial='{"scale": "1"}', md='{"scale": "1.3"}')
> ```

This currently has a bug that got fixed in main (the PR is [!3719](https://github.com/reflex-dev/reflex/pull/3719)), as a workaround:

```py
style={"&": rx.breakpoints(initial={"scale": "1"}, md={"scale": "1.3"})}
```

(Note that you don't need to put the dict in a string)

**Comment by adhami3310** [comment]
P.S. In the next release you wouldn't need the workaround

**Comment by dentro-innovation** [comment]
> ```python
> style={"&": rx.breakpoints(initial={"scale": "1"}, md={"scale": "1.3"})}
> ```


I tried using it right now with a rx.toast, and it doesn't seem to have any effect.

When I just use one attribute it does work `style={ "1.1",}`, so the problem does seem to be the workaround itself. 

Anyway, if it's available next release already I'll just wait!

**Comment by adhami3310** [comment]
> > ```python
> > style={"&": rx.breakpoints(initial={"scale": "1"}, md={"scale": "1.3"})}
> > ```
> 
> I tried using it right now with a rx.toast, and it doesn't seem to have any effect.
> 
> When I just use one attribute it does work `style={ "scale": "1.1",}`, so the problem does seem to be the workaround itself.
> 
> Anyway, if it's available next release already I'll just wait!

It generally works, but toast is a react component with special handling and doesn't support nested styling through emotion, and as such cannot be used with breakpoints. The only way to use it is to give a class name and do media queries in a CSS file :/
