### ISSUE TITLE
please add  object-fit into  video and image elements support

### ISSUE THREAD

**Issue by yutayouguan** [reflex-dev/reflex#3740]
The CSS properties "object-fit" that define how image and video elements are displayed within a container,  but  object-fit  can't  add into rx.video  style
![image](https://github.com/user-attachments/assets/c684c7fc-d385-4ca9-9fea-da2ebedb527c)

**Comment by yutayouguan** [comment]
rx.inset(
                rx.video(
                    url="/video/video.mp4",
                    loop=True,
                    playing=True,
                    controls=False,
                    muted=True,
                    width="auto",
                    height="100%",
                    style={"object_fit": "cover"},  # type: ignore
                    class_name=[
                        "video",
                    ],
                ),
                side="left",
                pr="current",
            ),

**Comment by yutayouguan** [comment]
as such image show, `style={"object_fit": "cover"}, ` is not work

**Comment by masenf** [comment]
Try with

```python
rx.video(
    ...,
    style={"& video": {"object_fit": "cover"}},
)
```

This will set the css property on the `video` element inside the react-player.

**Comment by yutayouguan** [comment]
Hi Masenf:
It's Work, Thank you
