### ISSUE TITLE
Wrap Shadcn

### ISSUE THREAD

**Issue by achen2089** [reflex-dev/reflex#3757]
Wrap shadcn in Reflex

**Comment by achen2089** [comment]
Could I be assigned this issue?

**Comment by itsmeadarsh2008** [comment]
To match up with the Shadcn's Quality. Each component should be a separate library.
https://github.com/reflex-dev/shadcn/issues/1
There is an empty repository till now but the project will accelerate if you collaborate with the guy.

**Comment by logan-markewich** [comment]
Very excited to see this move forward! 🚀

**Comment by elviskahoro** [comment]
@achen2089 we have a $500 dollar bounty for this! Let us know if you decide to take it on, details are in our Notion:
https://reflex-dev.notion.site/Bounties-73de092794674a5791a2fd0214405f65#0064d6b43172496c935d8c770b084ea8
