### ISSUE TITLE
Wanna know how scalable it is , is there any estimation about how may users it can handle on average on a 4gb ram generic vm?

### ISSUE THREAD

**Issue by Naveenbhargav-Mallampati** [reflex-dev/reflex#3780]
Dear contributors , thank you for your work.

I am just curious about how scaliable this system is.
Since on each user interaction needed an updation from the backend via websocket , is it feasible for like 30000 parallel users , on a low resources systems.

In an generic react or other frontend frameworks , the state-management is done in browser and the api calls etc are added as a load for the backend.

Will the  reflex way of handling all the state changes logic on each interacts add any extra load to the server.

Just asking out of curiocity.

**Comment by Alek99** [comment]
https://github.com/reflex-dev/reflex/issues/3745
