### ISSUE TITLE
Error in reflex Init

### ISSUE THREAD

**Issue by Jadj-cg** [reflex-dev/reflex#3804]
**Describe the bug**
Hey I`m new in programming was looking to use this framework try to do all steps but at the point of reflex init I get errors I think, not sure if this is normal or what am I doing wrong?

**To Reproduce**
1. C:\Users\Jose Chang>cd documents
2. C:\Users\Jose Chang\Documents>cd ElJardinDelEden
3. C:\Users\Jose Chang\Documents\ElJardinDelEden>python3 -m venv venv
4. C:\Users\Jose Chang\Documents\ElJardinDelEden>venv\Scripts\activate
5.(venv) C:\Users\Jose Chang\Documents\ElJardinDelEden>pip install reflex
6.  (venv) C:\Users\Jose Chang\Documents\ElJardinDelEden>reflex init
7. Errors  and at the end it tells "FileNotFoundError: [WinError 2] The system cannot find the file specified"

**Expected behavior**
flex to create the things needed for reflex init

**Screenshots**
![Screenshot 2024-08-16 130328](https://github.com/user-attachments/assets/dabcd6ca-eec5-470f-a937-c8fac706f619)
![Screenshot 2024-08-16 130405](https://github.com/user-attachments/assets/60cd0126-ba77-4cde-b8b0-df88c863ea56)

**Specifics (please complete the following information):**
 - Python Version: 3.12.5
 - Reflex Version: latest not sure 
 - OS: Windows 11
 
**Additional context**
I`m new to this not sure how can I get reflex to initiate and be successfully installed

**Comment by dimritium** [comment]
don't have a windows machine to reproduce but can you try adding `C:\Windows\System32\wbem` to your path

**Comment by Jadj-cg** [comment]
changed the path but having same issue (guess i can confirm the path because i belive the terminal design changes i don`t know if its because of this)
repeated the step and again in reflex init get the same
![Screenshot 2024-08-16 141005](https://github.com/user-attachments/assets/5c9cc9f8-9d8e-43f4-8e10-a9771932bf6b)
![Screenshot 2024-08-16 141054](https://github.com/user-attachments/assets/be8c7c7f-d774-4c35-b66e-128978688cf9)
![Screenshot 2024-08-16 141206](https://github.com/user-attachments/assets/e1b73345-f0a1-4899-9bae-abbe81fa057c)
![Screenshot 2024-08-16 141330](https://github.com/user-attachments/assets/ef301cf5-2d54-4e96-b101-8bc376a2d537)

**Comment by dimritium** [comment]
could you try a different terminal like PowerShell or there is a Terminal app by windows.
Not sure if that would work but you can try

**Comment by Jadj-cg** [comment]
Now I can`t even get to the venv
![Screenshot 2024-08-16 144132](https://github.com/user-attachments/assets/9c429f79-76aa-416b-9b2e-69a00af7c5bb)

**Comment by dimritium** [comment]
You can google this one.. there is a different script to activate on powershell

**Comment by Lendemor** [comment]
This seems like it was a permission issue on the user side.
I will close this issue.
Reopen a new issue if this is still happening on version 0.6.0+
