### ISSUE TITLE
Let me set a custom color for rx.progress

### ISSUE THREAD

**Issue by dentro-innovation** [reflex-dev/reflex#3817]
https://reflex.dev/docs/library/datadisplay/progress/#api-reference

It's strange that the color of the loading bar can only be set via `color_scheme`, and there I can only choose the default radix themes. 

I wanna use simply my own color, e.g. #FFF as the loading bar.

**Comment by masenf** [comment]
We used to have docs for this, but they appear to have been removed... https://github.com/reflex-dev/reflex-web/blob/masenf/changelog-0.4.9-and-friends/docs/library/datadisplay/progress-ll.md

Essentially you can set `background` to any valid css value and it should work

**Comment by wassafshahzad** [comment]
Can I try this one ?

**Comment by picklelo** [comment]
@wassafshahzad just assigned you!

**Comment by wassafshahzad** [comment]
@picklelo  This can be closed. I forgot to add the linked PR

**Comment by picklelo** [comment]
Merged in #3926
