### ISSUE TITLE
Support npm install of bun

### ISSUE THREAD

**Issue by brianmcconnel** [reflex-dev/reflex#385]
Bun is required for `pc run` and is installed using curl.   Would it be possible to also support installation of bun using an npm repository?

Thanks for your consideration,

**Comment by Alek99** [comment]
This is a good point and we'll discuss this, in the future we want to move away from npm and use bun. But the package is still premature and seg faults at someplaces which is why we use both at this moment

**Comment by brianmcconnel** [comment]
This wasn't a question about using bun vs npm.  It's more about installing bun on an isolated network that requires code scanning via an npm repository.
