### ISSUE TITLE
rx.Toast raises validation error if `title` prop passed explicitly in `0.5.10`

### ISSUE THREAD

**Issue by TimChild** [reflex-dev/reflex#3854]
**Describe the bug**
`rx.toast.error(title="some title", description="some description")` raises a ValidationError that `title` is not allowed. 

**Expected behavior**
I'd expect to be able to explicitly pass the `title` arg, but at the moment you have to pass the title as `message` or just the first positional argument. 
I think `title` is just missing from the new `ToastProps` basemodel

**Specifics (please complete the following information):**
 - Python Version: 3.12
 - Reflex Version: 0.5.10

**Additional context**
Only affects 0.5.10 where toast prop validation was introduced.

**Comment by masenf** [comment]
Would love a PR if you're willing 😀

**Comment by TimChild** [comment]
👍I'll have a look today. Hopefully should be a good easy one to start on.
