### ISSUE TITLE
Scroll in rx.text_area vanishes when `auto_height` is True

### ISSUE THREAD

**Issue by VishDev12** [reflex-dev/reflex#3863]
Wonderful work with Reflex, it's truly a dream come true for many!

In the text_area component, if `auto_height` is set to True, the scroll bar vanishes. So in cases where the user limits the height of the text_area component, there's no way to navigate the text inside the text_area with a scroll bar.

I believe this line is the issue:
https://github.com/reflex-dev/reflex/blob/99a0236d21e69f00aabe20a7dcb39c429ae9bb60/reflex/components/el/elements/forms.py#L504

Should this be set to scroll?

**Comment by danik292** [comment]
I will take this.
And do you have some testcase for this issue?
It will be helpful for me to catch.
thanks

**Comment by VishDev12** [comment]
Hi! I'm not sure about a test case, but I do have this example:

```python
rx.text_area(
    placeholder="Enter text",
    id="message",
    width=["15em", "20em", "45em", "50em", "50em", "50em"],
    min_width="15em",
    max_width="70em",
    min_height="3em",
    max_height="15em",
    enter_key_submit=True,
    auto_height=True,
    ...
)
```

Now, when a lot of text is entered, it is not possible to scroll inside the text area.

**Comment by danik292** [comment]
Thank mate I needed something like this.

**Comment by danik292** [comment]
@VishDev12  Hello I tested it and so far it looks like this isnt a bug with nightly reflex, because If you write a lot of text to a text field it will extend to hold all text. So I think you can close It as non bug.

**Comment by VishDev12** [comment]
Hey @danik292, thank you for exploring this! Sorry if this wasn't clear, but the issue is that when maximum height of the text_area is set, we expect the overflow text to be scrollable. But I'm guessing because of the following line, it is not scrollable and everything above max_height gets clipped; there is no scroll bar available inside the text_area: https://github.com/reflex-dev/reflex/blob/99a0236d21e69f00aabe20a7dcb39c429ae9bb60/reflex/components/el/elements/forms.py#L504

**Comment by masenf** [comment]
does it work as expected with that value set to "scroll"? if so then i believe that is the fix

**Comment by VishDev12** [comment]
Yes it does, and thank you for the confirmation! I've submitted the PR.
