### ISSUE TITLE
`_encode_var` does not know how to handle `ImmutableVar`.

### ISSUE THREAD

**Issue by abulvenz** [reflex-dev/reflex#3881]
**Describe the bug**
It raises `AttributeError: 'ImmutableVarData' object has no attribute 'dict'`

**Expected behavior**
No error.

**Possible fixes**
Register a serializer (Uiuiui, preserve the calling order, because `ImmutableVar` is subclass to `Var`)
![image](https://github.com/user-attachments/assets/12eb240a-5aaa-4404-a90c-f91247ae7bce)
Or fix it in `_encode_var`
![image](https://github.com/user-attachments/assets/a6197030-6596-4eb3-b7d8-2a6c83e25a0d)

**Comment by wassafshahzad** [comment]
Can you share a reproducible example ?

**Comment by adhami3310** [comment]
Is this still happening in `main`?

**Comment by adhami3310** [comment]
`_encode_var` is removed for now. Let us know if a similar issue still persists.
