### ISSUE TITLE
The code block doesn't display the code as is or appears broken.

### ISSUE THREAD

**Issue by RektPunk** [reflex-dev/reflex#3889]
**Describe the bug**
The code block doesn't display the code as is or appears broken.
I know this is due to the "\\" character, but I would appreciate it if you could show me how to fix it or how to properly use it.

**To Reproduce**
1. Example that code not displayed as is:
```python
import reflex as rx

code = """
def parse_sections_regex(text):
    pattern = r'<(.*?)>(.*?)</\1>'
    matches = re.findall(pattern, text, re.DOTALL)
    return matches
"""

def index() -> rx.Component:
    return rx.container(
        rx.vstack(
            rx.code_block(code, language="python", can_copy=True),
            spacing="5",
            justify="center",
            min_height="85vh",
        )
    )
app = rx.App()
app.add_page(index)
```
2. Example that broken
```python
import reflex as rx

code = """
def parse_sections_regex(text):
    pattern = r'<(.*?)>(.*?)</\\1>'
    matches = re.findall(pattern, text, re.DOTALL)
    return matches
"""

def index() -> rx.Component:
    return rx.container(
        rx.vstack(
            rx.code_block(code, language="python", can_copy=True),
            spacing="5",
            justify="center",
            min_height="85vh",
        )
    )
app = rx.App()
app.add_page(index)
```

**Expected behavior**
Show code as is.

**Screenshots**
1. First case
<img width="496" alt="image" src="https://github.com/user-attachments/assets/72708123-15a1-4d02-a11e-d5ed48f1c5c3">

2. Second case
<img width="861" alt="image" src="https://github.com/user-attachments/assets/0121377d-36e5-49bd-9802-84c10e4b6686">

**Specifics (please complete the following information):**
 - Python Version: 3.12
 - Reflex Version: 0.5.10
 - OS: mac os ventura 13.2

**Comment by wassafshahzad** [comment]
I ran the code on the development version and it appears to be fixed
I am running the following code
```
import reflex as rx

code = """
def parse_sections_regex(text):
    pattern = r'<(.*?)>(.*?)</\\1>'
    matches = re.findall(pattern, text, re.DOTALL)
    return matches
"""

def index() -> rx.Component:
    return rx.container(
        rx.vstack(
            rx.code_block(code, language="python", can_copy=True),
            spacing="5",
            justify="center",
            min_height="85vh",
        )
    )
app = rx.App()
app.add_page(index)
```

![Screenshot 2024-09-08 035408](https://github.com/user-attachments/assets/b86f0d45-31ea-407d-a62f-fa7f80111577)

**Comment by RektPunk** [comment]
That sounds great @wassafshahzad . Can you run the first example too, please?

**Comment by wassafshahzad** [comment]
![First](https://github.com/user-attachments/assets/9f302431-9bc2-4a1c-a9f6-f217f3e9ef9e)

The first one gives the following issue

**Comment by RektPunk** [comment]
TYSM, @wassafshahzad . Maybe, I can do what I want to do after version update.

**Comment by wassafshahzad** [comment]
@RektPunk  That sounds good
