### ISSUE TITLE
Add option for Nodejs path like `BUN_PATH`

### ISSUE THREAD

**Issue by kraanzu** [reflex-dev/reflex#3905]
**Describe the bug**
Reflex tries to install the required node version by itself into data directory but this fails on systems like NixOS or Guix because its not allowed to run binaries directly

```
NixOS cannot run dynamically linked executables intended for generic
linux environments out of the box. For more information, see:
https://nix.dev/permalink/stub-ld
```

**To Reproduce**
- reflex init and choose any template
- reflex run

**Expected behavior**
Reflex runs without any errors just like in the documentation

**Specifics (please complete the following information):**
 - Python Version: Python 3.12.5
 - Reflex Version: 0.5.10
 - OS: NixOS 22.04
 
**Additional context**
Related issue: https://github.com/reflex-dev/reflex/issues/1470

**Comment by kraanzu** [comment]
Hmm... I checked and it seems to return a path that is OK 

```
In [2]: get_node_path()
Out[2]: '/run/current-system/sw/bin/node'
```

In my case, The data directory  is `~/.local/share/reflex/`, and if I were to delete this, then it should use the `which("node")` but that is not the case, it re-installs the node binary and then the function above returns something different

```
In [2]: get_node_path()
Out[2]: '/home/kraanzu/.local/share/reflex/fnm/node-versions/v18.17.0/installation/bin/node'
```

and hence the error. I'll do a bit more digging on this

**Comment by kraanzu** [comment]
I think this function might be the issue while deciding whether to install node or not:

```python
def check_node_version() -> bool:
    """Check the version of Node.js.

    Returns:
        Whether the version of Node.js is valid.
    """
    current_version = get_node_version()
    if current_version:
        # Compare the version numbers
        return (
            current_version >= version.parse(constants.Node.MIN_VERSION)
            if constants.IS_WINDOWS
            else current_version == version.parse(constants.Node.VERSION)
        )
    return False
```

I'm currently using node version `18.20.4` which was the last version before they moved to `19.x`

The function above checks for total equality which causes the problem here, even the patch version update will return a False

**Comment by Lendemor** [comment]
#3981 no longer solve this issue, but a follow up PR will.

**Comment by kraanzu** [comment]
I also saw another mentioned PR which changed how the nodejs binary is checked, is reflex now supporting latest nodejs ?

**Comment by Lendemor** [comment]
With PR #4006, we've added a CI check to run the integration test with latest node (22.9.0 at the time of writing this, but CI will always check the latest one.)

You can either try the PR or wait for 0.6.1 which should include this fix.

`export REFLEX_USE_SYSTEM_NODE=1` will make sure that Reflex use the node found at `which node` instead of the fnm installed one.

**Comment by kraanzu** [comment]
Awesome. Thanks a lot
