### ISSUE TITLE
[ENG-3826] v0.6.0a1 breaks theming for Data editor

### ISSUE THREAD

**Issue by bertbarabas** [reflex-dev/reflex#3920]
**Describe the bug**
Before upgrading to v0.6.0a1, my Data Editor's dark mode theme worked. After only changing the version to v0.6.0a1, the dark mode for data editor fails. That is to say that regardless of what the current mode is, I only ever see light mode.

**To Reproduce**
I used the theme code straight from the data editor documentation

**Comment by bertbarabas** [comment]
Just checked Theme for data editor in v0.6.0a2, still does not appear to work...

**Comment by adhami3310** [comment]
Should be fixed in main! Thanks for catching it!

**Comment by masenf** [comment]
@bertbarabas fix also in 0.6.0a3 if you want to test the release candidate

**Comment by bertbarabas** [comment]
Thanks, works for me in 0.6.0a3 !
