### ISSUE TITLE
Support missing svg elements

### ISSUE THREAD

**Issue by ElijahAhianyo** [reflex-dev/reflex#3954]
Currently these are the SVG elements we support: https://github.com/reflex-dev/reflex/blob/5f296eec38b274800e7c37ab1a3d179f549e88d7/reflex/components/el/elements/media.py#L421

We should also support `svg.line`, `svg.ellipses`, `svg.radial_gradient`, `svg.text`

**Comment by JayanthK007** [comment]
Hi, i would like to work on this issue

**Comment by picklelo** [comment]
@JayanthK007 just merged a PR for this, feel free to take on another issue!
