### ISSUE TITLE
reflex 0.6.0  typing.Literal   rasie TypeError

### ISSUE THREAD

**Issue by yutayouguan** [reflex-dev/reflex#3994]
**Describe the bug**
upgrade reflex 0.6.0  typing.Literal   rasie TypeError

**Expected behavior**
TypeError: Unsupported type typing.Literal['xs', 'sm', 'md', 'lg', 'xl'] for guess_type.

**Screenshots**
![image](https://github.com/user-attachments/assets/0af67d60-a587-4d50-8958-d904b383548f)

**Specifics (please complete the following information):**
 - Python Version: 3.12.3
 - Reflex Version: 0.6.0
 - OS:  macOS 15
 - Browser (Optional): Arc

**Comment by masenf** [comment]
Do you have repro code? Were doing a follow up release on Monday to sweep up any issues that might have slipped the .0

**Comment by yutayouguan** [comment]
> Do you have repro code? Were doing a follow up release on Monday to sweep up any issues that might have slipped the .0

``` python

Size = Literal["xs", "sm", "md", "lg", "xl"]

class ResizableCard(rx.ComponentState):
    """Resizable card component."""

    id: str = "" 
    size: Size = "xs"
    title: str = ""


```

**Comment by BenedictusAryo** [comment]
Hi, any update on this issue ?
