### ISSUE TITLE
Using rx.popover inside rx.dialog

### ISSUE THREAD

**Issue by JoaquinVeraOrtega** [reflex-dev/reflex#3998]
**Describe the bug**
pop over component is opened and closed instantly if the trigger is not a button and is inside a dialog window

**To Reproduce**
 `rx.dialog.root(
        rx.dialog.trigger(rx.button("Open Dialog")),
        rx.dialog.content(
            rx.dialog.title("Welcome to Reflex!"),
            rx.popover.root(
                rx.popover.trigger(
                    rx.icon("circle-help", cursor="pointer"),
                ),
                rx.popover.content(
                    rx.flex(
                        rx.text("Simple Example"),
                        rx.popover.close(
                            rx.button("Close"),
                        ),
                        direction="column",
                        spacing="3",
                    ),
                ),
            ),
            rx.dialog.close(
                rx.button("Close Dialog", size="3"),
            ),
        ),
    )`

 - Python Version:  3.11
 - Reflex Version: 0.5.10
 - OS: Windows 11

**Comment by tgberkeley** [comment]
Just tried this exact code on Reflex version 0.6.1 and it seems to work as expected as seen in the video below:

https://github.com/user-attachments/assets/616a7ebe-c8e0-4358-ad9b-43247a6b8646

**Comment by GHC19** [comment]
Did you achieve it?

**Comment by JoaquinVeraOrtega** [comment]
It is working for me like in the video, latest reflex version (0.6.4)
