### ISSUE TITLE
reflex run --backend-only gets stuck

### ISSUE THREAD

**Issue by 00STER** [reflex-dev/reflex#3999]
**Describe the bug**
reflex run --backend-only get stuck on the: starting reflex app message

**To Reproduce**
1. python -m venv venv
2. source venv/bin/activate
3. pip install reflex
4. reflex init
5. reflex run --backend-only --loglevel debug

**Specifics (please complete the following information):**
 - Python Version: 3.12.3
 - Reflex Version: 0.6.0

**Comment by Lendemor** [comment]
Can you provide logs on where it get stuck? 
Also does this happens with your project, or also with a new blank one ?

**Comment by 00STER** [comment]
I could provide logs later but it gets stuck at:

**starting reflex app**

No logs after that using loglevel debug.

Happens with a fresh project, when going through the steps above to reproduce.

**Comment by Lendemor** [comment]
I tried to reproduce it, but the backend actually start for me (checked by visiting `http://localhost:8000/ping`).

I think the confusion come from the fact that the cli doesn't output the text for where the backend is running, but it's still running.
