### ISSUE TITLE
Pylance shows error when using not operator ~

### ISSUE THREAD

**Issue by bertbarabas** [reflex-dev/reflex#4059]
**Describe the bug**
Pylance reports that the following error when using the not operator ~ in a rx.cond expression:

The method "__invert__" in class "bool" is deprecated
  Will throw an error in Python 3.14. Use `not` for logical negation of bools instead.

**Expected behavior**
No exception

**Screenshots**
![image](https://github.com/user-attachments/assets/c4a0f29c-a21f-406b-8878-464fdcb3c565)

**Specifics (please complete the following information):**
 - Python Version: 3.12.3
 - Reflex Version: 0.6.2a1
 - OS: Ubuntu
 - Browser (Optional):

**Comment by adhami3310** [comment]
Should be fixed with #4066 , although using `rx.field` is optional.
