### ISSUE TITLE
Backslashes in string literals are weird

### ISSUE THREAD

**Issue by masenf** [reflex-dev/reflex#4079]
**Describe the bug**
When a string literal is rendered as a "Bare" in reflex, any backslashes which made it into the string are escaped a second time by javascript.

The question is, should reflex be escaping single backslashes when generating code? And should reflex be converting unrepresentable characters in string literals with their escaped equivalent?

**To Reproduce**
```python
import reflex as rx


@rx.page(route="/")
def bug() -> rx.Component:
    return rx.vstack(
        rx.markdown(r"""
# Hello world

Lift($$L$$) can be determined by Lift Coefficient ($$C_L$$) like the following
equation.

$$
L = \\frac{1}{2} \\rho v^2 S C_L
$$                 

$$
R = \\sum_{i=1}n{w_ir_i}=\\sum_{i=1}^n{x_ig_i}.
$$
"""),
        rx.text(r"\u2342"),
    )


app = rx.App()
```

Produced

```javascript
  <ReactMarkdown rehypePlugins={[rehypeKatex, rehypeRaw]} remarkPlugins={[remarkMath, remarkGfm, remarkUnwrapImages]} components={ComponentMap_4ffb469341e2b6627f60d58f709452af()}>
  {`
# Hello world

Lift($$L$$) can be determined by Lift Coefficient ($$C_L$$) like the following
equation.

$$
L = \\frac{1}{2} \\rho v^2 S C_L
$$                 

$$
R = \\sum_{i=1}n{w_ir_i}=\\sum_{i=1}^n{x_ig_i}.
$$
`}
</ReactMarkdown>
  <RadixThemesText as={`p`}>
  {`\u2342`}
</RadixThemesText>
```

**Expected behavior**
When a "raw" python string is used, the user does not expect needing to escape the backslashes _again_, but indeed this is necessary for the markdown math parser to correctly display the expression.

**Specifics (please complete the following information):**
 - Python Version: 3.12
 - Reflex Version: 0.5.10

**Comment by adhami3310** [comment]
for context on latest main, this is the output:

```jsx
<ReactMarkdown
  components={ComponentMap_b05fc871f4c07d9afa8e52fc86215f3f()}
  rehypePlugins={[rehypeKatex, rehypeRaw]}
  remarkPlugins={[remarkMath, remarkGfm, remarkUnwrapImages]}
>
  {
    "\n# Hello world\n\nLift($$L$$) can be determined by Lift Coefficient ($$C_L$$) like the following\nequation.\n\n$$\nL = \\\\frac{1}{2} \\\\rho v^2 S C_L\n$$\n\n$$\nR = \\\\sum_{i=1}n{w_ir_i}=\\\\sum_{i=1}^n{x_ig_i}.\n$$\n"
  }
</ReactMarkdown>
<RadixThemesText as={"p"}>{"\\u2342"}</RadixThemesText>
```

**Comment by adhami3310** [comment]
The expected output in the first case would be correct if the developer uses one backslach. In the second example, changing the raw string into a normal string would display the correct character (otherwise, would just display the string).

**Comment by masenf** [comment]
Yeah i think this is working as expected in 0.6.x, so we can probably close it
