### ISSUE TITLE
deployment regions link in the docs is broken

### ISSUE THREAD

**Issue by bertbarabas** [reflex-dev/reflex#4137]
**Describe the bug**
The deployment regions link doesn't show the list of regions:
https://reflex.dev/docs/hosting/deploy-quick-start/#reflex-deployments-regions

**To Reproduce**
Click on the link above, you'll see that it's on the page but there are no regions there

**Expected behavior**
The link should take you to the list of regions.

**Screenshots**
![image](https://github.com/user-attachments/assets/37aa0b5c-1a26-4bc7-958c-3591c47043b8)

**Comment by benedikt-bartscher** [comment]
The "Environment Variables" link seems to be broken as well

**Comment by ruhz3** [comment]
I think this issue should be on `reflex-dev/reflex-web` page.

**Comment by benedikt-bartscher** [comment]
can someone move it?

**Comment by ruhz3** [comment]
It looks like the same issue has already been created. 
https://github.com/reflex-dev/reflex-web/issues/817

**Comment by picklelo** [comment]
I'll close this since the ticket has been made on reflex-web.
