### ISSUE TITLE
Unify env vars

### ISSUE THREAD

**Issue by benedikt-bartscher** [reflex-dev/reflex#4172]
https://github.com/reflex-dev/reflex/pull/4168#discussion_r1799775136

> For some env vars, we're checking against ["true", "1", "yes"] rather than just "true".
> I think it'd be better to have an uniform method doing the check for boolean env var rather than duplicating logic everywhere.

by @Lendemor

Should we keep it simple, only allow "true"/"false" and raise a deprecation warning (and later an error) if something different is set?
Also let's move all env var constants to a SimpleNamespace class?

**Comment by benedikt-bartscher** [comment]
This is not fully done, however i can not reopen it.
is_frontend_only, is_backend_only, is_prod_mode, is_testing_env, ENV_BACKEND_ONLY_ENV_VAR, ENV_FRONTEND_ONLY_ENV_VAR, ENV_MODE_ENV_VAR, SKIP_COMPILE_ENV_VAR, ....

**Comment by adhami3310** [comment]
> This is not fully done, however i can not reopen it.
> is_frontend_only, is_backend_only, is_prod_mode, is_testing_env, ENV_BACKEND_ONLY_ENV_VAR, ENV_FRONTEND_ONLY_ENV_VAR, ENV_MODE_ENV_VAR, SKIP_COMPILE_ENV_VAR, ....

i must have missed these, do you want to do them in a PR or should i fix them soon?

**Comment by benedikt-bartscher** [comment]
I can maybe refactor it this evening, will keep you up2date about the progress

**Comment by benedikt-bartscher** [comment]
@adhami3310 i have done it locally and will push it this weekend
