### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: 'None' (Solved)

### ISSUE THREAD

**Issue by cusquitonet** [reflex-dev/reflex#4181]
hello I have this problem (view picture) when try reflex init, my system is archlinux runing python 3.11.10 in venv environment. I try with pyenv with same result. Only run python with sudo permit me ejecute reflex. the problem was probed in terminal and vscode with same result.
![Screenshot_2024-10-13_18-47-20](https://github.com/user-attachments/assets/20130206-e2a5-4518-bb2f-eda06aee19e0)

**Comment by adhami3310** [comment]
it seems it's not finding node and returning 'None' which is weird, is node/npm installed on your machine?

**Comment by cusquitonet** [comment]
No, I tried to run reflex init from scratch and I understood that if it doesn't find node then it installs it for me. Should I install it separately?

**Comment by adhami3310** [comment]
one thing you can try is installing node and using `REFLEX_USE_SYSTEM_NODE` flag. unsure why specifically it failed to install it for you

**Comment by cusquitonet** [comment]
By installing the npm package through Pacman I was able to get reflex to work perfectly. Thank you very much for the help.

**Comment by cusquitonet** [comment]
$ sudo pacman -S npm solve the problem.
