### ISSUE TITLE
Cannot find propper way to access query parameters

### ISSUE THREAD

**Issue by sabbraxcaddabra** [reflex-dev/reflex#4258]
Cannot find propper way to access query parameters to get access token from redirecting on my reflex frontend app

My State class is:
```
class State(rx.State):
    """The app state."""

    @rx.var
    def get_access_token(self):
        query_params = self.router.page.params
        print(query_params)
        access_token = query_params.get('access_token')
        print(access_token)
        return access_token
```

And my auth rout:
```
@rx.page(route='/app/auth/[[...]]', )
def auth():
    return rx.box(
        rx.text(State.get_access_token)
    )
```

First of all I try the following url `http://localhost:8050/app/auth/#access_token=my_token/` and this give me nothing (just blank white screen). Then I try url `http://localhost:8050/app/auth/access_token=my_token/` without # symbol and get in my console output from `get_access_token` method.
```
{'': ['access_token=my_token']}
None
```

I want to use the reflex routes with query parameters like `http://localhost:8050/app/auth/#access_token=my_token/`
Is there any chance do it?

 - Python Version: 3.12
 - Reflex Version: 0.6.3.post1
 - OS: Linux Fedora 40
 - Browser (Optional): Chrome

**Comment by Lendemor** [comment]
Tested your snippet locally, they are working properly when using this url : 
`http://localhost:3002/app/auth/?access_token=%22foobarbaz%22`
