### ISSUE TITLE
reflex_ag_grid propriedade localeText

### ISSUE THREAD

**Issue by hermilio** [reflex-dev/reflex#4286]
Describe the Custom Component
The custom component is an implementation of agGrid in a React application, specifically configured to support multiple languages for data grid display.

What is the purpose of the custom component?
The purpose of this custom component is to provide a data grid that allows for the visualization and manipulation of tabular data within the application, using the agGrid library. It is designed to support multiple languages by utilizing the localeText property, enabling the application to cater to a diverse user base with different language preferences.

What is the expected behavior of the custom component?
The component should render the agGrid data grid with all default UI labels, messages, and prompts translated based on the selected language. It should dynamically update the localeText property to reflect the current language, ensuring that all user interface elements, such as column menus, toolbar buttons, and pagination controls, are displayed in the appropriate language.

What are the use cases for the custom component?

Applications requiring a data grid that can be localized for users speaking different languages.
Scenarios where the data needs to be displayed in a user-friendly, interactive table format across various languages.
Cases where language flexibility is essential, such as international applications that need to accommodate a global audience.
Specifics (please complete the following information):

Do you have a specific React package in mind? Yes, the ag-grid-react package for integrating agGrid with React.
Additional context
This customization leverages the localeText property within the agGrid component to provide language-specific translations for all user interface elements in the grid. This setup allows for easy localization by updating the localeText object according to the user’s language preference, ensuring clarity and usability for a diverse audience.

**Comment by picklelo** [comment]
We have AG Grid available now - see the [docs here](https://reflex.dev/docs/library/tables-and-data-grids/ag-grid/)
