### ISSUE TITLE
Is there a way to create editable Table?

### ISSUE THREAD

**Issue by teabagk7** [reflex-dev/reflex#431]
I couldn't find a way to create editable table, could you help with that please?
1) Editing field by clicling on it.
2) Access field by "column" and "row" indexes.

**Comment by Alek99** [comment]
There may be a way to do it with a datable and editable but it's not ideal or easy.

However we could add a component like this in the future. If there any react library you like in particular? I'll do some research on some potential libraries we can wrap. This would be a nice feature to have.

**Comment by FHU-yezi** [comment]
Maybe we can build this with grid and editable components

**Comment by teabagk7** [comment]
> There may be a way to do it with a datable and editable but it's not ideal or easy.
> 
> However we could add a component like this in the future. If there any react library you like in particular? I'll do some research on some potential libraries we can wrap. This would be a nice feature to have.

[Dash datatable](https://dash.plotly.com/datatable) is a great example.
I almost don't have experience with react, so can't help with that.
Yeah, seems really great feature to have an interactive table, looking forward to it 👍🏻

**Comment by karndeb** [comment]
We could take a look at AG Grid. It is a fully-featured and highly customizable JavaScript data grid. It delivers good performance and has no 3rd party dependencies. Also has the most comprehensive set of features in the community version.

**Comment by Shahin-rmz** [comment]
[this](https://www.npmjs.com/package/react-x-editable) plugin seems what our fella wants

**Comment by Lendemor** [comment]
Closed by #1941
