### ISSUE TITLE
The semantic table does not stretch to the full width of the page

### ISSUE THREAD

**Issue by kesevone** [reflex-dev/reflex#4321]
**Describe the bug**
The table does not stretch to the end of the page, although in the demo the table is located to the end of the page width. I used all the necessary components from the template, replacing only the backend with my api to get users and removed button "Export".

As for "spacing", I also saw that "rx.table.cell" and "rx.table.column_header_cell" have "col_span", but when using this parameter, this appear only for column names, not for data.

**To Reproduce**
reflex init --template ci_template ([repo](https://github.com/reflex-dev/templates/tree/main/ci_template))

**Expected behavior**
Dynamic expansion of the table, as well as "spacing" between columns. Maybe it's already in reflex and I haven't figured it out. In the demo version, there is a large space between columns, but mine is too small.

**Screenshots**
## Demo table [cijob](https://cijob.reflex.run/)
![normal_table](https://github.com/user-attachments/assets/fcf18d4d-0558-415f-acc8-fd46e10b34d8)

## My table
![my_poop_table](https://github.com/user-attachments/assets/f8a53eeb-1088-4b31-b4b0-f9a3145da850)

**Specifics (please complete the following information):**
 - Python Version: 3.12
 - Reflex Version: 5.2.0
 - OS: Windows 11

**Comment by picklelo** [comment]
This should be resolved in reflex 0.6.5 - see #4378
