### ISSUE TITLE
Double import in .js for custom react code.

### ISSUE THREAD

**Issue by Ernelene** [reflex-dev/reflex#4375]
With version 0.6.4 and onwards I am getting a duplicate import error in the javascript code for custom react components.

![image](https://github.com/user-attachments/assets/dda29c73-2e74-4e08-b7eb-e7733627024e)

In version 0.6.3.post1 it only defines it as a const and does not "import" it as well.

**To Reproduce**
I added a custom react component like this:
`import reflex as rx
class E3DBar(rx.NoSSRComponent):
    library = "/public/echarts3DBar"
    tag = "ECharts3DBarReact"
    is_default = True
    plot_options: rx.Var[str] = ""
    plot_type : rx.Var[str] = ""
    

e3DBar_comp = E3DBar.create`

The error apears when the page loads on which the component is used.

**Comment by masenf** [comment]
@Ernelene was supposed to be yesterday, hopefully now today. If you want to try out the pre-release with this fix, you can install `reflex==0.6.6a2`
