### ISSUE TITLE
Cosmetic discrepancy: Dialogues

### ISSUE THREAD

**Issue by oReazy** [reflex-dev/reflex#4378]
**Describe the bug**
The error appears during the closing of the dialog

**To Reproduce**
Create a Reflex project and wrap the button with a dialog

**Expected behavior**
Smooth fade animation without breaks

**Video**

https://github.com/user-attachments/assets/351ad6a2-b37e-43ab-911c-9fdf66a37c69

**Specifics (please complete the following information):**
 - Python Version: 3.12
 - Reflex Version: 6.4
 - OS: Windows 11
 - Browser (Optional): Chrome
 
**Additional context**
-

**Comment by DeepQuantum** [comment]
Are you on version 0.6.4? I had the same issue and it was fixed in 0.6.5. It's because Radix-UI is having some issues in the newest version. https://github.com/reflex-dev/reflex/pull/4370 https://github.com/radix-ui/themes/issues/627
