### ISSUE TITLE
default_value parm is missing from rx.text_area

### ISSUE THREAD

**Issue by bertbarabas** [reflex-dev/reflex#4461]
**Describe the bug**
rx.text_area has no way to update with on_blur

If I use on_change, I can use value= to both capture the changes in my state and update the text_area widget as a user types into it.

But on_blur is the better event to use in my case because I only care about the final value in the text_area, I don't need to burden the system with an event to the server for each keystroke.

The problem is that using value= with on_blur just freezes the text_area (as you might expect).

With rx.input, I can use default_value to simply put the initial value into the input widget from my state and then use on_blur to update the state when the user finishes typing and leaves the field.

But there is no default_value for text_area.

So is default_value a missing parm for text_area or is this feature simply unavailable there forcing a developer to either update state on each keystroke or add more code and implement the page as a form?

**Comment by Lendemor** [comment]
Seems like default_value prop is working with rx.text_area.

Tested with: 
```python
@rx.page("/")
def index():
    return rx.text_area(custom_attrs={"default_value": "Hello"})
```

will make a PR to have the props natively 👍
