### ISSUE TITLE
Error when testing Reflex Cloud

### ISSUE THREAD

**Issue by al3xsdev** [reflex-dev/reflex#4497]
**Describe the bug**

**To Reproduce**
 - Code/Link to Repo:

**Expected behavior**

When following the steps to test the reflex cloud I received this error

**Screenshots**
![Captura desde 2024-12-06 14-52-32](https://github.com/user-attachments/assets/736ec641-1833-48f3-98fd-a2093f4eec1f)
![Captura desde 2024-12-06 14-52-51](https://github.com/user-attachments/assets/170c9220-45ec-48cf-bc03-9575e77f59e6)

**Specifics (please complete the following information):**
 - Python Version: 3.12.7
 - Reflex Version: reflex==0.6.6.post2
 - OS: 
 - Browser (Optional): Brave linux in fedora 41
 
**Additional context**

**Comment by ElijahAhianyo** [comment]
out of curiosity, what's the output when you do `pip freeze | grep reflex-hosting-cli`?

**Comment by al3xsdev** [comment]
Thank you very much for replying, I have the following result 
( `pip freeze | grep reflex-hosting-cli = reflex-hosting-cli==0.1.29` )

**Comment by al3xsdev** [comment]
I changed the Python version to 3.12.0 and changed the browser to run correctly.
