### ISSUE TITLE
Bug Report: rx.text_area component missing default_value property support

### ISSUE THREAD

**Issue by dkphhh** [reflex-dev/reflex#4501]
**Describe the bug**
it seems to be that the rx.text_area doesn‘t have the default_value property

**To Reproduce**
``` python
import reflex as rx

@rx.page(route="/test")
def test_page() -> rx.Component:
    return rx.container(
        rx.text_area(
            default_value="this is a test for text_area"
        ),
    )
```

<img width="1052" alt="image" src="https://github.com/user-attachments/assets/ecc814bf-55ca-466c-a30d-d16e2c7b0e3f">

**Screenshots**
I check the TextArea code, it doesn’t have a default_value property
<img width="826" alt="image" src="https://github.com/user-attachments/assets/bfff45c9-76ed-4b3b-9094-7e0ecac25008">

**Specifics (please complete the following information):**
 - Python Version:3.13
 - Reflex Version:v0.6.6.post2
 - OS: Linux、macOS
 - Browser (Optional): Chrome

**Comment by Lendemor** [comment]
Already fixed by #4462
