### ISSUE TITLE
Dynamic back navigation

### ISSUE THREAD

**Issue by bigr00** [reflex-dev/reflex#4544]
**Describe the Features**
Reflex needs a dynamic way to navigate back programmatically, like from a "Back" button in the UI.

One easy way would be for the router to have a `previous_page` and `previous_raw_page`, so it could be used like this:

```
class ExampleState(rx.State):
    """ Example state """

rx.button(
    "Back",
    on_click=rx.redirect(ExampleState.router.previous_page) 
)
```

This would enable simple to use navigation, since the router keeps track of the pages anyways.
Feels to me like a necessary part of the framework, as it's easy to implement and when documented on the reflex.dev page, would be widely used.

My current solution was to create an on_mount event hook to a NavigationState to the template wrapper of a page. The downside of this is the circular import issue, have to import the NavigationState right before using it in UI and it looks ugly.

The `previous_raw_page` is necessary to maintain the dynamic parameters if used.
 
**Additional context**
No such feature exists right now.

**Comment by benedikt-bartscher** [comment]
Great idea. However, a previous_page in `rx.State` would introduce additional payload size to every state. Maybe there is an easy solution with a computed var?

**Comment by benedikt-bartscher** [comment]
If many users like this feature, reflex could add a test for this or even provide a State Mixin. You could then use it like this:

```python
class YourState(rx.State, PreviousStateMixin):
  pass
```

**Comment by Lendemor** [comment]
It is already possible with this :
```python
@rx.page("/page2")
def page2():
    """Page 2."""
    return rx.button("Back", on_click=rx.call_script("window.history.back()"))

```

**Comment by masenf** [comment]
Simpler than that:

```python
@rx.page("/page2")
def page2():
    """Page 2."""
    return rx.button("Back", on_click=rx.event.back())
```

**Comment by Lendemor** [comment]
Right, I'll mark this as closed then.

**Comment by benedikt-bartscher** [comment]
> Simpler than that:
> 
> ```python
> @rx.page("/page2")
> def page2():
>     """Page 2."""
>     return rx.button("Back", on_click=rx.event.back())
> ```

Nice one, thanks!
