### ISSUE TITLE
Want scroller in components cards

### ISSUE THREAD

**Issue by Aarize29** [reflex-dev/reflex#461]
**Describe the bug**
Want scroller in components cards so that each component should have same height and have better user experience

![Screenshot (39)](https://user-images.githubusercontent.com/97665948/217053484-c0dc6d59-85bc-4c10-8bb7-000f5129c464.png)

**Solution** 
we can add overflow scroll in the card section

**Comment by Aarize29** [comment]
You can assign me , I will handle this issue

**Comment by masenf** [comment]
The website and docs were recently redesigned in the rebrand as Reflex, just wondering @Aarize29 if you might still be able to submit a patch for this.
