### ISSUE TITLE
Convert apk

### ISSUE THREAD

**Issue by saurabhwadekar** [reflex-dev/reflex#466]
Can we convert pynecone to apk like react native?

**Comment by r0b2g1t** [comment]
You mean to build a pynecone apk as an Android app?

**Comment by saurabhwadekar** [comment]
Yes bro

**Comment by r0b2g1t** [comment]
This is not directly possible. Maybe when you export the frontend and run it as a static Website locally in an apk. I don't have any experience with that.

**Comment by Alek99** [comment]
This is not possible yet, someone talked about working on a react native integration but I'm the near future we are focusing on the core package.

**Comment by r0b2g1t** [comment]
I have done some research about his topic. I would propose to write an article about this topic. Because the export has to much variables about the build of the apk, like Android Studio and manual steps. I will write the article in the next days.

**Comment by r0b2g1t** [comment]
I have written an article how to export your Pynecone app frontend to a mobile app:
https://medium.com/itnext/how-to-build-android-and-ios-apps-with-pynecone-6d2097a7610d

**Comment by saurabhwadekar** [comment]
Very important Article

**Comment by worldofgeese** [comment]
> I have written an article how to export your Pynecone app frontend to a mobile app:
> https://medium.com/itnext/how-to-build-android-and-ios-apps-with-pynecone-6d2097a7610d

Do you have a non-Medium link?

**Comment by worldofgeese** [comment]
> I have written an article how to export your Pynecone app frontend to a mobile app:
> https://medium.com/itnext/how-to-build-android-and-ios-apps-with-pynecone-6d2097a7610d

@r0b2g1t Do you have a non-Medium link?

**Comment by r0b2g1t** [comment]
> > I have written an article how to export your Pynecone app frontend to a mobile app:
> > https://medium.com/itnext/how-to-build-android-and-ios-apps-with-pynecone-6d2097a7610d
> 
> @r0b2g1t do you have a non-Medium link?

Sorry, no.
