### ISSUE TITLE
[REF-1061] Configure nightly build separated from the stable release.

### ISSUE THREAD

**Issue by Lendemor** [reflex-dev/reflex#480]
For development and testing purpose, it would be really nice to provide a version of Reflex that is not guaranteed to be stable but contains the latest commits.

Something like a `reflex-nightly` package which would be built once per day for example.

Thanks to @FHU-yezi for the idea. 

<sub>[REF-1061](https://linear.app/reflex-dev/issue/REF-1061/configure-nightly-build-separated-from-the-stable-release)</sub>

**Comment by masenf** [comment]
Do we want a separate package? or just pre-release version specs?
