### ISSUE TITLE
Add support for tuple returning from pages.

### ISSUE THREAD

**Issue by Cheesy-Brik** [reflex-dev/reflex#492]
When a page returns a tuple, unwrap the tuple as the args for a container element (such as pc.box). This would allow for syntax such as
```
def index():
  return pc.text("Hello"), pc.text("World")
```

**Comment by danik292** [comment]
@Alek99 I look for this.😊😊😊

**Comment by masenf** [comment]
@danik292 what is the use case for this? why would the user not just return a component?

**Comment by danik292** [comment]
@masenf so close it

**Comment by masenf** [comment]
Well, you were saying you wanted to work on it; I was just trying to better understand the scenario where it comes up before making a decision like that.

**Comment by danik292** [comment]
Well I think this can be useful when the user is making inputs there as recorded as tuple and after this rendered down like a map for example.

**Comment by danik292** [comment]
@masenf what is your opinion

**Comment by masenf** [comment]
Looking through the code, it seems we're already very close to supporting this:

https://github.com/reflex-dev/reflex/blob/76b8af3b42a618939c1fd7dd8af5dfaad9f5906b/reflex/app.py#L329-L330

We already wrap the returned component in an `rx.Fragment`, so it seems like this bit of code could attempt to splat the component into the fragment and if that gets a `TypeError` (not iterable), then just pass the component normally.

Maybe something like

```python
try:
    component = Fragment.create(*component)
except TypeError:
    component = Fragment.create(component)
```

I think it would work and the change doesn't seem too invasive, but we'll need tests and doc updates to go along with it.

**Comment by danik292** [comment]
@masenf so what should I  do?

**Comment by masenf** [comment]
@danik292 after discussing it with the team, we think it would be a cool feature. You may proceed with the implementation. ✔️

**Comment by danik292** [comment]
where to add this in app,py
```python
        if not isinstance(component, Component):
            try:
                component = Fragment(children=[i for i in component])
            except:
                pass


```
