### ISSUE TITLE
Feature request for simple CAPTCHA component

### ISSUE THREAD

**Issue by matt9197** [reflex-dev/reflex#526]
Would it be possible to have a component added to pynecone that makes it simple to interact with a service such as googles reCaptcha v2? Or if there is a better captcha provider or similar security feature that would be great as well.

This would help in terms of making secure production ready websites simple to make using pynecone.

Thank you very much,
Matt

**Comment by ElijahAhianyo** [comment]
This component is a good candidate for a third-party component

**Comment by masenf** [comment]
google recaptcha v2 implemented as a reflex component here https://github.com/masenf/reflex-google-recaptcha-v2
