### ISSUE TITLE
"pc run" fails with error

### ISSUE THREAD

**Issue by joel-danjuma** [reflex-dev/reflex#535]
**Describe the bug**
Each time I run "pc run" it installs packages and ends with this error : 
dyld: lazy symbol binding failed: Symbol not found: _posix_spawn_file_actions_addchdir_np
  Referenced from: /Users/joeldanjuma/.bun/bin/bun (which was built for Mac OS X 11.0)
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _posix_spawn_file_actions_addchdir_np
  Referenced from: /Users/joeldanjuma/.bun/bin/bun (which was built for Mac OS X 11.0)
  Expected in: /usr/lib/libSystem.B.dylib

**To Reproduce**
 - Code/Link to Repo:

**Expected behavior**

**Screenshots**
<img width="804" alt="Screenshot 2023-02-12 at 9 54 32 PM" src="https://user-images.githubusercontent.com/94052295/218582575-26f58c35-1640-4b78-990d-610c93ada0c0.png">

** Specifics (please complete the following information):**
 - Python Version:  3.8.2
 - Pynecone Version: 0.1.15
 - OS:  Mac OS Mojave V10.14.6
 - Browser (Optional):
 
**Additional context**

**Comment by ElijahAhianyo** [comment]
closing this now as it should work with the latest reflex release. Feel free to reopen if issue persists
