### ISSUE TITLE
BaseVar compare in tests

### ISSUE THREAD

**Issue by d29107d** [reflex-dev/reflex#569]
**Describe the bug**
The below codes actually pass.

**To Reproduce**
```
def test_add_var(test_state):
    test_state.add_var("dynamic_list", List[int], [5, 10])
    assert test_state.dynamic_list == [5, 10, 9]

    test_state.add_var("dynamic_int", int, 42)
    assert test_state.dynamic_int == 33

    test_state.add_var("dynamic_dict", Dict[str, int], {"k1": 5, "k2": 10})
    assert test_state.dynamic_dict == {"k1": 5, "k2": 123}
```

**Expected behavior**
    These asserts should fail.

** Specifics (please complete the following information):**
 - Python Version: 3.10
 - Pynecone Version: 0.1.16
 - OS: macos
 - Browser (Optional):
 
**Additional context**

**Comment by masenf** [comment]
These asserts will fail now, with a TypeError that says you cannot cast a Var/BaseVar as a bool.

To compare Var equality, use the `.equals` method.
