### ISSUE TITLE
pc.html does not pay attention to tags

### ISSUE THREAD

**Issue by hirscr** [reflex-dev/reflex#613]
**Describe the bug**
header tags like `<h1></h1>` have no effect on the text between the tabs

**To Reproduce**
you can just look at your own docs on website
 - Code/Link to Repo:](https://pynecone.io/docs/library/other/html)

**Expected behavior**
header tags should produce bolded and englarged text

**Screenshots**

** Specifics (please complete the following information):**
 - Python Version: 3.9
 - Pynecone Version: latest
 - OS:  mac
 - Browser (Optional): safari, chrome
 
**Additional context**

**Comment by Kaushal-Dhungel** [comment]
Hi, Can I work on this issue?

**Comment by Alek99** [comment]
> Hi, Can I work on this issue?

Yes you can work on this issue. Thanks!

**Comment by masenf** [comment]
The problem here is that reflex has a CSS reset which removes all distinctions between headings. So unless your site is using tailwind typography or setting your own CSS rules for the headings, they are going to appear visually identical.

**Comment by kylelee1027** [comment]
Hello, can I work on this?

**Comment by picklelo** [comment]
This is still an issue, but not sure what the solution is. As mentioned above the css is getting reset within the Reflex app, so not sure how to get the original one back.

**Comment by masenf** [comment]
This has been attempted a few times in the past. See https://github.com/reflex-dev/reflex/issues/1529

In that issue i have an example code which restores "nice looking" default styles for headers and other components via the tailwind/typography package and the `prose` class.

If you're planning to fix this issue, then i would suggest a similar route as described in that bug.

**Comment by kylelee1027** [comment]
I thought that maybe adding the typography plugin as a default value for tailwind in the reflex config would work but it didn't :( or maybe I just implemented it wrong?

**Comment by masenf** [comment]
You also need to add the `class_name="prose"` to the `rx.html` as a default. I think a recent PR just added `rx-Html` as another default class name, so you should be able to piggy back on that.
