### ISSUE TITLE
Installation error in linux

### ISSUE THREAD

**Issue by dev-deji-py** [reflex-dev/reflex#645]
I have it installed on vscode but when i type pc init it does't work instead it throws this error:

deji@deji-linux:~/Desktop/deji/PycharmProjects/pythonProject/happ$ pc run
Command 'pc' not found, but can be installed with:
sudo apt install fp-compiler-3.2.2

**Comment by HellAmbro** [comment]
It looks like you either don't have Pynecone installed or you are using a different python interpreter than where you installed it.
Try to reinstall.

**Comment by ElijahAhianyo** [comment]
closing this now, Feel free to reopen or open another issue if you have further issues or questions
