### ISSUE TITLE
Add CopyToClipboard Component

### ISSUE THREAD

**Issue by heumsi** [reflex-dev/reflex#660]
I found out about the existence of CopyToClipboard through the issue below.

https://github.com/pynecone-io/pynecone/issues/372

I want to use the CopyToClipboard component, but nowhere in the official documentation does it cover how to use it.

Could you please add this component usage to the documentation?

**Comment by heumsi** [comment]
Fortunately, I found the usage through the code.

```python
pc.copy_to_clipboard(
    pc.icon(tag="copy",),
    text="This text will be copied!"
)
```

Maybe you can contribute to my documentation?
If I can contribute, do you have any documentation that I can refer to?

**Comment by picklelo** [comment]
It's not builtin to the core library yet - but this would definitely be good to have. All the docs are in the pcweb repo - see [here](https://github.com/pynecone-io/pcweb/blob/main/pcweb/pages/docs/component_lib/forms.py).

**Comment by Lendemor** [comment]
Since we have the event `rx.copy_to_clipboard` I believe we can close this.
