### ISSUE TITLE
Possibly to add link tags in <head>

### ISSUE THREAD

**Issue by LouisFaure** [reflex-dev/reflex#662]
Hi, it would be nice to add elements such as link tags to the head section of a page. 

For example, this would be handy if one want to include a manifest.json (placed in `assets` folder) to transform the app into a PWA! 

It looks like the component is already present:
https://github.com/pynecone-io/pynecone/blob/38ecc668934df09ad1f55e702841833af4999e23/pynecone/components/base/link.py#L10-L23

So I suppose it should be straightforward to implement this possibility.

**Comment by Alek99** [comment]
Yes should be possible, we'll add it. Thanks for the suggestion!

**Comment by masenf** [comment]
should be possible in the next release 0.2.9 with #1868
