### ISSUE TITLE
Unable to view website in development mode.

### ISSUE THREAD

**Issue by rohitsathish** [reflex-dev/reflex#669]
I setup the basic structure without changes using ```pc init```, so there's no issues on the code side. Then when I enter ```pc run``` it installs the frontend packages and declares that the app is running. Screenshot below - 
![image](https://user-images.githubusercontent.com/46263358/224630367-139941b1-c72d-4b78-a879-1abe12a0d75d.png)

When I navigate to the URL, the site refuses to load with the following error - ERR_CONNECTION_REFUSED, localhost refused to connect.

It might be because I have installed pynecone in a conda virtual environment. Another user on Discord had the same issue when using conda.

 - Python Version: 3.10.9
 - Pynecone Version: 0.1.19
 - OS: Windows
 - Browser (Optional): Chrome
 - Virtual Env Package: Conda

**Comment by Alek99** [comment]
Ok thanks for pointing this out, I haven't experience this problem but we'll try and recreate it with conda.

**Comment by rohitsathish** [comment]
Sure. I'm having trouble running the local server on conda and venv. Even without a virtual environment, I get the same error. It works when using WSL though.

**Comment by Narzard** [comment]
I am using WSL and nothing else special. Not using venv, not using conda or anything. I also cannot establish a connection to the default site on localhost:3000 using http or https. Chrome just states SSL error and wont load it. It DOES however, load in EDGE just fine. Seems to be a chrome issue.

**Comment by ElijahAhianyo** [comment]
I believe this should work in the latest reflex release, feel free to reopen if you face futher issues
