### ISSUE TITLE
Responsiveness of controls are slow

### ISSUE THREAD

**Issue by zdrummond** [reflex-dev/reflex#671]
**Describe the bug**
Looking at a couple examples on the product page, there is a number of examples of slow front-end controls. 

The canonical example in the Intro has a counter. It has a noticeable lag, looks like ~300ms[1], but feels like near a second.

Looking at the React wrapping [demo](https://pynecone.io/docs/advanced-guide/wrapping-react), there is a noticeable latency when dragging the color circle around, but when I use the [demo site](https://omgovich.github.io/react-colorful/) for the original component, it has near-zero lag

**To Reproduce**
Uses the above and you should feel lag

**Expected behavior**
That all the Pyncone examples are fast with no extra effort. The simple example of a counter should show no lag, and the wrapped React counter should perform at the same as the component it is wrapping. 

**Screenshots**
[1] <img width="503" alt="pynecone_counter_perf" src="https://user-images.githubusercontent.com/1627527/224778931-48edc1c3-b021-4387-a4df-12645aeb8141.png">

** Specifics (please complete the following information):**
 - Browser: Chrome Version 110.0.5481.177 (Official Build) (x86_64)

**Comment by Alek99** [comment]
Got it thanks for digging into this. I'll look into this more but I think this has to do with larger apps. We are working on ways to prevent other components that don't update from re-rendering and you should see performance improvements on the main website as a result.

**Comment by zdrummond** [comment]
Quick follow up. On the counter, I did not realize it was hitting the server to update the value. Assuming your UI does not need long-term [state](https://pynecone.io/docs/state/overview) and instead wants to store up changes locally (e.g. building a dynamic form to submit), can you bind props to a local state store [instead](https://pynecone.io/docs/components/props#:~:text=Binding%20Props%20to%20State) of server hosted state?

**Comment by arihantnu10** [comment]
I am facing the same issue with the responsiveness. Please check the video attached for the tutorial in docs page:

https://user-images.githubusercontent.com/119093969/229191379-1731a48f-52f5-4ff5-a9b0-90579ec9cff7.mov

**Comment by parsoyaarihant** [comment]
> 

When running the same tutorial locally, it doesn't even respond.

**Comment by Alek99** [comment]
> When running the same tutorial locally, it doesn't even respond.

Are you running in dev mode or prod mode?

**Comment by ElijahAhianyo** [comment]
closing this issue for now
