### ISSUE TITLE
Add Links to Data Table

### ISSUE THREAD

**Issue by epnoon** [reflex-dev/reflex#679]
Is there a way to render links in a Datatable? 

Thanks!

**Comment by Alek99** [comment]
Right now there is not but we plan on making the datable better. I would use pc.table right now if you need to embed custom links, or components in your table.

**Comment by picklelo** [comment]
For cases of custom components, you should use the base `rx.table`. The data_table is a bit hard to customize and is meant mostly for read only simple data.
