### ISSUE TITLE
Updating State Outside of Event Handlers?

### ISSUE THREAD

**Issue by pb376** [reflex-dev/reflex#684]
I am testing pynecone by making a very basic small tool that wraps a CLI utility. I call `sh.tool(arg, _bg=True, _out=State.update_cmd_stdout)` in my `index` function to use the `sh` library to execute `tool` with `arg`, background the process, and have the library call the `State.update_cmd_stdout` method as a callback per line of stdout received. However, the callback function, an event handler on the state object, does not seem to be invoked. Is it possible to directly call state handler functions, or can they only be called by the framework internally based on trigger events?

**Comment by Alek99** [comment]
Sorry for the delay reply, I think you may be looking for api routes to call event handlers from outside of your Pynecone app. Lmk if this is what you are looking for https://pynecone.io/docs/advanced-guide/api-routes

**Comment by ZeD4805** [comment]
@pb376 
You would make a request to the api by defining an api route and sending an http request to 'http://localhost:8000/{your route}'.

I'm nowhere near in relevant time but I hope this is useful for people who stumble on this issue:

```
async def api_handler(payload: Dict[str, Any] = {}) -> None:
    event_ns = app.sio.namespace_handlers["/event"]
    responses = []
    logger.debug(payload)

    for state in app.state_manager.states.values():
        try:
            event = rx.event.Event(
                token=state.get_token(),
                name="my_event_handler",
                router_data=state.router_data,
                payload=payload,
            )
        except ValidationError as verr:
            print(verr)
            return

        async for update in state._process(
            event=event,
        ):
            # Emit the event.
            responses.append(
                event_ns.emit(
                    str(rx.constants.SocketEvent.EVENT), update.json(), to=state.get_sid()
                ),
            )
    for response in responses:
        await response

app = rx.App(state=State)
app.add_page(index)
app.compile()

app.api.add_api_route(
    "/{your route}",
    api_handler,
)

```
