### ISSUE TITLE
Allow for React component methods to be used (requires support for React refs)

### ISSUE THREAD

**Issue by lucasfbn** [reflex-dev/reflex#690]
I'm trying to wrap the react-player component:
https://www.npmjs.com/package/react-player

Which already works well with the following code (minimal example):

```
import pynecone as pc


class ReactPlayer(pc.Component):
    library = "react-player"
    tag = "ReactPlayer"
    url: pc.Var[str]
```

However, the react-player exposes several methods like `seekTo` and `getDuration`. 

Is there any way for me to wrap these methods and be able to call them on the Python ReactPlayer component? 

I imagine something like:

```
react_player = ReactPlayer.create(url="https://www.youtube.com/watch?v=outcGtbnMuQ")


def index() -> pc.Component:
    return pc.box(
        pc.vstack(
            react_player,
            pc.button("Seek", on_click=react_player.seek_to(10)),
        ),
        padding="5em",
        border_radius="1em",
    )
```

Copying answer from Discord:

> Alek99
> We don't support the ref yet to add seekTo and getDuration but will add support for this you can implement the call backs though onReady see the color picker examples get_controlled_triggers code

**Comment by Alek99** [comment]
Awesome thanks for making this ticket!

**Comment by ElijahAhianyo** [comment]
we do support custom refs now. Closing this ticket

**Comment by lucasfbn** [comment]
> we do support custom refs now. Closing this ticket

Amazing! Could you link to any resources regarding this? I wasn't able to find any. The PR will suffice.
