### ISSUE TITLE
Allow f strings in render code. 

### ISSUE THREAD

**Issue by Alek99** [reflex-dev/reflex#697]
**Describe the bug**

Right now f strings do not work in the render code.

**To Reproduce**
 - Code/Link to Repo:

pc.text(
     f"Hello {State.world}"
)

**Expected behavior**

Should work but is not rendered correctly.

**Comment by picklelo** [comment]
I'm reverting this PR since it had unintended side effects. This is trickier than expected - the solution may have to be just adding a `$` in front of your state vars in your f-strings and it will work.

For example:
```python
pc.text(
    f"Hello ${State.world}"
)
```
