### ISSUE TITLE
[Feature Request] Add shortcut to create interactive table

### ISSUE THREAD

**Issue by iron3oxide** [reflex-dev/reflex#749]
As a developer, I want to be able to create interactive (data) tables (meaning that something happens when I click on a row/column) quickly and concisely. As it stands right now, I would have to create a `pc.table` from scratch and add the desired callback to each row/column. It also seems to be my task to determine whether a `pc.td` is numeric so it is right-aligned. This is tedious and not concise at all.

I therefore propose a shortcut class called `InteractiveTable` (or similar), whose `create` method takes in a model (a Dataframe or similar in the State) and optional callbacks, e.g. `on_click_row`, `on_click_cell` etc. that are also located in the State. Inside the `create` method, the Dataframe is translated to pc table rows with each value wrapped in a `pc.td` (except the column names/headings of course). If the value is numeric, the `is_numeric` flag of the `pc.td` is set to `True`. The received callbacks are added to the `pc.td` and `pc.tr` respectively. 

What do you think? The idea that this should be an external library instead has crossed my mind, but I find this feature to be too useful to not at least propose it here. Also note that I have read #431 but I consider it a separate issue that might yield something like an `InteractiveDataTable`, which is different from the class proposed here, but could certainly make it a bit less useful in the future.

**Comment by Alek99** [comment]
I agree this is a needed core element. Are you think this as a shortcut with our regular table component or do you have another library for tables you would prefer?

**Comment by iron3oxide** [comment]
The former, it shouldn't take too much code if one limits the data model to be of one type (preferably a pandas or polars Dataframe) only. This would cover the common use case of a table filled by some kind of data source that needs to allow selection but not direct manipulation of cells, columns or rows. It would also give the developer full, but hopefully easy and transparent control over stuff like :

1. How the received data is to be presented in tabular form (not all API calls and DB queries return data that is immediately usable)
2. How and if search, filtering, pagination and sorting works
3. What happens with the table itself when a cell, column or row is clicked/selected (does it change colour? can multiple cells/columns/rows be selected?)

I would consider this to be an alternative to a DataTable where these things are probably preset for convenience and which (at least in the current version) seems to be made for client-side search operations only. If the next version of the DataTable doesn't have these shortcomings anymore, the shortcut proposed here would of course be obsolete.
