### ISSUE TITLE
Pynecone official todo example not work properly when --no-backend option

### ISSUE THREAD

**Issue by automatethem** [reflex-dev/reflex#806]
**Describe the bug**
when run app with "pc run --no-backend" command (with --no-backend option), todo app not work (add, delete).
,
**To Reproduce**
 - Code/Link to Repo:
https://github.com/pynecone-io/pynecone-examples/tree/main/todo

**Expected behavior**
Todo app's add, delete features should work properly

**Screenshots**

** Specifics (please complete the following information):**
 - Python Version: Python 3.10.9
 - Pynecone Version: v0.1.24
 - OS: Windows 10 Pro
 - Browser (Optional): Chrome
 
**Additional context**
When without --no-backend option (just pc run command), todo app add, delete work properly.
Thank you very much.

![screenshot](https://user-images.githubusercontent.com/108699325/231085492-e7cb15c6-d2d6-4a5f-9236-0342efdd8580.PNG)

**Comment by masenf** [comment]
Reflex app manages state via backend. If the app is running with no backend, it is expected that nothing will work.
