### ISSUE TITLE
[REF-2927] Allow Dash server to run for arbitrary network graphs (in addition to plotly)

### ISSUE THREAD

**Issue by ryanchern** [reflex-dev/reflex#813]
(Described problem in Discord and was told to open a ticket)

Currently, only plotly graphs are allowed, restricting usage, especially for network/social graphs.

Would love to be able to run Dash Cytoscape:

<img width="804" alt="Screen Shot 2023-04-12 at 15 03 24" src="https://user-images.githubusercontent.com/20213324/231596127-afdcb65b-cd4f-4942-b253-dc662d515a81.png">

https://plotly.com/python/network-graphs/

<sub>[REF-2927](https://linear.app/reflex-dev/issue/REF-2927/allow-dash-server-to-run-for-arbitrary-network-graphs-in-addition-to)</sub>

**Comment by picklelo** [comment]
Will reopen if people still want this.
