### ISSUE TITLE
Controlled inputs throw JS warning in console

### ISSUE THREAD

**Issue by picklelo** [reflex-dev/reflex#817]
The new controlled inputs/text areas works great, but throws a warning in the JS console that we should resolve.

**Comment by masenf** [comment]
What is the warning text?

I'm not able to reproduce any warning with a full control text input in either Firefox 111.0.1 or Safari 16.3 on macOS 13.2.1.

pynecone-0.1.24

Example project:

```python
import pynecone as pc


class State(pc.State):
    var: str = "init"


app = pc.App(state=State)

@app.add_page
def index() -> pc.Component:
    return pc.vstack(
        pc.input(value=State.var, on_change=State.set_var),
        pc.text_area(value=State.var, on_change=State.set_var),
    )

app.compile()
```

**Comment by masenf** [comment]
The entire full controlled input handling code has been removed.
