### ISSUE TITLE
File upload selected files preview

### ISSUE THREAD

**Issue by ElijahAhianyo** [reflex-dev/reflex#822]
currently, the dropzone doesn't show a preview of the selected files before they are uploaded. We should be able to show a preview

**Comment by amcraig** [comment]
> I have found a workaround for this issue. It's hacky but it works.
> 
> ![image](https://user-images.githubusercontent.com/110377310/260053161-0018aea0-be76-46aa-865a-6493369539a2.png)
> 
> ```
> import reflex as rx
> 
> class State(rx.State):
>     img: list[str] = []
>     val: str = "new"
>     uploading: bool = False
> 
>     async def handle_upload(self, files: list[rx.UploadFile]):
>         for file in files:
>             upload_data = await file.read()
>             outfile = f"assets/{file.filename}"
> 
>             # Save the file.
>             with open(outfile, "wb") as file_object:
>                 file_object.write(upload_data)
> 
>             # Update the img var.
>             self.img.append(file.filename)
> 
>         self.uploading = False
>         self.val = "Finished uploading"
> 
>     async def start_vars(self):
>         self.uploading = True
>         self.val = "Uploading files"
> 
>     async def clear_state(self):
>         self.reset()
> 
> def index():
>     return rx.center(
>         rx.script("""
> setInterval(function() {
>   var elements = document.querySelectorAll('.chakra-input.css-1kp110w');
>   elements.forEach(function(element) {
>     element.style.display = 'flex';
>   });
> }, 500);
> """),
>         rx.vstack(
>             rx.text(State.val),
>             rx.upload( 
>                 border="1px dotted black",
>                 padding="1em",
>                 height="4.5em",
>                 no_drag=True,
>                 no_click=True,
>             ),
>             rx.cond(
>                 State.uploading,
>                 rx.button(
>                     is_loading=True,
>                     is_disabled=True,
>                 ),
>                 rx.button(
>                     "Upload",
>                     on_click=[
>                         State.start_vars(),
>                         State.handle_upload(rx.upload_files()),
>                     ],
>                 ),
>             ),
>             rx.button(
>                 "Reset",
>                 on_click=[
>                     State.clear_state(),
>                 ],
>             ),
>             rx.foreach(State.img, lambda img: rx.image(src=img)),
>         ),
>     )
> 
> app = rx.App(state=State)
> app.add_page(index)
> app.compile()
> ```

Is this all your code? I don't see a way how you are updating the upload box with the file name.

**Comment by jq6l43d1** [comment]
Yes this is my code. The key is the javascript. Specifically this line: ```element.style.display = 'flex';``` That element is usually hidden (display = 'none').

**Comment by jq6l43d1** [comment]
Not having any visual feedback when uploading files was the biggest complaint from my users. Issue #822 has been open for 4 months and I got tired of waiting so I decided to see if I could tackle it myself. rx.upload used React Dropzone which supports listing the files that have been selected for upload, as seen in the example here: https://react-dropzone.js.org/#section-basic-example I was unsuccessful in my attempts to get React Dropzone to display the selected files the way that they do in that example. Hopefully someone will figure out how to do that someday soon. However, while I was working on it I was inspecting the code for the dropzone element in my browser and I noticed another element that that was hidden with display=none. I changed it to display=flex to see what it was and it's an element that let's you click on a button to select a file for upload and displays the selected file name after selection. I wrote a little javascript program to change that element from display = none to display = flex automatically and I set ```no_drag=True,
no_click=True,``` in the upload element to disable drag and drop and click to upload for React Dropzone and it works as a temporary workaround until there is a proper fix for #822. Let me know if you have any questions.

**Comment by amcraig** [comment]
@jq6l43d1 
That totally makes sense!
Thanks for the great explanation! 

I thought you left out some portion of your code where you adapted in the filename field.

**Comment by jq6l43d1** [comment]
It's crazy to think about how long this issue has been bothering me while the element I needed was right there the whole time it was just hidden.

**Comment by masenf** [comment]
In the upcoming release 0.2.5 you'll be able to access the selected files as a Var, `rx.selected_files`

```python
            rx.box(
                rx.foreach(
                    rx.selected_files,
                    lambda f: rx.text(f),
                ),
            )
```

**Comment by nick-youngblut** [comment]
>In the upcoming release 0.2.5 you'll be able to access the selected files as a Var, rx.selected_files

@masenf `rx.selected_files` doesn't seem to be in the current docs on `rx.upload`: https://reflex.dev/docs/library/forms/upload/

**Comment by masenf** [comment]
Thanks for pointing that out, we'll get it added.

https://github.com/reflex-dev/reflex-web/issues/187
