### ISSUE TITLE
Datatable doesn't resize based on adjusting the width of screen

### ISSUE THREAD

**Issue by Alek99** [reflex-dev/reflex#833]
**Describe the bug**

**To Reproduce**
 - Code/Link to Repo:

```python
pc.data_table(
    data=nba_data,
    pagination=True,
    search=True,
    sort=True,
    resizable=True,
)
```
**Expected behavior**

When adjusting the screen size the table should resize with the screen unless a constant size is specified
**Screenshots**

End up getting cut off when adjusting to a smaller screen.
<img width="526" alt="Screen Shot 2023-04-17 at 11 24 34 AM" src="https://user-images.githubusercontent.com/38776361/232576828-3f3ab38c-096b-4a37-b880-a7c703deaa0f.png">

** Specifics (please complete the following information):**
 - Python Version: 3.11
 - Pynecone Version: 0.1.23
 - OS: Mac
 - Browser (Optional): Any

**Comment by adhami3310** [comment]
So the main issue here is that Grid from gridjs-react assigns style property to the wrong div. It doesn't seem there's anything can be done from our side except by modifying gridjs-react itself.

**Comment by adhami3310** [comment]
As a workaround, you can do:
```py
rx.el.div(
    rx.data_table(
        data=nba_data,
        pagination=True,
        search=True,
        sort=True,
        resizable=True,
    ),
    width="100%",
)
```
