### ISSUE TITLE
matplotlib and altair

### ISSUE THREAD

**Issue by wangjiawen2013** [reflex-dev/reflex#847]
Hi,
Very pleased to find such a powerful tool !
It's very import to visualize our data on the web, we can use matplotlib  and altair in streamlit App. Does pynecone support matplotlib and altair ?

**Comment by 1sadiqhussain** [comment]
Yes, PyNecone supports both Matplotlib and Altair for data visualization in Streamlit Apps. Matplotlib is a widely-used plotting library in Python, while Altair provides a declarative interface for creating interactive visualizations. You can easily integrate these libraries into your PyNecone project to generate charts and graphs for web-based data visualization. Utilizing PyNecone, you can harness the power of Matplotlib and Altair to create compelling visual representations of your data in Streamlit Apps. Happy coding!

**Comment by mishana** [comment]
@1sadiqhussain How do you add Matplotlib plots in code? Say, i have a 32x32 rgb `numpy` array. How do I pass the figure created by `matplotlib.pyplot.imshow()` to be displayed in pynecone? I can't find a plotly-like connector.

**Comment by tgberkeley** [comment]
@EwoutH it would be great to learn more about your use case for Reflex and see if we can help. Are you around for a call. Here is my calendly: https://calendly.com/reflex-dev-tom/30min

**Comment by adhami3310** [comment]
closed by https://reflex.dev/docs/library/graphing/other-charts/pyplot#basic-example
