### ISSUE TITLE
Feature: API for manipulating State out-of-band

### ISSUE THREAD

**Issue by masenf** [reflex-dev/reflex#874]
When interacting with other python libraries State often needs to be updated in response to callbacks that occurred on the server side.

I'm currently synthesizing a fake update event and using EventNamespace.emit to send it out (see chatroom example), but it's a bit cheesy and currently breaks in prod mode, since set_state isn't called.

I would like to see an API off of App that allows a particular set of states to be modified in a contextmanager and then pushed to client+redis when exiting the context block.

```python
with app.modify_states(sids={client}) as states:
    if states:
        states[0].foo = 42
        states[0].substates["child"].bar = "out of band"
```

```python
with app.modify_states() as states:
    for state in states:
        state.foo = 42
```

**Comment by Alek99** [comment]
Good suggestion will think about this

**Comment by picklelo** [comment]
This is possible now with `app.state_manager.modify_state`
