### ISSUE TITLE
About pc.editable event trigger "on_change"

### ISSUE THREAD

**Issue by Hspix** [reflex-dev/reflex#900]
**Describe the bug**
On pynecone gallery, https://pynecone.io/docs/library/forms/editable
```
pc.editable(
    pc.editable_preview(),
    pc.editable_input(),
    value=EditableState.example_state,
    on_change=EditableState.set_uppertext,
    width="100%",
)
```
When delete or insert some characters, the mouse cursor moves to the end forcefully. Besides, there is a lilltle "lag" or delayed display during typing.

**Additional context**
Textarea component also act like this, 
```
pc.text_area(
     value=State.set_text, placeholder="enter...",
     on_change=State.change_text,
 )
```

**Comment by ElijahAhianyo** [comment]
Ah right. the fix(https://github.com/pynecone-io/pynecone/pull/871) for this was temporarily disabled due to a bug that was introduced. Should be fixed once there's a fix for that
