### ISSUE TITLE
pc run failed - because bun's upgrading is not work from installation.

### ISSUE THREAD

**Issue by milochen0418** [reflex-dev/reflex#901]
**Describe the bug**
In constants.py, we have 
```python
BUN_PATH = "$HOME/.bun/bin/bun"
INSTALL_BUN = "curl -fsSL https://bun.sh/install | bash -s -- bun-v0.5.9"
```

In pynecone/utils/prerequisites.py, we have 
```python
def install_bun():
    """Install bun onto the user's system.
    Raises:
        FileNotFoundError: If the required packages are not installed.
    """
    # Bun is not supported on Windows.
    if platform.system() == "Windows":
        console.log("Skipping bun installation on Windows.")
        return

    # Only install if bun is not already installed.
    if not os.path.exists(get_package_manager()):
        console.log("Installing bun...")

        # Check if curl is installed
        curl_path = path_ops.which("curl")
        if curl_path is None:
            raise FileNotFoundError("Pynecone requires curl to be installed.")

        # Check if unzip is installed
        unzip_path = path_ops.which("unzip")
        if unzip_path is None:
            raise FileNotFoundError("Pynecone requires unzip to be installed.")

        os.system(constants.INSTALL_BUN)
```
When the user calls `pc init`, the INSTALL_BUN will be invoked.
This installation will not automatically replace the old version, and the good thing is to avoid downloading again. 
The pynecone application developer doesn't need to know what bun version they use. 

If we change the bun version for fitting new pynecone, they will upgrade their pynecone package and then
find out `pc run` will get failed.

After my testing, the INSTALL_BUN can work well on my mac, we can replace any bun version by the command
https://github.com/pynecone-io/pynecone/pull/494

But the only issue of the logic is this logic condition
```python
    if not os.path.exists(get_package_manager()):
```
it check this path to decide updating bun or not. 

If you ever install pynecone install from 2023 Feb 10 
Then you can check `~/.bun/bin/bun --version` to see what bun version you have
And you can find out the bun version is old.

**To Reproduce**
 - Code/Link to Repo:

**Expected behavior**

**Screenshots**

** Specifics (please complete the following information):**
 - Python Version: python 3.11
 - Pynecone Version: upgrading from old pynecone install from 2023 Feb 10  to 2023 Apr 24  version into 0.1.27
 - OS: Mac OS X 
 - Browser (Optional): Chrome
 
**Additional context**

**Comment by Alek99** [comment]
I see ok will look into making a new command which will upgrade the install.

**Comment by milochen0418** [comment]
Thanks @Lendemor ~~~

**Comment by milochen0418** [comment]
@picklelo @Lendemor 
My OS is Mac OS X 
After testing on pynecone 0.1.29, it does not work. 
https://github.com/pynecone-io/pynecone/pull/938#issuecomment-1539317877
So we may need to reopen this issue again.
