### ISSUE TITLE
Can not connect to local rest api

### ISSUE THREAD

**Issue by automatethem** [reflex-dev/reflex#905]
**Describe the bug**
can not connect to local rest api, time out occurs.

**To Reproduce**
 - Code/Link to Repo:

pc init (in 52.78.31.107 server)
pc run (in 52.78.31.107 server)

```
import pynecone as pc
from pydantic import BaseModel
from typing import List
from typing import Dict
import requests
import json

'''
{"data": []}
'''
class Payload(BaseModel):
    data: List[Dict]

async def hello_api(payload: Payload):
    for datum in payload.data:
        #print(datum)
        pass
    return {"data": [{"message": "hello"}]}

class BaseState(pc.State):
    async def hello(self):
        print("test")
        url = "http://localhost:8000/hello_api" #can not connet to localhost rest api (blocked in requests.post line)
        #url = "http://52.78.31.107:8000/hello_api" #can not connet to localhost rest api by server's extermal address, too (blocked in requests.post line)
        payload = {"data": []}
        response = requests.post(url, json=payload) #blocked
        outputs = response.json()
        print(outputs)

def contents():
    return pc.button("hello", on_click=BaseState.hello)

app = pc.App(state=BaseState)
app.add_page(contents, route="/")
app.api.add_api_route("/hello_api", hello_api, methods=["POST"])
app.compile()
```

**Expected behavior**

Should print {"data": [{"message": "hello"}]} message in browser.

**Screenshots**

** Specifics (please complete the following information):**
 - Python Version: Python 3.9.13
 - Pynecone Version: 0.1.27
 - OS: Ubuntu 20.04
 - Browser (Optional): Chrome
 
**Additional context**

Thanks for supporting!

**Comment by Alek99** [comment]
Do other apis work just your local is not connecting?

**Comment by automatethem** [comment]
> Do other apis work just your local is not connecting?

 hi, can connet to external rest api well (not blockede)
see following example code.
Thank you your supporting.

    url = "https://jsonplaceholder.typicode.com/posts/1" #can connet to external rest api well (not blockede)
    response = requests.get(url) #not blocked
    outputs = response.json()
    print(outputs)

**Comment by automatethem** [comment]
Another information:
Rest api works when using http://52.78.31.107:8000/docs with browser via fastapi rest api tool.

**Comment by automatethem** [comment]
In summary:
local client (pynecone) to local rest api (pynecone) => not work
local client (pynecone) to remote rest api (pynecone) => work

**Comment by byt3bl33d3r** [comment]
This is happening to me as well.

Python 3.10 // Pynecone 0.1.28

```python
def index() -> pc.Component:
    return pc.center(
        pc.vstack(
            pc.heading("Welcome to Hughmungus!", font_size="2em"),
            pc.box("Get started by editing ", pc.code(filename, font_size="1em")),
            pc.link(
                "Check out our docs!",
                href=docs_url,
                border="0.1em solid",
                padding="0.5em",
                border_radius="0.5em",
                _hover={
                    "color": "rgb(107,99,246)",
                },
            ),
            spacing="1.5em",
            font_size="2em",
        ),
        padding_top="10%",
    )

async def hello():
    return {"message": "Hello World!"}

# Add state and page to the app.
app = pc.App(state=State)
app.add_page(index, title="Hughmungus")
app.api.add_api_route("/api/hello", hello)
app.compile()
```

Running `curl http://localhost:3000/api/hello` returns a 404.

**Comment by picklelo** [comment]
The api runs on the `8000` port - can you try `curl http://localhost:8000/api/hello`. We should make this more clear in the docs.

**Comment by byt3bl33d3r** [comment]
welp that worked, is there a reason why it the frontend and api run on two different ports? I'm assuming security/CORS related?

**Comment by picklelo** [comment]
The frontend `3000` port is for the NextJS app and the backend `8000` port runs the FastAPI Python app

**Comment by automatethem** [comment]
Blocking happens when in python not when external environment (curl ... etc)

**Comment by Lendemor** [comment]
Ran into this issue when making this example : https://github.com/reflex-dev/reflex-examples/pull/156

The core of the issue is that when the backend call itself over HTTP, it need to do so in `async` mode.

Without async, the backend softlock itself (the backend part doing the query doesn't return the control to let the backend part that answer the query run).
