### ISSUE TITLE
please support one click upload

### ISSUE THREAD

**Issue by sheldonchiu** [reflex-dev/reflex#933]
**Describe the bug**

Is there any way to complete the upload using one button and one click?

**To Reproduce**
 - Code/Link to Repo:
This is my current implementation, this require two click, first click to select the file and the second click to submit (the second click will open a file select window again...)
```python
pc.upload(
    pc.link(
        "Import",
        class_name=add_class_tag(TEXT_COLOR_CLASS, "pr-4"),
        # class_name=LINK_BUTTON_CLS,
        size="md",
        on_click=lambda: EnvState.import_env(
            pc.upload_files()
        ),
    ),
```

**Expected behavior**

**Screenshots**

** Specifics (please complete the following information):**
 - Python Version:
 - Pynecone Version:
 - OS: 
 - Browser (Optional):
 
**Additional context**

**Comment by aidanjrauscher** [comment]
I'm also trying to capture this behavior. Upload has an `on_drop` event trigger which I've tried to use, but I have been unable to get that to work.

**Comment by lcastiglione** [comment]
Hi!!.

Sorry for reopening this issue, but I would like to know if there's another way to upload a file with a single click. I'm creating an application that, in addition to allowing drag-and-drop, also enables users to click a button and upload the selected files. However, currently, I have to add two buttons to achieve this, and I can't find a way to do it with just one button. I tried this, but the files I'm uploading never appear within the time limit.

```python
class UploadState(rx.State):
    files: list[str]

    async def handle_upload(
        self, files: list[rx.UploadFile]
    ):
        """Handle the upload of file(s).

        Args:
            files: The uploaded files.
        """
        for file in files:
            upload_data = await file.read()
            outfile = rx.get_upload_dir() / file.filename

            # Save the file.
            with outfile.open("wb") as file_object:
                file_object.write(upload_data)

            # Update the img var.
            self.files.append(file.filename)

    async def wait_for_load_files(self):
        for i in range(100):
            try:
                files = rx.upload_files(upload_id="upload1")
                await self.handle_upload(files)
            except Exception as e:
                pass
            await asyncio.sleep(1)


def upload_button() -> rx.Component:
    return rx.fragment(
        rx.upload(
            rx.box(
                rx.button(
		   "Upload",
                    on_click=UploadState.wait_for_load_files(),
                ),
            ),
            id="upload1",
        )
    )
```
