### ISSUE TITLE
Existing table, PK is named differently than id.

### ISSUE THREAD

**Issue by fagkoz** [reflex-dev/reflex#968]
Hi all,

I am playing around with Pynecone and I wonder what is wrong here.

My DB URL looks like:

`db_url="mssql+pyodbc://USER:PASS@localhost/DATABASE?driver=ODBC+Driver+17+for+SQL+Server"`

And with this piece of Code I am getting only the first Row of more then 100 Test rows from the existing table.

```python
import pynecone as pc

class MyData(pc.Model, table=True):
    description: str
    misc: str

class State(pc.State):
    
    entries = list[MyData]
    
    def get_list(self):

        with pc.session() as session:
            self.entries = session.query(MyData).all()
            
        print(self.entries)
        print(len(self.entries))
            
@pc.route(route="/", title="Test", on_load=State.get_list)
def index():
    return pc.center(
        pc.heading("Test"),
    )

app = pc.App(state=State)
app.compile()
```

**Comment by Lendemor** [comment]
```
entries = list[MyData]
```

should be 

```
entries: list[MyData] = []
```

instead.

Do you also run into same error with a different DB (like sqlite) ?

**Comment by fagkoz** [comment]
Hi Lendemor,

thanks for your help.

For testing I created now a sqlite db which looks similar to the MS SQL:

```
class Test_Data(Base):
    __tablename__ = 'pynecone'
    id = Column(Integer, primary_key=True)
    col1 = Column(String)
    col2 = Column(String)
```
And changed the entries row.

Sadly I still running in the same issue (changed the topic), only the first row is showing.

```
[pynecone(col1='test', col2='test', id=1)]
1
```

**Comment by Lendemor** [comment]
Just tried your initial snippet of code without changing anything, it work for me : 

> [MyData(description='desc', id=1, misc='mmmmmm')]
> 1
> [MyData(description='desc', id=1, misc='mmmmmm'), MyData(description='desc', id=2, misc='mmmmmm'), MyData(description='desc', id=3, misc='mmmmmm')]
> 3


I'm not sure what's happening on your side, but there might be a problem with how you filled the DB.
Can you try to purge all the rows then add some rows with the following event handler : 
```
def add_data(self):
        with pc.session() as session:
            session.add(MyData(description="desc", misc="mmmmmm"))
            session.commit()
```
and change render method to :
```
@pc.route(route="/", title="Test", on_load=State.get_list)
def index():
    return pc.center(pc.heading("Test"), pc.button(on_click=State.add_data))
```

**Comment by fagkoz** [comment]
Thanks for your help, it works now. It was probably the way the Data is entered. While testing I recognized, when I create a table without the specific column "id" (for example I took "SO_ID" instead) the Code runs into an error cause the column id is missing.

`[SQL Server]Invalid column name 'id'. (207)`

Is there any workaround for this?

**Comment by fagkoz** [comment]
Can this behavior can turned off? In production is already an existing DB which does not have an id field, and I would define the Model only for reflecting the necessary columns. The DB modeling would be handled by another process.

**Comment by Lendemor** [comment]
I don't think so at the moment.
You could probably "reimplement" your own pc.Model as a substitute by looking at how it's done in the source code,
and removing the id field.

https://github.com/pynecone-io/pynecone/blob/main/pynecone/model.py#L57

**Comment by fagkoz** [comment]
Thanks I will take a look at this, maybe I can figure it out. Would be great to use this for my next project instead of Flask. However, it would be also awesome, if this would be an official option for existing DBs.
