### ISSUE TITLE
Make allowed component parameters explicit

### ISSUE THREAD

**Issue by iron3oxide** [reflex-dev/reflex#980]
This would be a bit of work, but the improvement to DX is definitely worth it IMO. At the moment, each time a developer wants to know which parameters a components `create` method will accept, of which type those should be and what constraints may be placed on them, they have to consult the docs as their IDE/editor will only be able to tell them that the component expects `*children` and `**props`. 

This is tedious and error prone. Instead (in lieu of better solutions), each component should probably override the `create` method and explicitly state the expected parameters, which are then passed to the generic `create` method of the super class.

**Comment by picklelo** [comment]
Yeah I've thought about this a bit - is there some way to magically inject this into the class's annotations?

 In addition to the component-specific props, there are also many styling props which can be any CSS key. If we made a list of these styling props, it would be nice for them to also come up in the autocomplete for the props.

**Comment by iron3oxide** [comment]
This links to #754, where I got off track when attempting to create CSS enums in order to only allow (at least somewhat) valid CSS strings to be passed to the component (tedious work which probably warrants its own library). Either way, that issue is irrelevant if the constrained types/enums are never actually used to type parameters.

I'm no expert in python magic and from what I read, one should avoid it where possible anyways. I think overriding the `create` method for each component class is the best solution here, but I'll happily stand corrected.

**Comment by masenf** [comment]
Mostly addressed by #1708 which adds generated `.pyi` files for most components, overriding the `create` method definition with the actual parameters and expected types. Subsequent follow-ups will include the event_triggers and style props. But those will be tracked via different issues. Closing this one for now.
