### ISSUE TITLE
Datatable state is lost when changing theme

### ISSUE THREAD

**Issue by iron3oxide** [reflex-dev/reflex#985]
**Describe the bug**
When `pc.toggle_color_mode` gets called, the state of a DataTable is reset, e.g. if it is filtered, that filter will be removed. This is not a major issue but somewhat unexpected and possibly annoying.

**To Reproduce**

1. create an app with a theme toggle and a datatable on the same page
2. modify the state of the datatable, e.g. by searching for a substring or changing the page
3. toggle the theme

**Expected behavior**
The state of the datatable to be preserved.

** Specifics (please complete the following information):**
 - Python Version: 3.11.3
 - Pynecone Version: 0.1.29
 - OS: Fedora 38
 - Browser (Optional): Brave

**Comment by Lendemor** [comment]
This does not occur anymore as of latest version, will close.
