### ISSUE TITLE
Add Chinese translation support

### ISSUE THREAD

**Issue by Gaolele-Github** [reflex-dev/reflex#988]
Hello,
I am an open-source technology enthusiast and am deeply impressed by your pynecone project. I noticed that the project does not yet have Chinese translation support, so I would like to introduce the project to more Chinese developers by creating a Chinese translation document.
I hope to create a Chinese translation document for the latest version of the project and upload it to the README or documentation section of the project, so that Chinese developers can better understand and use the project. I will do my best to ensure the quality of translation based on my translation ability and experience, and submit the documents to the warehouse within two months.
If this meets your requirements, I would be very grateful. If you need to further understand my experience and abilities, or if you would like me to follow specific standards when translating, please let me know.
Thank you for your time and look forward to your reply.
Best regards,
Gaolele

**Comment by Lendemor** [comment]
Hello,

just to clarify, but do you mean that: 
-  you want Pynecone to support displaying Chinese text.
-  you want the documentation to be in Chinese.

**Comment by Gaolele-Github** [comment]
I want Pynecone documentation to displaying Chinese text.

**Comment by Alek99** [comment]
Yes feel free to translate the docs, we can chat more on discord. 

Maybe an easier starting point would be to translate the readme first on our GitHub?

**Comment by Gaolele-Github** [comment]
No problem.

**Comment by ElijahAhianyo** [comment]
closing this now
